### ISSUE TITLE
Consistency of terms

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#1001]
The terms which need making consistent are:
 - frames
 - layers
 - data source for contours
 - images

If any items are changed there will need to be concomitant changes made to screenshots / any documentation. Let @Kechil know if you would like help with this.

Jordan you are listed amongst the assignees as you would be the ideal person to do QA on this. It's somewhat urgent as we would like to get this sorted for v1.4 (3 Aug).

**Comment by veggiesaurus** [comment]
I propose we change these all to "Image".

- Load Image (and maybe switch Append Image -> Add Image?)
- Layer List -> Image List
- Frame -> Image (In animator)

I feel Data Source still conveys the appropriate information, and we will eventually have support for imported contours, which would make "Image" the wrong term

**Comment by kswang1029** [comment]
Yes using “image” sounds a proper term.

**Comment by veggiesaurus** [comment]
Realised this also needs to be discussed with @confluence as we want the scripting interface to be consistent with the terms used on the frontend.

This will lead to a complicated but mostly IDE-automated refactoring process, that should be tackled as soon as we don't have any major pending PRs

**Comment by confluence** [comment]
I agree that the term "image" should be used consistently in user-facing text. I'm not convinced that we need to rename classes in code, and I'm concerned that this is going to open a massive can of worms. If we rename "frame" to "image" everywhere in the frontend, are we also going to rename this in the backend?

I can see that if we're going to document frontend actions for low-level script writers, this will lead to an inconsistency if we don't rename them. At the moment, only one user-facing high-level function in the prototype wrapper uses the word "frame", and that can easily be changed. Other than that, the wrapper uses the word "image" in functions exposed to the user, and only uses "frame" internally when referring to frontend functions. It will not be difficult to rename all these references, so the impact on the scripting interface is minimal either way.
