### ISSUE TITLE
Create cog for changing settings in image viewer

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#1003]
Other widgets have a cog to change settings. The image viewer needs to be made consistent with this.

**Comment by Kechil** [comment]
There needs to be more consistency for each widget in how it deals with settings and saving preferences in general.

**Comment by kswang1029** [comment]
@TienHao could you help on this issue for v1.4? This is basically adding a cog button to the image viewer widget window, just like other widgets (eg spectral profiler). The cog points to "overlay settings" dialogue which allows users to change AST layout and beam, etc.
