### ISSUE TITLE
Options for transfer function

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#1008]
Options for the transfer function and resampling mode to convert input image pixel values to screen / file pixel values. E.g., max vs mean, bilinear vs trilinear

**Comment by kswang1029** [comment]
Not sure what this means. Can we close this if there is no clear requirement?

**Comment by veggiesaurus** [comment]
is this related to how we map values to the colour map? Or is it how we handle pixels when not at 1.0 zoom?

**Comment by kswang1029** [comment]
Not sure about this issue. Can we close it for now?
