### ISSUE TITLE
Create a quick setup dialogue so user can select certain preferences at the start

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#1023]
This will have the added benefit of educating the user in some CARTA behaviours.

**Comment by kswang1029** [comment]
@veggiesaurus @TienHao I have created a doc to put down the idea. Please have a look.

https://docs.google.com/document/d/10Tu4pwhI21p7W0QJGULoTFSeyQVglzHAMMMeRvsA-Xk/edit

**Comment by veggiesaurus** [comment]
Do you think we also need some options for the colour scheme of the overlay?

**Comment by kswang1029** [comment]
Hmm good point but I am not sure. Maybe in the last panel we can add few more tips to let user know that the color scheme of the overlay and the colormap for raster are configurable too. Would that work? Hard to draw a line here as we should not have a lengthy initial setup.

**Comment by kswang1029** [comment]
instead of implementing this, we can use tutorial (doc, video) for the same purpose. close for now.
