### ISSUE TITLE
Region tool becomes deselected after creating a region

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#1024]
Usability comment:
I don't like it that the region tool becomes deselected after you draw only one region. Often I will want to draw many regions and this behaviour would be very annoying (i.e., having to select the region tool each time). I think that the tool should stay selected until you choose a different tool (this is the behaviour I expect and have experienced in many other software tools).

**Comment by Kechil** [comment]
Add a preference?

**Comment by kswang1029** [comment]
@kswang1029 preparing tooltip and terminology

**Comment by veggiesaurus** [comment]
@kswang1029 can we close this?

**Comment by kswang1029** [comment]
Yes
