### ISSUE TITLE
Re-configure any time not just the first time

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#1031]
Must be able to re-access preferences.

This arises from discussions about the Region Analytics form in the Usability Review.

**Comment by Kechil** [comment]
From Usability Review, Region Analytics: 
This is not just an issue for regions

**Comment by kswang1029** [comment]
@veggiesaurus @TienHao  I have created a doc to put down the ideas for this quick preferences setup dialogue. Please have a look.

https://docs.google.com/document/d/10Tu4pwhI21p7W0QJGULoTFSeyQVglzHAMMMeRvsA-Xk/edit

**Comment by kswang1029** [comment]
duplicated with #1023. close this one.
