### ISSUE TITLE
[xyz profilers] enhancement of tsv output

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#104]
Please add "#" to the second row ("x y" --> "# x y")
Please add pixel coordinate and world coordinate of the profile taken at.
Please add the labels of horizontal and vertical axes. 

Example header is like (from casaViewer)
#title: Spectral profile - HD163296_CO_2_1_zoom.image-raster
#region (world): Point[[17:56:21.289, -21d57m22.221]]
#region (pixel): Point[[89, 89]]
#coordinate: world
#xLabel: radio velocity [km/s]
#yLabel: [Jy/beam] Mean

**Comment by veggiesaurus** [comment]
- [ ] Comment out second row
- [ ] Pixel and world coordinates of profile (spatial/spectral)
- [ ] Horizontal and vertical axes
