### ISSUE TITLE
Rounding figures to make them fit better in spectral profiler box

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#1041]
Usability review comment:
When I opened the "Y Profile Settings" window, the window wasn't big enough and values were cut off (I had to resize the window). There were too many sig figs in some of the values (like Y Min and Y Max). I think they should either be rounded or the box expanded to see the whole number. Don't make the user scroll.

Is there a consistent method of dealing with this? Do we need to train scientists in scientific notation?
Could select a range of pixels?

**Comment by veggiesaurus** [comment]
@kswang1029 @TienHao I'm assigning this issue to the two of you, for investigation _after_ @panchyo0 has finished the plotly migration if necessary.
