### ISSUE TITLE
display Stokes value instead of numeric index in animator

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#1046]
When loading a Stokes cube, it is better to display I, Q, U, or V instead of 0, 1, 2, or 3 which are meaningless and misleading due to the classic 0-base or 1-base indexing issue.

The FITS standard document defines how numeric values in the header map to Stokes parameters and other polarization parameters. Table 29:
![Screen Shot 2021-06-14 at 3.04.14 PM.png](https://images.zenhubusercontent.com/590bdf9f51aa2c30577d5260/be903618-0859-48c7-b579-2d39a909bc74)

We will need to show the string in the "Symbol" column based on the "Value" column.

**Comment by kswang1029** [comment]
At the moment, if we load a cube with Stokes QU (the header is set correctly), the Stokes column in the image list widget still starts with 0. Numeric index should be 1 but we better just show alphabetic index as Q.

**Comment by Kechil** [comment]
Medium Priority
