### ISSUE TITLE
selecting texts with cursor in the file info box has an offset

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1053]
In other words, it seems we cannot select the correct row of texts, where the cursor is pointing at.
![Jul-22-2020 11-11-40](https://user-images.githubusercontent.com/20819712/88130240-92a23800-cc0c-11ea-8831-e413d3d3bc99.gif)

**Comment by veggiesaurus** [comment]
This is very irritating. It's a minor CSS-related bug, I'll try fix this for 1.4 final
