### ISSUE TITLE
spectral line query: performance impact when rendering too many line overlay

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1066]
Roughly the GUI becomes less responsive when more than a thousand line labels are rendered. With the spatalogue query, it is very easy to get many lines with a narrow frequency range. From the usability point of view, rendering too many labels at one time does not help much in the analysis and result in poor UX when zooming the profile. I suggest we limit the total number of lines up to 1000 to be rendered, so that only the first 1000 _selected_ lines will be rendered.  @duidae @veggiesaurus thoughts?

**Comment by duidae** [comment]
agreed to set a selection limit, and users may not know the rule of plotting only first 1000 lines, how about pop up a warning dialog "Please select less than 1000 spectral lines." and disable the plot button?

**Comment by duidae** [comment]
@kswang1029 @veggiesaurus is this approach acceptable?
select < 1000 lines will enable the button

![image](https://user-images.githubusercontent.com/25971696/88779290-2e5b1780-d1bc-11ea-8386-1c703f261614.png)

**Comment by veggiesaurus** [comment]
> @kswang1029 @veggiesaurus is this approach acceptable?
> select < 1000 lines will enable the button
> 
> ![image](https://user-images.githubusercontent.com/25971696/88779290-2e5b1780-d1bc-11ea-8386-1c703f261614.png)

That looks great, although I think it should be "fewer than". Right @confluence?
