### ISSUE TITLE
animator: range slider not responsive 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1078]
related to #870

To reproduce the issue:
1) load set_S255/S255_IR_sci.spw25.cube.I.pbcor.fits
2) click the animator tab in the default layout
3) should see mis-aligned slider control as #870 
<img width="630" alt="Screen Shot 2020-07-29 at 5 59 58 PM" src="https://user-images.githubusercontent.com/20819712/88786671-631f9c80-d1c5-11ea-89c5-810811dd3cbb.png">
4) after some efforts to make the controls back to normal, we cannot define a range using the range slider

![Jul-29-2020 17-55-50](https://user-images.githubusercontent.com/20819712/88786827-9530fe80-d1c5-11ea-918d-342481b5502e.gif)

**Comment by duidae** [comment]
it's a bug of blueprintJS, I've filed an issue a few months ago when implementing moment tab & trying to use range slider, https://github.com/palantir/blueprint/issues/4109
seems not fixed yet.
