### ISSUE TITLE
[animator] no radio button is checked

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#108]
To reproduce (found from testers feedback):
1) open J2000_test.hdf5
2) append orion_12co_hera.hdf5
3) in animator, click "Frame" radio button
4) open cube_x419_z101_68MB.hdf5 (so the previous two are closed)
5) now in animator, there is only "Channel" radio button and is not checked. So hitting "play" results in nothing.

**Comment by veggiesaurus** [comment]
I'm not sure how to handle this situation. You have a similar situation when you load two files, one 2D and one 3D. If you select the 3D file, and click the "Channel" radio button, and then switch to the other frame, the "Channel" radio button disappears, and you only have "Frame", but it's not checked.

**Comment by kswang1029** [comment]
this is a tricky issue I admit. It has some impact to UX but I feel it is not that critical. So maybe we keep this in mind and it is not necessary to fix this for v1.0-rel.
