### ISSUE TITLE
unable to hide a raster layer at a certain condition

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1082]
When the Layers column in the image list widget is not wide enough (default is not wide enough) to show "R" and "C", "R" is not clickable. 
![Screen Shot 2020-08-04 at 9 37 56 AM](https://user-images.githubusercontent.com/20819712/89243418-7c49a280-d636-11ea-8f85-94cda1716ea9.png)

We will need to manually widen the column to make "R" (and "C") clickable.

**Comment by kswang1029** [comment]
also mentioned by a beta tester.

**Comment by veggiesaurus** [comment]
how do you reproduce this? What browser and screen res? For me (Chrome, ubuntu, `devicePixelRatio=1`) the default width is large enough

**Comment by kswang1029** [comment]
I tried with a non-retina iMac with Chrome. The browser size is ~1700x940. Try with the mix page and load set_HD163296/HD163296_CO_2_1.fits then generate contours. When contours are generated, I see ...
