### ISSUE TITLE
Feature request - match color scale between images

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-frontend#1089]
One feature request I have for CARTA that would save me a lot of time is a button to match the scale limits between frames/images. I’m often comparing images of the same field (e.g. self-calibration loops) and wanting to see them with the same transfer function. So I have to copy and paste between the min and max boxes for all frames, which takes an annoying amount of time. It would be useful to have a single button to do this. Perhaps within the match column in the image list.

**Comment by kswang1029** [comment]
as a similar feature, it would be good to support linking the plot xy ranges of multiple spectral profile widgets, for example. There should be a number of places that can have benefits from this kind linking capacity. We probably need an epic to do it right.

**Comment by arusstaylor** [comment]
This is an important usability feature for comparative work.  Agree we should spend a bit of time thinking about design issues.


Russ

**Comment by veggiesaurus** [comment]
just to clarify, the clip min/max and scaling type (log, linear, etc) should all be matched
