### ISSUE TITLE
Feature request: case insensitive fuzzy search in file browser

### ISSUE THREAD

**Issue by lh-astro** [CARTAvis/carta-frontend#1092]
While the file browser is open filter matches by fuzzy search while typing.

**Comment by veggiesaurus** [comment]
@lh-astro searching is already case-insensitive. Could you specify exactly what you're requesting? at the moment, if you just search for `*<string>*`, it should provide a list of all files which contain `<string>`, regardless of case.

Are you requesting something along the lines of this? https://fusejs.io/examples.html#search-object-array

**Comment by lh-astro** [comment]
I'm not sure whether the fusejs module is doing what I'm thinking of. Here is an illustration

fuzzysearch('twl', 'cartwheel') // <- true
fuzzysearch('cart', 'cartwheel') // <- true
fuzzysearch('cw', 'cartwheel') // <- true
fuzzysearch('ee', 'cartwheel') // <- true
fuzzysearch('art', 'cartwheel') // <- true
fuzzysearch('eeel', 'cartwheel') // <- false
fuzzysearch('dog', 'cartwheel') // <- false

see https://github.com/bevacqua/fuzzysearch#fuzzysearchneedle-haystack
But you also want http://en.wikipedia.org/wiki/Levenshtein_distance implemented.

**Comment by lh-astro** [comment]
I'm not sure whether the fusejs module is doing what I'm thinking of. Here is an illustration
```
fuzzysearch('twl', 'cartwheel') // <- true
fuzzysearch('cart', 'cartwheel') // <- true
fuzzysearch('cw', 'cartwheel') // <- true
fuzzysearch('ee', 'cartwheel') // <- true
fuzzysearch('art', 'cartwheel') // <- true
fuzzysearch('eeel', 'cartwheel') // <- false
fuzzysearch('dog', 'cartwheel') // <- false
```

see https://github.com/bevacqua/fuzzysearch#fuzzysearchneedle-haystack
But you also want http://en.wikipedia.org/wiki/Levenshtein_distance implemented.

**Comment by lh-astro** [comment]
I'm not sure whether the fusejs module is doing what I'm thinking of. Here is an illustration
```
fuzzysearch('twl', 'cartwheel') // <- true
fuzzysearch('cart', 'cartwheel') // <- true
fuzzysearch('cw', 'cartwheel') // <- true
fuzzysearch('ee', 'cartwheel') // <- true
fuzzysearch('art', 'cartwheel') // <- true
fuzzysearch('eeel', 'cartwheel') // <- false
fuzzysearch('dog', 'cartwheel') // <- false
```

see https://github.com/bevacqua/fuzzysearch#fuzzysearchneedle-haystack
But you also want http://en.wikipedia.org/wiki/Levenshtein_distance implemented.

**Comment by lh-astro** [comment]
I'm not sure whether the fusejs module is doing what I'm thinking of. Here is an illustration
```
fuzzysearch('twl', 'cartwheel') // <- true
fuzzysearch('cart', 'cartwheel') // <- true
fuzzysearch('cw', 'cartwheel') // <- true
fuzzysearch('ee', 'cartwheel') // <- true
fuzzysearch('art', 'cartwheel') // <- true
fuzzysearch('eeel', 'cartwheel') // <- false
fuzzysearch('dog', 'cartwheel') // <- false
```

see https://github.com/bevacqua/fuzzysearch#fuzzysearchneedle-haystack
But you also want http://en.wikipedia.org/wiki/Levenshtein_distance implemented.

**Comment by veggiesaurus** [comment]
@lh-astro you can give PR #1096 a try on the ASIAA mix 'n match page, will send you the link on slack
