### ISSUE TITLE
synchronizing channel indicator in multiple spectral profilers while animating

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1097]
To reproduce:
1) load set_HD163296/HD163296_CO_2_1.fits, HD163296_13CO_2_1.fits, and HD163296_C18O_2_1.fits
2) match them in xy and z
3) launch three spectral profilers and set the image dropdown for each image
4) click "Next" or "Prev" in the animator and we will see all three red vertical lines updating their position.
5) click "Play" and we will see only one (the active image) is updating. Expect to see all three red vertical lines updating while animating too. 

![Screen Shot 2020-08-11 at 9 55 26 AM](https://user-images.githubusercontent.com/20819712/89848547-f4751280-dbb8-11ea-8b6c-810c20e2a430.png)

**Comment by veggiesaurus** [comment]
Should be fixed by matched animation branch

**Comment by kswang1029** [comment]
Yes, confirmed in the matched animation branch. I will close this.
