### ISSUE TITLE
cant save layout

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#1103]
layout is not saved in current dev branch

**Comment by veggiesaurus** [comment]
@duidae could you provide more details? layout saving works for me with dev branch

**Comment by duidae** [comment]
@veggiesaurus checked again with my dev & mix'n match, the saved layout is gone after reload: 
![55vup-fux7a](https://user-images.githubusercontent.com/25971696/89988537-49488400-dcb2-11ea-9121-f35e929eec24.gif)

**Comment by veggiesaurus** [comment]
I can't reproduce this with mix 'n match. Can you check what's happening in your local storage? Could your new layout be failing the JSON schema check?
