### ISSUE TITLE
smoothing in Stokes tool should also update the Q,U plot with the smoothed values

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#1114]
Smoothing the profiles in the Stokes tool should also update the Q,U plot with the smoothed versions of Q,U.

**Comment by kswang1029** [comment]
Is it required as an option to show the original scatter under the smoothed scatter? How would you like to colorize them?

**Comment by kswang1029** [comment]
@TienHao are you able to look into this during the v1.4 beta test?

**Comment by TienHao** [comment]
Yes, I can look into this issue.

**Comment by veggiesaurus** [comment]
> Is it required as an option to show the original scatter under the smoothed scatter? How would you like to colorize them?

I think showing both scatters might be very confusing. Showing the smoothed scatter would be really useful, though. The QU scatter is often very noisy, and smoothing it would allow the Faraday rotation to be more clearly visible

**Comment by arusstaylor** [comment]
agree that we should only show the smoothed Q,U values.
