### ISSUE TITLE
file browser forgot its pwd after moment generation

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1117]
(not sure if this is due to frontend or backend)

To reproduce:
1) load an image cube (and remember the path)
2) generate a moment image
3) launch file browser and it should point to $root (should be the path in 1))

**Comment by veggiesaurus** [comment]
I recently updated the front-end so that the previous directory was updated when using scripting or the URL parameters. I suspect that's what's causing it
