### ISSUE TITLE
disabling the data source dropdown of the contour config dialogue while animating

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1120]
As spotted by @zarda 

There are three places that can be used to switch to other images
1. the "image" slider of the animator
2. the image list widget
3. the "data source" dropdown of the contour config dialogue

When animating, 1. and 2. are disabled so that we cannot switch to other images. The same constraint should be applied to 3. At the moment, we can select other images with the dropdown but the image viewer does not respond to it (which is correct). We will just need to disable the dropdown when animating. 

@veggiesaurus backport 1.4-final?

**Comment by veggiesaurus** [comment]
if the two are unlinked, should it still be disabled? any need to allow users to change contours while animating?

**Comment by kswang1029** [comment]
I cannot think of a use case about changing contours _while_ animating.
