### ISSUE TITLE
Image slider deselected in animator when image appended

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-frontend#1121]
When a new image is appended, the image/frame slider appears in the animator. However, it is deselected, and then animator buttons don't work unless you first select it. It should be automatically selected.

**Comment by Jordatious** [comment]
Sounds good. For single channel images, it's the only slider.

**Comment by kswang1029** [comment]
My two cents: 
I think the image radio button should be selected only when the new appended image has no channel nor stokes axis. Channel axis should still be selected if channel axis exists.

**Comment by veggiesaurus** [comment]
> My two cents:
> I think the image radio button should be selected only when the new appended image has no channel nor stokes axis. Channel axis should still be selected if channel axis exists.

I guess that makes sense, yes. What about also automatically animating in image mode if you press play on a 2D image?

**Comment by kswang1029** [comment]
Good idea!
