### ISSUE TITLE
long file name in the title of the region list widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1123]
<img width="596" alt="Screen Shot 2020-08-19 at 12 22 02 PM" src="https://user-images.githubusercontent.com/20819712/90591905-d2ae0800-e216-11ea-9737-337ae65df037.png">
<img width="596" alt="Screen Shot 2020-08-19 at 12 05 35 PM" src="https://user-images.githubusercontent.com/20819712/90591909-d6418f00-e216-11ea-853a-facdd847048f.png">

**Comment by veggiesaurus** [comment]
@kswang1029 are you ok with us just truncating the image to a fixed length (e.g. 10) for 1.4?

**Comment by kswang1029** [comment]
@veggiesaurus I think the best way (instead of a workaround) is to show region properties in world coordinate and angular size by synchronizing the info from the region editing dialogue. If we show info in world coordinate and angular size, the file name is not needed.  @TienHao Could you help to _evaluate_ the issue to see if the required changes are small/safe for v1.4 or large/risky for v1.4?

<img width="1489" alt="Screen Shot 2020-08-19 at 4 34 20 PM" src="https://user-images.githubusercontent.com/20819712/90612028-12d2b200-e23a-11ea-9522-0e3549244533.png">

**Comment by TienHao** [comment]
I can help to evaluate this issue.
