### ISSUE TITLE
[2.0 suggestion] add computed animating status to appstore for others to access & refactor accordingly

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#1125]
since animation status is commonly used in quite some places: 

@computed get isAnimating() = {
return this.animatorStore.animationState === AnimationState.PLAYING;
}

**Comment by veggiesaurus** [comment]
> since animation status is commonly used in quite some places:
> 
> @computed get isAnimating() = {
> return this.animatorStore.animationState === AnimationState.PLAYING;
> }

There's a computed property in the animator store:

```
@computed get serverAnimationActive() {
        return this.animationState === AnimationState.PLAYING && this.animationMode !== AnimationMode.FRAME;
    }
```

I suggest we add another computed property `animationActive` that doesn't check the animation mode
