### ISSUE TITLE
[connect to URL; improvement] adding success/failed message? 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#113]
I tested with the desktop version and linked to the demo server from home. If the link is established, the "Connect to URL" window is gone. Could we add a pop up window to warn users that the connection is established? This would improve UX.

**Comment by veggiesaurus** [comment]
@kswang1029 this should also be fixed in master now

**Comment by kswang1029** [comment]
when connected to a remote url, shall we refresh the GUI to default states (just like when we enter api key)? I see when the connection to the remote url is established, in the file menu, I can "append" image and it seems the file list "remembers" the previous connection.

**Comment by veggiesaurus** [comment]
we do this by reloading the page for the API key, it's a little tricker to do while maintaining a connection, but I can look into it after 1.1.

**Comment by kswang1029** [comment]
sure. 
I was trying to view an image from ASIAA and another from IDIA. The animator has "two" frames, although I believe the first frame from ASIAA is no longer responsive.

**Comment by veggiesaurus** [comment]
yes, that will definitely occur :disappointed:  I'll open a new issue for this
