### ISSUE TITLE
ping pong test for spectral line query

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#1130]
ping pong test to check the status of splatalogue service is available or not initially

check website using curl:
https://www.2daygeek.com/linux-command-check-website-is-up-down-alive/

**Comment by duidae** [comment]
so far the working scenario is designed as(Fig 1):

1: when opening the spectral line query widget, frontend send ICD message to ask backend to ping splatalogue(check service alive)

2.1: backend sends ok to frontend to unmask when get HTTP 200 ok.
2.2: backend sends failure to frontend and frontend keeps masked, user can still reload to check service through the button in the splash screen(Fig 2).

pinging splatalogue means sending `curl -I https://splatalogue.online/` once(to avoid becoming a ping attack) to check the service is alive or not. 

@veggiesaurus @kswang1029 do u think it's ok for this improvement issue? any comment is welcomed. thanks.

Fig 1
![image](https://user-images.githubusercontent.com/25971696/126092907-399e8363-917f-464f-9be1-a95ecaf18744.png)

Fig 2
![image](https://user-images.githubusercontent.com/25971696/126093058-bdc07369-de28-42ca-9bca-fe66b8107509.png)

**Comment by kswang1029** [comment]
@duidae yes the plan sounds good. Let me check with Tony on putting the Splatalogue logo in CARTA.

**Comment by kswang1029** [comment]
Do we also need a repeating ping-pong _after_ the initial successful ping-pong? Such as every 5min, for example. If a ping-pong test fails, we display the splash screen and mask the GUI.

UPDATE: after thinking a while I think _if_ we implement a repeating check and if it fails, we should _not_ mask the UI but put a message somewhere instead as with the data at the frontend, users can still perform line ID overlay actions to some extend. Maybe we can add a green/red circle to the top-right corner as the service state indicator similar to the one we have at the top-right corner of the GUI now.

**Comment by duidae** [comment]
since splatalogue is an independent service maintained by others, I think only test once is better to avoid becoming a ping attack.

**Comment by veggiesaurus** [comment]
> since splatalogue is an independent service maintained by others, I think only test once is better to avoid becoming a ping attack.

If we we checked every 5 mins, and assumed that CARTA peaked at 1000 concurrent users _using_ the spectral query tool, that would be 3 requests per second. That shouldn't be a problem, although we should probably check with NRAO before implementing this sort of feature.

I think the more important question is whether splatalogue can handle a large number of concurrent users doing actual queries?
