### ISSUE TITLE
shortcuts conflict when using CARTA in the remote mode

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1143]
user feedback: https://github.com/CARTAvis/carta/issues/37

The shortcuts are dynamically determined by the operating system where we launch the backend. If we use the linux desktop in the remote mode from a remote linux server with a Mac as the client, then the shortcuts customized for the linux OS, which may not be usable due to conflicts with macOS.

e.g. ctrl+up is "next channel" in CARTA but ctrl+up is also "Mission control" in macOS.

**Comment by veggiesaurus** [comment]
If running in remote mode, we should defer to the browser based shortcuts, surely?
