### ISSUE TITLE
frontend support region type: line segment

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1149]
the line segment region can be used for
- spatial profiler
- pv generator

related to https://github.com/CARTAvis/carta-backend/issues/610

A line region should be defined in two ways:
1. center + length
2. two points

We will need to be able to define the line region in world coordinates and image coordinates. 

For spatially matched image, we will need to resample the line segment on the reference image with multiple points as a  straight polyline, then apply transformation of this set of points to the spatially matched image for render as a "curve". This is consistent with the shared region design (ie region re-projection) in CARTA. 

science requirements: https://docs.google.com/document/d/1mE-JeZjczT_GEPfllm-aNWWUZ903wTJy4JurxBq537c/edit#heading=h.pfjlp9m9fqp4

**Comment by kswang1029** [comment]
postpone to v3.0 (but needs to happen early when v3.0 dev cycle starts).

**Comment by YuHsuan-Hwang** [comment]
The feature of line regions is merged. Polyline regions remain to be implemented.
