### ISSUE TITLE
display xy labels and ticks properly for a position-velocity image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1150]
The x and y labels and ticks should be displayed properly based on the image header. (AST support)

**Comment by duidae** [comment]
@kswang1029 do we have details about this feature? thanks.

**Comment by kswang1029** [comment]
taken to following header as an example:

> SIMPLE  =                    T /Standard FITS                                   
BITPIX  =                  -32 /Floating point (32 bit)                         
NAXIS   =                    3                                                  
NAXIS1  =                  335                                                  
NAXIS2  =                  250                                                  
NAXIS3  =                    1                                                  
EXTEND  =                    T                                                  
BSCALE  =   1.000000000000E+00 /PHYSICAL = PIXEL*BSCALE + BZERO                 
BZERO   =   0.000000000000E+00                                                  
BMAJ    =   1.884508960777E-04                                                  
BMIN    =   1.530597441726E-04                                                  
BPA     =   7.251033782959E+01                                                  
BTYPE   = 'Intensity'                                                           
OBJECT  = 'HD163296'                                                            
BUNIT   = 'Jy/beam '           /Brightness (pixel) unit                         
PC1_1   =   1.000000000000E+00                                                  
PC2_1   =   0.000000000000E+00                                                  
PC3_1   =   0.000000000000E+00                                                  
PC1_2   =   0.000000000000E+00                                                  
PC2_2   =   1.000000000000E+00                                                  
PC3_2   =   0.000000000000E+00                                                  
PC1_3   =   0.000000000000E+00                                                  
PC2_3   =   0.000000000000E+00                                                  
PC3_3   =   1.000000000000E+00                                                  
CTYPE1  = 'OFFSET  '                                                            
CRVAL1  =   0.000000000000E+00                                                  
CDELT1  =   5.000000001404E-02                                                  
CRPIX1  =   1.680000000000E+02                                                  
CUNIT1  = 'arcsec  '                                                            
CTYPE2  = 'FREQ    '                                                            
CRVAL2  =   2.305120801231E+11                                                  
CDELT2  =   2.441261095581E+05                                                  
CRPIX2  =   1.000000000000E+00                                                  
CUNIT2  = 'Hz      '                                                            
CTYPE3  = 'STOKES  '                                                            
CRVAL3  =   1.000000000000E+00                                                  
CDELT3  =   1.000000000000E+00                                                  
CRPIX3  =   1.000000000000E+00                                                  
CUNIT3  = '        '                                                            
RESTFRQ =   2.305380000000E+11 /Rest Frequency (Hz)                             
SPECSYS = 'LSRK    '           /Spectral reference frame                        
ALTRVAL =   3.370630267856E+04                                                  
ALTRPIX =   1.000000000000E+00                                                  
VELREF  =                  257 /1 LSR, 2 HEL, 3 OBS, +256 Radio                 
COMMENT casacore non-standard usage: 4 LSD, 5 GEO, 6 SOU, 7 GAL                 
TELESCOP= 'ALMA    '                                                            
OBSERVER= 'mrawlings'                                                           
DATE-OBS= '2012-06-09T05:52:23.424000'                                          
TIMESYS = 'UTC     '                                                            
OBSRA   =   2.690886722618E+02                                                  
OBSDEC  =  -2.195621129269E+01                                                  
OBSGEO-X=   2.225142180269E+06                                                  
OBSGEO-Y=  -5.440307370349E+06                                                  
OBSGEO-Z=  -2.481029851874E+06                                                  
DATE    = '2021-02-18T06:47:44.583072' /Date FITS file was written              
ORIGIN  = 'CASA Viewer / FITS export'                                       

The idea is to display one spatial axis vs one spectral axis. In the above case, they are `CTYPE1  = 'OFFSET  '` and `CTYPE2  = 'FREQ    ' `. For the spatial axis, the name is not standardized so we may see it as "offset" or "position offset", or "position" etc. For the spectral axis, we will need to convert it to Velocity if the header is not Velocity. So in the above example, we will display the two axes "OFFSET (arcsec)" vs "LSRK Radio velocity (km/s)" and the treat them as linear axes.
<img width="647" alt="Screen Shot 2021-02-18 at 2 56 12 PM" src="https://user-images.githubusercontent.com/20819712/108317595-7b0a4c80-71f9-11eb-8e82-2b45377787c0.png">


[HD163296_CO_2_1_pv.fits.zip](https://github.com/CARTAvis/carta-frontend/files/6000770/HD163296_CO_2_1_pv.fits.zip)

**Comment by kswang1029** [comment]
as a note, for the frontend development, we will need the specific branch from @pford, which allows loading a pv image successfully.
