### ISSUE TITLE
support raster rendering with rectangular pixels

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1151]
This is mainly for displaying a position-velocity image properly. Sometimes, the aspect ratio of a PV image may be >> 1. If we render it with square pixels, the image is very hard to read. Because position and velocity are two independent quantities, there is no need to keep a pixel as square so that the image can be stretched for better readability. 

<img width="732" alt="Screen Shot 2020-08-24 at 5 28 34 PM" src="https://user-images.githubusercontent.com/20819712/91027966-6163c000-e62f-11ea-8794-b592217272da.png">

**Comment by veggiesaurus** [comment]
@kswang1029 how is this different from #262?

**Comment by veggiesaurus** [comment]
@kswang1029 and @veggiesaurus to discuss
