### ISSUE TITLE
support vector field rendering

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1155]
In order to display polarized intensity and angle properly, the frontend needs to support vector field rendering. 
For each line segment, length and orientation should be supported. For example, orientation is derived from one image (pixel value as angle) and length is derived from another image (normalized pixel value as the rendered length). In addition, block averaging (done by the backend) should be also supported to enhance signal-to-noise ratio.

counterpart backend issue: https://github.com/CARTAvis/carta-backend/issues/1002

Google doc [here](https://docs.google.com/document/d/1S8nNvonlowNwX_uPoPspxugUEnw5wRxbAS6y2HScTzs/edit#)

**Comment by veggiesaurus** [comment]
if we're smart, I think we can just adjust the mip level of the raster data requested from the backend. Then as users zoom in, they'll get more arrows per pixel, but the same _total_ number of arrows. 

For example, if the frontend needs one arrow every 32px, then the backend will downsample the image 32x32 when the image is at 1.0x zoom, and 16x16 when at 2.0x zoom, and so on

**Comment by veggiesaurus** [comment]
> if we're smart, I think we can just adjust the mip level of the raster data requested from the backend. Then as users zoom in, they'll get more arrows per pixel, but the same _total_ number of arrows.

Update: we've opted to generate the overlay at full resolution and stream to the frontend tile-by-tile, in a similar approach to the contour overlay.
