### ISSUE TITLE
File list scrolling broken in Firefox

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#1159]
Scrolling down through the list with the mouse scrollwheel (or trackpad two-finger scrolling) is extremely slow, and once you get to the bottom you can't scroll back up again -- you just keep jumping back to the bottom. Nothing else is affected -- scroll behaviour in the adjacent header window is completely normal. This only happens in Firefox (tested on Ubuntu) -- the scroll behaviour is normal in Chromium.

This warning appears in the console: `This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!`Cursory googling for these keywords leads to various issues which sound similar.

**Comment by veggiesaurus** [comment]
@confluence can you see if this still happens?

**Comment by confluence** [comment]
It appears to be fixed (as of very recently). It's fine in the latest beta.
