### ISSUE TITLE
add stokes dropdown in the histogram widget and the statistics widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1171]
Stokes dropdown needs to be added to the histogram widget and the statistics widget. This allows users to view Stokes analytics independently without using the animator stokes slider.

**Comment by markccchiang** [comment]
Is this feature for version 1.4? It seems not so straightforward to extract the stokes as an independent input parameter for histogram and statistics calculations. Not sure it can be done by this week.

**Comment by veggiesaurus** [comment]
I suggest we leave it out, it's too risky

**Comment by kswang1029** [comment]
ok

**Comment by kswang1029** [comment]
then there is no need to backport the frontend part.

**Comment by kswang1029** [comment]
remove the backport tag and add to v1.5 release.

**Comment by markccchiang** [comment]
The backend branch [mark/stokes_for_stat_and_hist_calc](https://github.com/CARTAvis/carta-backend/tree/mark/stokes_for_stat_and_hist_calc) and protobuf branch [mark/stokes_for_stat_and_hist_calc](https://github.com/CARTAvis/carta-protobuf/tree/mark/stokes_for_stat_and_hist_calc) are ready to test with the frontend.
