### ISSUE TITLE
the desktop instance got killed when killing a remote mode instance

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1179]
reported by two beta testers.

> when running with --remote, starting then closing a second, local instance of CARTA kills the first process as well.

> If I open the desktop and remote versions at the same time, and then press q to close the remote CARTA, it also kills the desktop one.

**Comment by ajm-ska** [comment]
I see why this happens. At the end of the `carta-remote.sh` script we have:

```
### Get the PIDs for the HTTP server and carta-backend

if command -v python3 &>/dev/null; then
  httpserver_pid=$(ps aux | grep ${USER:0:5} | grep '[p]ython3 -m http.server' | awk '{print $2}')
else
  httpserver_pid=$(ps aux | grep ${USER:0:5} | grep '[p]ython -m SimpleHTTPServer' | awk '{print $2}')
fi

carta_pid=$(ps aux | grep $USER | grep '[c]arta_backend' | awk '{print $2}')

### Wait for the user to enter 'q' before exiting
while true; do
    echo -en "Press q to close CARTA:"
    read input
    if [[ $input = "q" ]] || [[ $input = "Q" ]]
        then break
    else
       echo "" 
    fi
done

### Stop the HTTP server and carta_backend processes
kill $httpserver_pid
kill $carta_pid
```

So if the Electron Desktop version is running at the same time as remote mode, it is detected as a second carta_pid and so both (desktop + remote versions) are killed.

I thought of a way for it not to kill the Electron Desktop version. The Electron Desktop version must work with a fixed port number (In the case of the v1.4-beta1b it is `54140`). So we can simply use another grep condition with `-v` to exclude the PID including that port number. i.e.
> carta_pid=$(ps aux | grep $USER | grep '[c]arta_backend' | grep -v 54140 | awk '{print $2}')

This works. The Remote process is terminated and the Desktop version remains running.

The only limitation is that we can only run one Remote session this way. If there were multiple Remote session running, they would also be terminated. I guess it could be improved if we find each remote session's $port or $fport number and put it as another grep condition. e.g.
> carta_pid=$(ps aux | grep $USER | grep '[c]arta_backend' | grep -v 54140 | grep $port | awk '{print $2}')

I suppose that could be another solution to the first problem too. Each Remote session would only be able to find its own PID e.g. 
> carta_pid=$(ps aux | grep $USER | grep '[c]arta_backend' | grep $port | awk '{print $2}')

However, the Python httpserver would be an issue. We would need to somehow associate each httpserver instance with its Remote session. I'm not too sure how to do that yet...
> httpserver_pid=$(ps aux | grep ${USER:0:5} | grep '[p]ython -m SimpleHTTPServer' | awk '{print $2}')

Meanwhile I have a related question. @kswang1029 @veggiesaurus Is it OK that we can only run one Electron Desktop version of CARTA per computer?

**Comment by kswang1029** [comment]
@ajm-asiaa do you mean if we run v1.3.1, we cannot run v1.4, for example?

**Comment by ajm-ska** [comment]
I have an idea. We could make sure the script deals with `carta_pid` first and then `httpserver_pid`. We could add a new loop that checks if there are any `carta_pid` associated with remote sessions still running. If there are are any present then it does not kill any `httpserver_pid`. It would only kill all `httpserver_pid` when there are no remote session `carta_pid` left. That should allow the user to run multiple remote sessions and safely terminate any at any time.

**Comment by ajm-ska** [comment]
@kswang1029 v1.3.1 can run with v1.4 because a different port number is baked into the frontend and Electron. 
However, we can not run v1.4 and v1.4 together.

**Comment by kswang1029** [comment]
@ajm-asiaa i think it is okay to allow only _one_ Electron app. With --remote flag, users can have many instances as they want.

**Comment by ajm-ska** [comment]
I have improved the `carta-remote.sh` script now.

Instead of the line:
`carta_pid=$(ps aux | grep $USER | grep '[c]arta_backend' | grep $fport | awk '{print $2}')`
it is now using the following immediately after the carta-backend start up line:
`this_carta_pid=$!` 
This conveniently picks up PID of the carta-backend that each script starts up.

Then, after the "Press q to close CARTA" part it has:
```
### Stop the remote carta_backend process
kill $this_carta_pid

### Check if there are any other carta_pids (excluding Electron desktop carta_pid)
all_carta_pid=$(ps aux | grep $USER | grep '[c]arta_backend' | grep -v 54140 | awk '{print $2}' | wc -w)

### Only stop all HTTP servers if there are no remote carta_processes running
if [ $all_carta_pid -gt 0 ]; then
       echo "Case 1"    
       echo "Another remote session is still running. Not doing anything.
  else
       echo "Case 2"    
       echo "No other remote sessions are running. Stopping all python httpserver processes
       kill $httpserver_pid
fi
```
I'm just leaving in those echo lines for now so you can see what is going on more clearly.

`all_carta_pid` counts the number of carta-backend processes running by the user, excluding the Electron version.
After the carta-backend process of each remote script is killed, it checks if there are any other remote carta-backend processes running. If there are, it leaves all the user's SimpleHTTPServer processes running. If it detects that there are no other remote carta-backends running, it then it kills all SimpleHTTPServer processes.

So now multiple remote sessions can be started and stopped independently, while the Electron Desktop version remains unaffected.

**Comment by ajm-ska** [comment]
The MacOS version is not affected by this limitation, so no changes need to be made there.

**Comment by veggiesaurus** [comment]
probably fixed by simply running the carta backend without the bundled electron app (e.g. jupyter-notebook approach)
