### ISSUE TITLE
Red indicator of profile is out of bound

### ISSUE THREAD

**Issue by TienHao** [CARTAvis/carta-frontend#1191]
The red indicators of profiles are out of the current plotting area in the following widgets when zoom in:
* Spatial profiler 
* Spectral profiler 
* Stokes analysis 

![indicator](https://user-images.githubusercontent.com/20379662/92071967-b5666580-ede2-11ea-8a6e-7e36fc7df510.png)

**Comment by kswang1029** [comment]
this is regression. we don't see this in v1.3.1
better backport this? @veggiesaurus

**Comment by Kechil** [comment]
Related to #1207
