### ISSUE TITLE
Artifacts when using very large line widths in AST overlay

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#120]
Strange plotting artifacts crop up when using very thick line widths in AST. This will need to be fixed in the canvas plotting wrapper for AST.

![image](https://user-images.githubusercontent.com/592504/50137833-224f6a00-02a5-11e9-92bd-6f35f18d9e0c.png)

**Comment by duidae** [comment]
styleString in OverlayStore -> AST.plot in OverlayComponent -> plotGrid in ast_wrapper.cc -> axis.c or plot.c in ast library, need to check
