### ISSUE TITLE
blending three images with R, G, and B colors

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1204]
as one of the NRAO priorities.

allowing up to three images with each set to R or G or B color then blending them into one pseudo-optical image.

example image (work from Chin-Fei)
![HH212-2017-composite](https://user-images.githubusercontent.com/20819712/92888854-4626ec00-f448-11ea-97d0-5c3f8f6f15f3.jpg)

Requirement document:
https://docs.google.com/document/d/11lT4ZViLw95Jll1PCClxKhsWzvSF9_1caA_n7gwG4hg/edit?usp=sharing

**Comment by kswang1029** [comment]
assuming this does not require backend work. If it needs, please add "requiring_backend" tag.

**Comment by veggiesaurus** [comment]
if we keep the same approach of sending ZFP compressed data, then this is a purely frontend issue.

**Comment by kswang1029** [comment]
A potential issue I could imagine is we might have color bias due to compressed data. The blended color is sensitive to each color channel I suppose.

**Comment by veggiesaurus** [comment]
> A potential issue I could imagine is we might have color bias due to compressed data. The blended color is sensitive to each color channel I suppose.

I'm not sure what you mean by that. Surely for each channel you still need to do a float to R, G or B mapping?

**Comment by kswang1029** [comment]
At different zoom levels, different layers of the tile pyramid (ie different block averaging levels are applied) are delivered to frontend thus we will see the _apparent_ color changes a bit. If the apparent color changes different in different channel, we will see the false color image changing its apparent color too at different zoom levels I guess. I might be overthinking the issue but I will perform some experiments with python to see how good/bad it might be. 

<img width="1489" alt="Screen Shot 2020-11-19 at 7 15 55 PM" src="https://user-images.githubusercontent.com/20819712/99659394-c34f8c80-2a9b-11eb-87d5-c0726c71c941.png">
<img width="1484" alt="Screen Shot 2020-11-19 at 7 15 42 PM" src="https://user-images.githubusercontent.com/20819712/99659411-ccd8f480-2a9b-11eb-8210-30dd61253fb2.png">

**Comment by veggiesaurus** [comment]
oh ok, I see what you mean :thinking: Since the mean downsampling suppresses the extrema, highlights and shadows in a particular channel will be dependent on the zoom level.

**Comment by kswang1029** [comment]
evaluating technical details only (2023/10~12)
