### ISSUE TITLE
Google sign in non-authorized user getting past the dashboard to continuously fail authenticating at the frontend

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-frontend#1214]
When using Google Sign in, a user successfully authenticates with their Institutional Google account, but they are not listed in the `usertable.txt`. They are probably unaware that they are not authorized to access it because it accepted the Google login and began to load the frontend. They might assume something is wrong with the service, and perhaps refreshed their page(?, but ultimately left their browser tab open. Now the node.js log is continuously reporting a message in the following form, every 5 seconds:

> carta-node-server > WS upgrade request from 333.33.3.333 for authenticated user xxx
> carta-node-server > Could not find username xxx in the user map 

That will be a lot of unnecessary messages.

Expected behavior would be for the user to immediately get redirected to the dashboard, with no way to access the frontend, so the messages stop.

**Comment by ajm-ska** [comment]
Could the frontend ping the server or detect if the dashboard html is reachable somehow? 
If so, and if it can still detect/reach it, then it is likely a backend crash. If it can't detect it, then it must be a broken internet connection. Although I have no idea how to do it.

**Comment by veggiesaurus** [comment]
> Could the frontend ping the server or detect if the dashboard html is reachable somehow?
> If so, and if it can still detect/reach it, then it is likely a backend crash. If it can't detect it, then it must be a broken internet connection. Although I have no idea how to do it.

Right, that's what I was thinking :+1:

**Comment by veggiesaurus** [comment]
This issue will be handled in 2.0. Automatic reconnections will be removed in favour of user-driven reconnections (with automatic _resume_ when the reconnection occurs)
