### ISSUE TITLE
layout problem with Stokes widget

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#1220]
When I pin the Stokes widget I get a strange layout.  The whole right side is blank and all the plots are on the left side.

<img width="818" alt="Screen Shot 2020-10-04 at 4 35 02 PM" src="https://user-images.githubusercontent.com/9055533/95029871-5c4b5500-0660-11eb-987f-0d2d9cce50b8.png">

**Comment by kswang1029** [comment]
@arusstaylor are you using safari? If so it is a known issue: https://github.com/CARTAvis/carta-frontend/issues/970

**Comment by veggiesaurus** [comment]
duplicate of #970
