### ISSUE TITLE
file id of moment images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1224]
(Not sure if this is frontend or backend issue)
To reproduce the issue:
1) load set_HD163296/HD163296_CO_2_1.fits
2) create a rectangle region at the center and make moment images
3) match the resulting moment images to the spatial reference (aka HD163296_CO_2_1.fits)
4) regenerate moment images from HD163296_CO_2_1.fits and we will see
![Screen Shot 2020-10-08 at 10 41 26 AM](https://user-images.githubusercontent.com/20819712/95408963-4042fe80-0953-11eb-8060-31f71ba1c3e8.png)

When we re-request a new set of moment calculations, how the file_id of the previous moment image is handled? Do we need "CLOSE_IMAGE" involved?

**Comment by markccchiang** [comment]
@kswang1029  The file_id of the previous moment image will be closed, i.e. via the `CLOSE_IMAGE` command. Does this error messages still appear in the backend branch `mark/refactor_moment_generator`?

**Comment by kswang1029** [comment]
@markccchiang Tested with `mark/refactor_moment_generator`, it works well without those error messages. Close this for now.
