### ISSUE TITLE
Navigate to different channel using the spectral profiler

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#123]
The user should be able to click and drag (or just left click) the channel indicator in the spectral profiler to change the active channel

![image](https://user-images.githubusercontent.com/592504/50138391-241a2d00-02a7-11e9-9ea9-9e22cbdc3956.png)

**Comment by arusstaylor** [comment]
Agreed.  This is a desirable feature. An intuitive way to change channels based on features in the profile.

**Comment by duidae** [comment]
From Angus:

1. Make the draggable marker equivalent to the slider's marker (based purely on the requested channel). This will make the dragging much smoother (see below for demo based on quick hack.. the jumps there were due to me clicking)

2. Show another (non-draggable) marker to indicate what the current channel is. If the two are identical, only one will be shown in any case

3. When dragging, hide the "cursor" marker, since it's no longer needed, and will be behind the requested channel marker at all times.

**Comment by veggiesaurus** [comment]
_(@duidae sorry, I should have put the comment here :slightly_smiling_face: ) Here's the full comment:_

I agree, we should make it consistent. The other thing I've been thinking is that there's a problem with the profiler's marker at the moment: 
- The slider's position is based on the _requested channel
- Dragging the slider changes the _requested_ channel
- The marker's position is based on the _current_ channel
- Dragging the marker changes the _requested_ channel
This leads to jumpy behaviour when the requested channel is not equal to the current channel

![markers_comparison](https://user-images.githubusercontent.com/592504/54016298-1203a880-418b-11e9-8092-58392655c283.gif)

I propose we do the following: 
- Make the _draggable_ marker equivalent to the slider's marker (based purely on the _requested_ channel). This will make the dragging much smoother (see below for demo based on quick hack.. the jumps there were due to me clicking)

- Show another (non-draggable) marker to indicate what the current channel is. If the two are identical, only one will be shown in any case 
- When dragging, hide the "cursor" marker, since it's no longer needed, and will be behind the requested channel marker at all times. 

![marker_requested](https://user-images.githubusercontent.com/592504/54017181-dcac8a00-418d-11e9-9141-95de8d4fe4cd.gif)

**Comment by duidae** [comment]
so I think the remaining features would be:
1. disable grey moving marker when dragging
2. disable dragging function when playing animator

right?

**Comment by veggiesaurus** [comment]
@duidae yes I think that's all that's still required. Also need to disable clicking when playing the animator

**Comment by duidae** [comment]
@veggiesaurus ok!
