### ISSUE TITLE
Scripting: expose device pixel ratio in an attribute

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#1231]
The wrapper needs to know the device pixel ratio being used by a particular session so that it can adjust pixel sizes appropriately in action calls like setting the view dimensions, and ultimately get the same image output no matter what browser is being used.

**Comment by veggiesaurus** [comment]
@confluence didn't I do this already?

**Comment by confluence** [comment]
Yes, I think you did -- the scripting issue still needs work, but I think this one can be closed.
