### ISSUE TITLE
misalignment of UI elements

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1233]
potentially due to https://github.com/CARTAvis/carta-frontend/pull/1222

some UI elements are misaligned horizontally or vertically. e.g.,

![Screen Shot 2020-10-22 at 4 17 53 PM](https://user-images.githubusercontent.com/20819712/96844706-6489f980-1482-11eb-8876-7e48f96d1b94.png)
![Screen Shot 2020-10-22 at 4 18 22 PM](https://user-images.githubusercontent.com/20819712/96844707-65229000-1482-11eb-9df9-9799b19ca22d.png)
![Screen Shot 2020-10-22 at 4 17 40 PM](https://user-images.githubusercontent.com/20819712/96844688-60f67280-1482-11eb-93dc-9122daab365c.png)
![Screen Shot 2020-10-22 at 4 22 54 PM](https://user-images.githubusercontent.com/20819712/96845216-09a4d200-1483-11eb-97f3-3aea9b799006.png)
![Screen Shot 2020-10-22 at 4 23 45 PM](https://user-images.githubusercontent.com/20819712/96845223-0b6e9580-1483-11eb-9789-e23ccf3429e3.png)

**Comment by veggiesaurus** [comment]
@kswang1029 can you check if this regression is definitely due to #1222? It changed the way SCSS files were compiled to CSS, so it could be a likely candidate :thinking:

**Comment by kswang1029** [comment]
With the help from @ajm-asiaa (:rocket:), likely it is due to #1222. 
This frontend branch from the 6th October (e07a005) before #1222 works fine.
http://carta.asiaa.sinica.edu.tw/frontend/e07a005/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev
