### ISSUE TITLE
Catalog tool: Enhanced marker-based visualization

### ISSUE THREAD

**Issue by low-sky** [CARTAvis/carta-frontend#1237]
Allow for more catalog columns to be mapped to marker properties:

- Size of plotting symbol
- Colour of plotting symbol
- Orientation of plotting symbol

Build user interface to set transform between marker properties and catalog entries.

**Comment by kswang1029** [comment]
@low-sky A question:
for size/color/orientation mapping, I suppose we will only accept numeric columns (not string columns) as input, right? Then we can set up normalization via the GUI. Do we expect to support mapping with string columns?

**Comment by low-sky** [comment]
Yes, just numerical columns.  Sometimes you do want to do text annotation (e.g., source number) but just numerical initially.

**Comment by veggiesaurus** [comment]
Size and color are easy enough, but orientation will require a switch from plotly to our own custom built WebGL plotting library

**Comment by kswang1029** [comment]
if orientation is really required, the storypoint should be increased (currently 5).

**Comment by low-sky** [comment]
As noted in discussion with @panchyo0, we will need some controls for mapping numerical values to ranges.  A good example of this is for colour where the already have some tools in the render configuration for the image browser.  We'll want some similar functionality for colour, namely ability to set min and max of ranges considered, colour table for the points, and ideally the transform between numerical value and the output numerical value (i.e., log, sqrt, linear, etc.).

For size, we'll want to be able to do similar mapping (min and max of range considered) but also some tools on the control of the transform (i.e., does the value map to radius or area of circle; log transform of data, etc.).

**Comment by Jordatious** [comment]
It would be nice to increase this functionality and plot log axes, for example. Not sure why we need orientation of markers. I would have thought that's much less a priority than other basic plotting functionality.

**Comment by low-sky** [comment]
Orientation of markers is useful for plotting things like source catalogues for objects with major, minor axes and position angles.

**Comment by Jordatious** [comment]
Wouldn't that be less markers and more ellipses? Many source finders that write those properties to catalogues also write ds9 region files, which CARTA could import. I agree it'd be useful, but I'd prefer to see more basic plotting functionality added first.

**Comment by panchyo0** [comment]
closed with PR #1401
