### ISSUE TITLE
Catalog tool: ellipse plotting symbols

### ISSUE THREAD

**Issue by low-sky** [CARTAvis/carta-frontend#1239]
Allow catalogs to plot ellipses with catalog columns mapping to ellipse major and minor axis as well as orientation.

**Comment by low-sky** [comment]
Should also include arrows and lines in this category to support plotting of vector fields and pseudovectors

**Comment by veggiesaurus** [comment]
This is a major issue, because it would require us to do our own plotting, rather than using an existing plotting library, such as plotly.

**Comment by low-sky** [comment]
Unfortunately, oriented markers are going to be essential for the polarization use case and are helpful for other visualization cases too.  This can slide into another version but I think will be important.

**Comment by panchyo0** [comment]
@low-sky after PR #1401, we have ellipse and line shape supported for catalog. Could you please create another issue for arrow?
