### ISSUE TITLE
clip level

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#124]
shell we change "limits" to "clip" for better consistency?

<img width="350" alt="screen shot 2018-12-19 at 10 04 01" src="https://user-images.githubusercontent.com/20819712/50194390-96f1d980-0375-11e9-9fac-0530d2c4a536.png">

**Comment by veggiesaurus** [comment]
@kswang1029 what about:
- Limits -> Clip Percentile
- Min -> Clip Min
- Max -> Clip Max

to make it clear that we're referring to the clipping, rather than the graph range

**Comment by kswang1029** [comment]
Good idea! It is clear!
