### ISSUE TITLE
Catalog tool: Simple regressions and summary statistics

### ISSUE THREAD

**Issue by low-sky** [CARTAvis/carta-frontend#1240]
- Be able to report the slope and intercept of a linear fit to a selected region or subpopulation in a bivariate plot.
- Be able to report summary statistics for data in bivariate or histogram plots (e.g., mean flux density of selected sources, where flux density is a column in the catalog).

**Comment by veggiesaurus** [comment]
I think this should be split into two separate issues

**Comment by low-sky** [comment]
In discussion with, @panchyo0, I note that it would be good to toggle drawing the line of regression onto the scatter plot.
