### ISSUE TITLE
shortcut naming consistency

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#125]
toggle dark theme --> toggle dark/light theme

toggle frozen cursor: with F, it can freeze and unfreeze. Do we have a better term?

Open file --> Open image (same in File)
Append file --> Append image

add "Export image" cmd+E
<img width="468" alt="screen shot 2018-12-19 at 14 44 54" src="https://user-images.githubusercontent.com/20819712/50203584-fa433200-039c-11e9-9274-453243a6cc50.png">

**Comment by veggiesaurus** [comment]
Some possibilities:
- "Freeze/unfreeze cursor position"
- "Toggle cursor movement"
- "Toggle fixed cursor position"

**Comment by kswang1029** [comment]
What it actually does is to stop updating the profilers along the movement of the cursor. Maybe option 1 is closer?
