### ISSUE TITLE
Feature request: Open multiple files via file browser

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta-frontend#1250]
I can open and append multiple files via the debug menu with something like:

```
openFile("B6/fullcubes_12m/G337.92_B6_spw4_12M_spw4.image")
appendFile("B6/fullcubes_12m/G337.92_B6_spw4_12M_spw4.residual")
appendFile("B6/fullcubes_12m/G337.92_B6_spw4_12M_spw4.model")
```

It would be nice if we could select these with the usual shift-click or control-click interface in the file browser menu.

Comparing image, residual, and model is a common use case when inspecting clean cubes.

**Comment by veggiesaurus** [comment]
adding to V2.0, since this is a prerequisite for the Stokes support in https://github.com/CARTAvis/carta-backend/issues/611

**Comment by keflavich** [comment]
would it be valuable for me to cross-post this on https://github.com/CARTAvis/carta/issues/?

**Comment by veggiesaurus** [comment]
> would it be valuable for me to cross-post this on https://github.com/CARTAvis/carta/issues/?

I've migrated it here because it's specifically front-end related
