### ISSUE TITLE
Frontend chokes when loading region files with a large number of regions

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#1252]
After @pford fixed https://github.com/CARTAvis/carta-backend/issues/505, it looks like the issue now resides on the frontend. Loading a region file with ~3000 ellipses causes the frontend to completely choke. Memory usage keeps crawling up and CPU usage is around 100%

**Comment by veggiesaurus** [comment]
it seems that the initial loading choking is mostly due to the region list widget. If this is closed beforehand, then it seems to be _slow_ at loading, but still manages to load a 500 region file. But after loading, it's still unusable due to rendering all those regions inefficiently.

**Comment by veggiesaurus** [comment]
@Jordatious this is the issue you were describing. I agree its rather embarrassing...

**Comment by veggiesaurus** [comment]
Also raised by @arusstaylor in a separate issue.

**Comment by veggiesaurus** [comment]
I suspect the only solution to this issue is to use konva without the react wrapper when rendering regions. This would require quite a large rewrite

**Comment by veggiesaurus** [comment]
I think we can close this once the region list improvements are done

**Comment by duidae** [comment]
choke part fixed in https://github.com/CARTAvis/carta-frontend/pull/1664
region list part duplicate with #1694

**Comment by kswang1029** [comment]
see #1694 for a solution.
