### ISSUE TITLE
support LEL in the file browser

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1264]
This is to replicate the LEL (lattice expression language) support of the file browser in casaviewer. Users can enter an expression in a text field so that a new image can be formed dynamically. The relevant backend issue is: https://github.com/CARTAvis/carta-backend/issues/665

intro of LEL: https://casa.nrao.edu/casadocs/casa-6.0/imaging/image-analysis/lattice-expression-language-lel/lattice-expression-language

**Comment by pford** [comment]
Screenshot of viewer file browser, to load image aJ.fits with values squared.  "LEL expression" text input only appears when LEL checkbox is checked.
![viewer_filebrowser_lel](https://user-images.githubusercontent.com/856604/100281506-4868f480-2f27-11eb-90cf-2e4f5776e39f.png)
