### ISSUE TITLE
shortcut button conflict for launching the catalog file browser 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1269]
users feedback:

"Import catalog" is mapped to cmd+C. This is a terrible idea, because that is also the command for Copy. So every time I want to copy information from the statistics window, or the region window, I get the catalog navigator. Please, please, please change this.

**Comment by veggiesaurus** [comment]
@kswang1029 can you check if there are any other commonly used shortcuts that we're abusing?

**Comment by kswang1029** [comment]
will do. I will check macOS and ubuntu. Self-assigned for investigation.

**Comment by kswang1029** [comment]
Some notes:
1. When using macOS and a browser (either Safari, Chrome, or Firefox) to access a remote server (eg mix n match page), the CARTA shortcuts work fine as it use "ALT" key instead of mac's "CMD".
2. **Import catalog** needs a new shortcut as CMD+C or CTRL+C conflict with copy
3. When using CARTA in Linux VM on Mac, CTRL+UP/DOWN (changing channel) conflicts with macOS's "mission control".
4. When running CARTA remote in Linux VM on Mac and accessing it with a browser from macOS, CTRL is used.
5. When using Scientific Linux and Firefox to access the mix n match page, ALT is used. Native electron app uses CTRL.

I wonder if we want to unify the shortcuts with ALT exclusively so that the UX will be consistent among different OS and the way how CARTA backend is accessed. The cons for this would be ALT is not a common key adopted in macOS (using CMD) and Linux (using CTRL). Or can item 1 be using CTRL instead?

UPDATE: it sounds like we still can have either CMD or CTRL or ALT depending on the environments and we will just need to address item 2 and 3

**Comment by kswang1029** [comment]
Looks like using "G" is safe for **Import catalog**. We cannot use "T" as it means a new tab in browsers.

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 Sure, let's change to CMD+G. Any suggestion for item 3? How about changing to "shift+up/down"?

**Comment by kswang1029** [comment]
let's focus on catalog shortcut for now. item 3 needs some careful thoughts. Once catalog shortcut is fixed please file a PR and I will test.

**Comment by kswang1029** [comment]
item3 can be addressed in #1143
