### ISSUE TITLE
Changing order of images does not change order in animator

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta-frontend#1270]
I can change the order of images using the Image List tool.  In the animator, if I drag the tracker box left to right, it does the expected thing and obeys the order given in Image List.  However, if I use the Next/Previous tool, it retains the order in which the files were loaded instead of the modified order in Image List.

**Comment by kswang1029** [comment]
This issue is blocked by https://github.com/CARTAvis/carta-frontend/issues/1329 where the play button is not functional for the image iterator.

**Comment by kswang1029** [comment]
A set of test images for this issue is available in `set_dice` where there are six images as the "dice".
