### ISSUE TITLE
image artifacts seen in model/clean component images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1271]
User feedback:
> Carta sometimes shows a color that does not correspond to the
pixel value.  See the attached screenshot.
The colourscale goes from -0.002 to 0, so all 0 pixels should
be the lightest colour.  The cursor is over a pixel which
is a fairly different color, suggesting a value significantly
<0, but the cursor readout at top says "0.0".  casa viewer
and imstat agree that the actual value of pixel 5013,6481
is in fact 0.0, so it is the color shown by CARTA that is
in error. [This is a "model" image, so most of the pixels
are in fact identically 0.0]
I tried changing "compression quality" to 30, but there was no
change in the rendering.
This seems like a fairly large error, ~25% of selected color
range.

![CARTA_screenshot](https://user-images.githubusercontent.com/20819712/101312813-ad114100-388f-11eb-87a1-5b9c4cdd7665.png)

The user also suggested to turn off zfp compression for the bottom two layers of tiles.

**Comment by kswang1029** [comment]
@kswang1029 to explore all compression quality parameters to see how artifacts change

**Comment by kswang1029** [comment]
@veggiesaurus I have done some tests with a point source model image (one pixel as 10 and others as 0) and with different raster compression quality parameters.

For an image with 2816x2816 pixel (2816=256x11, point at tile center), starting from compression quality=**13** we won't see any defects at any zoom level with all different clip levels. With an image with 2560x2560 pixel (2560=256x10, point at tile edge), the conclusion is the same.
![Screen Shot 2020-12-16 at 2 52 37 PM](https://user-images.githubusercontent.com/20819712/102315044-69fd4f00-3fae-11eb-81f9-cdab433f8e7d.png)
![Screen Shot 2020-12-16 at 2 52 49 PM](https://user-images.githubusercontent.com/20819712/102315038-679af500-3fae-11eb-8211-f3542a2a439f.png)

So I think we should increase the default compression quality (static image) from 11 to 13 and set 13 as the lower bound of the spin box so that users won't have the chance to trigger this issue accidentally.

**Comment by kswang1029** [comment]
UPDATE: if the pixel value is 100, we need 15 to remove the defect. This seems to scale with the contrast (as expected).

**Comment by kswang1029** [comment]
@veggiesaurus I made a set of test images with a size of 2560x2560 and have a point source at the image center (but from tile perspective it is at the tile corner). With different pixel values, we need different compression quality parameters in order to not seeing artifacts with log scale (alpha=1000) and 90% clip (this is the setup to be able to see artifacts easily).

```
render with log, alpha=1000 (90% clip)
pixel_value	minimal_compression_quality
0.0001		20
0.001		19
0.01		20
0.1		17
1		11
10		13
100		15
1000		17
10000		18
100000		19
1000000		18
10000000	20
```
To solve this issue, we might do one of the following:
1) judging from the histogram distribution (which I don't know how to yet) and apply a dynamic compression level based on the lock up table above
2) change the default compression level from 11 to 20
3) change compression level only to the bottom tile layer
4) else?

**Comment by veggiesaurus** [comment]
I don't think changing the compression setting to 20 my default is a valid option, it will dramatically increase transfer size

**Comment by kswang1029** [comment]
How about we use the per-channel histogram and if more than 90%(this is just a wild guess and might need some experiments) of pixels concentrates in the bin containing 0, the backend overwrites the default compression quality from 11 to 20 (or the default+9 and up to 32)? This check is done on per-channel basis. If this approach is feasible, then this requires backend work instead of the frontend.
