### ISSUE TITLE
Initial support for saving/restoring/sharing of workspaces (frontend)

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-frontend#1272]
As an extension to layouts, states are a full CARTA session, including the images loaded, render settings, animator status etc.
It should be possible to save such states and reload them. 

Associated backend issue https://github.com/CARTAvis/carta-backend/issues/1185

Initial work for v4 beta1: (edit by @veggiesaurus)

- treat workspaces like layouts, in the sense that we have a list of them in CARTA, and stored in .carta/config or .carta/workspaces  (and in the database for controller users) This allows us to build up the functionality easily via the API stuff on the backend, and it will ensure that it works well for the controller and standalone.
- exporting/importing will be done manually at first (e.g. copy-pasting to the carta folder)
- temporary things (e.g. PV, moment images that haven't' been saved) don't get persisted

Working schema [here](https://cartavis.org/schemas/workspace_schema_1.json)

Things to save:
- CARTA version
- ~~Layout, including docked widgets, floating widgets, and dialogs. This defines a set of active widgets and dialogs to be restored.~~ deferred
- ~~The states of control UI elements in each active widget or dialog~~ deferred
- Preferences ?
- A list of loaded images
- A list of regions
- ~~A list of loaded catalogs~~ deferred
- ~~A list of catalogs retrieved from remote services (either we keep the recipes of query or we keep a copy of remote catalogs as part~~ deferred

**Comment by arusstaylor** [comment]
not only reload them but capture the state and share it.
