### ISSUE TITLE
Make carta-frontend installable through apt with all dependencies.

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#1273]
Aims:

* A single PPA with all CARTA components and dependencies packaged.
* This should probably be a pre-built version which does not depend on an npm install -- needs further investigation. Installing through npm should remain as a separate option.

This will probably be simplified if we can serve the frontend from the backend (using functionality in the new uWebSockets library)

This should be part of an epic, together with the corresponding issues in other components.

**Comment by kswang1029** [comment]
@veggiesaurus @confluence can we close this now?
