### ISSUE TITLE
fail to resume a session when in-memory moment images exist

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-frontend#1277]
Reproduce: 
Open a cube image and request some moment images. Disconnect the back-end and reconnect it. The front-end will ask user whether to resume, but it will be failed on both server or desktop carta.

Testing:
The resume functionality is good while we have several images which is load from file.

**Comment by duidae** [comment]
> need warning on frontend and to skip generated images such as moment map (and eventually PV)

![image](https://user-images.githubusercontent.com/25971696/109759270-b3f9e680-7c27-11eb-8735-c90563b3c5f9.png)

@kswang1029 the in-memory moment map images will be ignored when resuming session & append warnings as above, btw want to make sure: are PV images not able to be resumed either?

**Comment by kswang1029** [comment]
Yes, if the PV image is in-memory too. For v3.0, we will be able to generate a PV image from the GUI. This image will be in-memory and users can decide to save it to disk with "Save image". 

If users "load" a regular PV image from disk to CARTA, we will need to include it when resuming a session.
