### ISSUE TITLE
spectral matching with different conventions in the headers

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1283]
When exporting an image to a FITS file in CASA, there is an option to set the spectral convention as velocity in the header. So in principle we should see the original image and the exported image are perfectly matched with each others. However, we see an offset in the matched channel index. 
![Screen Shot 2020-12-23 at 1 44 32 PM](https://user-images.githubusercontent.com/20819712/102964095-c2d86480-4525-11eb-8c16-639897505a05.png)

[test image](https://drive.google.com/file/d/1yteh2a7EXNLMzcStOmmWxg3BUYu8hufY/view?usp=sharing)

**Comment by veggiesaurus** [comment]
off by one channel?

**Comment by kswang1029** [comment]
By a lot. The two red lines in the screenshot should be at the same channel (the profiles are identical).

**Comment by veggiesaurus** [comment]
the spectral matching is done by AST based on the headers. Is it possible that the backend is passing incorrect headers for the CASA image?

edit, no wait. I just re-read the issue. It's just the channel matching that seems to be the issue

**Comment by veggiesaurus** [comment]
The issue is in `getTransformedChannel` (and I assume will be the same in `getTransformedChannelList`). When we set the `FREQ` based image to use the same matching type as the other image (`VRAD`), AST needs to choose a new unit as well. Since we normally _display_ things as km/s, that's what it picks. But the `VRAD` image has its units in m/s, so the spectral matching is off by a factor of 1000.

The solution is to also set the correct units between both images

**Comment by kswang1029** [comment]
> The issue is in `getTransformedChannel` (and I assume will be the same in `getTransformedChannelList`). When we set the `FREQ` based image to use the same matching type as the other image (`VRAD`), AST needs to choose a new unit as well. Since we normally _display_ things as km/s, that's what it picks. But the `VRAD` image has its units in m/s, so the spectral matching is off by a factor of 1000.
> 
> The solution is to also set the correct units between both images

So I guess if the header is defined in wavelength we need to provide a correct unit too.

**Comment by veggiesaurus** [comment]
> > The issue is in `getTransformedChannel` (and I assume will be the same in `getTransformedChannelList`). When we set the `FREQ` based image to use the same matching type as the other image (`VRAD`), AST needs to choose a new unit as well. Since we normally _display_ things as km/s, that's what it picks. But the `VRAD` image has its units in m/s, so the spectral matching is off by a factor of 1000.
> > The solution is to also set the correct units between both images
> 
> So I guess if the header is defined in wavelength we need to provide a correct unit too.

Luckily we have a map for default units already thanks to @duidae
