### ISSUE TITLE
File Browser not sorting directories in alphabetical order

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-frontend#129]
When we use the File Browser to sort the File Name in either ascending or descending alphabetical order, it only sorts the files in a directory. It does not sort the directories. The directories seem to be in a random order. 

It is particularly noticeable now that we are using folder=$HOME as the root for the File Browser. I expect many users will have a lot of directories there.

I think it should sort the directories in ascending or descending alphabetical order, while keeping directories separate from the files, as it does now. 
e.g.
a/
b/
c/
a.fits
b.fits
c.fits

(Using latest Mac version: alma.asiaa.sinica.edu.tw/_downloads/CARTA-v1.0-beta4.dmg )

**Comment by veggiesaurus** [comment]
good find :+1: Will fix it now
