### ISSUE TITLE
new feature: allow user to change the velocity reference for WCS matching of cubes 

### ISSUE THREAD

**Issue by jehibbard** [CARTAvis/carta-frontend#1306]
We can match cubes in the spectral axis either by frequency, by channel, or by radio or optical velocity.  The latter are matched to the cube by using either a redshift for the object, or a rest frequency for a line (I suspect its by RESTFREQ). 

Problems arise when trying to register cubes of the same object that have incompatible values for the redshift, or a missing redshift. In this case, the spectral features in one cube will not properly overlay with the other. I will give an example later.

This ticket is a request to display the reference in the image list widget where the WCS registration/matching is enabled, and allow the user to change it. 

An example dataset where problems occur is from the ALMA archive, project code 2017.1.00079.S, where the 12m and 7m cubes of the 12CO(1-0) emission do not overlap if matching by Vrad. 
e.g. 12m SBname=M83_e_03_TM1
product = member.uid___A001_X1295_X35.M83_sci.spw21.cube.I.pbcor.fits
(header stays VELREF = 257, RESTFREQ=1.1500000E+11 Hz ALTRVAL=2.902229E+06 ALTRPIX=1.0)
register with 7m SBname=M83_e_03_7M
product = member.uid___A001_X1295_X37.M83_sci.spw16.cube.I.pbcor.fits
(header stays VELREF = 257, RESTFREQ=1.15271202E+11 Hz ALTRVAL=8.44435E+05 ALTRPIX=1.0)

If you contour the 7m, and append the 12m with z registration using Vrad, the contours do not overlay, presumably b/c they have different values for RESTFREQ. They do overlay if you change your preferences to make spectral matching=Frequency.

**Comment by jehibbard** [comment]
Another use-case would be when different spectral lines appear in the same cube (e.g.  13CO @110.20GHz & C18O @109.78GHz, or H13CO+ @88.75GHz & HCO+ @89.19GHz). If the requested feature is implemented so that multiple zeropoints/restfrequencies can be specified for the same cube, then the user would be able to see both these profiles plotted in the same velocity scale. That would argue for implementing changing the zero-point in the spectral profile widget (so the scope is the plotted spectra) rather than the image list (where the scope would be the entire cube).

**Comment by jehibbard** [comment]
I think this feature has to allow over-riding the value of the RESTFREQ in the header (for the case that there are multiple species in the same cube) as well as ALTRVAL/ALTRPIX (for the case where there are multiple kinematic systems in the same cube, e.g. HI observations of groups/clusters).

**Comment by kswang1029** [comment]
A useful reference https://www.aanda.org/articles/aa/pdf/2006/05/aa3818-05.pdf

**Comment by veggiesaurus** [comment]
changing this to a 3, because we can rely on AST for most of the calculations. It's more a matter of the UI
