### ISSUE TITLE
show warning to users when spatial matching failed & get AST error

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#1312]
to reproduce:
1. open a file with NAXIS3=stoke NAXIS4=FREQ
2. append a file with spectral axis
3. click XY matching

P.S.  the file in (1) has the headers as below (I renamed the file to multi-stoke so dont know what's the original file name):
![image](https://user-images.githubusercontent.com/25971696/107001106-06c8b580-67c4-11eb-8e3b-4af7721f3329.png)

![image](https://user-images.githubusercontent.com/25971696/107000924-af2a4a00-67c3-11eb-82e6-5149682f8a3a.png)

**Comment by veggiesaurus** [comment]
Any two images? Do they overlap at all?

**Comment by duidae** [comment]
i suspect the issue is caused by incorrect assumption that the freq axis is the 3rd axis and AST gives error when matching:
![image](https://user-images.githubusercontent.com/25971696/107001589-d897a580-67c4-11eb-88dd-1b6e696911b1.png)

**Comment by duidae** [comment]
image file in (1)
[multi-stoke.zip](https://github.com/CARTAvis/carta-frontend/files/5930758/multi-stoke.zip)

**Comment by kswang1029** [comment]
> image file in (1)
> [multi-stoke.zip](https://github.com/CARTAvis/carta-frontend/files/5930758/multi-stoke.zip)

the image is `set_HH211/HH211_IQU_zoom_4ch.image.pbcor` (CASA image format)

**Comment by kswang1029** [comment]
with dev+dev I tried two images as ra-dec-freq-stokes and ra-dec-stokes-freq, both spatial and spectral matching work. 🤔 could you attach your "0test.fits"?

**Comment by duidae** [comment]
[0test.zip](https://github.com/CARTAvis/carta-frontend/files/5931023/0test.zip)

**Comment by kswang1029** [comment]
The two images are at non-overlapping different hemispheres. So what you see is expected. 
![Screen Shot 2021-02-05 at 4 15 32 PM](https://user-images.githubusercontent.com/20819712/107007364-65466180-67cd-11eb-8671-11a5ece325f7.png)
![Screen Shot 2021-02-05 at 4 15 21 PM](https://user-images.githubusercontent.com/20819712/107007374-68d9e880-67cd-11eb-9951-57aee290ef96.png)

**Comment by kswang1029** [comment]
related to https://github.com/CARTAvis/carta-frontend/issues/719 and https://github.com/CARTAvis/carta-frontend/issues/587

**Comment by duidae** [comment]
why cant i see the AST grid? mine is different from the above image

**Comment by kswang1029** [comment]
> why cant i see the AST grid? mine is different from the above image

the two images are _before_ spatial matching. After triggering spatial matching, the grid of "0test.fits" cannot be generated due to the error your see from AST, thus empty.

**Comment by veggiesaurus** [comment]
I'm not sure what the solution is. It's rather confusing to the user to just see nothing. What if we automatically disable spatial matching if this occurs?

**Comment by kswang1029** [comment]
I suggest we catch the error and display a message why. Checking if two images (more precisely their WCS even beyond the image FOV) are matchable is a bit tricky.
