### ISSUE TITLE
widget cannot be created by drag-to-dock operation

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1318]
this seems to be the 2nd regression (https://github.com/CARTAvis/carta-frontend/issues/584).

The drag-to-dock way of creating a new widget is broken in dev.

The following is with v1.4 as a demo of how it should work.
https://user-images.githubusercontent.com/20819712/108319722-c540fd00-71fc-11eb-80ef-d820a7438a68.mp4

**Comment by veggiesaurus** [comment]
@kswang1029 any chance you can check which commit broke this? This seems to be broken for all widget types, so I suspect it's different to #584

**Comment by kswang1029** [comment]
starting from PR https://github.com/CARTAvis/carta-frontend/pull/1285
the previous PR https://github.com/CARTAvis/carta-frontend/pull/1284 works fine.

**Comment by veggiesaurus** [comment]
ok, then I'll assign it to @duidae

> starting from PR #1285
> the previous PR #1284 works fine.

**Comment by duidae** [comment]
#402
