### ISSUE TITLE
animation playback not working for the image iterator in the animator

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1329]
To reproduce, load two images, select the image radio button in the animator and click the play button. 

The frontend does not send out START_ANIMATION message to the backend. It does send out the message if it is channel or stokes.

**Comment by veggiesaurus** [comment]
Image animation is front-end only, so it shouldn't be sending anything. any messages in the dev console?

**Comment by kswang1029** [comment]
when the button is clicked, no new message is seen in the console.

**Comment by kswang1029** [comment]
` ksw/test_image_playback ` provides a one-liner fix to the issue. @veggiesaurus would you have a look to see if that makes sense when you have time?

UPDATE: same branch might fix https://github.com/CARTAvis/carta-frontend/issues/1270 too.
