### ISSUE TITLE
[file browser] File Browser presents cached file list when backend not running

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-frontend#133]
When the backend crashes or quits (press 'q'), the user can click "Open Image" and get a file list. Clicking an item in the file list displays "Cannot open file!" with subtext "Error: Could not send event".  This leaves the user wondering why they cannot open an image which worked before, or why new images copied or linked in the directory are not listed.  There is no way to tell that the backend is no longer running; the error message is confusing to the user.  This issue happens with both the desktop app and the remote version.

**Comment by kswang1029** [comment]
Can we add an icon (red/green light) to the upper-right corner of the GUI window to indicate the status of the backend? Maybe we need a "handshake" message which is exchanged regularly between the frontend and the backend?

**Comment by veggiesaurus** [comment]
That sounds like a good idea. We should also display an alert when the connection is dropped or the backend crashes
