### ISSUE TITLE
validate preferences.json and layout.json then apply error handling when needed

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1335]
PR https://github.com/CARTAvis/carta-backend/pull/746 introduces saving config files preferences.json and layout .json to the .carta folder. (Note the same issue already exists if users edit localStorge from browser)

These json files might be edited by users and might be edited so that some attributes are not understandable by the frontend resulting that frontend is initialized in an unexpected state (eg empty layout). We will need a way to catch exceptions and apply a default value. For example, in the preferences.json I set a wrong colormap to "jettt" then the frontend should catch it and apply a default colormap such as inferno.

**Comment by veggiesaurus** [comment]
@duidae can you take care of this? It should be pretty easy to just warn the user and apply default layout

**Comment by duidae** [comment]
ok
