### ISSUE TITLE
Popovers displayed on top of the splash screen

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#1346]
Popovers are displayed on top of the splash screen when the backend is disconnected.
![image](https://user-images.githubusercontent.com/43841102/110425859-06337f80-80e0-11eb-92bc-780721d29cd9.png)
![image](https://user-images.githubusercontent.com/43841102/110426348-e81a4f00-80e0-11eb-802d-d635883c1e7f.png)
This may be related to the `z-index: 999 !important;` settings in src/App.scss.

**Comment by acdo2002** [comment]
@kswang1029 I have tested this issue. 
Currently we have alter dialog (with "Retry" confirmButton) when the carta_backend is disconnected:
![carta-disconnection](https://user-images.githubusercontent.com/34430648/149898665-7ad22c3b-d381-4cdd-ac34-4eda28a02311.png)

So the popover display problem has been disappeared with current frontend design (confirmed/discussed with YuHsuan).

**Comment by kswang1029** [comment]
@acdo2002 ok thanks for analyzing the problem.
