### ISSUE TITLE
[frontend frozen] cursor position on a wide field image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#135]
with the demo server and the test image: 18h03m_tabular_axis.image

when the cursor points to a position **outside** the celestial sphere, the frontend (even the entire browser) becomes frozen.

If the cursor points at the region inside the rectangle and outside the circle, the frontend becomes frozen.
![screen shot 2019-01-14 at 11 24 33 am](https://user-images.githubusercontent.com/20819712/51095362-30829e80-17ef-11e9-8305-b2bbba6515d2.png)

Also confirmed that with other small FOV images, if we zoom all the way out to see the celestial sphere and point the cursor outside the sphere, the frontend becomes frozen. I believe this issue can be linked to issue #66

**Comment by veggiesaurus** [comment]
@kswang1029 I fixed this in comment bf57d48295f6e906c265fd3b23031a9ae3ce35e5. Can you re-test with an updated build?

**Comment by kswang1029** [comment]
@veggiesaurus Yes, tested and it is working well now. There is another backend issue with this image: if by panning and zooming to make the image totally outside the FOV, backend will crash. I will file an issue to the backend repo and I think we are okay to close this frontend one. 👍
