### ISSUE TITLE
log and power scaling function mapping issue

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1351]
With some discussions with @YuHsuan-Hwang when implementing a colorbar (https://github.com/CARTAvis/carta-frontend/issues/601) to the image viewer, we think the current log and power scaling functions do not map value [0, 1] to [0, 1] exactly. Rather, they map the value [0, 1] to [0, ~<1] when the control parameter "alpha" is large enough. However, if users define a small alpha such as 10, the upper bound will be significantly less than unity (e.g. if alpha=10, log scaling function gives 0.954). This results in color saturation for those values mapped above that upper bound.

To retain consistency, the log and power functions should be modified to
<img width="146" alt="Screen Shot 2021-03-16 at 1 40 53 PM" src="https://user-images.githubusercontent.com/20819712/111261319-430df200-865d-11eb-9b25-3b9158db4318.png">

The impact to the current users should be negligible as the default alpha is large enough. Note that after the change, the log and power scaling functions will be slightly different from the ones from ds9 where original we quote the formulae there.

**Comment by kswang1029** [comment]
@veggiesaurus do you think we can make the change here? The shader code needs some tiny changes too. eg https://github.com/CARTAvis/carta-frontend/blob/4b7a4ca26970eccb93ad1e8211875585193628f5/src/services/GLSL/pixel_shader_raster.glsl#L70
and
https://github.com/CARTAvis/carta-frontend/blob/4b7a4ca26970eccb93ad1e8211875585193628f5/src/services/GLSL/pixel_shader_raster.glsl#L73

**Comment by veggiesaurus** [comment]
yes please :+1: Assign to @YuHsuan-Hwang?
