### ISSUE TITLE
flux density showing up as NaN in stats widget

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#1355]
The flux density value for a region is consistent showing up as NaN in the statistics widget.  The beam is defined in the header and there are no nan values in the region.    All other statistical quantities are ok.   

<img width="1559" alt="Screenshot 2021-03-17 at 12 49 57" src="https://user-images.githubusercontent.com/9055533/111529443-66997100-871f-11eb-8d5e-e272d1ff0f5b.png">

**Comment by kswang1029** [comment]
Could you post or email me the full header?

**Comment by arusstaylor** [comment]
CTYPE3 = FREQCRVAL3 = 3.200319626566E+08CDELT3 = 3.994398350842E+07CRPIX3 = 1.0CUNIT3 = HzCTYPE4 = STOKESCRVAL4 = 1.000000000000E+00CDELT4 = 1.000000000000E+00CRPIX4 = 1.0CUNIT4 = PV2_1 = 0.000000000000E+00PV2_2 = 0.000000000000E+00RESTFRQ = 4.940656458412E-324 / Rest Frequency (Hz) SPECSYS = LSRK / Spectral reference frame ALTRVAL = -INF / Alternate frequency reference value ALTRPIX = 1.0VELREF = 257 / 1 LSR, 2 HEL, 3 OBS, +256 Radio TELESCOP = GMRTOBSERVER = USERDATE-OBS = 2019-08-27T18:55:00.801085TIMESYS = UTCOBSRA = 3.440703411543E+01OBSDEC = -4.832972747595E+00OBSGEO-X = 1.657069564687E+06OBSGEO-Y = 5.797969000072E+06OBSGEO-Z = 2.073044091645E+06

**Comment by arusstaylor** [comment]
I grabbed this from the header display in carta.  Unfortunately there does not seem to be any carriage returns in the header display.  Perhaps need an "export header as text file" option?

Below is the header from ds9

**Comment by arusstaylor** [comment]
SIMPLE  =                    T /Standard FITS                                   
BITPIX  =                  -32 /Floating point (32 bit)                         
NAXIS   =                    4                                                  
NAXIS1  =                12200                                                  
NAXIS2  =                 6800                                                  
NAXIS3  =                    1                                                  
NAXIS4  =                    1                                                  
EXTEND  =                    T                                                  
BSCALE  =   1.000000000000E+00 /PHYSICAL = PIXEL*BSCALE + BZERO                 
BZERO   =   0.000000000000E+00                                                  
BMAJ    =   2.777777777778E-03                                                  
BMIN    =   2.777777777778E-03                                                  
BPA     =   0.000000000000E+00                                                  
BTYPE   = 'Intensity'                                                           
OBJECT  = '        '                                                            
BUNIT   = '        '           /Brightness (pixel) unit                         
EQUINOX =   2.000000000000E+03                                                  
RADESYS = 'FK5     '                                                            
LONPOLE =   1.800000000000E+02                                                  
LATPOLE =  -4.833055555556E+00                                                  
PC1_1   =   1.000000000000E+00                                                  
PC2_1   =   0.000000000000E+00                                                  
PC3_1   =   0.000000000000E+00                                                  
PC4_1   =   0.000000000000E+00                                                  
PC1_2   =   0.000000000000E+00                                                  
PC2_2   =   1.000000000000E+00                                                  
PC3_2   =   0.000000000000E+00                                                  
PC4_2   =   0.000000000000E+00                                                  
PC1_3   =   0.000000000000E+00                                                  
PC2_3   =   0.000000000000E+00                                                  
PC3_3   =   1.000000000000E+00                                                  
PC4_3   =   0.000000000000E+00                                                  
PC1_4   =   0.000000000000E+00                                                  
PC2_4   =   0.000000000000E+00                                                  
PC3_4   =   0.000000000000E+00                                                  
PC4_4   =   1.000000000000E+00                                                  
CTYPE1  = 'RA---SIN'                                                            
CRVAL1  =   3.516666666667E+01                                                  
CDELT1  =  -2.777777777778E-04                                                  
CRPIX1  =   6.101000000000E+03                                                  
CUNIT1  = 'deg     '                                                            
CTYPE2  = 'DEC--SIN'                                                            
CRVAL2  =  -4.833055555556E+00                                                  
CDELT2  =   2.777777777778E-04                                                  
CRPIX2  =   3.401000000000E+03                                                  
CUNIT2  = 'deg     '                                                            
CTYPE3  = 'FREQ    '                                                            
CRVAL3  =   3.200319626566E+08                                                  
CDELT3  =   3.994398350842E+07                                                  
CRPIX3  =   1.000000000000E+00                                                  
CUNIT3  = 'Hz      '                                                            
CTYPE4  = 'STOKES  '                                                            
CRVAL4  =   1.000000000000E+00                                                  
CDELT4  =   1.000000000000E+00                                                  
CRPIX4  =   1.000000000000E+00                                                  
CUNIT4  = '        '                                                            
PV2_1   =   0.000000000000E+00                                                  
PV2_2   =   0.000000000000E+00                                                  
RESTFRQ =  4.940656458412E-324 /Rest Frequency (Hz)                             
SPECSYS = 'LSRK    '           /Spectral reference frame                        
ALTRPIX =   1.000000000000E+00 /Alternate frequency reference pixel             
VELREF  =                  257 /1 LSR, 2 HEL, 3 OBS, +256 Radio                 
COMMENT casacore non-standard usage: 4 LSD, 5 GEO, 6 SOU, 7 GAL                 
TELESCOP= 'GMRT    '                                                            
OBSERVER= 'USER    '                                                            
DATE-OBS= '2019-08-27T18:55:00.801086'                                          
TIMESYS = 'TAI     '                                                            
OBSRA   =   3.440703411543E+01                                                  
OBSDEC  =  -4.832972747595E+00                                                  
OBSGEO-X=   1.657069564687E+06                                                  
OBSGEO-Y=   5.797969000072E+06                                                  
OBSGEO-Z=   2.073044091645E+06                                                  
DATE    = '2021-01-20T19:32:23.653000' /Date FITS file was written              
ORIGIN  = 'CASA 5.5.0-149'                                                      
HISTORY CASA START LOGTABLE                                                     
HISTORY 2021-01-20T19:32:07 INFO SRCCODE='::ImageMetaDataRW::set'               
HISTORY Added beam major: 10 arcsec, minor: 10 arcsec, pa: 0 deg                
HISTORY 2021-01-20T19:32:07 INFO SRCCODE='::imhead'                             
HISTORY version: 5.5.0-149    Fri 2019/05/10 13:55:55 UTC                       
HISTORY 2021-01-20T19:32:07 INFO SRCCODE='::imhead'                             
HISTORY imhead(imagename="/idia/projects/supermightee/band3processed/cube/mosaic
HISTORY >_cube_r-05/0~1/superMIGHTEE_B3_XMMLSS_320MHz_smoothed", mode="put", hdk
HISTORY >y="bmaj", hdvalue="10.0arcsec", verbose=False)                         
HISTORY 2021-01-20T19:32:08 INFO SRCCODE='::ImageMetaDataRW::set'               
HISTORY Modified bmin from "10 arcsec                                           
HISTORY " to "10.0arcsec"                                                       
HISTORY 2021-01-20T19:32:08 INFO SRCCODE='::imhead'                             
HISTORY version: 5.5.0-149    Fri 2019/05/10 13:55:55 UTC                       
HISTORY 2021-01-20T19:32:08 INFO SRCCODE='::imhead'                             
HISTORY imhead(imagename="/idia/projects/supermightee/band3processed/cube/mosaic
HISTORY >_cube_r-05/0~1/superMIGHTEE_B3_XMMLSS_320MHz_smoothed", mode="put", hdk
HISTORY >y="bmin", hdvalue="10.0arcsec", verbose=False)                         
HISTORY 2021-01-20T19:32:08 INFO SRCCODE='::ImageMetaDataRW::set'               
HISTORY Modified bpa from "0 deg" to "0deg"                                     
HISTORY 2021-01-20T19:32:08 INFO SRCCODE='::imhead'                             
HISTORY version: 5.5.0-149    Fri 2019/05/10 13:55:55 UTC                       
HISTORY 2021-01-20T19:32:08 INFO SRCCODE='::imhead'                             
HISTORY imhead(imagename="/idia/projects/supermightee/band3processed/cube/mosaic
HISTORY >_cube_r-05/0~1/superMIGHTEE_B3_XMMLSS_320MHz_smoothed", mode="put", hdk
HISTORY >y="bpa", hdvalue="0deg", verbose=False)                                
HISTORY CASA END LOGTABLE                                                       
END

**Comment by kswang1029** [comment]
BUNIT is empty so that’s probably the reason why flux density is NaN.

**Comment by arusstaylor** [comment]
Hmm.  These fits images were written by casa.  Would not expect them to be problematic.  BUNIT should not strictly necessary to calculate flux density.   We are perhaps being to fussy?   There is a BTYPE keyword value.  Whatever the unit in the map the flux density will be in those units times the beam area.   If the units in the map are not  intensity (per beam), then the user needs to beware.

I will try adding BUNIT to see if that changes things.

**Comment by arusstaylor** [comment]
tried another image with a valid BUNIT and the flux density now reports correctly.  So indeed it is the BUNIT.  Thanks.

**Comment by kswang1029** [comment]
regarding saving header to a text file, I have created an issue #1357 to address it. Close this for now.
