### ISSUE TITLE
export information from the stats widget

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#1358]
It would be good to be able to export the data in the stats widget.  The information should include

- the name of the region
- the image name that the region is contained in
- the geometry of the region (pixel coordinates)
- the statistical quantities

**Comment by kswang1029** [comment]
Implemented via https://github.com/CARTAvis/carta-frontend/pull/1323

**Comment by kswang1029** [comment]
@arusstaylor this feature request has been implemented and will be included in the v2.0 release. Close this issue.
