### ISSUE TITLE
frontend crash when loading a 1x1 pixel image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1365]
This should be considered as an edge case but might accidentally happen when users generate a 1x1 subimage via the CARTA GUI. This only happens with 1x1 image. With 1xn it works fine. 
<img width="1610" alt="Screen Shot 2021-03-25 at 11 22 11 AM" src="https://user-images.githubusercontent.com/20819712/112414201-9c140f00-8d5c-11eb-93f8-eb952458cae8.png">

**Comment by veggiesaurus** [comment]
I think it's a corner case instead of an edge case 😇

**Comment by kswang1029** [comment]
> I think it's a corner case instead of an edge case 😇

LOL

**Comment by veggiesaurus** [comment]
remind me again, did we resolve to serve any tile smaller than 4x4 as uncompressed?

**Comment by kswang1029** [comment]
> remind me again, did we resolve to serve any tile smaller than 4x4 as uncompressed?

not sure🤔 I seem not having that memory. Test images are attached.
[tmp.zip](https://github.com/CARTAvis/carta-frontend/files/6311260/tmp.zip)

**Comment by TienHao** [comment]
I find out that 1x2,  1x3 and 2x1 images also have this problem.
The `tiles` in RasterTileData messages contains more elements in `imageData` than _asyncDecompressTile()_ expects. [width x height x 4] 
They all have at least four `0` in the end.

1x1 -> imageData length = 8 (expect 4)
![1*1](https://user-images.githubusercontent.com/20379662/128809083-0a6bb777-ae6d-4ca4-a75b-5c70db112219.png)

1x2 -> imageData length = 16 (expect 8)
![1*2](https://user-images.githubusercontent.com/20379662/128809098-fc5ac9ee-5cb7-45cf-aeda-d9673607ae31.png)

1x3 -> imageData length = 16 (expect 12)
![1*3](https://user-images.githubusercontent.com/20379662/128809107-490f6728-b06b-4481-8c05-1e5a1de32120.png)

2x1 -> imageData length = 16 (expect 8)
![2*1](https://user-images.githubusercontent.com/20379662/128809110-46d41c6f-06de-4e74-988c-74c5f68c97f6.png)

2x2 -> imageData length =16 :+1:
![2*2](https://user-images.githubusercontent.com/20379662/128810505-88b7c659-2ccd-4b28-93a0-834c0f2597ac.png)
