### ISSUE TITLE
profiles don't update when changing Stokes 

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#138]
Looking at an IQUV cube.  When I switch from Q to U using the Stokes animation, the x,y and z profiles do not update to show the U.  Basically changing the Stokes with the animator does not update the profiles to show the proper profile for the stokes being displayed in the image.

**Comment by kswang1029** [comment]
With the demo server and an ALMA IQU cube, I do see xyz profiles being updated when switching to different Stokes axes. Which cube is it?

![animator_stokes_xyzprofiler](https://user-images.githubusercontent.com/20819712/53054612-dce72d00-34df-11e9-8d26-f2483f5aefcb.gif)

**Comment by veggiesaurus** [comment]
@arusstaylor I think it might be an issue with our HDF5 backend server, since I just hacked together the spectral profile support. Not sure if it's worth fixing, considering we're deprecating our backend server.

**Comment by arusstaylor** [comment]
Agreed.  If it is an issue with the IDIA hdf5 backend then not worth fixing, as long as hdf5 support is coming quick with CARTA….   

Russ

**Comment by veggiesaurus** [comment]
Closing for now, as it appears to be specific to deprecated IDIA backend code.
