### ISSUE TITLE
stokes option for spatial profiles

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#1383]
One should be able to select stokes for the spatial (x,y) profiles widget.  The use case that I am immediately trying to work with is an image  that is just I,Q,U,V, i.e. there is only one frequency channel but four stokes.   But even for cubes one should be able to bring up spatial widget and assign a stokes.
Ideally one would be able to select multiple stokes to display in the same x or y profile.

**Comment by kswang1029** [comment]
Yes, good point. We are actually wait for "line" region (v2.0 for sure) to be implemented and then we will put image, region, possibly stats and stokes dropdown menus to the spatial profile widget.

**Comment by kswang1029** [comment]
this is part of https://github.com/CARTAvis/carta-frontend/issues/1399 
Close this one.
