### ISSUE TITLE
Disable the load button if any selected file type is invalid

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-frontend#1386]
When we open the files by selecting multiple files on FileBrowser interface, the frontend only check the first item we chose if the file type is valid. This behaviour would be an issue while selecting multiple region or catalog file. The backend reports that there is an invalid file if one of loading file is invalid.

**Reproduce:**
After opening an image, try to import region file and pick up a valid region file by hold Ctrl or command. If the first item we chose is valid but the others are image files for example. The Save button is not disabled.

**Possible solution:**
To check all selected items if the file type is valid. If any invalid, disable Load button.
Unable to pick up an invalid file as we add more items.
Filter out the image files  on File List when user try to import region or catalog file.

<img width="1218" alt="Screen Shot 2021-04-01 at 15 40 37" src="https://user-images.githubusercontent.com/10767557/113260256-9db37900-9300-11eb-8c88-093c7a9eb583.png">

**Comment by veggiesaurus** [comment]
I'm not convinced that we should be checking the file info for each file. That can add a lot of overhead when selecting multiple image files.

**Comment by kswang1029** [comment]
The current (more efficient) approach is to let the backend handles exceptions (eg invalid format, valid format but the data is corrupted etc) when attempting to load files. Can we close this issue?

**Comment by zarda** [comment]
The feature is already there.
When we open an image, the file browser will not list CRTF or xml, which might be filtered out.
We may apply this on other file format, which is already on the list.

**Comment by kswang1029** [comment]
From performance point of view, this may not be feasible. Close for now.
