### ISSUE TITLE
the shortcut (F1 key) for the online user manual doesn't work on Mac with Chrome

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#139]
Tested with the demo server with macOS and with Chrome.
The shortcut (F1 key) for the online user manual doesn't work on Mac with Chrome. Tried "Fn"+"F1" with an apple keyboard but it does not work.

**Comment by veggiesaurus** [comment]
we will have to change this shortcut for browser versions, as F1 is used by browsers to display their help page. We could try CTRL+F1?

**Comment by kswang1029** [comment]
I would like to avoid function keys since on laptops, they have special functions such as changing screen brightness, volume, play back, etc. Maybe we use shift+h? Note that for the shortcut cheatsheet, the shortcut is shift+? Might be good to use the same modifier.

**Comment by veggiesaurus** [comment]
happy to do that. Only reason we used F1 at first is that it's somewhat standard, but it does make things difficult when targeting browsers.

**Comment by veggiesaurus** [comment]
@kswang1029 now that I think about it, I'm not sure we should even have a shortcut for it at all. The general approach for most modern apps seems to be to _not_ use a shortcut (all Mac apps I tested didn't have a shortcut for help). Given that most people will only view the documentation a few times, probably don't need a shortcut for it

**Comment by kswang1029** [comment]
Sure. No shortcut for the online user manual is total okay I think.
