### ISSUE TITLE
Profiles broken for images with minimal headers

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#1393]
In the latest development version, images with minimal headers (e.g. the synthetic gaussian images produced by this script) have broken profiles (the cursor is fixed in the middle of the image and moving the cursor does not change the profiles. I suspect that this is connected to the recent axis changes. The affected images produce console warnings like Spectral frame not found and Sky frame not found.

I'm attaching a small zipped sample image which demonstrates the issue: [image-10-10-10.zip](https://github.com/CARTAvis/carta-frontend/files/6272540/image-10-10-10.zip)

I previously filed this as a [backend issue](https://github.com/CARTAvis/carta-backend/issues/789), but today I confirmed that it only occurs when I use the latest frontend. If I use the latest backend version but downgrade to the previous frontend development tag, the bug is not present.

**Comment by veggiesaurus** [comment]
I can confirm that the file attached doesn't work with the dev branches, and also seems to break AST for the LMCq.fits test file on mix 'n match. @duidae, can you take a look at this?I think it's related to #1344, because the files work fine in the commit before that.
