### ISSUE TITLE
z profiler profile settings are not cleaned after closing a image in 1.4

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#1398]
bug 1 reproduce:
1. open a image with stokes, select stokes to Q
2. create a region, select stat to RMS
3. close this image 
4. reopen this image or other image, the previous settings (stat/stoke) remains
 
![juvv9-3ke63](https://user-images.githubusercontent.com/25971696/114504407-68444f00-9c61-11eb-82da-c8734cd2bec7.gif)

bug 2 reproduce:
1. open a image
2. select to the image instead of active, should be highlighted
3. open another image
4. the image field stay highlighted for Active option, which is incorrect
 
![kvlk5-13paf (1)](https://user-images.githubusercontent.com/25971696/115374814-c512ad00-a1ff-11eb-9574-460ac87addb9.gif)

**Comment by veggiesaurus** [comment]
What is the proposed behaviour?

What about a situation where you have two images open and just close the one?

**Comment by duidae** [comment]
> What is the proposed behaviour?
> 
> What about a situation where you have two images open and just close the one?

I think the original intention is to keep the settings when opening multiple images & switching profiles without changing anything, but should still reset the settings when all images are closed.

**Comment by veggiesaurus** [comment]
> > What is the proposed behaviour?
> > 
> > What about a situation where you have two images open and just close the one?
> 
> I think the original intention is to keep the settings when opening multiple images & switching profiles without changing anything, but should still reset the settings when all images are closed.

I think this needs some thought. If a user sets up a layout for viewing stokes profiles, and then it aautomatically adjusts when they close an image and open a new one, that might frustrate them.

**Comment by duidae** [comment]
> > > What is the proposed behaviour?
> > > What about a situation where you have two images open and just close the one?
> > 
> > 
> > I think the original intention is to keep the settings when opening multiple images & switching profiles without changing anything, but should still reset the settings when all images are closed.
> 
> I think this needs some thought. If a user sets up a layout for viewing stokes profiles, and then it aautomatically adjusts when they close an image and open a new one, that might frustrate them.

confirmed with TienHao, that's a bug.
