### ISSUE TITLE
Expand features in the spatial profiler widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1399]
relevant backend issue: https://github.com/CARTAvis/carta-backend/issues/796

v3b1:
- [x] image drop down
- [x] region drop down
- [x] stokes drop down 

v3b2: covered in #1617

**Comment by duidae** [comment]
@kswang1029 @veggiesaurus seems current backend does not support sending spatial profile of non-cursor region. May need backend modification for region selection.

**Comment by kswang1029** [comment]
@markccchiang do you have time to make the backend support point region?

**Comment by duidae** [comment]
do we have conclusion for the backend part?

**Comment by kswang1029** [comment]
> do we have conclusion for the backend part?

@markccchiang could you help?

**Comment by markccchiang** [comment]
> > do we have conclusion for the backend part?
> 
> @markccchiang could you help?

Sorry for the late reply! I will do it.

**Comment by kswang1029** [comment]
Will need to keep this issue open for v3b2 where line region needs to be added to the spatial profile

**Comment by kswang1029** [comment]
@duidae regarding the stokes dropdown, can we add "current" which refers to the polarization slider? At the moment the selection is always synchronized with the polarization slider. This would limit some use cases.

**Comment by veggiesaurus** [comment]
@duidae can you split this into two issues, so that we can story-point and schedule them separately? I think this (the completed section) should be 3 points and the other 2.
