### ISSUE TITLE
[Profiler] broken profiler after scrolled on initially loaded widget

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#140]
reproduce the bug:

open frontend without loading any image -> scrolled on profiler widget -> load an image -> broken profiler

![out-2 ogv](https://user-images.githubusercontent.com/25971696/53163099-54b07700-3608-11e9-995e-8ed2ff3f577c.gif)

**Comment by kswang1029** [comment]
nice catch. It can be fixed by double-clicking to reset the range. But, yes we should prevent this. Would it be possible that we show "No file load" same as the render configuration widget? This should fix this issue right away.
