### ISSUE TITLE
remove unnecessary observable and computed decorators

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#1402]
There are a few instances where we are using an `@observable` decorator on properties that are actually constant. For example, `FrameStore::fraimeInfo` is assigned in the constructor, and should therefore just be a `public readonly`, rather than an `@observable`. This for example that `@computed get positionAxis()` should just be a `get positionAxis()`, unless there's any particular reason to keep them as `@computed`? (I guess they get cached when calculated? :thinking: )

**Comment by veggiesaurus** [comment]
requesting input from @duidae and @YuHsuan-Hwang

**Comment by duidae** [comment]
agreed, and may also good to specify private observable/computed/action, and remove warnings in console like:
> [MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: FrameStore@99.channel

seems some are from autorun(), would be good if can find a way to eliminate that.

**Comment by YuHsuan-Hwang** [comment]
Agree. It seems that `isPVImage(), positionAxis(), isUVImage(), uvAxis()` work fine without `@computed`.
