### ISSUE TITLE
frontend broken with Safari 13

### ISSUE THREAD

**Issue by panchyo0** [CARTAvis/carta-frontend#1404]
<img width="1431" alt="Screen Shot 2021-04-15 at 8 34 57 PM" src="https://user-images.githubusercontent.com/22226157/114963457-0e42b580-9e2a-11eb-8afb-4be36f376878.png">

related issue https://github.com/maslianok/react-resize-detector/issues/141

**Comment by veggiesaurus** [comment]
@panchyo0 can you see if just updating that module fixes this?

**Comment by veggiesaurus** [comment]
workaround: upgrade to safari 13.1
