### ISSUE TITLE
colorbar not rendered correctly when colormap is inverted

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#1415]
The colorbar looks fine until I invert the colormap. 

Normal:
![ds91 fits-image-2021-04-21-16-54-08](https://user-images.githubusercontent.com/592504/115574821-42065b00-a2c2-11eb-946a-9bd3c93187ab.png)

Inverted: 
![ds91 fits-image-2021-04-21-16-54-32](https://user-images.githubusercontent.com/592504/115574869-4e8ab380-a2c2-11eb-8e3c-2b64fde7d90e.png)

**Comment by kswang1029** [comment]
In dev with horizontal colorbar merged?

**Comment by kswang1029** [comment]
Ok I see this in bias/contrast branch, not in dev (before merging bias/contrast) and I missed it🙈

**Comment by veggiesaurus** [comment]
> Ok I see this in bias/contrast branch, not in dev (before merging bias/contrast)

oops, I thought it was in `dev` 🙈
