### ISSUE TITLE
Catalog flickering on Safari or Chrome (v 93, v 94) 

### ISSUE THREAD

**Issue by panchyo0** [CARTAvis/carta-frontend#1417]
Catalog overlay flickering on Safari and Chrome (tested with Radeon Pro 570X)

Effected version for chrome: 93.0.4577.63, 93.0.4577.82, 94.0.4606.71

reproduce: https://codesandbox.io/s/webgl2-ojb60?file=/src/index.ts
 
<img width="1725" alt="Version 14 0 3 (15610 4 3 1 7, 15610)" src="https://user-images.githubusercontent.com/22226157/115655369-68db8600-a2f0-11eb-86da-037b54b4d3e4.png">

https://user-images.githubusercontent.com/22226157/136637594-2c8bf790-7211-431a-827b-ae355ca47e2a.mp4

https://user-images.githubusercontent.com/22226157/136637597-14ef416e-f895-4eb7-8165-8c4778a7c418.mp4

**Comment by veggiesaurus** [comment]
is there a workaround for older versions  or safari 13.1?

**Comment by veggiesaurus** [comment]
@panchyo0 what is the underlying bug here?
