### ISSUE TITLE
frontend crash when click the plot button if no source passes the filter in the catalog widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1427]
this is not seen in the v1.4

the plot button should be disabled when no source passes filtering in the catalog widget.

https://user-images.githubusercontent.com/20819712/116840523-bddc9d80-ac08-11eb-935d-537498c4f719.mp4

![Screen Shot 2021-05-03 at 12 04 15 PM](https://user-images.githubusercontent.com/20819712/116840532-c503ab80-ac08-11eb-910d-36b3dae8733f.png)

**Comment by panchyo0** [comment]
fixed with PR #1401
