### ISSUE TITLE
matching line labels in velocity when there are multiple profiles from different cube

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1428]
POST v2.0 issue

With the v2.0 new feature "multiple profile plot", users can load two line cubes and show their profiles with the x-axis as frequency. Then users may use the spectral line query widget to select a set of lines to generate line ID overlay. This works well when the x-axis is frequency. When users switch to velocity, it is expected to see all line labels align to the profiles if profiles have same velocity reference. In the following example, we would expect to see 13CO and C18O line labels at the same position when we set velocity as the x axis. 

https://user-images.githubusercontent.com/20819712/116850384-2a649600-ac23-11eb-80b4-7a876ccca2d6.mp4

**Comment by duidae** [comment]
C18O, 219560.3541 MHz => 1140.3143710573258 km/s
13COv=0, 220398.6674 MHz => 0.017138872968295197 km/s

@kswang1029 does that mean the transformed value of C18O (1140.3143710573258 km/s) via AST is incorrect?

**Comment by kswang1029** [comment]
> C18O, 219560.3541 MHz => 1140.3143710573258 km/s
> 13COv=0, 220398.6674 MHz => 0.017138872968295197 km/s
> 
> @kswang1029 does that mean the transformed value of C18O (1140.3143710573258 km/s) via AST is incorrect?

Referring to the video, if the active image is 13CO, then the label for C18O is off, and vice versa.

**Comment by duidae** [comment]
> > C18O, 219560.3541 MHz => 1140.3143710573258 km/s
> > 13COv=0, 220398.6674 MHz => 0.017138872968295197 km/s
> > @kswang1029 does that mean the transformed value of C18O (1140.3143710573258 km/s) via AST is incorrect?
> 
> Referring to the video, if the active image is 13CO, then the label for C18O is off, and vice versa.

then why should them show at close positions when switching to radio velocity?

**Comment by duidae** [comment]
C18O can get correct value in radio velocity using HD163296_C18O_2-1.fits's wcs
C18O 219560.3541 MHz => 0.008055987438578108 km/s
13COv=0 220398.6674 MHz => -1144.6430312174466 km/s

13CO can get correct value in radio velocity using HD163296_13CO_2-1.fits's wcs
C18O 219560.3541 MHz  => 1140.3143710573258 km/s
13COv=0 220398.6674 MHz => 0.017138872968295197 km/s

the problem comes from how can we determine to use which wcs to transform.

**Comment by kswang1029** [comment]
> > > C18O, 219560.3541 MHz => 1140.3143710573258 km/s
> > > 13COv=0, 220398.6674 MHz => 0.017138872968295197 km/s
> > > @kswang1029 does that mean the transformed value of C18O (1140.3143710573258 km/s) via AST is incorrect?
> > 
> > 
> > Referring to the video, if the active image is 13CO, then the label for C18O is off, and vice versa.
> 
> then why should them show at close positions when switching to radio velocity?

The real observable spectral convention is frequency or wavelength (they are equivalent via c = lambda * nu. Radio observations tend to use frequency and optical/infrared observations tend to use wavelength.). That is, with a spectrometer we record signals at different frequencies or wavelengths. In the above case study, C18O at 219560.3541 MHz and 13CO at 220398.6674 MHz are observed at different frequency setups from the same source. This source along the line of sight has a relative physical motion with respect to the spectral reference frame (for galactic source it is usually LSRK, local standard of rest, kinematic). So what we observed would have a frequency shift due to the motion along the line of sight (doppler shift/effect). The frequency shift depends on the observing frequencies so the frequency shifts of the two lines are not identical. To compare them properly, we mostly convert the spectral convention from frequency/wavelength to velocity with respect to the spectral reference frame (eg LSRK). After the conversion, we will see the two lines are aligned in the velocity frame (so we don't have to worry about different doppler shifts in frequency). If we see the line peak velocity is positive (eg 10 km/s), this means the target source has a line-of-sight motion _away_ from the reference frame (eg LSRK). That is, redshifted. If we see the velocity is negative, this means the target source is moving _toward_ the reference frame. That is, blueshifted. So back to the line labeling, in frequency domain, we should see the two line labels aligned to the line peaks, respectively. In the velocity domain, as the line features are aligned, we should see the two line labels are aligned as well.

**Comment by kswang1029** [comment]
> C18O can get correct value in radio velocity using HD163296_C18O_2-1.fits's wcs
> C18O 219560.3541 MHz => 0.008055987438578108 km/s
> 13COv=0 220398.6674 MHz => -1144.6430312174466 km/s
> 
> 13CO can get correct value in radio velocity using HD163296_13CO_2-1.fits's wcs
> C18O 219560.3541 MHz => 1140.3143710573258 km/s
> 13COv=0 220398.6674 MHz => 0.017138872968295197 km/s
> 
> the problem comes from how can we determine to use which wcs to transform.

let me work out the procedures for you.

**Comment by kswang1029** [comment]
> > C18O can get correct value in radio velocity using HD163296_C18O_2-1.fits's wcs
> > C18O 219560.3541 MHz => 0.008055987438578108 km/s
> > 13COv=0 220398.6674 MHz => -1144.6430312174466 km/s
> > 13CO can get correct value in radio velocity using HD163296_13CO_2-1.fits's wcs
> > C18O 219560.3541 MHz => 1140.3143710573258 km/s
> > 13COv=0 220398.6674 MHz => 0.017138872968295197 km/s
> > the problem comes from how can we determine to use which wcs to transform.
> 
> let me work out the procedures for you.

The rules here are:
- if the spectral convention is other than velocity, do what we do now.
- if the spectral convention is _velocity_, then just label lines at the velocity specified by user using the text field. That is, if a user set velocity as 10 km/s, we just label all the lines at 10km/s. If the user sets a redshift 0.001, then we need to convert it to velocity and then label all the lines at that velocity.

**Comment by kswang1029** [comment]
> > > C18O can get correct value in radio velocity using HD163296_C18O_2-1.fits's wcs
> > > C18O [219560.3541](tel:219560.3541) MHz => 0.008055987438578108 km/s
> > > 13COv=0 [220398.6674](tel:220398.6674) MHz => -1144.6430312174466 km/s
> > > 13CO can get correct value in radio velocity using HD163296_13CO_2-1.fits's wcs
> > > C18O [219560.3541](tel:219560.3541) MHz => 1140.3143710573258 km/s
> > > 13COv=0 [220398.6674](tel:220398.6674) MHz => 0.017138872968295197 km/s
> > > the problem comes from how can we determine to use which wcs to transform.
> > 
> > 
> > let me work out the procedures for you.
> 
> The rules here are:
> 
> * if the spectral convention is other than velocity, do what we do now.
> * if the spectral convention is _velocity_, then just label lines at the velocity specified by user using the text field. That is, if a user set velocity as 10 km/s, we just label all the lines at 10km/s. If the user sets a redshift 0.001, then we need to convert it to velocity and then label all the lines at that velocity.

Note that this applies only when profiles are from different _images_. If it is the same image we still need to apply the current transformation.

**Comment by duidae** [comment]
![image](https://user-images.githubusercontent.com/25971696/117395077-e971c780-af29-11eb-9c28-97b2e8abc083.png)
would this be ok?
1. initial value 0 in numeric input
2. menu & numeric input disabled when Image button of multi profile is not clicked.
