### ISSUE TITLE
connecting to other backends and the status icon

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#144]
Not sure if this is an issue but let me describe here:

with the demo server at ASIAA https://carta.asiaa.sinica.edu.tw/ and using "connect to URL" to wss://dev-viewer.idia.ac.za/socket (i.e. IDIA demo server), the status icon becomes **ORANGE** from GREEN but in js console I do see REGISTER_VIEWER_ACK.success = True with a new session_id. "Open image" is greyed out.

with the IDIA demo server https://dev-viewer.idia.ac.za/ and using "connect to URL" to wss://carta.asiaa.sinica.edu.tw/socket (i.e. the demo server at ASIAA), the status icon becomes **RED** from GREEN but in js console I do see REGISTER_VIEWER_ACK.success = True with a new session_id. "Open image" is greyed out.

Note that the frontends are now different (different branches/commit) on the demo server and on the IDIA demo server. Certainly the backends are different.

**Comment by veggiesaurus** [comment]
@kswang1029 can you test this with the latest master commit? I've added some toast alerts and have fixed the connection status behaviour

**Comment by kswang1029** [comment]
yes, checked all three toast alerts. Nice.
