### ISSUE TITLE
PV image regions should have a fixed PA of zero

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1443]
This should be fixed for v2.0 release I think.

<img width="942" alt="Screen Shot 2021-05-14 at 1 45 09 PM" src="https://user-images.githubusercontent.com/20819712/118227173-af20a100-b4ba-11eb-9019-b515684ce891.png">

edit: After discussion betweek @kswang1029 and @veggiesaurus, decision is to limit rotation of rect/ellipse regions to images where the pixel ratio is exactly 1, otherwise rectangles become quadrilaterals and ellipses become :man_shrugging: who knows what.

**Comment by veggiesaurus** [comment]
🙋
