### ISSUE TITLE
label in region dropdown menus of the spectral profiler and moment generator out of sync 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1444]
When we change region in the moment generator, the spectral profile data get updated in the spectral profiler as expected. However the label does not get updated. @duidae could you help to have a look for v2.0 final?

https://user-images.githubusercontent.com/20819712/118429151-97882900-b703-11eb-984c-e1d6f60c8c9a.mp4

**Comment by kswang1029** [comment]
@duidae @veggiesaurus I wonder if we should decouple image and region dropdown menus between the moment generator and spectral profiler? That might be easier to fix the issue with little impact on UX. The sync'd feature in v1.4 is nice when there is only one profile in the spectral profiler. In v2.0, it gets more complicated so maybe we should consider to remove the sync feature to make the logic clear to users (ie no sync for image and region dropdown menus).

**Comment by duidae** [comment]
will limit the drop downs of image/region in moment tab to only pure selection but not changing the profiles in spectral profiler, is that ok?

**Comment by kswang1029** [comment]
> will limit the drop downs of image/region in moment tab to only pure selection but not changing the profiles in spectral profiler, is that ok?

yes. sounds like a simple solution.
