### ISSUE TITLE
multiple tsv files exported when the profile fitting result+residual are rendered in the spectral profile widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1456]
Profile export works fine when there is only one profile rendered. However, if profile fitting result presents, there are many tsv file got exported.

https://user-images.githubusercontent.com/20819712/119619648-cb1b2f80-be36-11eb-8df3-586af9013f42.mp4

@TienHao could you check please?

**Comment by kswang1029** [comment]
The five files are attached.

[tmp.zip](https://github.com/CARTAvis/carta-frontend/files/6544629/tmp.zip)

**Comment by TienHao** [comment]
> @TienHao could you check please?

yes, I can check this one.

**Comment by kswang1029** [comment]
it seems that the extra files are the model and residual? If so, when in the fitting mode, could you implement the tsv export as one single file with additional columns? Such as
x, y, model, residual
