### ISSUE TITLE
Cannot save a subimage from HDF5 to FITS

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1458]
Bug found via v2.0 beta test

A subimage in the FITS format cannot be created from a HDF5 image. It works if the target output format is CASA format.

**Comment by kswang1029** [comment]
@markccchiang please check with @YuHsuan-Hwang about the root cause. @YuHsuan-Hwang please help for v2.0 release. Thank you both 🙂

**Comment by markccchiang** [comment]
Not sure is it due to the problem in this code line https://github.com/CARTAvis/carta-frontend/blob/dev/src/stores/FileBrowserStore.ts#L82 (?)

**Comment by YuHsuan-Hwang** [comment]
@markccchiang Yes, I think it's due to this line. The initial filetype is set to HDF5.
Both fits and casa image can be saved after we select filetype from dropdown menu.
