### ISSUE TITLE
frozen profiler

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#146]
It appears that if the grey cursor vertical line disappears, we cannot use double-click to reset the x range in profiler.
![test](https://user-images.githubusercontent.com/20819712/53388765-5fcc2400-39c7-11e9-9b7b-bd891ac0b6d6.gif)

Likely only xy-profiler has this issue, not the z-profiler. We can reset the x range by using "Reset Range" button in the menu on the right.

**Comment by veggiesaurus** [comment]
@duidae can you sort this issue out? Looks like it was introduced by the latest guards you implemented.

**Comment by duidae** [comment]
@veggiesaurus ok
