### ISSUE TITLE
x unit in z-profiler

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#147]
if "Use WCS Values" is switched off in the z-profiler, the x unit displayed in the cursor info becomes "null". Should be "Channel".
![screen shot 2019-02-26 at 1 17 10 pm](https://user-images.githubusercontent.com/20819712/53389133-14b31080-39c9-11e9-98dc-676054c10959.png)

**Comment by veggiesaurus** [comment]
@duidae Can you fix this as well? should be pretty easy to solve. 

@kswang1029 since the other profilers use "px" for image coordinates, shouldn't this also be "px" instead of "channel"?

**Comment by kswang1029** [comment]
Hmm, px is precise but conventionally we call it channel.

**Comment by veggiesaurus** [comment]
In that case, I think we should go for "Channel X" instead of "X channel" (I realise that will require some adjustments @duidae ).

**Comment by kswang1029** [comment]
for the same reason, shall we use px 5, rather than 5 px for xy profiler?

**Comment by veggiesaurus** [comment]
That sounds a bit weird, doesn't it?

**Comment by duidae** [comment]
@veggiesaurus ok

**Comment by arusstaylor** [comment]
channel is preferred for the frequency axis.  px only suitable for spatial axes where the non WCS representation is pixels.

Russ
