### ISSUE TITLE
incorrect image index label in moment generator

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1479]
There images are loaded as 0, 1, and 2. But the label next to the image dropdown is 6

![Screen Shot 2021-06-02 at 1 54 45 PM](https://user-images.githubusercontent.com/20819712/120430864-3bcbca00-c3aa-11eb-93da-26acd9a88ca9.png)

**Comment by duidae** [comment]
please specify how to reproduce that

**Comment by kswang1029** [comment]
> please specify how to reproduce that

try
1. load three images in append mode
2. close them
3. load other few images in append mode and the file id should start from 0
4. the displayed id in the moment tab seems accumulating
