### ISSUE TITLE
Cursor widget to show cursor information for matched images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1484]
When there are multiple spatially and spectrally matched images, it is common to read the cursor information from all the images _in one place at the same time_. The information should include: 
- World coordinates
- Image coordinates of each image
- Spectral coordinate of each image including frequency, velocity, and channel index
- Stokes parameter of each image
- Pixel value with a unit for each image

Please let @kswang1029 know if a UI mockup is needed.

**Comment by YuHsuan-Hwang** [comment]
Separating this issue into two parts
1. implement basic UI and show cursor info of the active frame
2. show cursor info of multiple images
2.1. show explicit WCS for all frames
2.2. update cursor info of matched images when hovering

**Comment by veggiesaurus** [comment]
@YuHsuan-Hwang do you want to create a separate issue for the multi-cursor implementation, or just use this one?

**Comment by YuHsuan-Hwang** [comment]
> @YuHsuan-Hwang do you want to create a separate issue for the multi-cursor implementation, or just use this one?

@veggiesaurus I think we can just use this one
