### ISSUE TITLE
tile decompression failing

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1485]
<img width="614" alt="Screen Shot 2021-06-08 at 10 37 31 AM" src="https://user-images.githubusercontent.com/20819712/121114196-e0845680-c845-11eb-9603-6e4f67e44f22.png">

test image: 
[test.zip](https://github.com/CARTAvis/carta-frontend/files/6613139/test.zip)

@veggiesaurus could you have a look?

**Comment by kswang1029** [comment]
This is due to having a tile with a width of 1px. The image is 513x513. If we trim it to 512x512, it works properly.

**Comment by TienHao** [comment]
This issue has same root cause from TileService like #1365.
