### ISSUE TITLE
pv generator widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1489]
This new widget will allow users to
- trigger backend PV map calculation
- configure pv preview interactive mode (cube downsample factor)
- preview pv image in the interactive mode

science requirements: https://docs.google.com/document/d/1Z1fCDj9IujGvV6ER_bzjjL2j_bF5ykc34GRhPdOiXI4/edit

**Comment by pford** [comment]
I could not find a protobuf branch for the PV generator feature (no preview yet), so I created branch `pv_generator` with new files `control/stop_pv_calc.proto` and `request/pv_request.proto` (includes request, response, and progress messages) based on the moment generator messages.  Feel free to edit as needed.

**Comment by kswang1029** [comment]
interactive pv image preview will be addressed in a new issue.
