### ISSUE TITLE
error editing the clip range values

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#149]
If the clip range value has a bunch leading zeros in front of the decimal point e.g.

0.000003

When I use delete expecting to delete only the 3 it deletes everything up to the decimal point. I just want to deleted the last digit in the string.

**Comment by kswang1029** [comment]
I think this is because when the "3" is deleted, the remaining is 0.00000 which is actually 0 so it displays just like that. Maybe we can validate the input value with a longer time to prevent this? Or maybe there is a more clever way to avoid this issue.

**Comment by veggiesaurus** [comment]
The way to get around this is to validate the input only when changing focus from the element or pressing enter. I've run into the same issue with the region dialog, and I believe its an acceptable solution, will merge in a fix once the region dialog is done.

**Comment by duidae** [comment]
okok
