### ISSUE TITLE
support complex image visualization as raster

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1492]
related to the backend issue: https://github.com/CARTAvis/carta-backend/issues/520

frontend should provide options to visualize a complex-valued image as
- real
- imaginary
- amplitude
- phase

Potentially we can use the animator for the UI. To be discussed further.

**Comment by duidae** [comment]
Mockup:

![image](https://user-images.githubusercontent.com/25971696/124239676-875dc900-db4c-11eb-83e6-54c08bf9732d.png)

**Comment by veggiesaurus** [comment]
@kswang1029 how important is it to support images that have _both_ Stokes _and_ real/imag? If I understand correctly, supporting complex images is primarily aimed at pipeline development work, which means you'd be very unlikely to build a Stokes hypercube with complex data.

If they are mutually exclusive, then we can simplify the UI considerably

**Comment by kswang1029** [comment]
> @kswang1029 how important is it to support images that have _both_ Stokes _and_ real/imag? If I understand correctly, supporting complex images is primarily aimed at pipeline development work, which means you'd be very unlikely to build a Stokes hypercube with complex data.
> 
> If they are mutually exclusive, then we can simplify the UI considerably

I think they are mutually exclusive. Stokes cube is one. And spatial-spatial-spectral cube with complex values is another.

**Comment by veggiesaurus** [comment]
Ok, then could we actually simplify things and make the "stokes" slider more generic, to support either Stokes IQUV _or_ real/imag/ampl/phase?

**Comment by veggiesaurus** [comment]
I think we should use the following mapping:
Stokes I -> Amplitude
Stokes Q -> Real
Stokes U -> Imaginary
Stokes V -> Phase

this will allow us to repurpose the Stokes widget for compex image inspection

**Comment by kswang1029** [comment]
UPDATE: based on the idea from https://github.com/CARTAvis/carta-backend/issues/520#issuecomment-1083037459 the frontend will just mock up a LEL to load a complex image based on the selected component.
