### ISSUE TITLE
Remember layout of file open dialog

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta-frontend#1495]
The "file open" dialog always resets to the same size when you reopen it to open/append a new file.  I often have to resize the filename bar to be bigger because my filenames are descriptive and therefore long, and that's the only way to tell an `.image.tt0` from a `.sumwt`.  It would be nice if the file open dialog could remember the shape of the columns and the shape of the overall box (I often make it bigger) between uses.

**Comment by kswang1029** [comment]
This ? https://github.com/CARTAvis/carta-frontend/issues/1253

**Comment by keflavich** [comment]
🤦‍♂️ yes

**Comment by veggiesaurus** [comment]
I guess this is the problem with having three different places to submit issues 🙈

**Comment by keflavich** [comment]
Ah, should I raise that as an issue on https://github.com/CARTAvis/carta then?  "Reduce # of issuetrackers" :trollface:
