### ISSUE TITLE
no update on image cursor values when switching stokes or channel

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#150]
When I use "F" to fix the position of the cursor in the image, and then switch Stokes the cursor display values on the image do not change.   Same thing happens if I change frequency.  These values do not update.

**Comment by kswang1029** [comment]
yes, confirmed with the demo server. The "Value: xxx" entry needs to be updated when changing channel or stokes via the animator.

**Comment by arusstaylor** [comment]
this problem also occurs when blinking frames.  The position and values of the pixel under the cursor does not update when animating between frames.
