### ISSUE TITLE
strange cursor position of draggable marker

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#151]
sometimes the center of the draggable Rectangle box will not align with the red marker, so the dragging behavior is a little bit odd (the dragging icon may shift from the red marker)
![ttt](https://user-images.githubusercontent.com/25971696/53469776-40ea9200-3a9a-11e9-95c8-8c5fd55b48cc.png)

**Comment by kswang1029** [comment]
Yet another HiDPI issue?

**Comment by veggiesaurus** [comment]
No, it looks like a bug in Konva, where the rectangle is not being updated properly. Have fixed it, issuing a PR shortly
