### ISSUE TITLE
incorrect label for cursor region in the moment generator tab

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1513]
When the active region is cursor, the label next to the region dropdown is "Image". It should be "Cursor".

![Screen Shot 2021-06-22 at 1 33 30 PM](https://user-images.githubusercontent.com/20819712/122869230-88c60f00-d35e-11eb-9c0c-4bdc2fee9828.png)

**Comment by duidae** [comment]
I think we have discussed this last time, cursor region actually indicates generating the moment of the whole image.

**Comment by kswang1029** [comment]
Yes but the generate button is disabled.

![Screen Shot 2021-06-22 at 2 02 49 PM](https://user-images.githubusercontent.com/20819712/122872136-954c6680-d362-11eb-9e24-c02ecf85e104.png)
