### ISSUE TITLE
pixel highlight by colorbar cursor value

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1518]
As an advanced feature (cannot remember if there is any other viewer having the same feature), it would be nice to support pixel highlight by colorbar cursor value. That is, when we use mouse to point a color (hence a pixel value) on the colorbar in the image viewer, CARTA highlights those pixels with values >= the colorbar cursor value. This would serve as a manual version of source identification tool. Example mockups (from @veggiesaurus):
![ds91 fits-image-2021-06-23-10-43-21](https://user-images.githubusercontent.com/20819712/123067660-c18be400-d443-11eb-8733-79e695136e76.png)
![m51_xray fits-image-2021-06-23-10-36-48](https://user-images.githubusercontent.com/20819712/123067678-c6509800-d443-11eb-8a2e-383b649fdab0.png)

It appears that changing pixels with values < the colorbar cursor value to "grey" provides better visibility and UX. The only drawback is it does not work if the selected colormap is grey. We could consider grey colormap as a special case and implement a different way of pixel highlight (or just forget about it; TBD).

**Comment by veggiesaurus** [comment]
Current implementation: 

https://user-images.githubusercontent.com/592504/123089597-71068d80-d427-11eb-82de-1061d005fc25.mp4
