### ISSUE TITLE
Spectral matching does not respect coordinate conversions

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta-frontend#1536]
The spectral matching tool ("Z" in the image list) seems to work only in the native spectral dimension.  I'd like it to operate in velocity when I convert the cubes to velocity in the spectral viewer.  Is that possible?

**Comment by veggiesaurus** [comment]
It can work with radio/optical velocity, frequency or channel. What do you have set for preferences -> global -> spectral matching? If it's already set to radio velocity, do each of your images show the correct velocity when loaded independently?

**Comment by keflavich** [comment]
I see, thanks - I didn't realize this had to be changed in preferences.  I was expecting it to be an option somewhere near the spectral matching tools, either in the conversion menu:
![image](https://user-images.githubusercontent.com/143715/123650709-d4face80-d7f8-11eb-8408-074b56e1a926.png)

or the image list:
![image](https://user-images.githubusercontent.com/143715/123650745-dfb56380-d7f8-11eb-9c37-a66a6262e41b.png)

**Comment by veggiesaurus** [comment]
Is this something that users are likely to change often? I'd imagine most would just set it to match radio velocity and forget about it?

**Comment by keflavich** [comment]
Yes, all the time.

The common use case is: I'm working on a broadband (2GHz) window with ALMA looking at either two different targets in the same frequency, or the same target with two different array configurations or two different weightings or reduction parameters, say.  I want to match them spectrally so I can search for differences.

Then, I find two lines toward the same source that I want to compare in velocity space.  Right now, afaik, I have to split out two new cubes with difference rest frequencies, load them up, change my locking preference to velocity, and then I can compare them.

It would be better if I could switch between the freq and vel matching in different sessions - often, I will have these two analysis processes going on in parallel.

Also, it would be nice if we could change the rest/reference frequency on the fly... I'd say that is actually a much higher priority.

**Comment by kswang1029** [comment]
Now in the image list widget, we can change the reference system to perform spectral matching. Also now we can re-set a rest frequency for spectral matching in velocity space. Can we close this issue?
