### ISSUE TITLE
Catalog marker maximum size of 50 pixels not enforced on manual entry 

### ISSUE THREAD

**Issue by stevenrjanssens** [CARTAvis/carta-frontend#1544]
In the catalog tool, the 50 pixel maximum marker size isn't stated and it is possible to manually set a larger size with no user feedback.

**Comment by panchyo0** [comment]
Hi @stevenrjanssens, Could you please provide more details? for example, How to reproduce this issue?

**Comment by stevenrjanssens** [comment]
<img width="542" alt="Screen Shot 2021-07-06 at 1 55 11 AM" src="https://user-images.githubusercontent.com/2381197/124572162-49d39700-ddfd-11eb-84db-08b8eb419bd4.png">

Hi @panchyo0, I attached a screenshot showing the catalog settings size dialog. For me, the only time the user is made aware of the 50 pixel maximum size is if the size is increased using the arrows rather than entered manually.
