### ISSUE TITLE
cursor/data value update in profilers

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#155]
Closing the setting menu of profiler can disable displaying current cursor value in profiler. Demo below:
![issue](https://user-images.githubusercontent.com/20819712/53706947-b32af000-3e67-11e9-9a08-31a14d8b749f.gif)

**Comment by veggiesaurus** [comment]
@duidae I think you need to re-enable the cursor again on `mousemove`, not just `mouseenter`
