### ISSUE TITLE
File browser shows blank location permanently after certain files are opened

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#1552]
Backend commit: c9d0819
Frontend commit: 1d3477a

This appears to be limited to specific (not all) HDF5 images. I haven't been able to reproduce it with any FITS files. Examples of affected files:

* hlsp_candels_hst_acs_gn-tot-60mas_f606w_v1.0_drz.hdf5
* XMMLSS_3_contcube.hdf5
* GALFACTS_S3_average_image_I.hdf5
* 502nmos.hdf5
* GNPilot.centre.I.hdf5

I will check if rolling back to the previous backend and/or frontend commit resolves this.

**Comment by confluence** [comment]
Screenshot of the bug:

![Screenshot from 2021-07-08 16-24-51](https://user-images.githubusercontent.com/651030/124939011-136a6780-e009-11eb-9163-61b6a4a03b37.png)

This is what the file browser looks like when it is opened from the menu (either to open or to append a file) after one of the affected files has been opened. The navigation doesn't work (clicking on the root icon does not cause the root directory to be loaded).

**Comment by kswang1029** [comment]
What does the console log say? Specifically do you see file_list_request and file_list_response?

**Comment by confluence** [comment]
When the browser is in the broken state, a FILE_LIST_REQUEST is sent (for the correct directory), but there is no response.

When one of the unaffected files is open, I have confirmed that the same request is made and receives the expected response.

**Comment by confluence** [comment]
I have confirmed that this problem does not occur in the previous backend commit, `19ead62`.

**Comment by confluence** [comment]
I am closing this and opening a new backend issue.
