### ISSUE TITLE
spectral conversion failed

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1563]
after the new FITS header parser improvement https://github.com/CARTAvis/carta-backend/pull/827 the supermosaic image has a problem showing velocity info in the cursor info bar. 

![Screen Shot 2021-07-12 at 5 29 25 PM](https://user-images.githubusercontent.com/20819712/125264965-f4384680-e336-11eb-9c0e-ab4bddd9c4d7.png)

**Comment by veggiesaurus** [comment]
@duidae can you look into this?

**Comment by duidae** [comment]
will do

**Comment by duidae** [comment]
`CTYPE3 = VELO-LSR /  Z COORDINATE TYPE`

the new header does not satisfy fits standard in Table 25.
![image](https://user-images.githubusercontent.com/25971696/125910200-c39af720-d4ce-498f-bb00-43e71b995e3f.png)

**Comment by veggiesaurus** [comment]
> `CTYPE3 = VELO-LSR / Z COORDINATE TYPE`
> 
> the new header does not satisfy fits standard in Table 25.
> ![image](https://user-images.githubusercontent.com/25971696/125910200-c39af720-d4ce-498f-bb00-43e71b995e3f.png)

Actually the issue is not quite that. The CTYPE3 can have a suffix. The issue is that the suffix in this case (`LSR`) does not match table 2 of https://www.aanda.org/articles/aa/pdf/2006/05/aa3818-05.pdf (the algorithm suffix).

**Comment by veggiesaurus** [comment]
If the velocity conversion is not available, shouldn't we show _nothing_ instead of `undefined`?
