### ISSUE TITLE
region size not displayed 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1572]
This _might_ be due to the recent backend change (https://github.com/CARTAvis/carta-backend/pull/827) on how FITS headers are extract from images. 
![Screen Shot 2021-07-15 at 11 13 13 AM](https://user-images.githubusercontent.com/20819712/125723705-8696971d-af7a-4f23-9cea-cdb98887b2c5.png)

**Comment by kswang1029** [comment]
more investigation is needed to find the root cause as a counter example is found.

**Comment by kswang1029** [comment]
When the size is not displayed, the image list widget is blank. The console says

![Screen Shot 2021-07-15 at 11 35 49 AM](https://user-images.githubusercontent.com/20819712/125725232-fc904b19-43b9-49cc-b747-82dba3ec8a09.png)

**Comment by kswang1029** [comment]
With ALMA image cubes, the region size can be displayed properly. But for the images from elsewhere (eg Hubble, Herschel etc), the region size is empty. I guess this is certainly related to the header as before we used casacore to unify headers but now we use the raw header content. The size calculation (with AST?) needs to be checked.

**Comment by kswang1029** [comment]
My speculation: possibly this is due to missing CDELT in the header. In some images, the pixel size info is stored in the CD matrix.

**Comment by veggiesaurus** [comment]
> My speculation: possibly this is due to missing CDELT in the header. In some images, the pixel size info is stored in the CD matrix.

AST should be able to handle CD and PC matrices :thinking:

**Comment by kswang1029** [comment]
as a note: if we create a line region, the region list widget may crash due to size calculation.

**Comment by YuHsuan-Hwang** [comment]
https://github.com/CARTAvis/carta-frontend/blob/dev/src/stores/FrameStore.ts#L1290
the root cause is that `getWcsSizeInArcsec` returns null if there are no `CDELT1` and `CUNIT1` in the header

**Comment by veggiesaurus** [comment]
> https://github.com/CARTAvis/carta-frontend/blob/dev/src/stores/FrameStore.ts#L1290
> the root cause is that `getWcsSizeInArcsec` returns null if there are no `CDELT1` and `CUNIT1` in the header

Ok, for now we can just guard against `null`. For beta-2 we can make sure we can handle CD and PC matrices

**Comment by YuHsuan-Hwang** [comment]
> > https://github.com/CARTAvis/carta-frontend/blob/dev/src/stores/FrameStore.ts#L1290
> > the root cause is that `getWcsSizeInArcsec` returns null if there are no `CDELT1` and `CUNIT1` in the header
> 
> Ok, for now we can just guard against `null`. For beta-2 we can make sure we can handle CD and PC matrices

Ok. I send a PR for the line region crash first

**Comment by YuHsuan-Hwang** [comment]
I prefer we use AST `astDistance` to calculate the distance of `(CRPIX1 , CRPIX2)` and `(CRPIX1 + 1, CRPIX2)` to obtain the (approximate) unit length of the region.
Another solution would be changing the current formula from `CDELT1` to `(PC1_1 + PC1_2) * CDELT1` (PC formalism) or `CD1_1 + CD1_2` (CD formalism). However, I prefer we use AST so that we can ensure the number is consistent with the grid overlay. We can also avoid adding complicate codes for distinguishing PC and CD formalism.

edit: should be `((PC1_1*CDELT1)**2 + (PC2_1*CDELT2)**2) ** 0.5` (PC formalism) or `(CD1_1**2 + CD2_1**2) ** 0.5` (CD formalism)

**Comment by kswang1029** [comment]
> I prefer we use AST `astDistance` to calculate the distance of `(CRPIX1 , CRPIX2)` and `(CRPIX1 + 1, CRPIX2)` to obtain the (approximate) unit length of the region.
> Another solution would be changing the current formula from `CDELT1` to `(PC1_1 + PC1_2) * CDELT1` (PC formalism) or `CD1_1 + CD1_2` (CD formalism). However, I prefer we use AST so that we can ensure the number is consistent with the grid overlay. We can also avoid adding complicate codes for distinguishing PC and CD formalism.

sounds like a good idea to me.

**Comment by kswang1029** [comment]
> I prefer we use AST `astDistance` to calculate the distance of `(CRPIX1 , CRPIX2)` and `(CRPIX1 + 1, CRPIX2)` to obtain the (approximate) unit length of the region.
> Another solution would be changing the current formula from `CDELT1` to `(PC1_1 + PC1_2) * CDELT1` (PC formalism) or `CD1_1 + CD1_2` (CD formalism). However, I prefer we use AST so that we can ensure the number is consistent with the grid overlay. We can also avoid adding complicate codes for distinguishing PC and CD formalism.

If CRPIX is inside the raster image which is mostly flat, yes, this sounds like a good idea. However, it is possible to have cropped image with CRPIX being outside the cropped image. If the image has significant projection distortion, then we might have trouble. 🤔

UPDATE: but I think the case I mentioned would be non trivial to well define a reference angular size per pixel. So I guess the proposed solution is still a good one.

**Comment by YuHsuan-Hwang** [comment]
> If CRPIX is inside the raster image which is mostly flat, yes, this sounds like a good idea. However, it is possible to have cropped image with CRPIX being outside the cropped image. If the image has significant projection distortion, then we might have trouble. 🤔
> 
> UPDATE: but I think the case I mentioned would be non trivial to well define a reference angular size per pixel. So I guess the proposed solution is still a good one.

I think for both the current approach and my solution we are facing the projection distortion problem. We can first try if the AST function works and then try to handle the projection distortion in the future
