### ISSUE TITLE
Polygon region creation bug

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#1589]
https://user-images.githubusercontent.com/43841102/127272753-d5f65b21-ca28-451f-b589-a48f34b2dc75.mov

Double clicking creates an extra creation point of a polygon region.
~~Occurs on ubuntu but works fine on macOS.~~ Seems to occur after #1569 is merged. May due to the upgrade of the Konva package.

edit: occurs on both ubuntu and macOS

**Comment by kswang1029** [comment]
with my local Mac env, konva@8.1.1 is used. What's on the CARTA server @ajm-asiaa ?

**Comment by ajm-ska** [comment]
@kswang1029 I checked in the Jenkins build folder for the latest "carta-frontend-dev". 
`/var/lib/jenkins/workspace/carta-frontend-dev/node_modules/konva` says `"konva@8.1.1"`, so it must be the same as your Mac.
