### ISSUE TITLE
Change stokes multiple selection design in save image

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#1607]
In the Save image dialog, we may change the stokes single selection to multiple selection as in the z profiler widget for design consistency. It will also become convenient to implement other kinds of polarization (options of "Stokes I/Q/U/V" and "XX/YY/...") after this change.
Current stokes selection in Save image:
![image](https://user-images.githubusercontent.com/43841102/128667899-9a79ae75-6200-47ff-8999-8d9c9157d51f.png)

Design in Z profile:
![image](https://user-images.githubusercontent.com/43841102/128668148-85f1828d-9588-4ffb-a65c-798e6dad202c.png)

**Comment by kswang1029** [comment]
The reason why it is a single-selection list is that due to FITS header limitation (CRVAL, CDELT, CRPIX), Stokes list needs to be contiguous and with equal step. For example, IQV is not allowed. If we use multiple selection, we will need to validate the selections first before making the request to the backend.

**Comment by YuHsuan-Hwang** [comment]
Oh I see... we can keep this design

**Comment by kswang1029** [comment]
@YuHsuan-Hwang do you think we can close this issue?

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 Multiple selection design is more consistent with other designs in Carta, but maybe it's not necessary to change the design

**Comment by kswang1029** [comment]
> The reason why it is a single-selection list is that due to FITS header limitation (CRVAL, CDELT, CRPIX), Stokes list needs to be contiguous and with equal step. For example, IQV is not allowed. If we use multiple selection, we will need to validate the selections first before making the request to the backend.

@YuHsuan-Hwang If we use multi-select checkbox, we will need to _**validate**_ the selections before making a request to the backend. Either way is fine. OK let's keep this issue open for now.
