### ISSUE TITLE
better layout when the viewer is too narrow to show the entire tool buttons

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1613]
At the moment we wrap the tool buttons but in some cases this results in an unpleasant layout. 

<img width="971" alt="Screen Shot 2021-08-10 at 2 38 59 PM" src="https://user-images.githubusercontent.com/20819712/128820111-8d866cdb-ff73-42a9-877c-f539f086dceb.png">

We may try to use popover or other better responsive layout for this use case.

https://user-images.githubusercontent.com/20819712/128820323-581e678f-e93e-4f0f-bd71-57b7998d08de.mov

**Comment by kswang1029** [comment]
beside the cosmetics issue, there is also usability issue with the current design. The space for cursor interaction becomes very small in some cases if the cursor info bar is long and we have tool buttons wrapped. 

<img width="428" alt="Screen Shot 2021-08-10 at 2 51 22 PM" src="https://user-images.githubusercontent.com/20819712/128821517-f65da4f3-dac9-4750-aee5-00b46157f4d4.png">

**Comment by veggiesaurus** [comment]
We could add a single `<<` button that causes all the rest of the panel to slide out / slide in?

**Comment by kswang1029** [comment]
> We could add a single `<<` button that causes all the rest of the panel to slide out / slide in?

that also works I guess
