### ISSUE TITLE
add control buttons for single/multiple panel view

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1614]
Possible place for the single/multiple panel buttons is the top-right corner of the widget. 

<img width="1187" alt="Screen Shot 2021-08-10 at 2 44 07 PM" src="https://user-images.githubusercontent.com/20819712/128820693-b68d3df6-003b-421a-80d7-02f842ddb782.png">

**Comment by veggiesaurus** [comment]
I think three buttons should be used: 
- [x] switch between multi-panel modes (single, dynamic, static)
- [x] forward/backward switches between pages when in multi-panel mode
