### ISSUE TITLE
Expand the features in the spatial profiler: line region/averaging width

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#1617]
Expand the features in the spatial profiler widget including:

- [ ] a region dropdown menu to select cursor or a line region
- [ ] averaging width (in pixel) in the settings

**Comment by veggiesaurus** [comment]
note: separated from #1399

**Comment by duidae** [comment]
extended from #1399

**Comment by veggiesaurus** [comment]
> extended from #1399

good timing :laughing:
