### ISSUE TITLE
Distance measurement doesn't work with click-to-pan mode

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#1624]
As reported by @Jordatious:

If the user has drag-to-pan disabled in the preferences menu, bad things happen when you try to use the distance measuring tool (like things panning twice and so on). We should just disable click-to-pan with the left button when the user is in distance measuring mode (they can still pan using the middle button)

**Comment by Jordatious** [comment]
What's the use case for panning while measuring a distance? Maybe to stay zoomed in for a fine-grain measurement, requiring the user to pan before putting down the 2nd anchor? Would command-click for panning also be useful in such a case, or too confusing / complex? Many people like me don't have the middle click!

**Comment by veggiesaurus** [comment]
cmd + click should work fine too, yep!
