### ISSUE TITLE
use a linked image for spatial coordinates for the Stokes widget profiles

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#1644]
Currently the stokes widget is set up to use one of the channel images to get the cursor spatial coordinate position for generating the Stokes profiles. If would be extremely useful if we could use a spatial linked image to generate the x,y pixel coordinate for the profile.  The primary use case would be using a more sensitive broad-band radio image (e.g. first moment image) that shows sources to fainter flux levels than a single channel image. But in general it would be useful to use any matched image to generate the spatial coordinates for the profile.

**Comment by kswang1029** [comment]
This is supported as of v3b2 I suppose? After spatial matching, regions are shared. In the Stokes analysis widget, we can use the image and region dropdown to select the target image and region, respectively, for visualizing Stokes profiles and scatter plot. @arusstaylor could you confirm this is possible, or did I not get the idea?

**Comment by arusstaylor** [comment]
Have tried this out in v3b2.  It works as desired. Very nice.
I note that the Stokes widget still is not handling the Nan frames correctly in the plots.

**Comment by kswang1029** [comment]
Good to know matching works. 🙂 the nan channel rendering issue has been addressed in the dev and will be in v3b3.

**Comment by kswang1029** [comment]
considered as done.
