### ISSUE TITLE
Beta 3.0: cannot start

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta-frontend#1661]
I'm trying to start up the beta version, and I get an error that indicates that a GUI frontend is being loaded:

```
$ /orange/adamginsburg/software/CARTA-v3.0.0-beta.AppImage --no_browser --root=$PWD --port=35537

(CARTA:2062): Gtk-WARNING **: 10:18:04.805: cannot open display:
```

but as you can see, I specified `--no_browser` as one of the arguments.  What am I doing wrong?

**Comment by keflavich** [comment]
Should I repost/move this to https://github.com/CARTAvis/carta/issues?

**Comment by veggiesaurus** [comment]
@keflavich can you give us some more info on this? what is this running on? can you try extracting the appimage and running from there?

**Comment by keflavich** [comment]
```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)
```

Where can I find instructions for extracting & running the appimage?

**Comment by veggiesaurus** [comment]
@keflavich not sure if you found the instructions...

To extract, run `./CARTA-v3.0.0-beta.1b-ubuntu.AppImage --appimage-extract` and `cd squashfs-root` and run `AppRun` (or run `bin/carta_backend` to run the backend directly)

**Comment by keflavich** [comment]
I found and followed the instructions to put `APPIMAGE_EXTRACT_AND_RUN=1` at the start of the line, and that seems to have worked.  I don't think those instructions were there when I asked ~6 weeks ago.

**Comment by kswang1029** [comment]
May we close this issue?
