### ISSUE TITLE
The size of catalog overlay on Apple M1 and with Retina display

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#1662]
The size of catalog overlay does not increase as expected when size is larger than around 30:
![Screen Recording 2021-09-30 at 3 42 16 PM](https://user-images.githubusercontent.com/43841102/135563215-32212f71-9cac-4461-b6ec-545a10b76808.gif)

Can be reproduced only on Apple M1 and with Retina display (with `devicePixelRatio = 2`). This may be due to the difference of webgl 2.0, particularly the `Aliased Point Size Range`.

Webgl 2.0 report on Apple M1 which I am using:
<img src="https://user-images.githubusercontent.com/43841102/135562151-ea863752-675d-4b4f-ad0a-ca0fed3451d3.png" width=50% height=50%>

**Comment by kswang1029** [comment]
FYI: iPad Pro 13 M1 is free of this issue (ios 14.8)
Aliased point size range is [1, 511]

**Comment by veggiesaurus** [comment]
This should eventually be fixed by #1802
