### ISSUE TITLE
[spectral profiler] unable to display profile

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#167]
With the demo server: CARTA v1.1-alpha | frontend 2b16cf5 | backend bff7bc0 , spectral profiler does not work after the following actions:
1) load set_QA/supermosaic.10.fits
2) move cursor on the image to see profiles
3) load a new image, for example, set_QA/orion_12co_hera.hdf5
4) move cursor on the image
5) now the spectral profiler should show nothing.

**Comment by veggiesaurus** [comment]
@kswang1029 thanks, I was trying to work out a way to reproduce this bug :) 
@duidae perhaps this is related to the new guards in place?

**Comment by duidae** [comment]
let me check

**Comment by duidae** [comment]
if open 2 cubes both with spectral data consecutively, spatial profile will have "Out of bounds profile request:" error
