### ISSUE TITLE
show multiple-panel switch of the image viewer only when needed 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1676]
If we have other tab sharing the same box with the image viewer, that tab will also have the multiple-panel switch. If we switch tabs back and forth, we see more and more switches. 

https://user-images.githubusercontent.com/20819712/138095636-17546baf-d8f1-44ea-b275-5784a7f549b9.mov

also if it is the animator docked as a tab, we still see a cog. Animator widget does not have a setting dialog (yet)

**Comment by veggiesaurus** [comment]
reopening this due to issues discovered by @kswang1029
