### ISSUE TITLE
[spectral profiler] jumping channel indicator while dragging

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#168]
with the demo server: CARTA v1.1-alpha | frontend 2b16cf5 | backend bff7bc0
The channel indicator (red line) jumps back and forth while dragging. The following example tries to change the channel from 79 to 165.
![spectralProfiler](https://user-images.githubusercontent.com/20819712/54106604-a717d300-4411-11e9-8975-20f0a8529cad.gif)

**Comment by veggiesaurus** [comment]
@kswang1029 fixing this requires changing the marker to the "requested" channel instead of current channel: https://github.com/CARTAvis/carta-frontend/issues/123#issuecomment-470862572

@duidae can you give this a try?

**Comment by duidae** [comment]
@veggiesaurus okok
