### ISSUE TITLE
AST grid generation when non-zero CROTA header exists 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1689]
It appears that if the image has a non-zero CROTA header, CARTA does not render the coordinate grid lines correctly. 

![Screen Shot 2021-11-02 at 3 49 23 PM](https://user-images.githubusercontent.com/20819712/139806574-f03b8269-1e02-4b39-8f75-355ec6b94b86.png)

**Comment by veggiesaurus** [comment]
can you paste the header from DS9 here? And what does it come up as in CARTA?

**Comment by kswang1029** [comment]
> can you paste the header from DS9 here? And what does it come up as in CARTA?

left:CARTA, right:ds9
![Screen Shot 2021-11-02 at 5 03 24 PM](https://user-images.githubusercontent.com/20819712/139817099-11aca077-f2d7-45ca-a1e3-c89cc79afa6b.png)

**Comment by veggiesaurus** [comment]
:see_no_evil: can you paste the text from DS9, so that I can try run it through AST's built-in plotting routines?

**Comment by kswang1029** [comment]
my bad....

[crota_header.txt](https://github.com/CARTAvis/carta-frontend/files/7459302/crota_header.txt)

AST should be able to handle CROTA (tried the web demo)
![Screen Shot 2021-11-02 at 5 05 32 PM](https://user-images.githubusercontent.com/20819712/139818018-45cc4d63-afe9-491f-b8df-6f4c2b231076.png)

**Comment by veggiesaurus** [comment]
I wonder if it has anything to do with the weird HISTORY entries for the PC matrix?

**Comment by kswang1029** [comment]
problem (will be) solved with https://github.com/CARTAvis/carta-backend/pull/937
