### ISSUE TITLE
migrate region list to virtualised table

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#1694]
The region list is currently a simple HTML table. This is fine for very small region sets, but @duidae has made major improvements to the render speed for regions (see #1664). The bottleneck is now back on the region viewer. 

We should make this a simple virtualised table. We could use BlueprintJS tables, but I think we want to try to migrate away from them in future. Should we try just using a simple react virtualized table library, such as [react-window](https://github.com/bvaughn/react-window)?

**Comment by kswang1029** [comment]
duplicate #1252. Set estimate to 0.
