### ISSUE TITLE
Incorrect region size

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#1696]
File: Halpha_map.fits, NHI_ZEA.fits
Steps to reproduce:
1. load two images
2. spatially match the second image
3. unmatch the image
4. create a region in the second image (without panning/zooming the image first)

![image](https://user-images.githubusercontent.com/43841102/140690833-07ed8513-800a-4f07-9e00-5299cceadbc3.png)

**Comment by kswang1029** [comment]
the size difference between the control points box and the cyan solid line box seems to correlated to the image pixel ratio between the two images. 

in the following example, the two images have same FOV but the pixel size ratio is 2. 
![Screen Shot 2021-11-08 at 3 20 14 PM](https://user-images.githubusercontent.com/20819712/140699867-57f866b5-ba57-4737-8213-ff28d18ab03a.png)
