### ISSUE TITLE
Region support for V1.1

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#170]
High-level issue for all features required for V.1

- [x] Basic support for creating, resizing and editing rectangular and elliptical regions
- [x] Support for selecting which region is displayed on a per-widget basis
- [x] Regions widget showing list of regions, allowing users to select them, delete them or open their properties window
- [x] Region Properties dialog, showing the current properties of the region, and allowing users to edit them
- [x] Histogram widget for displaying histograms for a specific region
- [x] Stats widget for displaying statistics for a specific region

Things that probably won't make it into V1.1, based on timelines (these can be moved to another issue once confirmed): 
- [ ] Point regions (apart from cursor)
- [ ] Importing / exporting region files

**Comment by kswang1029** [comment]
for "Basic support for creating, resizing and editing rectangular and elliptical regions", we need HiDPi support as well. 
![hidpi](https://user-images.githubusercontent.com/20819712/54506040-8998bb00-4975-11e9-9d2d-52a585f5c114.gif)

**Comment by veggiesaurus** [comment]
@kswang1029 have created a separate issue for this: #190

**Comment by veggiesaurus** [comment]
Major features now implemented. Testing and refinements, bugfixes following.

**Comment by veggiesaurus** [comment]
@kswang1029 can we close this?

**Comment by kswang1029** [comment]
Yes. Shall we create new for point and polygon for v1.2?

**Comment by veggiesaurus** [comment]
Sure, will do so soon.

**Comment by kswang1029** [comment]
This is a big milestone! 👍👍👍
