### ISSUE TITLE
panning matched images results in region rendering out of sync

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1702]
The following example is to generate a moment image from a cube then match the two images. If we pan on one image, the region on the other image is rendered out of sync, and vice versa. 

https://user-images.githubusercontent.com/20819712/142136506-30c8dec1-fda0-4ae9-aa7f-4af248f463ea.mov

this might be related to #1696

**Comment by kswang1029** [comment]
call for helpers on this issue for v3b2 as this has more impact on usability.

**Comment by veggiesaurus** [comment]
Was this introduced in the region rendering PR? Or has it been there since multi panel view was added?

**Comment by kswang1029** [comment]
> Was this introduced in the region rendering PR? Or has it been there since multi panel view was added?

probably after region rendering PR or something else. The CUC build is fine.

**Comment by kswang1029** [comment]
> > Was this introduced in the region rendering PR? Or has it been there since multi panel view was added?
> 
> probably after region rendering PR or something else. The CUC build is fine.

this is probably due to something else. I remembered the our of sync problem had been addressed in the region rendering PR.

**Comment by veggiesaurus** [comment]
> probably after region rendering PR or something else. The CUC build is fine. 

My guess is either the region rendering or the high resolution image export PR. I guess we can assign @duidae or @YuHsuan-Hwang accordingly.

**Comment by YuHsuan-Hwang** [comment]
Can only be reproduced on Retina display. May be related to `devicePixelRatio`
