### ISSUE TITLE
pv image pixel rendering seems to have rounding effect

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1708]
This is tested with a small pv image with the offset axis having three pixels only. When we pan the image, it seems the rendered raster image can be panned to discrete locations. Also the pixel width changes. I tested with regular small spatial-spatial images and panning works fine. This can be reproduced in single panel view too. It seems this is due to the dynamic pixel ratio implementation when rendering a pv image?

UPDATE: this issue exists with non-square pixel images too.

https://user-images.githubusercontent.com/20819712/142799653-731fbe17-dd37-418a-85b0-6b767addf91c.mov

[small_pv.fits.zip](https://github.com/CARTAvis/carta-frontend/files/7578154/small_pv.fits.zip)

**Comment by kswang1029** [comment]
@veggiesaurus help wanted.

**Comment by kswang1029** [comment]
marked as a critical bug as this affects UX of PV image visualization.

**Comment by veggiesaurus** [comment]
@kswang1029 can you make a separate issue for the jumpy drag-pan, because this is unrelated to rendering itself

**Comment by kswang1029** [comment]
> @kswang1029 can you make a separate issue for the jumpy drag-pan, because this is unrelated to rendering itself

https://github.com/CARTAvis/carta-frontend/issues/1790 it is
