### ISSUE TITLE
Incorrect positions of region anchors

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#1731]
Region anchors are at incorrect positions after we view other images.

One way to reproduce:
1. disable multi-panel mode
2. open two images
3. create a region in the first image (used file: HD163296_CO_2_1.fits)
![image](https://user-images.githubusercontent.com/43841102/144006603-f64eb542-4218-4cf8-8ee1-4ddda7a7f73b.png)
4. set the active frame to the second image
5. set the active frame to the first image
![image](https://user-images.githubusercontent.com/43841102/144006674-8e4d39f4-0905-4d0a-a4bc-e2ea4e084841.png)
6. the anchors move back to the correct position if we pan the region

**Comment by kswang1029** [comment]
different from https://github.com/CARTAvis/carta-frontend/issues/1696?

**Comment by YuHsuan-Hwang** [comment]
> different from #1696?

found in the latest `dev` branch

**Comment by kswang1029** [comment]
if we switch between the single and multiple panel view and switch active image, we can see region jumps/got resized to other location. 🤔

**Comment by kswang1029** [comment]
I see a pattern here with zoom actions only:
if we have a 4 pixel by 4 pixel image loaded with a region of 2 pixel by 2 pixel at the image center, then on the secondary image, the region is rendered to fill up the field of view at 2x zoom level.

primary image

![Screen Shot 2021-11-30 at 5 06 43 PM](https://user-images.githubusercontent.com/20819712/144017929-3639dbf5-0bdc-41e2-89c5-80e665f3ff69.png)

secondary image

![Screen Shot 2021-11-30 at 5 07 12 PM](https://user-images.githubusercontent.com/20819712/144017987-a92ed4db-67ea-455e-aa47-396fb7fa4b21.png)


If the test image is 5 pixel by 5 pixel and a region of 1 px by 1 px at center, then on the secondary image we need 5x zoom level to see the rendered image filled up the field of view.

primary image

![Screen Shot 2021-11-30 at 5 12 17 PM](https://user-images.githubusercontent.com/20819712/144018673-a6a7fa7c-467a-487c-a242-e515fead744c.png)

secondary image

![Screen Shot 2021-11-30 at 5 11 47 PM](https://user-images.githubusercontent.com/20819712/144018705-dfd1d4eb-9485-4644-ad87-7e160a211931.png)


If pan action is involved, we will see region got rendered with an offset (possibly correlated to the amount of pan offset)

**Comment by kswang1029** [comment]
@duidae could you please check this issue? it is from the performance improvement PR and could not be picked up.
