### ISSUE TITLE
persistent export image tooltip

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1742]
This only happens after 100% resolution is clicked.

<img width="521" alt="Screen Shot 2021-12-07 at 1 49 04 PM" src="https://user-images.githubusercontent.com/20819712/144973861-405c1964-bce4-4cd2-8f51-c8e9a4c25714.png">

**Comment by veggiesaurus** [comment]
@kswang1029 what browser and OS were you using? @Michaelazzz can't reproduce this issue

**Comment by kswang1029** [comment]
macOS Monterey and chrome browser 


https://user-images.githubusercontent.com/20819712/162920443-5318dcdb-9a57-408a-9593-f935f06c3685.mov

**Comment by veggiesaurus** [comment]
I can reproduce this with Linux and Chrome as well
