### ISSUE TITLE
region re-rendering with click to pan method

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1751]
Reported by a user using v3b2 release.

To reproduce:
1) load an image and create few region
2) hold command (Mac) or control (linux) and click to pan the image (or use preferences dialog to enable click-to-pan as default pan method)  
3) we should see regions are not rendered at their correct locations.

https://user-images.githubusercontent.com/20819712/146339612-8c9c217f-9fb3-4b2c-bdde-b253ad0e64a6.mov

**Comment by veggiesaurus** [comment]
is this the same thing that @Jordatious spotted? :thinking:

**Comment by Jordatious** [comment]
Hmm yes it seems to be the same as https://github.com/CARTAvis/carta/issues/110, except mine often corrected itself eventually!
