### ISSUE TITLE
stokes widget does not handle Nan channels correctly in line or step style plotting

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#1752]
In latest beta release 3.00 b2  the Stokes widget is not doing the right thing for Nan channels It is showing a value which looks it is the close value of the actually data. This is not the desired behaviour.   This only occurs for line or step style plotting.  It works correctly for scatter plots (i.e.points).  

<img width="878" alt="Screenshot 2021-12-16 at 10 28 22" src="https://user-images.githubusercontent.com/9055533/146428318-98347297-a8de-4dd9-b841-8308373dbc30.png">

**Comment by veggiesaurus** [comment]
I wonder if this is related to the chartjs upgrade 🤔

**Comment by kswang1029** [comment]
possibly. @arusstaylor do you have a test cube for us to implement regression test?

**Comment by kswang1029** [comment]
possibly. I will try to make a test cube and use that to create a regression test.

**Comment by arusstaylor** [comment]
There are several on the /carta_share mount at IDIA.  Can you access these?

**Comment by arusstaylor** [comment]
There are several on the /carta_share mount at IDIA.  Can you access these?  

Russ

**Comment by kswang1029** [comment]
I don't have access but I think I can make a test stokes cube directly. Thanks.

**Comment by arusstaylor** [comment]
Hi, were you able to make a test cube for this?  Let me know if you need me to do anything.

**Comment by kswang1029** [comment]
Yes. I have generated a cube for testing and fixing the issue. Thanks.
