### ISSUE TITLE
Ability to render older AIPS cubes with FELO-HEL velocity axis

### ISSUE THREAD

**Issue by jehibbard** [CARTAvis/carta-frontend#1771]
**Describe the bug**
v2.0 correctly renders older cubes that have CTYPE3 units of FELO-HEL or VELO-LSR, but v3.0-2b does not.

**To Reproduce**
1. Get the two cubes from https://www.cv.nrao.edu/~jhibbard/FITS/u10214/ (one is VLA data reduced in AIPS, the other from CARMA reduced in Miriad
2. Read them into both CARTA v2.0 and v3.0-2b
3. Set up contours for each cube (levels don't matter)
4. You'll see the following:
- the velocity units in v3b are not km/s, and frequency is not reported
- the contours from one cube overlay on different channels in the other (v2.0 is correct)
- the zprofile spectra look the same, but using the red bar to change the channel works very differently in the two versions (e.g. whether or it changes the channel that is displayed/contoured depends on which image is selected, and whether or not you are in the region where the spectra overlap or not)
- in the image widget grear wheel, the restfreq does not show up even though this field is filled in the image headers

**Expected behavior**
I expect v3b to give same results as v2.0

**Screenshots or videos**
See text in attached screenshot 
![CARTA-FELO-HEL-issue](https://user-images.githubusercontent.com/72573082/152605546-acfa67da-bd86-4dc8-90a2-409f9a717ed7.png)

**Platform info (please complete the following information):**
 - OS: [e.g. iOS] macOS Catalina 10.15.7
 - Browser [e.g. chrome, safari] Safari 15.3
 - Version [e.g. 22] v2.0 & 3.0-2b

**Additional context**
Here is what Kuo-Song had to say about this problem:

"This is because before v2.0 (inclusive), RAW FITS headers are pre-processed by casacore to have a unified format (happen at the backend) for the frontend to render coordinate grid and perform image matching. After v2.0, due to users’ complaints about not seeing RAW headers or casacore not processing headers correctly, we (actually Pam did :) ) removed the casacore preprocessor and just use CFITSIO to get the RAW header. So in this case, yes, I think this is because the frontend library we used for coordinate grid and image matching (AST) may not interpret or handle FELO-HEL well. Could you submit an issue to the frontend repo? We will try to investigate this backward compatibility issue. Thanks."

**Comment by pford** [comment]
Backend PR merged, to restore previous behavior using casacore FITS headers when this velocity axis is detected.

@kswang1029 please close this issue when appropriate.
