### ISSUE TITLE
frontend crash when the histogram in the render config is panned/zoomed to view empty data

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1777]
**Describe the bug**
The histogram plot in the render config widget adjusts the y-range automatically. When we pan and zoom the histogram showing empty data points, the docked widget will crash. If the widget is undocked, the entire frontend GUI will crash. This histogram widget, however, does not have this issue. 

**To Reproduce**
1. load an image
2. pan/zoom the histogram so that there is no histogram data point in the plot
3. the issue shows up

**Expected behavior**
the frontend GUI should not crash. The behavior of the histogram widget is fine. 

**Screenshots or videos**

https://user-images.githubusercontent.com/20819712/152913172-9ee51f59-6cb1-4d9b-996c-24aa36c92715.mov

![Screen Shot 2022-02-08 at 11 36 43](https://user-images.githubusercontent.com/20819712/152913429-0c610c75-88c2-4dfd-b077-a0724be69321.png)

**Platform info (please complete the following information):**
 - OS: macOS Monterey
 - Browser: chrome
 - Version 98.0.4758.80 

**Additional context**
N/A

**Comment by veggiesaurus** [comment]
Probably a duplicate of #1772

**Comment by kswang1029** [comment]
fixed by #1773
