### ISSUE TITLE
Feature request: copy from window

### ISSUE THREAD

**Issue by acsch** [CARTAvis/carta-frontend#1795]
When loading or saving a region file, the content appears in a window. It
would be useful to be able to copy the text (and paste it into a local
file) which is sometimes preferable/faster over saving and downloading the
file via ssh.

**Comment by kswang1029** [comment]
fixed via #1798

**Comment by veggiesaurus** [comment]
@kswang1029 this doesn't allow you to actually copy a new region file to the clipboard, right?

**Comment by kswang1029** [comment]
we can use cursor to select texts and use ctrl+c or cmd+c to copy the text to the clipboard. Simply selecting should not trigger copy automatically. Do I understand the question correctly?

**Comment by acsch** [comment]
The cursor does not select any text for me, that's the problem. Are we 
talking about the same window? When I click on 'import region', then 
select a region in the file browser, the content of the file is viewable 
but not selectable.

**Comment by kswang1029** [comment]
> The cursor does not select any text for me, that's the problem. Are we talking about the same window? When I click on 'import region', then select a region in the file browser, the content of the file is viewable but not selectable.
> […](#)

It should have just been fixed in the dev. Will be available in the v3-beta3 release (~late April 2022)

**Comment by acsch** [comment]
Okay, thanks!

**Comment by Jordatious** [comment]
Would downloading the region file (i.e. to your local disk and not to the server, similar to exporting the image as a PNG) address this a bit more comprehensively?

**Comment by kswang1029** [comment]
#1798 enables cursor text selection only. Then it is up to the user to use ctrl+c / cmd+c to copy the text to the clipboard.

**Comment by veggiesaurus** [comment]
> we can use cursor to select texts and use ctrl+c or cmd+c to copy the text to the clipboard. Simply selecting should not trigger copy automatically. Do I understand the question correctly?

what I'm saying is that you can only do this for existing regions. If you want to copy a _new_ region set to the clipboard, you have to save it, then open the browser again and select the text.

I can imagine scenarios where saving a sub-cube or a region to your local computer would be very useful. Especially in situations like the ALMA archive. I but I think this is a separate issue

**Comment by acsch** [comment]
It certainly would help since it cuts out some of the intermediate steps.
