### ISSUE TITLE
Feature request: Show/hide regions

### ISSUE THREAD

**Issue by acsch** [CARTAvis/carta-frontend#1796]
The overlay of a region affects one's search for sources (it distracts and
can block out fine features). One might also like to see the unobstructed
image and compare it with the regions one found, without going through the
effort of removing (currently not easy for many regions) and reloading. It
would thus be very useful to be able to show an hide regions (cf ds9).

**Comment by Jordatious** [comment]
@kswang1029 wasn't this once a feature? I'm not sure where it has gone. Maybe it is now hidden ;)

**Comment by kswang1029** [comment]
> @kswang1029 wasn't this once a feature? I'm not sure where it has gone. Maybe it is now hidden ;)

@Jordatious nope. At the moment only the raster image layer and the contour image layer can be hidden via the image list widget.

**Comment by YuHsuan-Hwang** [comment]
closed via #1940
