### ISSUE TITLE
Bad behavior when coming back from sleep

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta-frontend#1808]
I'm using the standalone app v3.0.0-beta.1b on my mac laptop.  When I put the computer to sleep (close it), it appears to clear the GPU cache.  CARTA then goes into a waiting mode where it asks whether to reload the session.  As long as it's in this waiting mode, it uses ~50% CPU according to activity monitor, using up battery & causing the fans to go strong - i.e., it's doing a lot of processing for nothing.  As soon as I hit 'Retry', the problem clears up.  It would be helpful to avoid this behavior.

**Comment by kswang1029** [comment]
It appears related to the electron wrapper. carta_backend uses 0% cpu during that state. @ajm-asiaa do you have any idea?

**Comment by ajm-ska** [comment]
I reproduced the issue on my MacBook using the Electron version. After waking from sleep, the frontend reports the "_You have been disconnected from the server. Do you want to reconnect message?_". Then I see the `CARTA-v3.0.0-beta.1 Helper (GPU)` process in Activity Monitor jumps to more than 30%. 

After that, I tried the Homebrew version of CARTA with the frontend running in Chrome. I checked Chrome processes in the Activity Monitor when frontend is displaying the disconnect message and I saw the `Google Chrome Helper (GPU)` process jumping to around 40%. 

Therefore it is not exclusively a CARTA Electron version issue. It seems to be related to Chrome (Although I know Electron is basically Chrome). 

Finally I tried the Homebrew version of CARTA with the frontend running in Firefox. With Firefox, CARTA does not appear to disconnect when the MacBook goes to sleep for some reason. It warrants further investigation, but maybe a workaround for now is to use the Homebrew version of CARTA with Firefox? 

Perhaps @veggiesaurus may have an idea as to why the "Retry" screen on the frontend occupies CPU?

This might even be an issue on Linux laptops that are running the Debian versions of CARTA with Chrome, or a carta-controller session that has disconnected and idle in a tab of the user's browser. I guess it happens on Desktop computers too, but there, occupied CPU is not as noticeable. @confluence Are you reproduce the issue on a Linux laptop?

**Comment by confluence** [comment]
I believe that I have reproduced the issue in the Focal packaged version using Firefox. If I use Chromium, the session reconnects automatically.

(If anyone else wants to try reproducing this, bear in mind that by default your OS may enter an idle state rather than an actual powered-down sleep mode. I'm not sure what the current situation is with macOS.)

This is definitely a browser / frontend-related issue.

**Comment by kswang1029** [comment]
@veggiesaurus do you have any idea about this issue? It might be good to address this for v3b3 if time allows.

**Comment by kswang1029** [comment]
lower priority for v3-final release
