### ISSUE TITLE
page switch buttons show up elsewhere after an image is loaded

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1817]
**Describe the bug**
page switch buttons show up elsewhere after an image is loaded

<img width="847" alt="Screen Shot 2022-03-31 at 10 31 45" src="https://user-images.githubusercontent.com/20819712/160964491-d3d9a331-bbbf-4cb4-93d7-1a2128d77e8f.png">

**To Reproduce**
load an image and observe the top-right corner of each widget. 

**Expected behavior**
only the image viewer needs page switch buttons at the top right corner.

**Platform info (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome
 - Version 100

**Comment by kswang1029** [comment]
@TienHao sorry I may miss the problem when checking https://github.com/CARTAvis/carta-frontend/pull/1804 could you have a look again for v3b3 release please?

**Comment by TienHao** [comment]
> @TienHao sorry I may miss the problem when checking #1804 could you have a look again for v3b3 release please?

@kswang1029 Sure. not a problem.
