### ISSUE TITLE
an option to hide cursor info bar in the image viewer

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1818]
when multiple panel view is enabled with many images loaded, the cursor info bar in the active panel likely would block space for cursor interaction. As now we have the cursor info widget, we should consider adding an option in the settings dialog to hide the cursor info bar.

**Comment by veggiesaurus** [comment]
![image](https://user-images.githubusercontent.com/592504/162143307-40c23c30-889d-4aee-85db-dc13783cf724.png)
don't we have that already?

**Comment by kswang1029** [comment]
🙈
