### ISSUE TITLE
Add NonIdealState for image save panel

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#1827]
**Describe the bug**
Need `NonIdealState` for the image save panel when there is no active images.

**To Reproduce**
1. Open a file
2. Open Save image dialog from the menu
3. Close the file by the menu or the image list widget
4. See crash

**Expected behavior**
See NonIdealState

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/43841102/163119076-6d5f43d4-b966-444f-9bc1-7acdd4a577b2.png)

**Platform info (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: latest dev branch

**Comment by kswang1029** [comment]
embarrassing!
