### ISSUE TITLE
provide an optional second spectral conversion to the cursor info in the spectral profiler 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1837]
given the time pressure of the v3 release, an alternative solution for the feature https://github.com/CARTAvis/carta-frontend/issues/1703 (see implementation challenges in https://github.com/CARTAvis/carta-frontend/pull/1835) is to just add an additional spectral value based on the user selection to the cursor info in the spectral profiler.

![Screen Shot 2022-04-26 at 15 55 32](https://user-images.githubusercontent.com/20819712/165250902-715118cf-5f6f-40bf-9cda-f507d6da740a.png)

In the above example, at the moment we show (frequency, intensity). If it is enabled from the settings dialog (default off) and velocity is selected, then we show (frequency, velocity, intensity) instead. 

The reference image for freq-velo conversion should be the “active” or user-selected image. This is relevant when multi-profile plot mode is enabled. 

quick mockup
![Screen Shot 2022-04-26 at 16 44 23](https://user-images.githubusercontent.com/20819712/165262175-056b43bf-67c5-46ea-b9df-f8df954d6036.png)

Attached is a doc I compiled from AST user manual regarding spectral and spatial conversion functions. Hope it helps.
[carta_ast_specConvert_wcConvert.pdf](https://github.com/CARTAvis/carta-frontend/files/8561046/carta_ast_specConvert_wcConvert.pdf)

**Comment by kswang1029** [comment]
@jrhosk @YuHsuan-Hwang This is one of the possible (and easiest maybe) solutions for #1703 that I can think of. As for the actual implementation of adding a 2nd spectral axis as PR #1835 is doing, there might be another way to achieve similar result by treating x2 and y2 axis as independent axes (based on my understanding from chartjs doc) but this requires R&D time to verify the idea. For the upcoming v3 release, I suggest we try to achieve the cursor info approach and worry about #1703 later on. Please let me know if this is sensible to you. :)

**Comment by jrhosk** [comment]
So the consensus is that I should work on #1703 and leave #1835 until some R&D can be done?

**Comment by jrhosk** [comment]
> given the time pressure of the v3 release, an alternative solution for the feature #1703 (see implementation challenges in #1835) is to just add an additional spectral value based on the user selection to the cursor info in the spectral profiler.
> 
> ![Screen Shot 2022-04-26 at 15 55 32](https://user-images.githubusercontent.com/20819712/165250902-715118cf-5f6f-40bf-9cda-f507d6da740a.png)
> 
> In the above example, at the moment we show (frequency, intensity). If it is enabled from the settings dialog (default off) and velocity is selected, then we show (frequency, velocity, intensity) instead.
> 
> The reference image for freq-velo conversion should be the “active” or user-selected image. This is relevant when multi-profile plot mode is enabled.
> 
> quick mockup ![Screen Shot 2022-04-26 at 16 44 23](https://user-images.githubusercontent.com/20819712/165262175-056b43bf-67c5-46ea-b9df-f8df954d6036.png)
> 
> Attached is a doc I compiled from AST user manual regarding spectral and spatial conversion functions. Hope it helps. [carta_ast_specConvert_wcConvert.pdf](https://github.com/CARTAvis/carta-frontend/files/8561046/carta_ast_specConvert_wcConvert.pdf)

The document is great, thank you! Are there other such documents? More documentation would be amazing.

**Comment by kswang1029** [comment]
> So the consensus is that I should work on #1703 and leave #1835 until some R&D can be done?

@jrhosk we should evaluate these two features with @YuHsuan-Hwang and see which one is realistic for v3 final release.

**Comment by YuHsuan-Hwang** [comment]
> @jrhosk we should evaluate these two features with @YuHsuan-Hwang and see which one is realistic for v3 final release.

I would prefer we work on this issue for v3

**Comment by kswang1029** [comment]
> > @jrhosk we should evaluate these two features with @YuHsuan-Hwang and see which one is realistic for v3 final release.
> 
> I would prefer we work on this issue for v3

How about this feature goes first and if time allows, revisit #1703 and continue #1835?. The two features have common parts (spectral conversion, specifically) so part of codes in #1835 may be re-used I guess.
