### ISSUE TITLE
mean and rms do not update after smoothing

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#1838]
The display of the mean and rms in a profile do not update when smoothing.  I set a profile do display the mean and rms.  Then I smoothed the data.  The mean should not change due to smoothing but the rms will.  However, the mean and rms do not update after smoothing.    Whenever a new smooth is implemented the mean and rms should update if they are turned on.

**Comment by kswang1029** [comment]
we can also overplot the original profile together with the smoothed profile. Do you mean, as long as smoothing is applied, we  should use the smoothed profile to render the green rms/mean box?

**Comment by arusstaylor** [comment]
If you are showing  only the smoothed profile then the green rms/mean box should be from the smoothed data.  If both the original and smoothed are displayed this it is more complicated. Ideally one would show the results for both.

**Comment by kswang1029** [comment]
> If you are showing only the smoothed profile then the green rms/mean box should be from the smoothed data. If both the original and smoothed are displayed this it is more complicated. Ideally one would show the results for both.

thanks. I will think about the case when both original and smoothed profiles are rendered at the same time.
