### ISSUE TITLE
catalog overlay matching position error

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1842]
**Describe the bug**
With a set of controlled images and catalog which the world coordinates of test sources are known, it appears that a matching error is seen in the test like the following screenshot. Please help confirming that this issue is reproducible.

![model fits-model_imregrid_galactic fits-image-2022-05-09-14-10-09](https://user-images.githubusercontent.com/20819712/167350812-27ed36af-ddf7-471a-b394-00922ce347e7.png)

If we just load one of each image separately and render the catalog, positions are accurate. 

**To Reproduce**
1. get a copy of the test images and catalog at https://drive.google.com/file/d/1KPtBSxrenhYZFkn3UslfDB0IAuX9kXVZ/view?usp=sharing
2. load the two images and match them 
3. load the catalog and enable catalog overlay rendering
4. observe the image to see the position offset

**Expected behavior**
no position offset is observed. 

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 101
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Comment by veggiesaurus** [comment]
> **Describe the bug** With a set of controlled images and catalog which the world coordinates of test sources are known, it appears that a matching error is seen in the test like the following screenshot. Please help confirming that this issue is reproducible.
> 
> ![model fits-model_imregrid_galactic fits-image-2022-05-09-14-10-09](https://user-images.githubusercontent.com/20819712/167350812-27ed36af-ddf7-471a-b394-00922ce347e7.png)
> 
> If we just load one of each image separately and render the catalog, positions are accurate.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. get a copy of the test images and catalog at https://drive.google.com/file/d/1KPtBSxrenhYZFkn3UslfDB0IAuX9kXVZ/view?usp=sharing
> 2. load the two images and match them
> 3. load the catalog and enable catalog overlay rendering
> 4. observe the image to see the position offset
> 
> **Expected behavior** no position offset is observed.
> 
> **Platform info (please complete the following information):**
> 
> * OS [e.g. macOS Monterey]: macOS Monterey
> * Browser [e.g. chrome, safari, electron app]: chrome
> * Browser version [e.g. 22]: 101
> * Backend branch [e.g. dev, v3b2 release]: dev
> * Frontend branch [e.g. dev, v3b2 release]: dev

what happens if you increase the control map resolution?

**Comment by kswang1029** [comment]
> > **Describe the bug** With a set of controlled images and catalog which the world coordinates of test sources are known, it appears that a matching error is seen in the test like the following screenshot. Please help confirming that this issue is reproducible.
> > ![model fits-model_imregrid_galactic fits-image-2022-05-09-14-10-09](https://user-images.githubusercontent.com/20819712/167350812-27ed36af-ddf7-471a-b394-00922ce347e7.png)
> > If we just load one of each image separately and render the catalog, positions are accurate.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. get a copy of the test images and catalog at https://drive.google.com/file/d/1KPtBSxrenhYZFkn3UslfDB0IAuX9kXVZ/view?usp=sharing
> > 2. load the two images and match them
> > 3. load the catalog and enable catalog overlay rendering
> > 4. observe the image to see the position offset
> > 
> > **Expected behavior** no position offset is observed.
> > **Platform info (please complete the following information):**
> > 
> > * OS [e.g. macOS Monterey]: macOS Monterey
> > * Browser [e.g. chrome, safari, electron app]: chrome
> > * Browser version [e.g. 22]: 101
> > * Backend branch [e.g. dev, v3b2 release]: dev
> > * Frontend branch [e.g. dev, v3b2 release]: dev
> 
> what happens if you increase the control map resolution?

I tried 512x512 only but it doesn’t help.

**Comment by kswang1029** [comment]
@veggiesaurus you are right about speculating it is the control map resolution. The error is correlated with the control map. With 1024, it is more accurate. The error increases when we decrease it to 512, 256, and 128, respectively.  

![cm_128](https://user-images.githubusercontent.com/20819712/167368951-92c39805-12c8-44e8-8e0f-41a41db4e69d.png)
![cm_256](https://user-images.githubusercontent.com/20819712/167368960-25e467c8-051d-4aac-82cd-0553f7cc4222.png)
![cm_512](https://user-images.githubusercontent.com/20819712/167368966-e7aab0fb-22cf-4a1a-9bea-565095488b1a.png)
![cm_1024](https://user-images.githubusercontent.com/20819712/167368969-31203939-7525-4dbe-a87a-c6fba702e05d.png)

**Comment by YuHsuan-Hwang** [comment]
fixed via #1870
