### ISSUE TITLE
performance impact to the file browser when trying to export regions from a large set of regions

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1867]
Moving the file browser becomes much less responsive when the region list is long. 

To experience this issue, please try to load 10 regions and launch the file browser for region exporting. Then try to drag and drop the file browser to a new location (or try to resize the dialog). This should give us a smooth user experience. Now repeat the exercise by loading 1000 regions instead. The file browser becomes much less responsive when we try to resize the dialog or relocate the dialog. 

https://user-images.githubusercontent.com/20819712/169963478-7e5da254-fafd-4d1a-b2ae-275443b7e499.mov

**Comment by veggiesaurus** [comment]
I think we just need to make a virtualised list for this
