### ISSUE TITLE
Add a link to the dashboard on the splash screen

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#1874]
There are some situations where the user gets stuck at the splash screen (e.g. the backend has crashed or locked up, or their authentication is invalid). It would be useful to add a link to the dashboard (in situations where there _is_ a dashboard, i.e. in SDM) to this splash screen.

Suggested by @Jordatious after feedback from IDIA users

**Comment by veggiesaurus** [comment]
![image](https://user-images.githubusercontent.com/592504/171608469-ca2d3cf9-b91b-4f45-bc37-5c2e4b6963cd.png)

@Jordatious where would you suggest we add this?

**Comment by Jordatious** [comment]
Suggested by @Jordatious after telling users endlessly how to restart their backend!

What about something like this?
![171608469-ca2d3cf9-b91b-4f45-bc37-5c2e4b6963cd](https://user-images.githubusercontent.com/10542136/171626456-56f6bb9d-1691-4748-bb87-e91f9c0401c1.png)

**Comment by kswang1029** [comment]
If there is a timeout for such cases, maybe we can reuse the popup prompt for reconnection when we lost connection of an existing session. Then for SDM the dashboard button is also included.

**Comment by kswang1029** [comment]
this is related to #1895
