### ISSUE TITLE
Turn off automatic vopt to vrad conversion in header display

### ISSUE THREAD

**Issue by kmhess** [CARTAvis/carta-frontend#1877]
**Describe the bug**
CARTA does not display the true FITS header.  It either converts (in the case of ctype3='velo-hel'), or insists (in the case of ctype3='freq') that the data is in the radio convention even if it is not true.  It also displays the wrong spatial coordinate type.

**To Reproduce**
1. Load a file that is has 'CTYPE3=VELO-HEL'. 
2. Inspect the header of the file in the file browser.  In the 'Header' tab, the 'CTYPE3' is always displayed as 'VRAD'.  In the 'File information' tab, the 'velocity definition' is always set to radio. Display the original header of the FITS file. 
3. Load a file that is has 'CTYPE3=FREQ'. 
4. Inspect the header of the file in the file browser.  In the 'File information' tab, it has a velocity definition set to radio, even though this makes no sense in the context of the data.
5. Load a file that has 'CTYPE1=RA---NCP' and 'CTYPE2=DEC--NCP'. 
6. Inspect the header of the file in the file browser.  In the 'Header' tab, these will always be displayed as '*--SIN'.

**Expected behavior**
Display the original header of the FITS file!

**Screenshots or videos**
Left is the header from CARTA; right is the output from astropy.  DS9 and astropy header displays are the same, so I can only assume that CARTA is the one doing the conversion. In particular note that CTYPE* are all different as well as CRVAL3, CRPIX3, CDELT3.
<img width="1579" alt="Screen Shot 2022-06-06 at 11 36 29" src="https://user-images.githubusercontent.com/14857798/172183227-d506202c-77ff-41d5-a30b-d2f15927b89a.png">

**Platform info (please complete the following information):**
 - macOS Monterey 12.3.1

 - CARTA 2.0.0

**Additional context**

**Comment by kswang1029** [comment]
Could you please give v3-beta3 a try? We have made changes in header parsing after v2.0 release.

**Comment by kmhess** [comment]
Okay, thanks for the heads up.

**Comment by kswang1029** [comment]
@kmhess thanks. please do let us know if v3-beta3 works or not.

**Comment by kmhess** [comment]
@kswang1029 It looks like the Apple-M1 v3-beta3 version works.  Thanks for the heads up.  In checking this, I found another issue which I will post separately.
