### ISSUE TITLE
Creating polygon regions on spatially matched images

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#1887]
**Describe the bug**
When creating a polygon region on a spatially matched image, we render dash lines for preview. The dash lines are unprojected straight lines, and then are projected into curves after a new control point is created. However, the last line segment remains a unprojected straight line after the entire region is created.

**To Reproduce**
1. Open two images and match the second one to the first one.
2. Create a polygon region on the second image. The last line segment (the horizontal line in the image) remains a straight line.
<img src="https://user-images.githubusercontent.com/43841102/173982534-0f0a4bac-4f5c-4551-bed6-aa7e2253dd9b.png" width="300" />
4. Unmatch and rematch the second image. The last line segment is correctly projected now.
<img src="https://user-images.githubusercontent.com/43841102/173982560-e18d682c-7a64-46f4-8d31-6e6435b6f081.png" width="300" />

**Expected behavior**
All line segments are correctly projected.

**Screenshots or videos**

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: M1 macOS BigSur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 102
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Additional context**

**Comment by kswang1029** [comment]
Uh nice catch 🙈
