### ISSUE TITLE
[critical bug for v3-final release] Regions shifting visually when multiple images opened

### ISSUE THREAD

**Issue by marcinglowacki** [CARTAvis/carta-frontend#1899]
**Describe the bug**
Regions can appear misaligned (or the wrong region being selected) when having regions imported onto multiple images, e.g. image cubes. This is reflected in the carta viewer and also in saved images. 

**To Reproduce**
Open two images (in my case, at least one being an image cube, not tried 2 continuum cubes) with regions imported. Scroll in and out, select different region boxes, etc.. Can be exasperated by then closing the 2nd image (see attachment showing resulting visual display). Possible issues enhanced by streaming large image cubes from Australia. 

**Expected behavior**
Not this. 

**Screenshots or videos**
Saved image showing the region box is shifted to the upper left from where it was originally (centre, around the contours). Contours and background image are correctly aligned. 
![J_exampleoverlay](https://user-images.githubusercontent.com/29977213/176629299-584fc0f6-b667-47cb-b4d2-e39b579545ba.png)

View after closing a second image, in this case a second image cube. 
![cartabeta_graphicalissue](https://user-images.githubusercontent.com/29977213/176629309-3e34a473-6007-4030-94f8-57562994861a.png)

If applicable, add screenshots/videos to help explain your problem.

**Platform info (please complete the following information):**
 Browser (Chrome); carta-beta [ilifu]

**Additional context**

**Comment by kswang1029** [comment]
@marcinglowacki could you record what you have been doing to reproduce the issues as a video please? If possible, starting with a fresh session.

**Comment by kswang1029** [comment]
> @marcinglowacki could you record what you have been doing to reproduce the issues as a video please? If possible, starting with a fresh session.



> @marcinglowacki could you record what you have been done to reproduce the issues as a video please? If possible, starting with a fresh session.

**Comment by kswang1029** [comment]
Out of curiosity, the image with contours has the colorbar to the right side misaligned with the FOV box. 🤔️

**Comment by marcinglowacki** [comment]
I have uploaded a couple videos here: https://drive.google.com/file/d/1TzvrEN9qDNT7DKMsnHIETkEEQ-t0ekpG/view?usp=sharing 

They show a) a successful case of opening two images (spectral line cube and a single-channel image), loading regions correctly, making a moment 0 map, saving the image, and the image looking fine, and b) a unsuccessful case where I loaded images separately, and had the second open when importing regions (same file). Regions are shifted well away from where they should.

CARTA1 and CARTA2.png follow that second video showing the regions imported fine again when selecting the first image first and then importing regions again. Selecting the same specific region box whether it is wrongly shifted visually or not (the difference between the two images) shows that CARTA still understands where it actually is (same spectrum in the Z Profile window), even when it isn't showing it in the right place. I have seen this issue in different cases earlier this week (no recording, sorry) for two image cubes rather than one image cube, one continuum image.

**Comment by kswang1029** [comment]
@marcinglowacki sorry the url points to CARTA2.png.

**Comment by kswang1029** [comment]
ok. I think I can reproduce the issue.

**Comment by kswang1029** [comment]
To reproduce the problem:
1. download the attached test images
2. load m51_151_MHz.fits
3. load the region file test.crtf and we should see 
![Screen Shot 2022-07-01 at 10 44 27](https://user-images.githubusercontent.com/20819712/176813265-4e28bf44-2a96-4e62-8a3c-a9ca09f802f5.png)
These set of regions are rendered at their correct locations as our reference.
4. start over again, load m51_151_MHz.fits
5. append m51cm3i_8_small.fits
6. match them spatially and set m51cm3i_8_small.fits as active
7. load region file test.crtf and we should see
![Screen Shot 2022-07-01 at 10 48 11](https://user-images.githubusercontent.com/20819712/176813663-43020598-34a8-4a40-9232-2324d0ce9ac6.png)
Regions are not rendered at the correct locations.

[carta_region_import_on_matched_image.zip](https://github.com/CARTAvis/carta-frontend/files/9024702/carta_region_import_on_matched_image.zip)


The issue appears to be related to the pixel size ratio of the reference image and the matched image. In the following example, the two images have identical FOV but the pixel size of cluster_00128.fits is twice the pixel size of cluster_00256.fits. Then if we have them as the matched image, respectively, we see the region has position offset correlated to the pixel size ratio.
![Screen Shot 2022-07-01 at 10 56 03](https://user-images.githubusercontent.com/20819712/176814952-b58fee07-654f-41b5-8bc0-c8e1235f3aa0.png)
![Screen Shot 2022-07-01 at 10 55 30](https://user-images.githubusercontent.com/20819712/176814965-56b4643a-9e76-4c82-9610-53a28e79a43d.png)

**Comment by kswang1029** [comment]
It turns out that the region image coordinates returned from the backend use the matched image as the image coordinate reference (IMPORT_REGION/groupId:1). But as two images are now matched, so the region should now refer to the reference image as the reference then do the usual region matching steps to map region from reference image to matched image. 
![Screen Shot 2022-07-01 at 11 10 13](https://user-images.githubusercontent.com/20819712/176816057-60e52288-61bc-452e-bacb-72c44ce801a2.png)

**Comment by marcinglowacki** [comment]
> 

Apologies; https://drive.google.com/drive/folders/1XKPTucoTYs7nKUD6OYcdq8PqRh1o3A1V?usp=sharing

**Comment by kswang1029** [comment]
> Apologies; https://drive.google.com/drive/folders/1XKPTucoTYs7nKUD6OYcdq8PqRh1o3A1V?usp=sharing

Yes, thank you. Confirmed that we are seeing the same issue.
