### ISSUE TITLE
Scripting support: allow hiding of colorbar gradient element

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#1908]
In the `OverlayColorbarSettings`, every element of the colorbar can be shown or hidden independently, except for the colour gradient itself.

This is inconvenient for the scripting use case of fetching different layers of the image view separately and vectorising some of them. While the border, numbers, etc., are drawn elements which are vectorisable, the gradient is not, and should be kept as a raster image.

It is currently possible to save just the gradient to its own layer (by hiding everything else), but it is not possible to save everything _except_ the gradient to its own layer. An additional boolean flag for gradient visibility would solve this problem.

**Comment by veggiesaurus** [comment]
I don't see any reason to add this to any user facing preference, but have no problem with it being added as an underlying function
