### ISSUE TITLE
ellipse region: major axis definition in CARTA and CASA

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#191]
In CASA, the major axis of an ellipse region is pointed in North-South direction, probably this is how it is defined in CRTF:
_Ellipse; center of the ellipse is [x, y]; semi-major and semi-minor axes are [bmaj, bmin]; position angle of the major axis is pa:
ellipse[[x, y], [bmaj, bmin], pa]_

So a CRTF file as:
_ellipse [[05:35:27.46552, -005.26.24.6684], [856.4888arcsec, 93.6376arcsec], 0.00000000deg] coord=J2000, corr=[I]_
is visualized as
![Screen Shot 2019-03-19 at 10 46 41 AM](https://user-images.githubusercontent.com/20819712/54576736-523d1380-4a34-11e9-9e11-d84117ed9d7b.png)

However, in CARTA, the major axis of an ellipse is in East-West (this is the usual mathematical definition). See below, the shape of the ellipse and the size values in the region list.
![Screen Shot 2019-03-19 at 10 53 04 AM](https://user-images.githubusercontent.com/20819712/54577051-38e89700-4a35-11e9-8c80-ffe96c45caf5.png)

We will have to choose a side to align with, and as we adopts CRTF in CARTA, the major axis convention need to be revised in CARTA.

**Comment by arusstaylor** [comment]
The convention for position angle in astronomy is indeed zero for north.  However if we tie the pa to a direction on the sky the pa of the region in pixels will change for different WCS, so we will not really see the correct behaviour until v1.2.

Russ

**Comment by arusstaylor** [comment]
The convention for position angle in astronomy is indeed zero for north.  However if we tie the pa to a direction on the sky the pa of the region in pixels will change for different WCS, so we will not really see the correct behaviour until v1.2.

Russ

**Comment by veggiesaurus** [comment]
Will adjust the zero of rotation to north for ellipses. Should be an easy fix.
