### ISSUE TITLE
Deprecation warnings related to Sass

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-frontend#1941]
**Describe the bug**
Does anyone else see a lot of deprecation warnings when building the frontend?
For example:

```
Creating an optimized production build...
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($border-radius-adjustment, 2) or calc($border-radius-adjustment / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
61 │         left: $border-radius-adjustment/2;
   │               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    src/layout-base.scss 61:15  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($border-radius-adjustment, 2) or calc($border-radius-adjustment / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div
```
etc.

It occurs with all three versions of Node used by our Jenkins CI:

- Node v12.22.12 (with npm 6.14.16)
- Node  v14.20.0 (with npm 6.14.17)
- Node  v16.16.0 (with npm 8.11.0)

We use 'n' in Jenkins to switch between node versions, so I guess it always installs the latest Node version that is newer than the default Node version from the OS package manager.

**To Reproduce**
1. Install n with `npm install -g n`
2. Select a Node version, e.g. `n 12`
3. Double check you can access it `n exec 12 node -v` (should say v12.22.12)
4. Build carta-frontend as usual making sure you are using the Node version from 'n'
    `n exec 12 npm install`
    `n exec 12 npm run build-docker`
5. Note the deprecation warnings.

**Expected behavior**
There should be no deprecation warnings.

**Platform info (please complete the following information):**
 - OS: Ubuntu 20.04 
 - Browser: Chrome 
 - Browser version: 102
 - Backend branch: dev
 - Frontend branch: dev

**Additional context**
Perhaps one workaround would be to use 'n' to install specific older versions of Node e.g. `n 16.13.1` in order to avoid the deprecation warnings, but the issue may eventually catch up with us, so it might be best to fix it?

**Comment by veggiesaurus** [comment]
This will be fixed by the blueprint 4 upgrade

**Comment by kswang1029** [comment]
ok #1395 it is

**Comment by ajm-ska** [comment]
@veggiesaurus @kswang1029 I'm sorry if this is a dumb question, but what is the current plan/schedule for the blueprint 4 upgrade?

**Comment by veggiesaurus** [comment]
@ajm-asiaa I'd like to aim for the first beta of v4.

**Comment by kswang1029** [comment]
> @ajm-asiaa I'd like to aim for the first beta of v4.

yes. this requires significant amount of time for testing as well.
