### ISSUE TITLE
mirror cursor location on spatially matched images rendered in the multi-panel mode

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1947]
user feedback from v3 beta test

With v3 release, users can read the cursor values from different matched images via the cursor info widget. This is an enhancement to show/highlight the cursor world coordinates on matched images as well so that users can not only read the cursor values from the cursor info widget but also can _see_ what feature is pointed in the image viewer.

**Comment by YuHsuan-Hwang** [comment]
closed via #2002
