### ISSUE TITLE
Having an option to keep or replace generated moment or pv images when a new request is made (frontend)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1951]
user feedback from v3 beta test

With v3 release, when a new request made in the pv generator or moment generator, generated images from the previous request will be removed. Users would like to have an option to keep or replace the pv or moment images. 

The companion backend issue is https://github.com/CARTAvis/carta-backend/issues/1176

**Comment by pford** [comment]
Does PR #2007 for this issue include keep/replace **moment** images?  In the backend, I separated the moment feature in a new issue [#1202](https://github.com/CARTAvis/carta-backend/issues/1202) and opened draft PR [#1203](https://github.com/CARTAvis/carta-backend/pull/1203).

**Comment by pford** [comment]
@crocka was this done for Moment images too?  If not, we need to create a new issue for it.  I opened PR [#1203](https://github.com/CARTAvis/carta-backend/pull/1203 for issue 1202) for the backend part.

**Comment by crocka** [comment]
> @crocka was this done for Moment images too? If not, we need to create a new issue for it. I opened PR [#1203]([CARTAvis/carta-backend#1203](https://github.com/CARTAvis/carta-backend/pull/1203) for issue 1202) for the backend part.

No, it's not done for moment images.
