### ISSUE TITLE
Set a range to the spectral axis to generate a pv image (frontend)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1952]
user feedback from v3 beta test

With v3 release, a PV image is generated using the entire spectral axis along the pv cut. The enhancement is to be able to set a spectral range to generate a pv image. This is helpful to focus on a certain line feature in the cube.

The companion backend feature is https://github.com/CARTAvis/carta-backend/issues/1177

**Comment by pford** [comment]
Added `spectral_range` (channel min and max `IntBounds`) to `PvRequest` message, as in `MomentRequest` message.

carta-protobuf branch `pv_gen_features`
