### ISSUE TITLE
Support loading swapped-axes image cubes (eg RA-Channel-Dec) (frontend)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1953]
user feedback from v3 beta test

This is to support rotated cubes such as RA-Channel-Dec.

The frontend needs to be able to render the coordinate grid properly based on the image header.

The companion backend issue is https://github.com/CARTAvis/carta-backend/issues/1178

**Comment by markccchiang** [comment]
When a swapped-axes (spectral vs. direction) image is loaded, the channel axis labels and unit (conversion from channel to degree) in the animation widget or spectral profile widget need to be changed. I guess it would be better to be done in a separate issue.

**Comment by kswang1029** [comment]
done via #2011
