### ISSUE TITLE
Region dialog should update control points when they are changed

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#197]
How important is it that the control points displayed in the region dialog are updated when users move or scale a region? (similar to how it is displayed in the region list). This is a bit tricky to do, since we want to make sure that the region dialog's control points require the "apply" button to be pressed before any permanent changes to the region are made.

In a related question, how important is it that the control points displayed in the image viewer are updated when the user changes the values in the region dialog (before clicking "Apply")?

@kswang1029 thoughts on this?

**Comment by kswang1029** [comment]
certainly having the content of region dialog seamlessly sync'd with the region in image viewer would provide better UX and allows users to interactively modify a region interchangeably with cursor and text fields. To achieve this, we will need to validate the content before applying the parameters. What casa viewer adopts is that the validation is triggered by 1) users hit return key or 2) the text field is unfocused. If the validation is failed, the text field is reset with the previous (valid) parameter.
![demo](https://user-images.githubusercontent.com/20819712/54965230-a737d700-4faa-11e9-9b59-16c0445fc9dd.gif)

**Comment by veggiesaurus** [comment]
Our initial plan was to prevent region updates until the user explicitly clicked "apply". Perhaps it's easy to just update automatically? That would make the above possible.

**Comment by veggiesaurus** [comment]
fixed in #199
