### ISSUE TITLE
Implement OpenID connect support

### ISSUE THREAD

**Issue by daikema** [CARTAvis/carta-frontend#1999]
Support login through OpenID Connect identity providers.  Note that the bulk of this effort takes place [in the controller package](https://github.com/CARTAvis/carta-controller/issues/128) but some additional effort here is required to support token renewals and manage logout.

Note that [a pull request](https://github.com/CARTAvis/carta-frontend/pull/1861) had previously been opened, but is being reimplemented instead using an approach which puts most of the implementation on the server-side to avoid issues whereby some identity providers didn't support the client configuration needed.

**Comment by kswang1029** [comment]
@daikema would you update this a bit on the status?

**Comment by daikema** [comment]
Had totally forgotten that this issue existed in this repo.  Had restructured the code a bit such that the refresh tokens and access tokens almost matched those using the conventional PAM / LDAP auth modes.  This resulted in extremely minimal changes in https://github.com/CARTAvis/carta-frontend/pull/2016/ that only slightly tweaked how the logout was handled.

In conjunction with https://github.com/CARTAvis/carta-controller/pull/129 OIDC auth code flow login should be functional now when used with dev branch of controller for past few weeks already.
