### ISSUE TITLE
Raster matching on append

### ISSUE THREAD

**Issue by d3v-null** [CARTAvis/carta-frontend#2004]
Hey folks,
Well done on creating such a wonderful UI so far. I'm a huge Carta fan.

In v3.0 Global preferences, it's possible to enable `WCS matching on append`. How feasible would it be to add a similar setting to enable raster matching on append? 

I know it's possible to individually enable raster matching on each image, but this becomes tedious when looking at a large number of images.

If it's not feasible to add such a setting, how might one do this with snippets? I had a look at the examples, but it would be great if someone could point me to a reference for the `app` object.

Thanks.

**Comment by veggiesaurus** [comment]
this should be easy enough to add, I think. Good suggestion!

In terms of a reference for the `app` object, we're working on proper documentation and lots of example for the first v4 beta (end of the year), but in the mean time you can open your browser devtools, go to the javascript console and type `app`. That should give you some autocomplete help, although it's a stopgap for now.

![image](https://user-images.githubusercontent.com/592504/188575879-006e6cbd-a7d5-4565-b276-eaaaa378b221.png)
![image](https://user-images.githubusercontent.com/592504/188576117-6b3b3238-147e-4172-b48c-d666cda6c141.png)


For your specific case, here's one way to solve it:

```javascript
for (const frame of app.frames) {
    app.setRasterScalingMatchingEnabled(frame, true);
}
```
