### ISSUE TITLE
Exporting X/Y profile data gives blank file in CARTA v3.0

### ISSUE THREAD

**Issue by travisthieme** [CARTAvis/carta-frontend#2021]
**Describe the bug**
My apologies if this is not a 'frontend' bug. Wasn't quite sure where to put this. 
Anyway, when trying to export a profile (x/y) in CARTA v3.0, it just exports a blank file. It was working fine in v3.0 beta 3.

**To Reproduce**
1. Open CARTA v3.0
2. Load a 2D fits image
3. Create a line region
4. Select 'export data' in the bottom right of the profiler
5. This results in a blank .tsv file in v3.0, but works as expected in v3.0 beta 3.

**Expected behavior**
I have two .tsv files exported using the previous steps. One exported from CARTA v3.0 beta 3 and one exported from CARTA v3.0. Both filenames are labeled accordingly. I have exported them as pdfs in order to upload here. 

**Screenshots or videos**
N/A

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey 12.6

**Additional context**
This is using the 'stand-alone application' for M1 Mac downloaded from the CARTA homepage. 
Please let me know if I can supply more information!

[profile_v3beta3.pdf](https://github.com/CARTAvis/carta-frontend/files/9671385/profile_v3beta3.pdf)
[profile_v3.pdf](https://github.com/CARTAvis/carta-frontend/files/9671386/profile_v3.pdf)

**Comment by kswang1029** [comment]
@TienHao could you help on this?
