### ISSUE TITLE
Unnecessary notification of the latest release

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#2023]
**Describe the bug**
We get unnecessary notification of the latest release when we compare the current frontend repo version v3.0.1 to the carta repo version v3.0.0. Maybe we need to ignore the patch version difference when we compare (assuming that we always update both repos when we have major/minor/beta updates).

**To Reproduce**
1. Run `app.preferenceStore.clearPreferences(["checkNewRelease", "latestRelease"]);` to reset the settings.
2. Reload frontend.
3. See the notification on the upper-right corner.

**Expected behavior**
No new notification.

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/43841102/193194110-1c4b2718-957f-423b-80d6-af36cbd6ad9d.png)

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 105
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev and v3.0.1

**Comment by veggiesaurus** [comment]
I think we need to actually parse the semver string and only notify if there's an actual upgrade

**Comment by veggiesaurus** [comment]
We can use https://www.npmjs.com/package/semver for this
