### ISSUE TITLE
[GUI UX] variable width of a dropdown menu depending on the context (eg filename)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2044]
we have many dropdown menus in the current GUI. There are two width styles observed: one is to fit the width of the displayed context, and the other is a fixed width and is independent to the displayed context. Example is given below. The "data source" dropdown menu on the left is the former while the image dropdown on the top right is the latter. We would need to unify the behavior of the width of a dropdown menu. In addition, the overflow context is displayed differently as the examples at the top right and the bottom right. 

![Screen Shot 2022-11-17 at 13 35 21](https://user-images.githubusercontent.com/20819712/202364849-55db99a1-c769-49a9-97d5-ae42a6e0ca89.png)

**Comment by YuHsuan-Hwang** [comment]
Three kinds of image dropdown style:
1. fixed width
2. same size with the length of the active filename
3. same size with the max length of all the filenames but within max size of the dialog

<img width="616" alt="image" src="https://user-images.githubusercontent.com/43841102/202373213-d82ca7b1-a1e7-420e-9dc3-7b0eab5b7e3b.png">

We may want to avoid hidden UI in the second style. Personally prefer the third style.
