### ISSUE TITLE
[GUI UX] remove redundant "Close" button

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2045]
Mostly we can use the X button at the top-right corner of a window to close the window. If that's the case, the "Close" button at the bottom-right corner (usually) is redundant and not that needed. We should consider to remove the close button if the X button presents. If there is no X button (eg popup) we would need to keep the close button if it is needed. 

![Screen Shot 2022-11-17 at 13 44 07](https://user-images.githubusercontent.com/20819712/202366248-e4c9761b-5f86-4e60-bb26-f1ad2e09ff1f.png)

**Comment by YuHsuan-Hwang** [comment]
Close buttons in other dialogs:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/43841102/202378287-51578f2e-b7bb-43d4-9a5d-5b1d66f2e431.png">

**Comment by loveluthien** [comment]
More dialogs have a "close" button. Should we remove them as well?
<img width="1226" alt="截圖 2023-10-14 下午3 08 37" src="https://github.com/CARTAvis/carta-frontend/assets/6416595/15b76273-7a64-4949-8682-0dba54d74989">

**Comment by kswang1029** [comment]
> More dialogs have a "close" button. Should we remove them as well? <img alt="截圖 2023-10-14 下午3 08 37" width="1226" src="https://user-images.githubusercontent.com/6416595/275161581-15b76273-7a64-4949-8682-0dba54d74989.png">

Yes, please.
