### ISSUE TITLE
[GUI UX] ambiguous button names in the catalog widget and the spectral line query widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2046]
Improvements for the catalog widget to consider:
1. add the capability to trigger catalog filtering with a return in the filter fields.
2. rename the "Filter" button as "Apply filter" 
3. rename the "Reset" button as "Reset filter"
4. rename the "Close" button as "Close catalog" (this is to avoid confusion as "close widget")

![Screen Shot 2022-11-17 at 13 53 12](https://user-images.githubusercontent.com/20819712/202367473-5456b370-d5eb-4df9-978d-0e9ef9ef7f0e.png)

Improvements for the spectral line query widget to consider:
1. add the capability to trigger catalog filtering with a return in the filter fields.
2. rename the "Filter" button as "Apply filter" 
3. rename the "Reset" button as "Reset filter"
4. rename the "Clear" button as "Clear plot"

![Screen Shot 2022-11-17 at 13 58 28](https://user-images.githubusercontent.com/20819712/202368204-4c40df0a-15c0-4ebd-a35c-6fe0a6f42e66.png)

**Comment by acdo2002** [comment]
This improvement is more make sense to me to understand how to use them!

**Comment by YuHsuan-Hwang** [comment]
would be good to have different colors, for example:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/43841102/202378530-1152598e-7ec0-44db-a81b-0920d53035b1.png">
