### ISSUE TITLE
crash when opening PV generator

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#2052]
**Describe the bug**
Frontend crashes when opening PV generator without any images loaded.

**To Reproduce**
1. Launch Carta
2. Don't load any images and click PV generator

**Expected behavior**
PV generator opened without crash

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/43841102/203274707-15da0548-58ff-4095-92e1-22296a68d311.png)

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 107
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Comment by kswang1029** [comment]
note this exists in dev. v3-stable release is fine.
