### ISSUE TITLE
region list in not rendered properly with missing entries

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2058]
**Describe the bug**
With the default layout, the region list widget is not active. If we create some regions and set the region list widget active, we see the first few entries are not rendered.

**To Reproduce**
1. load an image
2. create four regions (eg polyline, polyline, ellipse, rectangle)
3. select a region in the image viewer
4. set the region list widget active
5. should see the first few entries are not rendered

Note that v3-stable does not have this issue. The problem exists in the dev.

**Expected behavior**
Region list should be rendered properly. 

**Screenshots or videos**
![Screen Shot 2022-11-25 at 09 39 10](https://user-images.githubusercontent.com/20819712/203883787-be824645-7c18-4a69-8cdf-b173ad4fca8b.png)

https://user-images.githubusercontent.com/20819712/203884133-d01fe019-77a1-44aa-9757-729da6a8a268.mov

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 107
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Comment by kswang1029** [comment]
not sure if this is related? https://github.com/CARTAvis/carta-frontend/pull/2008 @I-Chenn

**Comment by kswang1029** [comment]
if we use the default layout and close the two spatial profiler widgets, when we switch to the region list widget, it will be empty with a soft crash with errors in the JS console.

**Comment by I-Chenn** [comment]
> if we use the default layout and close the two spatial profiler widgets, when we switch to the region list widget, it will be empty with a soft crash with errors in the JS console.

@kswang1029 , I try to re-produce the soft crash but fail to get the error you mentioned (please check the video below):
[Screencast from 02-01-2023 12:28:52 PM.webm](https://user-images.githubusercontent.com/106953609/215949128-5db941c7-253c-4d3f-ac4e-e9276a8d94e0.webm)
Did I do it right to your description?

**Comment by kswang1029** [comment]
> > if we use the default layout and close the two spatial profiler widgets, when we switch to the region list widget, it will be empty with a soft crash with errors in the JS console.
> 
> @kswang1029 , I try to re-produce the soft crash but fail to get the error you mentioned (please check the video below): [Screencast from 02-01-2023 12:28:52 PM.webm](https://user-images.githubusercontent.com/106953609/215949128-5db941c7-253c-4d3f-ac4e-e9276a8d94e0.webm) Did I do it right to your description?

hmm not sure how I triggered the soft crash. It might be related to the window size. Please leave it for now.
