### ISSUE TITLE
[region statistics] full image statistics does not restore after a region is removed

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#206]
If I removed my only one region, the stats widget goes back to "image" but the stats values do not update accordingly.

![roi_stat2](https://user-images.githubusercontent.com/20819712/55131329-266b0d80-5159-11e9-91d7-0e26a2f392c2.gif)

**Comment by veggiesaurus** [comment]
@kswang1029 please test with frontend build `2105ab3` (branch `angus/fix_widget_region_selection`)

**Comment by kswang1029** [comment]
Yes, works well now. 👍
