### ISSUE TITLE
Remove blueprint popover warnings in the image view settings

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#2080]
**Describe the bug**
Blueprint shows warnings when opening the image view settings.

**To Reproduce**
1. Open Carta
2. Open image view settings
3. Check the console

**Expected behavior**
No warnings.

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/43841102/211500237-adc36238-509f-4bf1-9ad2-2c6afff1d15c.png)

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 108
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Additional context**

**Comment by kswang1029** [comment]
Fixed via #2081.
