### ISSUE TITLE
UI not responding to cursor clicks

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2085]
**Describe the bug**
For a menu with "hover to expand submenu" feature, if we "click" the menu first then click one option in the submenu, there is a chance that the mouse click is ignored so no corresponding event is triggered.

https://user-images.githubusercontent.com/20819712/211988488-52d8e151-4698-4fca-a030-61425f493b98.mov

**To Reproduce**
1. launch CARTA
2. Click the "View" menu
3. Click the "Layouts" menu instead of hovering on it to see its submenu
4. Click "Save Layout" and we will see the menu is closed without a popup window.

**Expected behavior**
should see a popup window as a corresponding event for the mouse click event to the "Save Layout" option.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: chrome, electron app
 - Browser version [e.g. 22]: 108
 - Backend branch [e.g. dev, v3b2 release]: dev, v3-stable electron app
 - Frontend branch [e.g. dev, v3b2 release]: dev, v3-stable electron app

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 @TienHao I looked into this issue a bit and found that this is fixed in PR https://github.com/CARTAvis/carta-frontend/pull/1975 after we upgrade popover2 > v1.5.0. I think we can simply just link this issue to that PR.

**Comment by kswang1029** [comment]
> @kswang1029 @TienHao I looked into this issue a bit and found that this is fixed in PR #1975 after we upgrade popover2 > v1.5.0. I think we can simply just link this issue to that PR.

Excellent!

**Comment by YuHsuan-Hwang** [comment]
Closed by #1975.
