### ISSUE TITLE
Service menu is displayed in the v3-stable electron app for macOS and in the deb package for ubuntu linux

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2086]
For the v3-stable release, the "Server" menu should be displayed _only_ when CARTA is deployed with the CARTA controller. 

<img width="383" alt="Screen Shot 2023-01-11 at 12 25 20" src="https://user-images.githubusercontent.com/20819712/211717578-b7a428ed-0024-437d-9103-26d4b4970e42.png">

**Comment by I-Chenn** [comment]
This issue is due to an inappropriate logic of revealing the **Restart Service** sub-menu and is then fixed in 321ad04.

**Comment by veggiesaurus** [comment]
@kswang1029 no need to backport this, right? seems harmless

**Comment by kswang1029** [comment]
> @kswang1029 no need to backport this, right? seems harmless

right, it does not bite.

**Comment by kswang1029** [comment]
This can be closed due to the new implementation from #2070
