### ISSUE TITLE
MobX stores need to be refactored

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#209]
the `AppStore` MobX store is getting a bit unwieldy, and should be refactored. Easy candidates are: 

- Creating a `DialogStore` for handling dialog visibility
- Moving some of the longer non-action functions (diffs and calculating requirements) to a separate file

**Comment by veggiesaurus** [comment]
partial refactor in #223

**Comment by veggiesaurus** [comment]
@duidae did we assign this to you? Or was it someone else?

**Comment by duidae** [comment]
no but I can do it 😀
