### ISSUE TITLE
refine the context order in the File menu

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2092]
**Describe the bug**
This is pointed out by @pford.

The current context order in the File menu is not logically sensible. 
![Screen Shot 2023-02-01 at 09 44 19](https://user-images.githubusercontent.com/20819712/215924825-b37d7a7a-7493-4b5d-830a-d81846fcf5b6.png)

We should group the context as the following:

group1:
Open image
Append image
Save image
Close image

group2:
Import regions
Export regions
Import catalog
Export image
 
group3:
Preferences
Server

@pford @confluence @veggiesaurus @YuHsuan-Hwang @ajm-asiaa please see if this new grouping strategy is better.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 109
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Comment by ajm-ska** [comment]
@kswang1029 Why not have "Export image" in Group 1?

Or what about the following? 
Would there be too many horizontal lines?

group1:
Open image
Append image
Save image
Export image
Close image

group2:
Import regions
Export regions

group3:
Import catalog

group4:
Preferences

group5:
Server

**Comment by YuHsuan-Hwang** [comment]
either design looks good to me 👍

**Comment by I-Chenn** [comment]
I have just made a draft-PR #2093 following Kuo-Song's idea, but still open for discuss.
I list both the results of Kuo-Song's and Anthony's ideas below:
@kswang1029's idea:
![image](https://user-images.githubusercontent.com/106953609/215976852-17a5a48e-d273-4383-9299-6cb5a896bf41.png)
@ajm-asiaa's idea:
![image](https://user-images.githubusercontent.com/106953609/215982469-cb3aa3b3-1aee-46e4-88ec-1e1d00066fa9.png)

**Comment by kswang1029** [comment]
> @kswang1029 Why not have "Export image" in Group 1?
> 
> Or what about the following? Would there be too many horizontal lines?
> 
> group1: Open image Append image Save image Export image Close image
> 
> group2: Import regions Export regions
> 
> group3: Import catalog
> 
> group4: Preferences
> 
> group5: Server

my little concern is Save image and Export image are in the same group. It might introduce confusion which does what.

**Comment by pford** [comment]
My thought was to include "Export image" in the "image" section.  I think moving it to another group does not lessen confusion (and adds "why is this down here?").  But if you mouse over it, you see the resolution options which indicate its action.

**Comment by ajm-ska** [comment]
Would it be a good idea to rename "Export image" to something else? 
Although I can not think of anything suitable apart from "Export screenshot" and then I know that might sound like it takes the entire CARTA window and not just the image view part. "Export image view screenshot" might be too long.
What about "Export image view"?

**Comment by YuHsuan-Hwang** [comment]
How about "Export as PNG"? and can be changed to "Export As..." when we support other types in the future.

**Comment by YuHsuan-Hwang** [comment]
The png file includes not only the image but also regions, catalog overlay, ... . Maybe we shouldn't put it with the image actions.

**Comment by kswang1029** [comment]
My grouping strategy is 
Group1 image file related actions 
Group2 actions of import/export non image (cube) files
Group3 misc

for workspace import/export, it will be as the new Group3 and misc shifts to Group4

**Comment by kswang1029** [comment]
“Print image as …” ? This is a bit old fashion though. Or “Convert image as …” or simply “Convert image”?

**Comment by ajm-ska** [comment]
I like the "Print image as ..." idea. 
But what about simplifying it further to just "Print ..."? 
(Particularly if the PNG includes more than just the image).
I feel that would really differentiate it from the other "image" related actions. 
Then for now, the menu could expand to something like "to PNG file: Resolution" with the existing 100%-400% options.

**Comment by kswang1029** [comment]
> How about "Export as PNG"? and can be changed to "Export As..." when we support other types in the future.

Export canvas?

**Comment by pford** [comment]
The tooltip is "Export image"
![Export_image](https://user-images.githubusercontent.com/856604/216456625-e3315019-85b7-4d2e-bc92-31593632d3ef.png)

**Comment by kswang1029** [comment]
> The tooltip is "Export image"
> ![Export_image](https://user-images.githubusercontent.com/856604/216456625-e3315019-85b7-4d2e-bc92-31593632d3ef.png)

The tooltip "Export image" of the button in the image viewer makes sense as it is clear on which will be exported. But in the File menu, it is not that explicit so we might consider to use a more explicit/less ambiguous term there. I think those two terms at the two different places do not have to be identical.
