### ISSUE TITLE
"Copy Session URL to clipboard" modification needed for macOS Electron version

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-frontend#2102]
**Describe the bug**

For the macOS Electron version of CARTA, the `File > Server > Copy Session URL to clipboard` feature will need to be modified. 
At the moment it copies something like this: 
```
file:///Applications/CARTA.app/Contents/Resources/app/index.html?socketUrl=ws://localhost:55051&token=c533b90f-5bf1-4814-b81c-a889a35e79d8/
```

It should instead be:
```
http://localhost:55051?token=c533b90f-5bf1-4814-b81c-a889a35e79d8/
```

I imagine it should be easy to fix. I guess an extra loop can be added to the appropriate section in `src/components/Menu/RootMenuComponent.tsx` to check for the presence of "socketUrl" in the string, and if present it could take the value of socketUrl, as well as substitute "ws" with "http", and "&" with "?" (Replacing "&" with "?" is necessary as the python scripting interface does not seem to be able to parse it "&").

**To Reproduce**
1. Run our CARTA-python-test-17-2-23.dmg macOS Electron version.
2. Click on File > Server > Copy Session URL to clipboard
3. Paste it somewhere.
4. See the extended URL.

**Expected behavior**
For easier python scripting interface use, the URL should be shorter. There should be 3 changes:
1. Only copy the text after socketUrl=
2. Replace "ws" with "http"
3. Replace "&" with "?"

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]:  macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: Electron app  CARTA-python-test-17-2-23.dmg
 - Browser version [e.g. 22]: Electron 23.0.0 (Chrome 108)
 - Backend branch [e.g. dev, v3b2 release]: dev 28152ab
 - Frontend branch [e.g. dev, v3b2 release]: dev 2978e72

**Comment by ajm-ska** [comment]
Maybe I can tackle this issue? I have a working solution now. It can be solved by replacing lines 197 to 209 of `src/components/Menu/RootMenuComponent.tsx` with the following: 
```
serverMenu.push(
  <Menu.Item
    text="Copy session URL to clipboard"
    onClick={async () => {
      try {
        const url = new URL(window.location.href);
        if (!url.searchParams.has("socketUrl")) {
          await navigator.clipboard?.writeText(window.location.href);
        } else {
          const socketUrl = url.searchParams.get("socketUrl");
          const token = url.searchParams.get("token");
          const httpUrl = socketUrl.replace("ws", "http");
          const finalUrl = `${httpUrl}?token=${token}`;
          await navigator.clipboard?.writeText(finalUrl);
        }
        AppToaster.show(SuccessToast("clipboard", "Session URL copied!"));
      } catch (err) {
        console.log(err);
      }
    }}
  />
);

```

**Comment by veggiesaurus** [comment]
> Maybe I can tackle this issue? I have a working solution now. It can be solved by replacing lines 197 to 209 of `src/components/Menu/RootMenuComponent.tsx` with the following:
> 
> ```
> serverMenu.push(
>   <Menu.Item
>     text="Copy session URL to clipboard"
>     onClick={async () => {
>       try {
>         const url = new URL(window.location.href);
>         if (!url.searchParams.has("socketUrl")) {
>           await navigator.clipboard?.writeText(window.location.href);
>         } else {
>           const socketUrl = url.searchParams.get("socketUrl");
>           const token = url.searchParams.get("token");
>           const httpUrl = socketUrl.replace("ws", "http");
>           const finalUrl = `${httpUrl}?token=${token}`;
>           await navigator.clipboard?.writeText(finalUrl);
>         }
>         AppToaster.show(SuccessToast("clipboard", "Session URL copied!"));
>       } catch (err) {
>         console.log(err);
>       }
>     }}
>   />
> );
> ```

can you make a draft PR for this?
