### ISSUE TITLE
navigator.clipboard without secure origin problem

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-frontend#2108]
**Describe the bug**
When testing #2102 in a CARTA AppImage, I found a new issue; The `Copy session ID to clipboard` and `Copy session URL to clipboard` feature does not work.

After investigating I see why. The feature uses `navigator.clipboard` and that apparently "requires a secure origin - either HTTPS or localhost".  However, our CARTA AppImage uses a HTTP IP address and not "localhost". e.g. 

> http://10.211.55.38:3002/?token=e3d039b9-7b85-4207-b815-026121432a4e

Therefore, the `navigator.clipboard` feature does not work. 

If we extract the AppImage and simply run the carta_backend executable, we get a URL with "localhost" and then the copy & paste feature works.

So we could either modify the AppImage to not show the IP and instead show "localhost" (although I wonder if there are other use cases where the user would have an http:// IP address?), or have a fallback method to `navigator.clipboard` such as the older `document.execCommand`.

1. Run an AppImage built from the current 'dev' branch carta-backend and carta-frontend.
2. Click on File > Server > Copy session ID to clipboard.
3. Try to paste it.

**Expected behavior**
The session ID and URL should be able to be copy and pasted.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: Ubuntu 20.04
 - Browser [e.g. chrome, safari, electron app]: Chrome
 - Browser version [e.g. 22]: 110
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Comment by kswang1029** [comment]
additional constraint from safari https://developer.apple.com/forums/thread/691873

**Comment by kswang1029** [comment]
> So we could either modify the AppImage to not show the IP and instead show "localhost" (although I wonder if there are other use cases where the user would have an http:// IP address?), or have a fallback method to `navigator.clipboard` such as the older `document.execCommand`.

we need to show the ip of the server which runs the carta_backend in order to support the "remote" case such as 
1) ssh a_remote_server
2) launch carta with --no_brwoser
3) copy the displayed URL to my local broswer
So we cannot use localhost as it refers to my local computer.

**Comment by kswang1029** [comment]
`navigator.clipboard` requires https which is never the case for the user deployment mode (UDM). So possible solutions (including what @ajm-asiaa pointed out)
1. use `document.execCommand("copy")`
2. instead of supporting the copy function, we simply display session URL and ID as copy-able text in a popup window. The in the File->Server menu, we replace the current implementation with a "Session info" option which leads to the popup window.
@ajm-asiaa @veggiesaurus @confluence @YuHsuan-Hwang any ideas which one is better (need to find a balance in UX and security)?

**Comment by veggiesaurus** [comment]
Does this approach not solve the issue? https://www.electronjs.org/docs/latest/api/clipboard

Oh wait, sorry. This is not for the electron app :see_no_evil:

**Comment by veggiesaurus** [comment]
> 1. use `document.execCommand("copy")`

That should work, I think. The main problem with security seems to be when non-secure sites try to _read_ from the clipboard, rather than write

**Comment by ajm-ska** [comment]
> That should work, I think. The main problem with security seems to be when non-secure sites try to _read_ from the clipboard, rather than write

OK. I almost have `document.execCommand("copy")` method fully working in [this branch](https://github.com/CARTAvis/carta-frontend/tree/ajm/2108_url_copy). I confirm the Session ID part now works in an AppImage. I just made a small logic oversight in the Session URL part that will be easy to fix.
