### ISSUE TITLE
Image not updating when changing channel in the spectral profiler

### ISSUE THREAD

**Issue by crocka** [CARTAvis/carta-frontend#2123]
Images are noticed to stay stagnant while changing channel in the spectral profiler using the red line.

1. Open two images side by side, make sure one of the images has spectral axis.
2. Open spectral profiler and set the image source to, for instance, image one.
3. Click on the other image so that it becomes the activeFrame.
4. Drag the redline in spectral profiler, and notice that the selected image source is not updating.

https://user-images.githubusercontent.com/20819712/226804596-5b0578e4-7364-4bbd-8301-b4e9889d21b4.mov

**Expected behavior**
It is expected to see the selected image source in the spectral profiler to be actively updating while changing channel by dragging the red line.

**Comment by kswang1029** [comment]
fixed in #2100
