### ISSUE TITLE
Updating Node versions in the Github Actions CI

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-frontend#2132]
**Describe the bug**
At present, our carta-frontend Github Actions CI does a format-check, and a production build using Node v12, v14, and v16.

According to information [here](https://endoflife.date/nodejs): 

- Node v12 LTS security support was end-of-life (EOL) on 30 Apr 2022.
- Node v14 LTS security support will soon be EOL on 30 Apr 2023.
- Node v16 LTS security support is scheduled to end on 11 Sep 2023.
- Node v18 LTS will have active support ending on 18 Oct 2023 and security support ending on 30 Apr 2025.

I propose modifying our carta-frontend Github Actions CI to drop the Node v12 and v14 builds, and add a Node v18 build instead. (Also, the format-check stage currently uses node v14, but we could update that to v18). With these modifications the Github Actions CI would then do the following:

- carta-frontend format-check using Node v18 LTS
- carta-frontend production build using Node v16 LTS
- carta-frontend production build using Node v18 LTS

Perhaps Node v20 LTS could be added later, once it becomes available.

With Node v16 and v18, it appears we still need to use the `--legacy-peer-deps` flag.

On the current carta-frontend `dev` branch we need to use the `--openssl-legacy-provider` flag for Node v18, but it looks like that flag is not required with @YuHsuan-Hwang's `yuhsuan/1974_package_update` branch.

@veggiesaurus and @YuHsuan-Hwang What do you think of this proposal?

**Comment by YuHsuan-Hwang** [comment]
I'm ok with the plan. Could we remove `--legacy-peer-deps` flag with the blueprintjs v4 upgrade?

**Comment by ajm-ska** [comment]
I just tried on the `angus/1395_blueprint4` branch. Unfortunately, it currently does not fix the need for the `--legacy-peer-deps` flag:

> root@baf995a20a39:/mount# n exec 16 npm install
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: carta-frontend@3.0.1
> npm ERR! Found: react@17.0.2
> npm ERR! node_modules/react
> npm ERR!   dev react@"^17.0.1" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.0.0-0" from react-split-pane@0.1.92
> npm ERR! node_modules/react-split-pane
> npm ERR!   dev react-split-pane@"^0.1.91" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /root/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2023-03-29T09_49_21_415Z-debug-0.log

Unless it will work once the upgrade is complete? Will it be using the latest React 18.2.0 by the end?

**Comment by YuHsuan-Hwang** [comment]
Maybe we will upgrade React in a separate branch.
