### ISSUE TITLE
Blank screen when using layout with histogram widget

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-frontend#2178]
carta-v4.0-beta won’t let me use the histogram widget unless an image is open. And if I have a histogram widget within my layout, I get a completely blank screen upon launching CARTA, even if I launch with an image being opened (e.g. using `?file=blah.fits` in the URL). If I remove the histogram widget from my layout, it works fine. And similarly, if I first open an image, and then restore my layout with the histogram widget included, it’s happy to do that after an image is opened. None of this is the case with carta-v3.0.1. You should be able to reproduce that, but let me know if you want more info.

**Comment by kswang1029** [comment]
![Screenshot 2023-05-26 at 06 48 25](https://github.com/CARTAvis/carta-frontend/assets/20819712/d05188e8-a3f4-4b66-91a3-aa1e45efc0b9)

**Comment by kswang1029** [comment]
@markccchiang do you have time to have another look?
