### ISSUE TITLE
Large image performance issues when render config histogram visible

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-frontend#2183]
Using the CARTA IDIA server(s), we (@lh-astro, @veggiesaurus and @Jordatious) have been visualising a large (67k x 54k pixel!) image, and have found performance issues, such as waiting 5-10 seconds for a number of operations, including for the image to open, for the render config / transfer function to change, and for the high res tile to load during panning or zooming. If the render config widget is shrunk so that the histogram disappears, those problems go away, which suggests the slowness is from re-rendering the histogram. Interestingly, with the histogram widget open but the render config widget closed/shrunk, there are no performance issues, even when the image is opened and the histogram is rendered.

**Comment by veggiesaurus** [comment]
Note, I'm fairly sure this is related to the _size_ of the histogram array (around 60 000 bins). We're probably doing something that's _O(n)_ rather than the number of visible bins.

**Comment by kswang1029** [comment]
I suggest we set an upper limit of nbin. Rendering that many bins does not help much science at all.

**Comment by veggiesaurus** [comment]
I actually thought we did that already :see_no_evil:

**Comment by kswang1029** [comment]
Nope, it is sqrt(x*y) IIRC.

**Comment by kswang1029** [comment]
@veggiesaurus do the scaling function plus bias and contrast play a role here? That might explain why having histogram widget alone is fine.

**Comment by kswang1029** [comment]
🤔wonder if this belongs to the backend repo?

**Comment by veggiesaurus** [comment]
Yes I think it's the overlay that we use to render the line

**Comment by veggiesaurus** [comment]
@Jordatious turns out this is a duplicate of a very old issue :see_no_evil: https://github.com/CARTAvis/carta-backend/issues/306
