### ISSUE TITLE
Image arithmetic does not seem to work

### ISSUE THREAD

**Issue by lh-astro** [CARTAvis/carta-frontend#2220]
**Describe the bug**
When using image arithmetic similar to `"image1"["image2" > 0.5]"` it does not seem to get applied.

**To Reproduce**
(see .gif below)
1. Open image browser
2. use image arithmetic similar to `"image1"["image2" > 0.5]"` 

**Expected behavior**
I would expect some sort of mask cutout.

**Screenshots or videos**
![default](https://github.com/CARTAvis/carta/assets/55444940/72c08207-c489-4e5e-baa5-8a8f9b495ef4)

**Platform info (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 115

**Additional context**

**Comment by kswang1029** [comment]
Test image attached
[dice_one.fits.zip](https://github.com/CARTAvis/carta-backend/files/12224731/dice_one.fits.zip)

with the LEL like
`"dice_one.fits"["dice_one.fits">2]`
we expect to see the central circular feature survived and all the other pixels are masked. This is doable with the casaviewer but not CARTA.

It appears that it may be a frontend issue actually based on the protobuf message
![Screenshot 2023-08-01 at 12 51 18](https://github.com/CARTAvis/carta-backend/assets/20819712/17438644-961e-403d-9ad5-e0b663d715ed)
the "file" and "hdu" entries are not set correctly.

for example, if we simply load and image by multiplying -1, the message looks like 
![Screenshot 2023-08-01 at 12 53 36](https://github.com/CARTAvis/carta-backend/assets/20819712/fc1002d8-131b-4633-8267-3805ab071b6e)
where "file" contains the full LEL expression.
