### ISSUE TITLE
Scripting feature request: make polarization guessing function accessible

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#2222]
The functions `getStokeType`, `getTypeFromHeader` and `getTypeFromName` are currently private functions in `StokesDialogComponent.tsx`. It would be helpful if these functions were accessible through one of the stores, so that the wrapper could reuse them.

**Comment by veggiesaurus** [comment]
I assume you mean `getStokesType`, right?

**Comment by confluence** [comment]
> I assume you mean `getStokesType`, right?

[It's called what it's called!](https://github.com/CARTAvis/carta-frontend/blob/91262be92d9c2b1ba095acb68460d598e131b141/src/components/Dialogs/StokesDialog/StokesDialogComponent.tsx#L242) Maybe we should rename it at the same time.

**Comment by confluence** [comment]
An additional suggestion for improving this function: in `getTypeFromName`, uppercase the segments of the name before comparing them to polarization names.

**Comment by veggiesaurus** [comment]
> > I assume you mean `getStokesType`, right?
> 
> [It's called what it's called!](https://github.com/CARTAvis/carta-frontend/blob/91262be92d9c2b1ba095acb68460d598e131b141/src/components/Dialogs/StokesDialog/StokesDialogComponent.tsx#L242) Maybe we should rename it at the same time.

Definitely!
