### ISSUE TITLE
Telemetry Enhancement - Adding carta build package information

### ISSUE THREAD

**Issue by crocka** [CARTAvis/carta-frontend#2226]
- [ ] Particularly some way to know if the user is running a carta-controller version, DEB package, RPM, Linux AppImage, or a macOS Electron version. May need some backend implementations?

**Comment by kswang1029** [comment]
this is implemented via https://github.com/CARTAvis/carta-backend/pull/1300 right? @ajm-asiaa

**Comment by ajm-ska** [comment]
@kswang1029 Partially, yes.
