### ISSUE TITLE
Scripting: correctly support setSize for a ruler annotation

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#2246]
This is a minor bug / inconsistency in the region class: the `size` property correctly handles the ruler annotation in the same way as a line or vector, by returning the x and y distances between the endpoints. However, the `setSize` function does *not* include the ruler in the line and vector case (which calculates and sets the endpoints using the center point and the new size), and instead falls back to the default case, which sets the second control point to the values provided (which is not the correct interpretation of the control points for this class).

I don't think that this has any effect in the GUI, since this function is not exposed to the user in the edit dialog for this region class, but a scripting user can access this function on the parent class. I have added a workaround to the wrapper (implementing the correct method for this subclass), but a snippet user could run into the same problem, so it would be a good idea to fix this in the frontend.

Edit: `setCenter` has the same issue, and this class also doesn't store a rotation.

**Comment by confluence** [comment]
I see now that this may be non-trivial because the ruler also doesn't store a rotation -- I am still investigating how to implement this correctly in the wrapper.

**Comment by confluence** [comment]
I have found another inconsistency: the native frontend `setSize`, when called directly on a line or vector region with a width and height, inverts both values (so if you set the size to e.g. (200, 200) and then use `size` to retrieve the size, you get (-200, 200), and vice versa). I assume that this is an artifact of how the line region dialog calls the function (the user doesn't supply these values directly; they're calculated from the length and rotation).

**Comment by YuHsuan-Hwang** [comment]
I agree that the size of regions should always be positive. I think this also causes a bug when setting start/end in the region dialog. To reproduce:
1. Create a line region (start at bottom-left and end at top-right).
2. Set the end x position to be the same as start x position.
3. Fail to update the region.

Expected behavior: The region should be able to modified to vertical and horizontal lines.

**Comment by confluence** [comment]
@YuHsuan-Hwang While I was implementing the ruler code, I noticed that the frontend uses `atan` rather than `atan2` to calculate the line angle, which (at least in the Python implementation) causes a divide by zero error if the start and end Y are equal (which is why I switched to `atan2` in my code). I wondered if this would cause an issue in the frontend implementation, but I was unable to reproduce it at the time -- I was able to edit line regions to be horizontal. Now, however, I see that if I make a line region from (200, 100) to (500, 400) I am unable to make either the X values or the Y values equal when using pixel coordinates (but world coordinates seem fine -- although sometimes the conversion to pixels isn't exact, so I haven't exhaustively tried all options). I see that there's a lot of additional logic in the dialog code which may be affecting this.

**Comment by confluence** [comment]
@YuHsuan-Hwang I have tested the raw size / center / rotation functions with the latest dev, and I can confirm that `setSize` now works correctly for ANNRULER, but rotation is still not implemented, and therefore `setCenter` doesn't do the right thing (because it uses the rotation, which is always zero). I think the issue is that ANNRULER needs to be added to the list of types that triggers the `getLineAngle` calculation (in three places in the region code), and also to `setRotation`.
