### ISSUE TITLE
A blank screen shown when clicking X/Y profile setting button without opening images

### ISSUE THREAD

**Issue by markccchiang** [CARTAvis/carta-frontend#2247]
**Describe the bug**

Not sure has anyone reported this minor bug. When starting the Carta without opening images, if we click the X/Y profile setting button, as shown in the screenshot below, a blank screen will show up. 

**To Reproduce**
1. Start the Carta and do not open any image
2. Click on X or Y profile setting button
3. Result in a blank screen

**Expected behavior**
X or Y profile setting panel should be normally shown like when we have opened images.

**Screenshots or videos**
<img width="1683" alt="carta-frontend-issue" src="https://github.com/CARTAvis/carta-frontend/assets/5379602/145ee9c6-bf6f-41a8-a762-c970a0b07b33">

**Platform info (please complete the following information):**
 - OS: macOS Ventura 
 - Browser: Chrome
 - Browser version: 116.0.5845.179 
 - Backend branch: dev, v4 release
 - Frontend branch: dev, v4 release

**Additional context**
No.

**Comment by kswang1029** [comment]
I guess it is a frontend crash due to null.
