### ISSUE TITLE
UI minor issue in PV generator

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2248]
1. The help button at the top-right corner of the PV preview widget is not functional (my fault not added the component) but I think if possible we can remove it as we do not need it.
2. "Start Preview" button should be "Start preview" for UI consistency elsewhere.

**Comment by HKUICBmain** [comment]
login with forget password

**Comment by HKUICBmain** [comment]
![Authoizaton20240221](https://github.com/user-attachments/assets/953cd7d7-35cd-41eb-b602-380696f4c8d6)
