### ISSUE TITLE
failed to match images spatially

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2252]
**Describe the bug**

In some special cases (probably trying to match images with different coordinate systems, such as FK5 <-> GALACTIC), CARTA refuses to match images. The console log shows

![Screenshot 2023-09-11 at 21 00 57](https://github.com/CARTAvis/carta-frontend/assets/20819712/25c7f9ca-bf8c-429b-ac08-0ab752bd7e77)

Once we start seeing the error, we will not be able to match any images. Sometimes, if we change the active image and redo matching, it may work or may not.

See the steps below to reproduce the issue.

This might be a regression between the v3 and v4 releases. With v3, the issue cannot be reproduced.

**To Reproduce**
1. download the test images at https://drive.google.com/file/d/1ZVJxTFF_K56cTlnB4vXYuAIen-xKr5dy/view?usp=share_link
2. load the folder using filename to sort
3. load all the images _at once_ in the order like below
![Screenshot 2023-09-11 at 20 50 54](https://github.com/CARTAvis/carta-frontend/assets/20819712/c6c2029d-3d78-4c8f-8bb9-d289b093c2e1)

4. the image viewer should stay as 2x2 grid
5. without touching anything else, try to match images in order (or try to match the 8th image directly)
6. until the 8th image we will see matching failure and cannot match any other images anymore
7. try to change the active image and repeat the test, sometimes we can match images but it may fail again

If we preconfigure the grid layout to 4x4, for example, all images can be matched successfully. Maybe this is something to do with AST memory management/leakage or racing condition?

**Expected behavior**
images should match

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura
 - Browser [e.g. chrome, safari, electron app]: electron
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: dev, v4-stable
 - Frontend branch [e.g. dev, v3b2 release]: dev, v4-stable

**Comment by YuHsuan-Hwang** [comment]
A simple way to reproduce:
1. Disable multi-panel mode
2. Load spire250_ext.fits (with default system FK5)
3. Append spire250_ext_GAL.image (with different default system GAL)
4. Spatially match the second image and see failure (expected: no failure)
5. Set the first image as active and see FK5 coordinate (expected: GAL coordinate)

If we enable multi-panel mode, we can successfully match the second image. When the second image is appended, we see the first image is displayed with GAL coordinate.
