### ISSUE TITLE
[UI/UX moment generator] default region to "image" instead of "active" 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2260]
When we try to make a moment map via the moment generator in CARTA, usually we make a region and check its region spectrum to determine the spectral range, and sometimes the intensity threshold, for the calculations. The current UI behavior is setting the region dropdown menu to "Active". This results in masked moment images and usually this is what we do not want. I suggest we set the default region to "Image" instead. If users want to apply a spatial mask, they can select a specific region.

![Screenshot 2023-09-25 at 12 34 40](https://github.com/CARTAvis/carta-frontend/assets/20819712/10fbc34d-4d16-4919-901f-2a208d3ad30c)

**Comment by loveluthien** [comment]
@kswang1029 How about Histogram and Statistic wedgits? In #512, the default of "region" is set to "active".

**Comment by kswang1029** [comment]
@loveluthien we just need a change in moment generator. The reason is usually we use region to get a spectrum to determine a channel range to make moment images, as well as a guide for intensity threshold. However, that does not mean users always want to use the same region as a mask to make moment images. Usually we use full image area to make moment images. If a sub-image is needed, users can set a region manually.
