### ISSUE TITLE
Pre-set layouts and user presets

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#227]
Users should be able to:
- [X] Select a layout from a set of carefully designed presets that suit different analysis tasks. For example, "Image only", "Polarization", "Basic profiles", "Default"
- [X] Adjust the layout to suit their requirements, and then save their custom layout as a new preset
- [X] Remove, rename and overwrite existing presets

Allowing users to design presets and select from sensible defaults will streamline their workflow. Currently, users must rearrange their widgets each time they start CARTA.

user defined layout may include widget details as following: 
- spatial profiler: cooridnate, show mean, line type
- spectral profiler: coordinate, statistic, show mean, line type
- histogram: log scale, line type
- the rest: just the layout itself

implementation & behaviors:
* UI
  * user presets will go as a list under layout -> User layouts -> ...
  * Layouts -> User layouts -> ... and Layouts -> Presets ->
* save layout
  * save a JSON object that has a similar structure to how we currently construct the goldenLayout object
  * layout -> Save layout
  * prompt them to enter a name
* delete layout
  * Layouts -> Save layout and Layouts -> Delete layout
  * Delete Layout should pop up a dialog with a select, allowing you to select which _user_ layout to delete
  * 2 options: Delete and cancel
  * Create (green button) and cancel
  * in the save dialog, if you enter the same name as an existing layout, it should show a warning under the text input saying that you will overwrite the existing layout

"helper text" for that https://blueprintjs.com/docs/#core/components/form-group)
save things under the `dockedWidgets`, and then later on we can add a field `undocketWidgets`

**Comment by kswang1029** [comment]
Complexity:
- when users switch from one preset layout or custom layout which has been displaying some data to another preset layout, widgets need to be activated or de-activated so that the backend will not do unnecessary calculations and just do necessary calculations.  
- window size consistency
- allowing undocked widgets?
