### ISSUE TITLE
User preferences dialogue

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#228]
A number of user preferences need to be configurable and remembered when restarting CARTA. A non-exhaustive list of preferences:
- [X] global: Color theme (“View” -> “Interface” ; default: “Light”)
- [X] global: Layout (default: “Cube view”, see the above section “Predefined layouts”)
- [X] global: Auto-launch file browser when CARTA is initialized (default: “enabled”)
- [X] global: Default cursor behaviour? (frozen, not frozen)
- [X] global: Default image zoom level (“zoom to fit” vs “zoom to 1.0x”)
- [X] Color map in render config widget  (default: “inferno”)
- [X] Color map scaling  (default: “Linear”)
- [X] Default clip level (default: “99.9%”)
- [X] AST Global -> Color (default: “? blue”)
- [X] AST Grid -> Visible (default: “yes”)
- [X] AST Labels -> Visible (default “yes”)
- [X] Default WCS type: Automatic (follows convention based on coordinate system)
- [X] Default WCS type: Degrees
- [X] Default WCS type: Sexigesimal
- [X] region: Region creation mode (“center-to-corner” vs “corner-to-corner”)
- [X] region: Default region color (default: “cyan”)
- [X] region: Default region line width
- [X] region: Default region dash thickness
- [X] region: Default region shape 
- [X] Compression quality (images): values 1 -> 32 [default: 11, tooltip: _compression quality when looking at still images]
- [X] Compression quality (animation): values 1-> 32 [default: 9, tooltip: _compression quality when playing back animations]
- [X] GPU tile cache size: values: 512 -> 8192 in steps of 128 [default: 512, tooltip: _maximum number of image tiles stored in GPU memory]
- [X] System tile cache size: values 1024 -> 16384 in steps of 256 [default: 4096, tooltip: _maximum number of image tiles stored in system memory]
- [ ] How long to wait before requesting a tile (not sure how to phrase this)
- [ ] Progressive loading (default: enabled) [whether or not to show tiles as they arrive, or wait until all arrive before showing]
- [ ] NaN pixel color (when available)
- [ ] NaN pixel transparency (when available)
- [ ] Default region export format (DS9, CRTF)

While not enabling any _new_ science work, it will help with usability and streamline work. Currently, users have to change these values every time CARTA is opened, and in some cases, for each file opened.

**Comment by duidae** [comment]
[ ] Color theme (“View” -> “Interface” ; default: “Light”)
[ ] Color map in render config widget  (default: “inferno”)
[ ] Color map scaling  (default: “Linear”)
[ ] Layout (default: “Cube view”, see the above section “Predefined layouts”)
[ ] Default clip level (default: “99.9%”)
[ ] Auto-launch file browser when CARTA is initialized (default: “enabled”)
[ ] AST Global -> Color (default: “? blue”)
[ ] AST Grid -> Visible (default: “yes”)
[ ] AST Labels -> Visible (default “yes”)
[ ] Default WCS type: Automatic (follows convention based on coordinate system)
[ ] Default WCS type: Degrees
[ ] Default WCS type: Sexigesimal
Region creation mode (“center-to-corner” vs “corner-to-corner”)
NaN pixel color (when available)
NaN pixel transparency (when available)
Default region color (default: “cyan”)
Default region line width
Default region dash thickness
Default region shape
Default cursor behaviour? (frozen, not frozen)
Default image zoom level (“zoom to fit” vs “zoom to 1.0x”)
Compression quality 
Tile cache size (how many MB of tiles to store)
Some other tiling options?
How long to wait before requesting a tile (not sure how to phrase this)
Progressive loading (default: enabled) [whether or not to show tiles as they arrive, or wait until all arrive before showing]

**Comment by duidae** [comment]
@veggiesaurus @kswang1029 
about the region creation mode, what if the preference is ambiguous related to the hotkey? For example, when the preference is set to "corner to corner", and hotkey "ctrl" is also referring to "corner to corner", then there is no way to create region in "center to corner" mode, is that an acceptable behavior?

**Comment by kswang1029** [comment]
what about:
when in "center-to-corner" mode, holding "ctrl" enables "corner-to-corner" mode.
when in "corner-to-corner" mode, holding "ctrl" enables "center-to-corner" mode.

**Comment by veggiesaurus** [comment]
@kswang1029 I agree. The user should always be able to use the alternate mode by holding ctrl

**Comment by duidae** [comment]
@veggiesaurus  @kswang1029 Do u think that adding a "reset to default" button to the dialogue for users to restore settings in each tab to system defaults would be useful? 

![reset](https://user-images.githubusercontent.com/25971696/59747990-bc23be00-92ac-11e9-8a14-8e8b82e5ebf8.png)

**Comment by kswang1029** [comment]
Great idea!

**Comment by duidae** [comment]
yes to the current tab only
