### ISSUE TITLE
A proper word to represent both region and annotation in the export dialog

### ISSUE THREAD

**Issue by loveluthien** [CARTAvis/carta-frontend#2297]
**Describe the bug**

As reported in [here](https://github.com/CARTAvis/carta-frontend/pull/2283#pullrequestreview-1746304763) (see append image), we need to replace word "region" with a proper term that is generic for region and annotation.

**To Reproduce**
1. Create regions and annotations
2. Click "Export all regions" button.
3. See the content in the right panel.

**Expected behavior**
Proper word to represent both region and annotation.

**Screenshots or videos**
![](https://user-images.githubusercontent.com/20819712/285197979-4ccf6781-22fb-4ab8-8761-8a496fca56e5.png)

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura, ubuntu
 - Browser [e.g. chrome, safari, electron app]: 
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: v4-stable, dev
 - Frontend branch [e.g. dev, v3b2 release]: v4-stable, dev

**Comment by YuHsuan-Hwang** [comment]
Looks like we also need to fix the numbers (selected / total). The second number should be larger or equal to the first one.
