### ISSUE TITLE
support uni-color colormap in the render config widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2300]
This is considered as a preparation work for https://github.com/CARTAvis/carta-frontend/issues/1204 

The idea is to add a button linking to a color swatch like we do for the AST overlay color selector
![Screenshot 2023-11-28 at 17 40 59](https://github.com/CARTAvis/carta-frontend/assets/20819712/d83875ec-8ffe-40e2-8cd3-0a9d377a7afd)

Then users would have the freedom to form a unicolor colormap from black to a selected color (eg, cyan).

**Comment by veggiesaurus** [comment]
are we going to adjust the shader or simply append the colormap texture? 🤔 

I'd quite like to adjust the shader, as this will (in future) give us an opening to allow users to create custom colormaps

**Comment by kswang1029** [comment]
> are we going to adjust the shader or simply append the colormap texture? 🤔
> 
> I'd quite like to adjust the shader, as this will (in future) give us an opening to allow users to create custom colormaps

Open to any ideas that have potentials 🙂
