### ISSUE TITLE
save region profile to text

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#232]
The file header should show the correct region type and its properties.

Following is an example of save a profile of a rectangle region.
```
# G14.114-0.574_line1-spw2_2.image.pbcor.fits Z profile
# xLabel: Frequency (GHz)
# yLabel: Value (Jy/beam)
# region (pixel): Point[1761, 3]
# region (world): Point[18:17:31.37, -17:01:34.9]
# x	y

```

**Comment by veggiesaurus** [comment]
@kswang1029 can you give an example of what you'd like it to look like for ellipse and rectangle regions?

**Comment by kswang1029** [comment]
let's try to be consistent with casa region text format:
rotbox[[x, y], [x_width, y_width], rotang] for rectangle
ellipse[[x, y], [bmaj, bmin], pa] for ellipse

sounds reasonable?

=========as a reference from casa cookbook===========
- Rectangular box; the two coordinates are two opposite corners:
box[[x1, y1], [x2, y2]]
- Center box; [x, y] define the center point of the box and [x_width, y_width] the width of the sides:
centerbox[[x, y], [x_width, y_width]]
- Rotated box; [x, y] define the center point of the box; [x_width, y_width] the width of the sides; rotang the rotation angle:
rotbox[[x, y], [x_width, y_width], rotang]
- Polygon; there could be many [x, y] corners; note that the last point will connect with the first point to close the polygon:
poly[[x1, y1], [x2, y2], [x3, y3], ...]
- Circle; center of the circle [x,y], r is the radius:
circle[[x, y], r]
- Annulus; center of the circle is [x, y], [r1, r2] are inner and outer radii:
annulus[[x, y], [r1, r2]]
- Ellipse; center of the ellipse is [x, y]; semi-major and semi-minor axes are [bmaj, bmin]; position angle of the major axis is pa:
ellipse[[x, y], [bmaj, bmin], pa]

**Comment by veggiesaurus** [comment]
can we use just pixel coords for this?

**Comment by kswang1029** [comment]
yes. let's worry about wcs in v1.2+

please also add unit such as 
rotbox [ [ 60pix , 50pix ] , [ 30pix , 30pix ] , 30deg ]
