### ISSUE TITLE
export image: scaling issue on HiDPi screens

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#233]
- Exported image is incorrect when using HiDPi screen
- Regions are missing from exported images

**Comment by veggiesaurus** [comment]
@kswang1029 can you verify this is fixed on mix 'n match? branch `angus/fix_image_export`

**Comment by kswang1029** [comment]
yes it works nicely. 
![SR4_continuum fits-image-2019-4-5-17-44-18](https://user-images.githubusercontent.com/20819712/55619041-80f41180-57ca-11e9-9c67-4eafe8cc76fb.png)
