### ISSUE TITLE
carta-frontend: Make the API endpoint configurable, or prepend the Base URL

### ISSUE THREAD

**Issue by at88mph** [CARTAvis/carta-frontend#2336]
**Describe the bug**
We run the `carta-backend` and `carta-frontend`:
```sh
add-apt-repository ppa:cartavis-team/carta && \
apt update && \
apt install -y carta
```
In the browser, we serve it at some generated session ID: 
`https://example.com/sessions/carta/28938`

Which works for most things, other than accessing the API endpoints (`layout`, `database`).

The `apiAddress` is looked up in the `/config` document:
https://github.com/CARTAvis/carta-frontend/blob/dev/src/index.tsx#L36

This is hard-coded to be an absolute path, if enabled (`/api`):
https://github.com/CARTAvis/carta-backend/blob/dev/src/HttpServer/HttpServer.cc#L111

Which means the current baseURL is ignored and the base `/api` is expected to be routed.  Just making that `api` rather than `/api` would ensure it is kept in the current context, or simply making it configurable if it isn't already.

**To Reproduce**
Steps to reproduce the behaviour:
While running in the browser:
1. Go to 'View' -> 'Layouts' -> 'Save Layout'
2. Enter name
3. Click 'Save'
4. We expect https://example.com/sessions/carta/28938/api/database/layout, but the `PUT` is trying to use https://example.com/api/database/layout

**Expected behaviour**
Keep the API calls in the current context, under the current `baseURL` as declared in:
https://github.com/CARTAvis/carta-frontend/blob/dev/src/index.tsx#L32

**Platform info (please complete the following information):**
 - MacOS Sonoma
 - Browser Safari 17.2.1
 - Browser Google Chrome 120.0.69

**Comment by at88mph** [comment]
Hi there.  I noticed this got placed into GitHub Projects.  Does that mean it will be looked into?  Thanks!

**Comment by kswang1029** [comment]
We are handling this issue via https://github.com/CARTAvis/carta-backend/pull/1338

**Comment by kswang1029** [comment]
done with https://github.com/CARTAvis/carta-backend/pull/1338
