### ISSUE TITLE
parsing ATCA FITS header - no WCS grid rendered

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2357]
**Describe the bug**

With v4.1-stable, some of the ATCA FITS images cannot have WCS grid rendered properly (missing) at the frontend.

The attached image shows the headers as displayed in v3 (left) and v4.1 (right) respectively.
<img width="911" alt="Screenshot 2024-03-07 at 15 39 46" src="https://github.com/CARTAvis/carta-backend/assets/20819712/1e13455f-2aad-4c72-9f4b-e345c64af6a1">

The key difference is CTYPE3
v3
CTYPE3 = VELO-HEL
BUNIT = JY/BEAM
v4.1
CTYPE3 = VELO
BUNIT = Jy/beam

With ds9 we see
CTYPE3  = 'VELO-HEL'
BUNIT   = 'JY/BEAM '

With some other ATCA FITS images, it works just fine (ex https://drive.google.com/file/d/1ynmyPlgEJolb_1D8m5tWNapXIGMwmUHO/view?usp=sharing)

**To Reproduce**
1. download the test image here: https://drive.google.com/file/d/1MrseMvR3j9YVeLk_4bwCmDjvIaPHUtye/view?usp=sharing
2. load it and we will see missing WCS grid.
3. try to generate a moment image but we will see errors in the browser's console.

<img width="423" alt="Screenshot 2024-03-07 at 15 50 40" src="https://github.com/CARTAvis/carta-backend/assets/20819712/792fcc22-6f46-4eaf-91f3-98e7a670977e">

**Expected behavior**
WCS grid should be rendered and moment image can be generated. 

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura
 - Browser [e.g. chrome, safari, electron app]: v4.1 electron app 
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: v4.1, dev
 - Frontend branch [e.g. dev, v3b2 release]: v4.1 dev

**Comment by TienHao** [comment]
I found both ATCA images are inconsistent between the OpenFileAck and the fits files headers in CTYPE3. There might be a change of file info parsing from the backend causing this problem.

For the WCS rendering failed ATCA image([link](https://drive.google.com/file/d/1ynmyPlgEJolb_1D8m5tWNapXIGMwmUHO/view?usp=sharing)):
The headerEntries of OpenFileAck from the backend shows **CTYPE3 = 'VELO'**.
But the header from the fits file shows **CTYPE3 = 'VELO-HEL'**
<img width="751" alt="截圖 2024-05-02 下午2 48 59" src="https://github.com/CARTAvis/carta-frontend/assets/20379662/34d7d973-b73a-4bb5-a1eb-c51e87bd0a35">
<img width="1515" alt="截圖 2024-05-02 下午2 38 03" src="https://github.com/CARTAvis/carta-frontend/assets/20379662/c86f8862-1f64-4ab3-b4a6-a7b28e5b22c1">

For the WCS rendering succeeded one([link](https://drive.google.com/file/d/1MrseMvR3j9YVeLk_4bwCmDjvIaPHUtye/view?usp=sharing)):
The headerEntries of OpenFileAck from the backend shows **CTYPE3 = 'VELO'** just like the failed one.
But the header from the fits file shows **CTYPE3 = 'VELO-LSR'**
<img width="751" alt="截圖 2024-05-02 下午2 58 14" src="https://github.com/CARTAvis/carta-frontend/assets/20379662/e1e3364b-d29f-443a-a3ae-4c5f6cd82a66">
<img width="1267" alt="截圖 2024-05-02 下午3 09 36" src="https://github.com/CARTAvis/carta-frontend/assets/20379662/ff5e8b86-c4ca-4e74-a5db-51b1a79596fa">

I am not sure why it works fine for the second image, but the missing of chars is spotted.

**Comment by kswang1029** [comment]
Refer to https://github.com/CARTAvis/carta-backend/issues/1375 for the issue.
This is going to be fixed via https://github.com/CARTAvis/carta-backend/pull/1376.

**Comment by kswang1029** [comment]
> This is going to be fixed via [CARTAvis/carta-backend#1376](https://github.com/CARTAvis/carta-backend/pull/1376).
