### ISSUE TITLE
[WCS grid] support image coordinate grid in the image viewer

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#2366]
With v4.1 / dev, the WCS list in the image viewer contains the regular world coordinate systems. When we load an image without valid WCS headers, the coordinate grid will be rendered in the image coordinate, which is nice. However, for images with valid WCS headers, there is no way to render the coordinate grid in the image coordinate. It would be helpful if we include this option in the list. Once we have this, handling exceptions in the multi-panel view would be more straightforward.

**Comment by veggiesaurus** [comment]
@kswang1029 eventually we should also look into doing spatial/spectral matching using image coords instead of WCS, for misbehaving images or more generic images during pipeline development

**Comment by kswang1029** [comment]
Yes that's the next step
