### ISSUE TITLE
Support set rest frequency for image moments

### ISSUE THREAD

**Issue by ParfenovS** [CARTAvis/carta-frontend#2374]
Image moments creation does not take into account the custom rest frequency given in image list settings. There should probably be related Issue for the carta-backend that uses casacore CreateMoments function that does not support custom rest frequency as an input parameter.

**Comment by kswang1029** [comment]
implemented in https://github.com/CARTAvis/carta-backend/pull/1387 and https://github.com/CARTAvis/carta-frontend/pull/2404
