### ISSUE TITLE
Editing of regions in WCS coordinates

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#238]
Regions should be editable in WCS as well as pixel coordinates.
An example of this is implemented in DS9: 

![image.png](https://images.zenhubusercontent.com/5c49a9893e05565f72326066/e179325f-4a5c-4697-949d-c9c2532e3880)

**Comment by kswang1029** [comment]
Requirements
- provide flexible wcs coordinate systems (icrs, fk5, fk4, galactic, etc)
- provide flexible coordinate format (hms/dms, deg/deg)
- provide flexible units (milli-arcsec, arcsec, arcmin, degree) for size related parameters (rotation or "angle" in the above screenshot should just be degrees)
- sanity check of the input fields

Complexity of defining a polygon in wcs coordinates. Suppose we provide a list of anchors in counterclockwise order. Once an anchor is modified in the dialog, we need to verify if the new anchor is valid or not (new anchor may create crossing line segments).

**Comment by duidae** [comment]
current approach is:
1. add 1 on 1 wcs points corresponding to control points in Region Store
2. UI loads control points & wcs points for displaying/editing

@veggiesaurus, @kswang1029 mentioned about we may have some other WCS related features, so wonder & wanna confirm that would this approach be compatible with your work?
