### ISSUE TITLE
Support for point regions

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#239]
Region shapes need to be extended to point regions (similar to cursor)
- [x] Create point regions
- [x] Select point regions
- [x] Move point regions

edit: splitting out polygon regions to a separate issue

**Comment by kswang1029** [comment]
Creating/modifying a polygon needs to have a real-time check of validity (no crossing line segments are allowed).

**Comment by veggiesaurus** [comment]
implemented by @zarda :raised_hands:
