### ISSUE TITLE
WCS Group support for widgets

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#240]
Various widgets will need their configuration panels updated, to allow users to select to which frame of a WCS group the widget is linked.

As an example, a spectral profile might be linked to the master (raster) frame of a group, while another spectral profile widget might be linked to a contour overlay

**Comment by kswang1029** [comment]
Related widgets
- animator
- render config widget for multiple images in the wcs group
- spatial profiler
- spectral profiler
- histogram
- statistics
- region list

Proposed new widgets
- image list of wcs group (reorder, set visible/invisible, set reference coordinate system)
- cursor information
