### ISSUE TITLE
improvement of statistics widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#242]
Suggestions from Juergen
- (i) I wonder if the image statistics could give the number of masked pixels, too.  
- (i) stats should have scientific notation, I would argue for 4 significant digits, e.g. 1.3244 x 1e2 Jy/beam 
- (i) stats need units 
- (i) the stats should also show the beam size 
- (b) the numerical value of rms differs. going for only a single pixel, I see the same values for all values (except for sigma which is 0 and sumsq which are both explained), but the rms is numerically different. probably a machine precision issue, will be solved by going for the significant digits as mentioned above

**Comment by veggiesaurus** [comment]
Assigning this a story point of (1), assuming the first suggestion (masked pixels) is handled by its separate issue.

**Comment by arusstaylor** [comment]
The change to display at the values in scientific notation and to add units should be done for v1.1 release.
