### ISSUE TITLE
improvement of region list widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#243]
Suggestions from Juergen
- (i) Maybe change the word ‘rotation’ to ‘PA’  everywhere 
- (b) looks like I can put a really large number in the ‘line width’ but there seems to be an upper limit on the thickness of the region itself. the number should also hit an upper max to make the behavior consistent. similar for the dash length  
- (i) the region list should also have units for the size (pix) and rotation/PA (deg)

**Comment by veggiesaurus** [comment]
does a rotated box also have a "position angle" ? isn't that specific to an ellipse?

**Comment by kswang1029** [comment]
in my mind, PA or rotation is the same and clear. Not sure how much UX we can obtain if we change to PA. Maybe it is better to preserve PA only for beam shape.

**Comment by arusstaylor** [comment]
Rotated rectangle does have a PA. It is the angle of the long axis of the rectangle. This information is needed to reconstruct the rectangle from stored information.

Russ
