### ISSUE TITLE
Wrong XY coordinate if no wcs

### ISSUE THREAD

**Issue by lmytime** [CARTAvis/carta-frontend#2449]
**Describe the bug**
The image panel shows wrong X and Y coordinates.
<img width="989" alt="Snipaste_2024-12-12_15-51-32" src="https://github.com/user-attachments/assets/35fd086b-4c2f-4ad7-a05f-c7909df0df0e" />
It is a simple image with 8 pixels. If I show is using matplotlib:
<img width="677" alt="image" src="https://github.com/user-attachments/assets/939d7fc3-24fa-46b0-a9bc-2dbea9ab5f9d" />
It seems a `X-1, Y-1` somewhere.

**To Reproduce**
1. Mock a simple fits image using python:
```python
import numpy as np
from astropy.io import fits
data = np.array([[1,2,3,4],
                 [5,6,7,8]])
hdu = fits.PrimaryHDU(data)
hdu.writeto('test.fits', overwrite=True)
```
3. Open  `test.fits` using CARTA.
4. Check the numbers of the grid.

**Expected behavior**
It should be something like the matplotlib screenshot above.

**Platform info (please complete the following information):**
 - macOS

**Comment by kswang1029** [comment]
Thanks for reporting the issue. We are working on supporting image coordinate grid (even with a valid WCS) and this issue has been addressed. The fix will be part of the coming v5-beta due late Feb 2025.
