### ISSUE TITLE
Improvements to default layout

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#253]
The default layout needs to be changed in the following way:
- [x] Stats widget removed from layout, as it slows down animations
- [x] Log widget removed from layout, as it's not needed by default
- [x] Default layout for screens with a certain cutoff height (720px?) should group animator and region list in a single tab
- [x] Spectral and histogram widgets should have their region and stokes selectors shown in a row above the graph, rather than in the settings panel

**Comment by kswang1029** [comment]
just an idea, what if we move "region" out from the setting menu for spectral and histogram widgets? (c.f. statistics widget)

**Comment by arusstaylor** [comment]
I agree.  “region” is not really a setting.  It is a functional feature.

Russ

**Comment by veggiesaurus** [comment]
where do we move it to? It would significantly reduce the size of the widget's graph. If we keep the settings panel open by default, users could then still choose to hide it if they want more real estate for their plot

**Comment by arusstaylor** [comment]
Keeping the setting menu open significantly reduces the real estate for the display in the widgets also.  

How about adding a selector tool to the popup tool bar that has the export data and export image symbols.  This could be used to allow the user to select Stokes and Region for the display. 

Russ

**Comment by kswang1029** [comment]
but we will lose the ability to see/know which region/stokes is being displayed.

**Comment by arusstaylor** [comment]
Could we not addt the Stokes to the winder header?  It now just says "Z Profile: Cursor”  when looking at the cursor and changes to "Z Profile: Region #1" when I select region.  Could we add a Stokes being viewed to the header if the image has a Stokes axis?

Russ

**Comment by veggiesaurus** [comment]
@kswang1029 That info is shown in the widget header. 

@arusstaylor My hesitation for showing it with the popover is:
- it would require about 140px per setting, so for WCS group, when we have region, stokes and layer settings, that's 420px. Add another ~ 60 px for the existing buttons, and we're almost at 500 px for the popover, which will look weird and obscure the axis label, and possibly the cursor info
- combining dropdown menus and popovers is an extremely fiddly process. 

On a 1920x1080 screen, this is roughly how much it would use up:
![image](https://user-images.githubusercontent.com/592504/56117808-2f394d00-5f69-11e9-86d5-8e202ee6f0b9.png)

On a 1280x170 screen when using the default widget columns:
![image](https://user-images.githubusercontent.com/592504/56117926-7e7f7d80-5f69-11e9-888d-add5ff933f5e.png)

**Comment by veggiesaurus** [comment]
> Could we not addt the Stokes to the winder header? It now just says "Z Profile: Cursor” when looking at the cursor and changes to "Z Profile: Region #1" when I select region. Could we add a Stokes being viewed to the header if the image has a Stokes axis? Russ

When you explicitly select a Stokes value in the settings, it shows the Stokes coordinate in the label as well:
![image](https://user-images.githubusercontent.com/592504/56118014-ad95ef00-5f69-11e9-9fd7-09fbf1541f62.png)

**Comment by arusstaylor** [comment]
OK.  so that is covered.
Russ

**Comment by arusstaylor** [comment]
So maybe we need an actual tool bar for the z profile widget?  
Russ

**Comment by veggiesaurus** [comment]
@arusstaylor I think we do, and I agree with the desire to move them out of the settings panel. Will implement this and see how it looks.

**Comment by arusstaylor** [comment]
Thanks
Russ

**Comment by arusstaylor** [comment]
I also think that when you change the statistic being displayed the label of the y axis on the display should change to match.  Instead of generic “value” replace with “mean”. or “RMS” or whatever stat i being display.  “Value” is the appropriate label only for  “cursor”. 

And for the Stokes selector, displaying “current” seems like a cop out.  Why not display the actual Stokes being display?  

Russ

**Comment by veggiesaurus** [comment]
> I also think that when you change the statistic being displayed the label of the y axis on the display should change to match. Instead of generic “value” replace with “mean”. or “RMS” or whatever stat i being display. “Value” is the appropriate label only for “cursor”. 

That sounds like a good idea. Could we create a separate issue for that? 

> And for the Stokes selector, displaying “current” seems like a cop out. Why not display the actual Stokes being display?

There's a difference between selecting "current" and explicitly selecting a specific Stokes value. If "current" is selected, the Stokes value changes when you change the Stokes value in the animator. If you explicitly select a Stokes value, then that's fixed, regardless of which Stokes cube you're currently looking at. We could add the current Stokes value to the label as well, so it would look something like 

- Current (Q)
- I
- Q
- U
- V

**Comment by arusstaylor** [comment]
Thanks for explaining “current”.  I agree it is a good thing. I think you should leave it as is.

Will add an issue re the y-axis label.

Russ

**Comment by veggiesaurus** [comment]
I think the suggested approach works nicely. There will be another dropdown for WCS added later. The "Stats" dropdown is automatically hidden when the region is a point type. 

![image](https://user-images.githubusercontent.com/592504/56129479-7c75e880-5f82-11e9-97cc-65b957f1342b.png)

**Comment by arusstaylor** [comment]
This approach does the job.  Another, more compact and perhaps more elegant, option would be just the words  "Region   Stokes   Statistic”  with drop down menus.  This would be in keeping with the style of the main window menu.     Good to have a uniform style for menus.

And does the “region” option disappear if there are no regions defined?, and would the whole thing disappear if there is not Stokes axis, and no region defined?

Think you should just write out “Statistic” instead of “Stats”. 

Russ

**Comment by veggiesaurus** [comment]
I've changed the text to show Statistic.

The issue with having other things disappear when there isn't a Stokes axis or another region is that animating between frames which differ by Stokes axis or by number of regions would lead to the graph being resized and jumping around

We don't use menus in any our widgets, but we do use styled dropdowns, so it would be good to change these to be consistent with the existing dropdowns, as seen in the render config widget. We eventually want to be able to use a multi-select, allowing users to select multiple Stokes or regions on a single widget.

**Comment by arusstaylor** [comment]
Agreed re the disappearing menu. Perhaps just grey out when not applicable?
Agreed that consisted style of drop downs among widgets is essential.

**Comment by veggiesaurus** [comment]
Good idea.

**Comment by veggiesaurus** [comment]
@kswang1029 can you give this a test on mix 'n match (branch `angus/layout_changes`)

**Comment by kswang1029** [comment]
Yes! The default layout looks good and clear. Spectral profiler widget works well too. 
Thanks for all the fruitful discussions @veggiesaurus @arusstaylor 👍

**Comment by veggiesaurus** [comment]
merged into `dev` and backported to `1.1_release`
