### ISSUE TITLE
Contours

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#259]
This epic is for tracking all issues related to displaying image contours as overlays.

**Comment by acdo2002** [comment]
One phenomenon about Contours function would like to be double checked:
When I did the ICD tests, I found that the progress of the received ContourImageData in not always increase. (the progress of RegionHistogramData is always increase) Is this phenomenon expected?
the received progress would be like: (only receiving ContourImageData, no other format data receiving at the same time)
0.13401905025529978 
0.16451332768600282 
0.21641686078172484 
0.1948412712196192 
0.3017727447075934
But it will reach 1 at the end.

I would be very appreciated if anyone can answer it.

**Comment by veggiesaurus** [comment]
@acdo2002 the contour data is generated and delivered in parallel (one thread per level). The progress returned in the contour data is the fraction of the image that has been traversed for the associated level. As such, when generating contours with multiple levels, the progress behaviour is not expected to always increase. With a single level, it should always increase though.

**Comment by kswang1029** [comment]
is it possible that progress = 1.0 has arrived while progress < 1.0 is still steaming?

**Comment by kswang1029** [comment]
from my test, I see progress=1 is streamed multiple times.

**Comment by veggiesaurus** [comment]
@kswang1029 progress=1 just means the associated level is complete. We can estimate the overall progress as an arithmetic or geometric mean of all the levels' progress values. Frontend currently uses arithmetic

**Comment by kswang1029** [comment]
OK, so if we request 5 levels, we should see at the end 5 CONTOUR_IMAGE_DATA messages with progress==1.0.

**Comment by kswang1029** [comment]
> progress=1 just means the associated level is complete. We can estimate the overall progress as an arithmetic or geometric mean of all the levels' progress values. Frontend currently uses arithmetic

Yes, now I see why. Thanks.
