### ISSUE TITLE
animator usability enhancement

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#265]
referencing https://github.com/CARTAvis/carta-backend/issues/367

Missing features
- [x] playback mode: forward (implemented), backward, bouncing, blinking 
- [x] set start and end ranges
- [x] Adjust step for playback
- [x] display channel index as well as the corresponding frequency and velocity.

**Comment by veggiesaurus** [comment]
#330 implements the start and end playback mechanism and adds the underlying support for most of the remaining functionality, which still needs to be exposed in the UI

**Comment by veggiesaurus** [comment]
the first entry in the list should be implemented before 1.3. @kswang1029 who should we assign this to?

**Comment by kswang1029** [comment]
@duidae Could you look into the first item please?

**Comment by duidae** [comment]
ok

**Comment by duidae** [comment]
it's almost done, however the behavior of play backwards seems incorrect, it does not stop when reaching the first frame and does not loop again when reaching the end, using the message with start frame = last frame, delta = -1, wait for Hengtai to confirm

**Comment by duidae** [comment]
![image](https://user-images.githubusercontent.com/25971696/96689355-deec4800-13b4-11eb-9b75-7e5b3b7e5c8e.png)
added step to UI, btw @kswang1029  would you please elaborate the fourth requirement? thanks.
> display channel index as well as the corresponding frequency and velocity

**Comment by kswang1029** [comment]
@duidae I suggest we replace "Req.... Current....." by the reference frame, frequency and velocity, such as the following mockup.

<img width="930" alt="Screen Shot 2020-10-21 at 4 20 03 PM" src="https://user-images.githubusercontent.com/20819712/96693312-ab5fec80-13b9-11eb-8d28-f3ab5ab28f8b.png">

**Comment by duidae** [comment]
@kswang1029 so we dont have to handle #424 since "Req.... Current....." is no longer needed, right?

**Comment by kswang1029** [comment]
Yes. @veggiesaurus could you confirm this in case I miss something?

**Comment by kswang1029** [comment]
@duidae with origin/jason/issue_265 fbf9ec5, if step=5, we see the sequence is 0, "1", 6, 11, 16, 21. And if we stop and start again, it is "22", 27, 32, ... It seems there is always a single channel step then the step as specified with the spinbox. Could you have a look?

**Comment by kswang1029** [comment]
@duidae @veggiesaurus do you think we can combine the UI of frame rate and step with a dropdown followed by a spinbox? This would save space.

![Screen Shot 2020-10-22 at 1 40 01 PM](https://user-images.githubusercontent.com/20819712/96829408-300b4300-146c-11eb-98c8-e4b191edeb49.png)

**Comment by duidae** [comment]
it's still under development, can test it after PR sent

> @duidae with origin/jason/issue_265 [fbf9ec5](https://github.com/CARTAvis/carta-frontend/commit/fbf9ec5345585e790e0bf64dfd451fe617b32564), if step=5, we see the sequence is 0, "1", 6, 11, 16, 21. And if we stop and start again, it is "22", 27, 32, ... It seems there is always a single channel step then the step as specified with the spinbox. Could you have a look?
