### ISSUE TITLE
chart usability enhancement

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#266]
Allowing users to customize the displayed x range and y range by text input.
Charts include
- render config widget
- spatial profiler widget
- spectral profiler widget
- histogram

**Comment by panchyo0** [comment]
@kswang1029 can you provide more details? for example the should we match exactly the max and min number for x and y range according data? should we allow the min text input larger than max text input? what accuracy we should use for user input data? Thanks

**Comment by kswang1029** [comment]
I suggest we add a “custom range” toggle and provide text fields as user input in the setting dialogue. The field should provide basic validations (numbers only) and min has to be smaller than max. We can trim user input as the following:

100000.1234
10000.1234
1000.1234
100.1234
10.1234
1.1234
0.1234
0.01234
0.001234
0.0001234

**Comment by panchyo0** [comment]
closed with PR #611
