### ISSUE TITLE
support image annotation (frontend)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#267]
beside the "region" shapes, the following annotation types need to be supported:
- text
- ascii symbol (e.g., ⭐︎)
- arrow (with/without heads)

Need the capability to import a text file of annotations (e.g., plot "+" at the location of each source from a survey)

**Comment by arusstaylor** [comment]
This is something we have discussed as a collaboration tool.  The idea is to add an annotation file to the hdf5-IDIA data format that would be a property of the image and viewable and editable by a collaborative team.    This is more involved than a simple ability to define regions, and I think annotations should be handled separately from regions.   Regions are an analytic tool. Annotations are for collaboration or for creating pictures for publication or presentation.
