### ISSUE TITLE
enhancement: overlaying molecular transitions in spectral profiler

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#269]
This requires molecular line database (JPL, CDMS, etc). 
Need a text field for velocity or red-shift correction.

**Comment by arusstaylor** [comment]
would one need to enter the redshift of the object for this to produce sensible results?

**Comment by kswang1029** [comment]
yes, there should be a text field for velocity or red-shift.

I do have another idea similar to this: we actually can produce synthetic spectrum for over plotting.

**Comment by arusstaylor** [comment]
Or perhaps if there is a template of line positions one could click and drag it to fit the positions of spectral lines and the redshift would result

**Comment by kswang1029** [comment]
yes, that works too. Will have detailed plan once we are up to this.

**Comment by duidae** [comment]
#863

**Comment by Kechil** [comment]
Same as #650 so closing
