### ISSUE TITLE
click on region in list centres region in image

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#273]
I think it would be good if when one selects a region with the mouse  in the region list the image recentres to display that region.  Sometimes I have panned the image so the region is longer shown in the image.  Being able to click on the list to relocate the image to the region would be nice.

**Comment by veggiesaurus** [comment]
this is the sort of thing that would definitely require a user preference dialog, as it would annoy some users.

**Comment by veggiesaurus** [comment]
@arusstaylor maybe double clicking?

**Comment by arusstaylor** [comment]
yes, double clicking is probably better.  Demonstrates real intention....
