### ISSUE TITLE
api-key enhancement: ignore extra spaces

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#296]
One user feedback is if by copy-and-paste there are extra spaces in the copied api-key, then authentication does not work (well it actually works since the registered api key is wrong).

To improve this UX, can we ignore any extra spaces in the end?
For example: if users copied-and-paste "1234 " to the text entry, the frontend actually sends "1234" to the backend.

**Comment by veggiesaurus** [comment]
easy fix for 1.1 (one liner)
