### ISSUE TITLE
pan image to a user-input coordinate

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#305]
a suggestion from v1.1 beta tester (optical astronomer working with single channel large image):
One should be able to ‘pivot’ to a position of interest through an input coordinate box (in WCS and/or pixel format).

**Comment by Kechil** [comment]
needs assistance from science team

**Comment by kswang1029** [comment]
close this and refer to https://github.com/CARTAvis/carta-frontend/issues/1176
