### ISSUE TITLE
cursor info:  toggle WCS info between sexagesimal and decimal?

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#306]
suggestion from v1.1 beta tester
One should be able to toggle WCS info between sexagesimal and decimal! I personally think WCS Info should be expressed in decimal coordinates by default, but I realize I may not be in the majority here. it might be worth polling a group of users and see what they’d rather have.

**Comment by veggiesaurus** [comment]
Something for the user preferences dialog in 1.2?

**Comment by kswang1029** [comment]
maybe in the "overlay settings" dialog? Currently we use decimal for galactic coordinate and sexagesimal for equatorial coordinates.

**Comment by veggiesaurus** [comment]
we actually have that hidden in the overlay settings already. But if we are going to use it across more than just the overlay (cursor info, profile plots, etc), it should probably be in user preferences. Something simple like:

WCS info:
- Automatic (what we currently use, and what appears to be the standard)
- Decimal
- Sexagesimal

**Comment by kswang1029** [comment]
I see. that would work too

**Comment by arusstaylor** [comment]
This preference is definitely something that will vary between users.  In my experience people like sexadecimal for coordinates displays but decimal for calculations and data entry.

**Comment by kswang1029** [comment]
I think this is implemented now. Shall we close this?

**Comment by veggiesaurus** [comment]
@kswang1029 can you re-test this and confirm that it behaves as expected?

**Comment by kswang1029** [comment]
@veggiesaurus @arusstaylor 
Currently, if we change coordinate system via the overlay dialog, the format of the wcs coordinate will change _dynamically_ with respect to the selected coordinate system. It will be effective once the cursor updates position. For ICRS, FK5, and FK4, the format is sexagesimal. For galactic and ecliptic, the format is decimal. If users want to just see a certain format in the cursor info bar (for example, sexagesimal) regardless the coordinate system, users can configure it via the preference dialog. However, a reload is needed to make the change effective. @arusstaylor are you okay with this?

**Comment by Kechil** [comment]
needs Russ to sign off on it.
