### ISSUE TITLE
migrate create-react-app-typescript to Create React App

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#321]
ref: https://vincenttunru.com/migrate-create-react-app-typescript-to-create-react-app/

**Comment by duidae** [comment]
working notes:
Create React App does not support Webpack loaders, so need to solve importing glsl problem

**Comment by veggiesaurus** [comment]
you can use the cra rewiring package to solve this, and other MobX decorator issues by overriding the default webpack config. 

https://github.com/arackaf/customize-cra

**Comment by duidae** [comment]
![out ogv](https://user-images.githubusercontent.com/25971696/57353447-18b69800-719b-11e9-8d0f-135d2ec3f8df.gif)

seems still have some problems with decorators

**Comment by veggiesaurus** [comment]
For another project, I ended up using:

```
module.exports = {
    webpack: override(
        addDecoratorsLegacy(),
        disableEsLint()
    )
};
``` 

and it seemed to work fine with decorators

**Comment by duidae** [comment]
@veggiesaurus thanks for the tip, after investigating, the decorator problem is from blueprint's  '@HotkeysTarget'

I tried with a wrapper in a simple example App and works, so may need to move out the renderHotkeys like below:
https://github.com/palantir/blueprint/issues/2972

**Comment by veggiesaurus** [comment]
Perhaps we could look into `react-hotkeys` instead? It would be nice to have more control over the hotkeys functionality and the dialog rendering.

**Comment by duidae** [comment]
hmm will try
