### ISSUE TITLE
initial scrolled location of the file list in file browser

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#323]
To reproduce the issue with the demo server:
1) scroll down to find set_QA_performance folder (should be at ~50% of the list)
2) click set_QA_performance
3) now the file list is blank. we will need to scroll up to top to see a short list and we can scroll down to have the short list be totally out of the view. 

suggested: always start at the top when navigating to a new folder.

**Comment by veggiesaurus** [comment]
@kswang1029 can you check if this is still an issue with the current implementation (as of PR #981) ? I attempted to fix it :thinking:

**Comment by kswang1029** [comment]
this is fixed
