### ISSUE TITLE
wcs coordinates in region dialog

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#335]
This issue exist in the v1.1 release (my bad, not able to catch this before the release.....)

When a region is defined and we bring up the region dialog, the wcs coordinates are fine. 
![Screen Shot 2019-05-23 at 9 21 05 AM](https://user-images.githubusercontent.com/20819712/58219201-8edf0100-7d3c-11e9-8cc6-ccaad70b43bb.png)

However, if we move the region, then wcs coordinates are incorrectly transformed accordingly. 
![Screen Shot 2019-05-23 at 9 21 20 AM](https://user-images.githubusercontent.com/20819712/58219212-969ea580-7d3c-11e9-9ca9-18765ea73d31.png)

**Comment by kswang1029** [comment]
@zarda @veggiesaurus I track down this issue a bit and found that this issue is related to the current zoom level of the image. In the above example, once we see the wcs strings are broken, then if we zoom further out and move the region a bit, the wcs strings are back to normal and it seems to be normal forever.

**Comment by zarda** [comment]
This issue will not happen whenever closing spatial profile. Looking into the reason.

**Comment by kswang1029** [comment]
This is an interesting finding. 👍  Confirmed. If there is no spatial profiler widget, the world coordinates are computed correctly. 

In the spatial profiler widget, the top axis displays the world coordinates. Maybe there is an unexpected connection here.

**Comment by veggiesaurus** [comment]
I suspect what's happening is that the format is being set in the spatial profiler, and not being properly un-set.

**Comment by zarda** [comment]
Fixed on [branch](https://github.com/CARTAvis/carta-frontend/tree/hj/%23335) but have no idea of detailed ast command words. It will need any changes if there would be side effect.
