### ISSUE TITLE
when I left click inside a region it selects the region instead of centring the image

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#337]
Apparently this is the expected behaviour but I think it is not the desired behaviour.  Some region are quit large and I expect to be able to centre the image on a feature with left click.  And it is not intuit to click on a feature in a large region and have the region be selected. I think preferred behaviour is for the region to be selected by click on the region delimiter, ie. on the line or the toggle tools that define the region.  This is more intuitive and captures better the intent of the user I think. It is also the behaviour of ds9.

**Comment by veggiesaurus** [comment]
DS9 uses a click anywhere inside the region to select a region. By default, it is in "none" mode, in which you can't select any regions, and uses middle-click to pan. When in "region" mode, you can click anywhere inside a region to select it.

**Comment by arusstaylor** [comment]
oh. Didn't realize.  Funny, I always seem to have bit to trouble selecting the region trying to hit the line. 
Russ

**Comment by veggiesaurus** [comment]
my personal preference would be to use "click and drag" to pan around the image, but use "ctrl/cmd + click" or middle click to center an image on a particular point. 

These sort of choices could go into the user preferences dialog, to allow the user to choose their prefered behaviour.

**Comment by arusstaylor** [comment]
Yes, since there are various preferences on this I think it is good to let the user select this behaviour.

Russ
