### ISSUE TITLE
z profile statistics display should invalidate while waiting for new data. 

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#338]
I am looking at some output stokes cubes from MeerKAT.  Only 100 channels.  Takes about 10 seconds to update the display of stdDev even in a fairly small region.    When I move the region, the profile display show data for the old position until the new data arrives. For wait times of 10 seconds unless the user pays very close attention it is not clear if the profile is the new one or old one until it updates.  Better behaviour would be for the display to go empty or otherwise indicate that the profile is not valid until the new data arrives.

**Comment by kswang1029** [comment]
with partial update of region/cursor spectral profile, I think this issue is fixed.

**Comment by Kechil** [comment]
Need to check with Russ
