### ISSUE TITLE
animation smoothness

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#339]
not sure if this belongs to frontend or backend, but I will just describe the issue here.

using the dev branch as of May 30, 2019 with supermosaic.10.fits at 15 fps, the animation seems to be played batch by batch, so the desired fps is not uniform.
![animator](https://user-images.githubusercontent.com/20819712/58611596-41393a00-82e2-11e9-8177-fd7318d2a0f2.gif)

in addition, the backend may crash by playing / stopping (cannot find a reproducible procedure so far).

**Comment by kswang1029** [comment]
after clean up browser cache, the symptom is gone. close this issue for now.

**Comment by arusstaylor** [comment]
Does this mean users will have to do regular browser cache purges to maintain performance of CARTA?

**Comment by kswang1029** [comment]
Possibly. I did not clean up cache recently but there are some significant changes of the codebase. 

For general users, they would need to clean up cache for every release (so every few months). For developers and testers (like me), it is best to do daily to make sure cache does not affect tests.

**Comment by arusstaylor** [comment]
Interesting.  I guess this means we should let users know they should clear cache with release notes.

**Comment by kswang1029** [comment]
Yes, I will keep this in mind. And maybe we can look for a way to invalidate cache automatically if there is such.

**Comment by veggiesaurus** [comment]
@arusstaylor one of the the recent changes I've made to the frontend is removing the service worker, which is designed to cache things. This should help with the situation. It's also up to the server itself to make sure that requests don't get cached (out of the scope of CARTA and more about server deployment)
