### ISSUE TITLE
unify color selection widget

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#341]
so far we have 2 kinds of color selectors, better to unify them to the advanced one

![color](https://user-images.githubusercontent.com/25971696/58624163-34c4d980-8302-11e9-9c41-28a00748b764.png)

**Comment by veggiesaurus** [comment]
The reason I’d suggest using the one on the right is that different color maps may fit with different overlay / region color schemes. If users have a particular preference in theirs of color map, they may want to pick a custom color to fit with their choice of color map

**Comment by duidae** [comment]
yes will upgrade all to the advanced selector

**Comment by veggiesaurus** [comment]
@TienHao we will need to adjust the AST wrapper a bit to make it compatible with this approach (currently it has a fixed set of colours)
