### ISSUE TITLE
Delay rendering until all tiles are available when changing channels

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#348]
When switching channels, the image is rendered once the first tile arrives, rather than waiting for all required tiles. This makes comparing changes between channels difficult, as most of the image is not visible, as shown in the animation below. 

![tile_change_channel](https://user-images.githubusercontent.com/592504/60331228-7940a500-9994-11e9-8159-41b8506cdadc.gif)

Delaying rendering until all new tiles are available (as well as the channel histogram) would solve this issue. However, this would also mean that there is a much longer delay between changing channels and getting visual feedback (similar to the delay in 1.1), so this might have to be made user-configurable in future.

When zooming and panning, the image should still be rendered as soon as tiles are available. rather than waiting for all tiles to be fetched.

**Comment by veggiesaurus** [comment]
@arusstaylor does this describe the issue correctly?

**Comment by kswang1029** [comment]
@arusstaylor if keep the old tile displayed until the new tile at the same location is ready, would it solve your concern? You can imagine that for each tile, it will behave just like the old (current) way of switching to different channels.

**Comment by veggiesaurus** [comment]
it's tricky to imagine how that would look without implementing it, I guess. Some pros and cons:
+ Would prevent the annoying flashing between channels
+ Would still give users much faster feedback than waiting for the entire image when the network connection is poor
- During the transition, it might look quite weird, and it might not be clear as to which tiles have arrived and which are old
- Not clear which histogram/clip bounds should be used to render the old tiles. Should they use the new render config, or the old? (Leads to some complexity)

**Comment by veggiesaurus** [comment]
Some progress has been made on this issue: Rendering is now performed only once all tiles are received. On a slow connection, this means a much longer wait between channels, but at least there is no missing data when it appears:

![tile_change_channel_progress_fixed_scale](https://user-images.githubusercontent.com/592504/60370371-bfc6eb80-99f6-11e9-8bea-f4c44f98eb1b.gif)

However, there's still a remaining issue, that the _histogram_ is delivered first and is updated straight away. If fixed clipping bounds aren't used, it means that the existing tiles are rendered with the _new_ histogram bounds as soon as the histogram is updated, and then the new tiles are rendered with the new histogram bounds once all tiles are received. It's not really noticeable when switching between adjacent channels, but very noticeable when switching between channels with very different histograms. See below for a particularly bad example of this:

![tile_change_channel_progress](https://user-images.githubusercontent.com/592504/60370548-319f3500-99f7-11e9-9f2a-e1683dacdb57.gif)

This should also be reasonably easy to fix, but I will also have to make sure it works when switching between Stokes cubes.

**Comment by veggiesaurus** [comment]
closing issue for now, as it is mostly fixed. There are some issues with switching between Stokes cubes, but these can be handled separately.
