### ISSUE TITLE
Stokes QUV and PI should be viewable as fractional amounts

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#359]
A new switch should be added to the spectral profile component, which allows users to toggle fractional polarization on or off. The switch should be placed here:

![image](https://user-images.githubusercontent.com/592504/60709394-9505f700-9f10-11e9-9abc-22c5073d494c.png)

When the switch is off, Q, U, V and PI behave as normal. When the switch is _on_, they are scaled relative to Stokes I, (i.e `PI (%) = PI / I * 100 = sqrt(QQ + UU)/I * 100`). This means that the spectral requirements will need to include Stokes I when this switch is on. 

@arusstaylor as suggested "Fractional pol." as a label. If this is too long, we can try reword it ("Pol %"? "Frac. Pol."? )

When viewing with fractional polarization on, the y-axis label should change accordingly.

**Comment by arusstaylor** [comment]
Also the plots of Q and U vs frequency become Q/I and U/I versus frequency, and the Q,U scatter plot becomes a Q/I,U/I scatter plot.

**Comment by arusstaylor** [comment]
Note that PI is short for polarised intensity, which is not the appropriate label when in fractional mode. One could either to just use the generic 'P', for polarisation in all cases with  unit change from JY/beam in intensity mode to unitless or percent in fractional pol mode depending whether you display as fraction or percent. I guess the benefit of expressing in percentage is that you can explicitly put the (%) in the units so it is clear what is being displayed.

**Comment by veggiesaurus** [comment]
@arusstaylor could we use _Q/I (%)_, _U/I (%)_, _P/I (%)_ as axis labels? Would that be clear enough?

**Comment by arusstaylor** [comment]
Yes, that would work well.

**Comment by panchyo0** [comment]
added switch button for Q/I, U/I, V/I and PI/I on branch "qi/stokes_plot". Please check.
