### ISSUE TITLE
displaying current tiles when zooming out until new tiles coming in

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#363]
dev branch as of July 9, 2019:
Currently tiles are reused for display when zooming in until new tiles are ready. The same behavior should be applied to zooming out to avoid flashing. 

![tileZoomOut](https://user-images.githubusercontent.com/20819712/60864084-20ef8a00-a255-11e9-98a6-f4172e86941b.gif)

**Comment by veggiesaurus** [comment]
@kswang1029 I wrote a long comment justifying why I thought limiting the number of higher-resolution tiles to 3 layers, but GitHub seems to have lost it. Long story short (you can see the performance measurements [here](https://docs.google.com/spreadsheets/d/16TBkemxQU3ov2lheb4snJFOMR_1dA6eANSHl33600Y4/)), it's a divergent geometric series, so we need to limit it somewhere. 

Can you test the branch `angus/show_highres_tiles` please?

**Comment by kswang1029** [comment]
Will do!

**Comment by kswang1029** [comment]
tested with images with various sizes (10~50000), now zooming out is very smooth and there is no flash anymore. With network limiter, I can see higher-resolution tiles being update with proper-resolution tiles. 👍👍👍
