### ISSUE TITLE
[cursor info bar] WCS coordinates  not updating along with cursor movements

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#364]
dev branches frontend and backend as of July 9, 2019

The WCS coordinates are not updating along with cursor movement. 
![wcsCoord](https://user-images.githubusercontent.com/20819712/60865500-be988880-a258-11e9-861e-f23d125d34df.gif)

Master-master branches work properly.

**Comment by veggiesaurus** [comment]
wondering if this regression is due to updating the AST library. I'll have a look

**Comment by veggiesaurus** [comment]
@kswang1029 the commit that updated the AST library was `8ba02dd0af404800468b0e5d57def2e3f28e1180`. Can you see if this issue occurs prior to that?
