### ISSUE TITLE
spatial profiles should be decimated client-side to prevent plotting library performance issues

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#366]
Note: This is a pre-cursor to the profile delivery optimisation feature. Currently, the plotting library takes a considerable amount of time to update large (10K) profiles. We should decimate spatial profiles before plotting them, and update the decimation as the user zooms in on the graph.

Once profile delivery optimisation is implemented, this feature will be deprecated. However, implementing this on the frontend is initially much simpler, and will allow us to investigate performance issues with large images more readily.

**Comment by veggiesaurus** [comment]
Some progress has been made on this issue. When decimating on the frontend, I take the original data and the number of pixels in the graph widget (for now, just using the entire widget width, this can be improved since the graph has some padding), and then use that to determine how many min/max pairs are required (approximately one pair for each pixel in the graph), and then decimate the graph accordingly.

The results are great in terms of scalability. Measuring a large file (10K) and a very large file (48K), using just the x profiler with a width of 740px (the default width), the following results were obtained:

Time taken to process spatial updates, as measured by `onStreamedSpatialProfileData` function:

LMCq (10k x 10k):
dev: 65 +- 10 ms
opt: 15 +- 2 ms

ultravista (48k x 48k): 
dev: 280 +- 20 ms
opt: 16 +- 2 ms

@kswang1029 I'd like to get these improvements in before v1.2, can you see if the graphs look ok using branch `angus/profile_optimisation` using mix 'n match? They should update their decimation factor on the fly as you zoom in :sunglasses: (I noticed some crashes, so it's not quite ready for merging yet)

**Comment by arusstaylor** [comment]
These are impressive performance improvements and keeps us close to our 10 updates per second which seems the golden rate for a pleasing interactive experience.

**Comment by veggiesaurus** [comment]
yes, hopefully if we have a few graphs, we'll still be able to reach 10 fps. This is currently only implemented for spatial profiles, but the same can be done for spectral profiles too, which will be more important for ALMA data and its vast number of channels

**Comment by arusstaylor** [comment]
and 32k mode spectral imaging coming soon with MeerKAT 32,000 channels.....

**Comment by veggiesaurus** [comment]
Only very minor differences are visible when applying the decimation (this one a factor of 4x):
![compare_plot](https://user-images.githubusercontent.com/592504/61075137-a6bc3280-a419-11e9-98a6-3c03fa4b971e.gif)
Similarly small differences when using retina screens:
![compare_plot_retina](https://user-images.githubusercontent.com/592504/61075238-d1a68680-a419-11e9-96a9-2e1afb527261.gif)

**Comment by veggiesaurus** [comment]
Spatial profiles done in PR #379, spectral profiles to follow.
