### ISSUE TITLE
pixel boundary at very high zoom level (minor issue/question)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#373]
with dev(tiled)+dev AND master(non-tiled)+master as of July 15, 2019

Unexpected pixel corner is seen when the zoom level is very high (appears to happen near the image center only).
![pixelHighZoom](https://user-images.githubusercontent.com/20819712/61192643-8aa1e500-a6e8-11e9-9615-55f9fa7b65b5.gif)

Question: it only happens at very high zoom level (the level that is not an usual use case), do we really need to fix this?

**Comment by veggiesaurus** [comment]
This looks like a floating point precision issue in the GPU pixel shader. It’s probably fixable reasonably easily, but personally I’m not sure it should be anything other than low priority. How on earth did you spot that?

**Comment by kswang1029** [comment]
"Curiosity Killed the Cat."

yes (very) low-priority it is. :)
