### ISSUE TITLE
Visual indicators for partial spectral profiles

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#382]
Partial spectral profiles are now being sent to the frontend. However, when displaying these plots, we should have visual indicators so that the user is aware that the plots are "in progress".

- [ ] Display partial plots using semi-transparent or desaturated colors
- [ ] Display subtle progress indicator to show what percentage of the profile has been calculated and delivered

**Comment by kswang1029** [comment]
For item 1 and hdf5 cubes, how about we use the progress as the transparency of the entire profile? So when the profile is being updated, we will see it becoming more saturated in color.

**Comment by veggiesaurus** [comment]
I think that could work, but we should have a min and max cutoff, so that (a) the graph is still visible even if only 10% complete and (b) there's a clear difference between 90% and finished (otherwise the transition might be too subtle. 

I'd suggest we use `alpha = 0.25 + progress / 2.0`, when `progress < 1.0`, which gives us a rage between 0.25 and 0.75 for partial profiles.
