### ISSUE TITLE
regression: toolbar drag sources are broken

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#384]
The toolbar's drag sources seem to have been broken by a recent commit or package upgrade. This means that new widgets can no longer be docked, but must first be created as floating widgets, and then docked.

**Comment by veggiesaurus** [comment]
@duidae can you look into this? It occured when you changed how the theme is applied. Currently, the drag sources are broken until you toggle the theme, after which they work properly. It's likely a very minor fix, such as automatically applying themes on startup.

**Comment by duidae** [comment]
@veggiesaurus  ok
