### ISSUE TITLE
[animator] the first frame of an animation needs to be within the playback range

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#389]
with dev July 19, 2019

if a range of channels is defined (e.g., 130~150) and the current channel is < 130 (e.g. 112), the animation will start at the current channel, not start from channel 130.

It works as expected if the current channel is between 130 and 150, or the current channel is > 150.

see demo
![animatorRange](https://user-images.githubusercontent.com/20819712/61506662-6b22f900-aa15-11e9-8814-bb6fa0dfb35e.gif)

**Comment by veggiesaurus** [comment]
@kswang1029 can you confirm that this is fixed in `angus/fix_animator_start_frame`?

**Comment by kswang1029** [comment]
some issues (tested with set_numberCube/cube_x4200_z15_999MB.fits):
now if range=[4, 7] and current=10, at 1fps, I see "11" then "4" then "5"...
and before "11", there might be an other channel being shown.

**Comment by veggiesaurus** [comment]
ah, ok. I see why this is happening, I'll sort it out today
