### ISSUE TITLE
Tile caches need to handle changing frames

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#396]
Currently, there are some issues with tiled rendering not working properly when switching between frames. Each image should have its own "L2" compressed cache, and use the shared "L1" GPU cache. When switching frames, the L1 cache should be cleared, forcing decompression of tiles from L2. This doesn't seem to be happening at the moment. Instead, both frames seem to be rendering the same tiles on the GPU.

**Comment by veggiesaurus** [comment]
@kswang1029 can you check if the behaviour you noticed before (when appending files and changing between frames) is fixed in `angus/tile_l2_cache_changes`?

**Comment by kswang1029** [comment]
@veggiesaurus now it is working perfectly!
