### ISSUE TITLE
dropdown indicator is not visible in "light" theme

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#405]
The dropdown indicator that is used when there are too many tabs in a stack is not visible in the light theme:

![image](https://user-images.githubusercontent.com/592504/61776401-3c34ca80-adfb-11e9-92e5-539a99807b6e.png)

In dark theme, it's visible, although not very noticeable: 
![image](https://user-images.githubusercontent.com/592504/61776434-49ea5000-adfb-11e9-9a50-d37aea8efedc.png)

`.lm_header .lm_controls .lm_tabdropdown:before` needs to be edited in the Golden Layout theme CSS

**Comment by kswang1029** [comment]
<img width="82" alt="Screen Shot 2019-12-03 at 22 06 04" src="https://user-images.githubusercontent.com/20819712/70058063-32c53580-1619-11ea-8840-5985bb52a7de.png">
<img width="89" alt="Screen Shot 2019-12-03 at 22 05 51" src="https://user-images.githubusercontent.com/20819712/70058064-335dcc00-1619-11ea-883a-6178f44e03b5.png">

Yes, now with light theme, it is visible and clear. With dark theme, it can be improved by using a lighter color identical to the "pin" perhaps? In fact, shall we use same color for all icons?

For light theme, we use the color identical to box and triangle icons. For dark theme, we use the color identical to the pin.

**Comment by TienHao** [comment]
<img width="105" alt="截圖 2019-12-05 下午3 13 41" src="https://user-images.githubusercontent.com/20379662/70212505-5a7be100-1772-11ea-8696-447dcc0fb1fa.png">
<img width="93" alt="截圖 2019-12-05 下午3 14 48" src="https://user-images.githubusercontent.com/20379662/70212528-65cf0c80-1772-11ea-8a13-49b32a5159d8.png">
Are these OK? These will have different colors in different theme

I also adjust floating widget header button to the same color.
<img width="789" alt="截圖 2019-12-05 下午3 14 08" src="https://user-images.githubusercontent.com/20379662/70212614-91ea8d80-1772-11ea-9f9f-f80b617947a4.png">
<img width="824" alt="截圖 2019-12-05 下午3 14 40" src="https://user-images.githubusercontent.com/20379662/70212646-a7f84e00-1772-11ea-9eb6-049bc09f5918.png">

**Comment by kswang1029** [comment]
Great!
