### ISSUE TITLE
[UX] server info in login dialog

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#408]
could add info such as:
* server ip/name
* last login time...etc

**Comment by veggiesaurus** [comment]
@duidae can you edit the description to add what server info you think should go in there, as a starting point for the discussion? If we display the server IP, we will need to either modify the backend and ICD to return the IP, or use a web-based lookup service to get the IP. 

In general, each frontend will correspond to a specific backend, so the IP or address might not be too helpful, but the version info could be useful. I'm not sure if this is best handled here or in an "about" dialog
