### ISSUE TITLE
point regions cannot be clicked if inside a region with area < 4

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#409]
Point regions cannot be clicked on if they're in a region with an area smaller than 4 px<sup>2</sup>. This is because point regions are assigned an area of 4. Could the area be zero?

![point_region_area](https://user-images.githubusercontent.com/592504/61865086-e7648300-aed2-11e9-9422-c0858c65d4b4.gif)

**Comment by kswang1029** [comment]
Is this closed by accident?

**Comment by kswang1029** [comment]
@zarda Is this closed by accident? 
This issue remains in the dev branch. Reopen this issue as a record.

**Comment by zarda** [comment]
Fixed by #414

**Comment by veggiesaurus** [comment]
issues should stay open until the PR that fixes them is merged into `dev`
