### ISSUE TITLE
highlight value = 0.0 grid line in profiles

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#413]
Have been using the dev viewer to look at some recent MeerKAT MIGTHEE polarization cubes.   Here is a shot of the viewer with Stokes U and Q profiles widgets. Of interest in these profiles is to assess if the signal is significant different from noise around zero. It would be very nice if the grid line at 0.0 were highlighted some way (thicker or darker line).   

![Screen Shot 2019-07-29 at 1 23 26 PM](https://user-images.githubusercontent.com/9055533/62045703-58bf7100-b206-11e9-8588-10fd3e606659.png)

**Comment by Kechil** [comment]
needs to be consistent for all widgets

**Comment by panchyo0** [comment]
closed with PR #592
