### ISSUE TITLE
view file information or image header

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#417]
We should be able to view the image header of the current frame.  One way to do this is to add  "image header" or "image info"  sub menu to the "view" menu.  This would bring up a text widget containing the image header. 

Alternately one could add an info panel that contains the file information.  Not sure which is more useful the file information or the header.  The header is more complete, but the file info is more readable.

**Comment by veggiesaurus** [comment]
This sounds like a useful addition. We should be able to re-use a fair portion of the file browser dialog code to do so.
