### ISSUE TITLE
Should we adjust layout delete menu items?

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#418]
Saving and deleting layouts is working nicely at the moment. However, I'm wondering if we can make it a little simpler. Here's how you delete layouts at the moment:

![current_layout_delete](https://user-images.githubusercontent.com/592504/62131340-4bc08180-b2db-11e9-8889-672063083a1f.gif)

I think we could get away with simply showing the list of layouts once, and then using a delete icon next to each user layout:
![suggested_layout_delete](https://user-images.githubusercontent.com/592504/62131432-7dd1e380-b2db-11e9-8a19-0010954907df.gif)

Not sure if this is preferable or not. It seems easier to delete things, but perhaps it's _too_ easy this way.

**Comment by kswang1029** [comment]
Perhaps with a pop up for confirmation?
