### ISSUE TITLE
make the breadcrumbs always visible even if scrolling down a long file list

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#420]
Currently the breadcrumbs are visible when the file list is scrolled to the top. If the file list is long and if we scroll down, breadcrumbs are not visible. 
![Screen Shot 2019-07-31 at 11 44 25 AM](https://user-images.githubusercontent.com/20819712/62182350-e3c87480-b388-11e9-9843-d1b45beafab1.png)
![Screen Shot 2019-07-31 at 11 44 38 AM](https://user-images.githubusercontent.com/20819712/62182352-e7f49200-b388-11e9-97af-85393a785e5a.png)

Suggest to make breadcrumbs always visible just like the header (File name, type, size) of the file list.

**Comment by kswang1029** [comment]
a relevant cosmetics issue of the scroll bar:
![Jul-31-2019 13-49-01](https://user-images.githubusercontent.com/20819712/62186821-1169e980-b39a-11e9-86f1-3a60aa534f43.gif)

**Comment by zarda** [comment]
![Screen Shot 2019-08-01 at 16 48 27](https://user-images.githubusercontent.com/10767557/62279273-58301000-b47c-11e9-9a63-5ac057d93e59.png)

**Comment by veggiesaurus** [comment]
@zarda if we can just adjust the padding a bit, I think that would be a good solution

**Comment by kswang1029** [comment]
Are we using the space above file info for the breadcrumbs as well? That helps to display path for nested folder structure I think.

**Comment by veggiesaurus** [comment]
> Are we using the space above file info for the breadcrumbs as well? That helps to display path for nested folder structure I think.

We could do that, if you don't think it would look odd. @zarda , perhaps give that a try?

**Comment by zarda** [comment]
![Screen Shot 2019-08-01 at 18 25 45](https://user-images.githubusercontent.com/10767557/62286263-f1b1ee80-b489-11e9-910d-8d10dcf047a5.png)

**Comment by veggiesaurus** [comment]
@zarda I think KS meant use the entire vertical space, not _just_ the info. So something like this pseudocode:

```
<div>
    <breadcrumbs/>
    <div display=flex>
        <FileList/>
        <FileInfo/>
    </div>
</div>
```

**Comment by kswang1029** [comment]
a mockup would be like this
![62279273-58301000-b47c-11e9-9a63-5ac057d93e59](https://user-images.githubusercontent.com/20819712/62340046-bc041880-b510-11e9-9f6b-59ee97a95cf3.png)

**Comment by zarda** [comment]
![Screen Shot 2019-08-02 at 12 40 57](https://user-images.githubusercontent.com/10767557/62344984-f1b1fd00-b522-11e9-9687-b9d47686441c.png)

**Comment by kswang1029** [comment]
apart from where we put breadcrumbs, there is an issue with 320ce6b:
The last entry in the list is not visible. Check the length of the scroll bar at top and at bottom.
![Aug-02-2019 12-58-22](https://user-images.githubusercontent.com/20819712/62345632-a1886a00-b525-11e9-8c92-f2b8ff93e56c.gif)

As a comparison with the dev branch, the last entry "supermosaic.10.fits" is not visible. 
![Screen Shot 2019-08-02 at 12 58 51 PM](https://user-images.githubusercontent.com/20819712/62345670-c846a080-b525-11e9-994a-3545e744b64c.png)

**Comment by zarda** [comment]
Thanks for information. Fixed the border issue.
![Screen Shot 2019-08-02 at 16 14 42](https://user-images.githubusercontent.com/10767557/62355024-bcb4a300-b540-11e9-9ff2-c85d5f37d3b3.png)

**Comment by veggiesaurus** [comment]
@zarda what about putting the breadcrumbs across the entire dialog width, like @kswang1029 suggested?

**Comment by arusstaylor** [comment]
I agree it would be better to put the breadcrumbs across the entire width.

**Comment by kswang1029** [comment]
@zarda please use a wider default width. Long file name is quite common.
<img width="797" alt="Screen Shot 2019-08-02 at 16 44 57" src="https://user-images.githubusercontent.com/20819712/62357285-50886e00-b545-11e9-9a2b-45ed9112a1e0.png">

Please make the minimum height even smaller (c.f. dev branch) and please make sure responsive layout still works when we resize (vertically and horizontally) the file browse dialog.

**Comment by arusstaylor** [comment]
refer you to issue #325. Would be nice to address that as well.

**Comment by zarda** [comment]
Revised
![Screen Shot 2019-08-02 at 18 41 46](https://user-images.githubusercontent.com/10767557/62364957-67cf5780-b555-11e9-85cd-5e9e1bf5441a.png)

**Comment by arusstaylor** [comment]
This is looking better.  Probably nice to have just a bit more space between the breadcrumb directory info and the file info box.

**Comment by kswang1029** [comment]
@zarda 
With 6e77020,
1) please restore the size of the file browser dialog as the dev. Now it is too small in width.
<img width="1440" alt="Screen Shot 2019-08-02 at 19 20 35" src="https://user-images.githubusercontent.com/20819712/62366997-04e0bf00-b55b-11e9-81d8-93500ee7c34e.png">

2) now items are mis-aligned.
<img width="800" alt="Screen Shot 2019-08-02 at 19 21 53" src="https://user-images.githubusercontent.com/20819712/62367144-51c49580-b55b-11e9-9398-66fe873b8f77.png">
