### ISSUE TITLE
region dialog for cursor

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#427]
Color and name are not needed in the region dialog for "cursor".
![Screen Shot 2019-07-31 at 1 57 02 PM](https://user-images.githubusercontent.com/20819712/62187231-3f036280-b39b-11e9-8c7a-1c67ad27f670.png)

**Comment by veggiesaurus** [comment]
I think we should disable the region dialog for cursor entirely

**Comment by kswang1029** [comment]
Yes, that's better.

**Comment by arusstaylor** [comment]
agree.
