### ISSUE TITLE
displayed "value" in the cursor info bar should be for cursor, not point region

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#428]
When a point region is updated, the "value" in the cursor info bar is also updated. We should keep the "value" dedicated to cursor only. 
![Jul-31-2019 14-03-13](https://user-images.githubusercontent.com/20819712/62187452-00ba7300-b39c-11e9-9b7e-427c8ffde2f7.gif)

**Comment by arusstaylor** [comment]
Agreed.  The value displayed in the info bar should always be the value under the cursor.
