### ISSUE TITLE
Error in Chart.js library's update when refreshing plots

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#433]
When converting to scientific notation, it seems there's an issue with the Chart.js. It's not entirely clear how to reproduce this issue, but it seems to occur frequently with @panchyo0's Stokes widget branch and `GNPilot.IQU.fits`. 

@arusstaylor this is the issue you mentioned to me yesterday. Screen goes blank and the dev console shows the output below

![image](https://user-images.githubusercontent.com/592504/62189660-d9e64780-b36f-11e9-82d7-9d1b14786c3c.png)

**Comment by kswang1029** [comment]
it is the scatter plot.
![Jul-31-2019 14-55-28](https://user-images.githubusercontent.com/20819712/62190167-4af32280-b3a3-11e9-8538-09130f0dae1d.gif)

**Comment by veggiesaurus** [comment]
The offending line is `tickString = tickValue.toExponential(Math.floor(logTick) - Math.floor(logDelta));`. I might have to file an issue with ChartJS and fix it there.

**Comment by veggiesaurus** [comment]
Closing this issue, as it is fixed with a workaround in `dev`. This should be re-examined if the Chart.js bug is solved.
