### ISSUE TITLE
cursor info bar: cursor value when the cursor is outside the image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#435]
it would be better to show nothing about the cursor value when the cursor is outside the image to avoid confusion as coordinates are still updating along with the cursor movement. 

![Aug-01-2019 10-50-39](https://user-images.githubusercontent.com/20819712/62262135-3e75d500-b44a-11e9-989b-20db2ce691c0.gif)

**Comment by Kechil** [comment]
leave out whole value field?
