### ISSUE TITLE
cannot add new anchor to a polygon when it overlaps with other region in some cases

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#439]
The guider disappears in some circumstances when a polygon overlaps with other region. 
It appears that the issue is related to the relative areas of the two regions.

This works fine:
![Aug-02-2019 13-47-47](https://user-images.githubusercontent.com/20819712/62347496-810fde00-b52c-11e9-87c0-2e834aaeb07c.gif)

But not this one:
![Aug-02-2019 13-47-29](https://user-images.githubusercontent.com/20819712/62347513-8a994600-b52c-11e9-81d7-36a4ffc9afdd.gif)

**Comment by veggiesaurus** [comment]
I'm not sure how to get around this. The smaller region needs to be layered on top, to avoid prevent it from being unclickable. I guess a workaround here is to move the other region temporarily.

**Comment by veggiesaurus** [comment]
Perhaps we need the ability to lock regions? That way they don't get rendered to the hit graph

**Comment by kswang1029** [comment]
possibly to have the polygon on top temporarily  _when_  guider is visible?

**Comment by veggiesaurus** [comment]
Exactly...we can't tell if the guide should be visible if the polygon is not in front. I think the same applies to anchors for other regions, doesn't it?

**Comment by kswang1029** [comment]
@veggiesaurus you are right.... hmmm...

![Aug-02-2019 15-38-51](https://user-images.githubusercontent.com/20819712/62352841-b7088e80-b53b-11e9-8ab1-4114c8983769.gif)

**Comment by veggiesaurus** [comment]
I think the way to solve this is to allow the user to lock regions in the region info dialog or the region list. Locking a region would prevent any form of interaction with the region, so the user could move other regions on top of it, pan over it and so on.

**Comment by kswang1029** [comment]
Locking via region list would be more straightforward I think. Surely we need to lock function in region dialog too.

**Comment by veggiesaurus** [comment]
Work-in-progress. I think it works quite nicely:

![region_lock](https://user-images.githubusercontent.com/592504/62545054-39a58c80-b861-11e9-965e-3c20098c2b97.gif)
