### ISSUE TITLE
cannot create a polygon if users click too fast

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#443]
I think this is an exceptional case but that may happen.
![Aug-06-2019 09-57-15](https://user-images.githubusercontent.com/20819712/62505849-d439a780-b830-11e9-9eeb-d7021098b059.gif)

**Comment by veggiesaurus** [comment]
this has been bugging me for a while. The problem is that clicking fast counts as a "double click", which then ends the polygon creation. Not sure how to get around this issue

**Comment by kswang1029** [comment]
I see. Iceboxes?

**Comment by veggiesaurus** [comment]
Yes, and then if user feedback from the beta brings it up, we can try to sort it out. Possibly we can manually trigger double-clicking and then have control over the double-click duration. Do you think if we halved the double click duration that would solve the issue?

**Comment by zarda** [comment]
Could we check the distance between clicks? The creation will finish, if the distance is small.
