### ISSUE TITLE
missing image viewer when reloading a special layout

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#444]
if there is only one widget docked and the image viewer widget is undocked, and if we save this kind of layout and reload it, the image viewer will be gone and cannot be launched anymore. 
![Screen Shot 2019-08-06 at 2 05 38 PM](https://user-images.githubusercontent.com/20819712/62514993-926e2880-b853-11e9-9eb9-f6ccd03dc70d.png)

**Comment by duidae** [comment]
this is a little bit tricky, currently closing/undocking image viewer is provided to user, but there is no drag source of it for recovery(& we should not provide for performance/resource concern), so the easiest way to fix it is to disable close/undock in golden-layout, however only disabling close is achievable...my ideas are:
1. add a default image view to layout without image view  in left column
2. save floating widgets to layout & recover them when layout is loaded

@veggiesaurus @kswang1029 how do u think?

**Comment by veggiesaurus** [comment]
@duidae we need to have floating widgets in the layout anyway. Lets take that route.

**Comment by kswang1029** [comment]
@duidae could you check if image viewer is docked before saving the layout? I did an experiment before that if we have all widget undocked, we cannot save the layout and we will see an error prompt.

**Comment by duidae** [comment]
@veggiesaurus hmm ok
@kswang1029 yes if the docked layout is empty, the error message will prompt when saving, and we cant force the image viewer to be docked, so the solution is still to save floating widgets to layout

**Comment by kswang1029** [comment]
@duidae what I meant is before saving a layout, can we check the state of the image viewer to see if it is currently docked or not? If it is undocked, we show an error prompt.

**Comment by duidae** [comment]
@kswang1029  I think we should ensure that there is at least one image viewer in each layout, no matter it is docked or undocked

**Comment by duidae** [comment]
reference for making stack unstackable: https://github.com/golden-layout/golden-layout/issues/357
