### ISSUE TITLE
point style in graph makes profile decimation artifacts/side effects much more noticeable 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#452]
See the attached gif.
![Aug-07-2019 10-15-15](https://user-images.githubusercontent.com/20819712/62589592-4e832e00-b8fc-11e9-9eef-8bcec3c9c10e.gif)

Maybe a quick solution is to remove point style (and may solve $453 too).

**Comment by veggiesaurus** [comment]
Could we use random decimation instead of min max?

**Comment by kswang1029** [comment]
That would make profile features distorted, right? I think the current min/max decimation does preserve profile features well. 

I feel this profile decimation (either min/max or random) needs to work with line or step plots since they kind of visualizing interpolation via connection lines.

**Comment by veggiesaurus** [comment]
Hmmm, perhaps. I think we might need to disable decimation when using a point plot

**Comment by kswang1029** [comment]
> Hmmm, perhaps. I think we might need to disable decimation when using a point plot

That would be good!
