### ISSUE TITLE
Save as png in Stokes widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#454]
Currently each of the profile plots (Q&U, PI, PA) can be exported as png separately. This introduces an issue of missing x tick labels.
![IRCp10216_sci spw0 cube IQUV manual pbcor fits-profile-2019-8-7-10-51-41](https://user-images.githubusercontent.com/20819712/62591291-b9833380-b901-11e9-8e4e-f415ec7bf75c.png)

As an improvement, we could consider to save all three plot together as one png plot.

**Comment by veggiesaurus** [comment]
@kswang1029 the ticks are now saved correctly in the individual plots

**Comment by kswang1029** [comment]
@veggiesaurus Yes!
