### ISSUE TITLE
incorrect x range of profile widget (spatial/spectral) when open a new image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#463]
if we open image A, check spectral profile, and modify the x range by zooming, then if we open image B (image A will be closed then) and check spectral profile, we will see empty plot if image A and image B have different frequency coverage. Thanks to @panchyo0 for spotting this!

**Comment by Kechil** [comment]
@panchyo0 should be addressed after switching to plotly

**Comment by panchyo0** [comment]
closed after PR #1434
