### ISSUE TITLE
polarization angle is incorrect

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#470]
Polarization angle is calculated incorrectly, it is currently half of what it should be.

**Comment by veggiesaurus** [comment]
@arusstaylor @low-sky, continuing our email chain: 

@panchyo0 has a pull request waiting (#468) that changes it to use  `0.5 * Math.atan2(u, q)`
Is that definitely the right equation? Most of the literature I've seen just specifies `0.5 * atan(u/q)`, which implies a smaller range. `atan2` is generally more useful, since it can tell you which quadrant things are in, but is this a generally accepted definition?

**Comment by arusstaylor** [comment]
The equation above will map the angle onto 0 to 180 degrees.  This is acceptable. I am fine with the angle being displayed on that range.  There is no convention but typically PA is either mapped to 0 to 180 or -90 to 90.   Either is ok.    The physics is that PA has no direction.  It is not a true vector.  To convert from 0 to 180 to -90 to 90 you just need to flip the values in range 90 to 180 by 180 so that for instance 91 = -89 and 179 = -1.

**Comment by kswang1029** [comment]
@arusstaylor when we plot a polarization segment on the image, are we referring 0 degree to North?

**Comment by arusstaylor** [comment]
Yes polarization angle of 0 should be North an increase counterclockwise.  See https://arxiv.org/abs/1612.03045

**Comment by veggiesaurus** [comment]
@arusstaylor `atan2` has a range of [-pi, pi], so the equation `0.5 * Math.atan2(u, q)` has a range of [-90, 90]

**Comment by kswang1029** [comment]
@arusstaylor thanks for the reference : ) So I would suggest we make it consistent in the PA plot.

**Comment by arusstaylor** [comment]
@veggiesaurus.  Ok we are fine then.

**Comment by arusstaylor** [comment]
@kswang1029 I think this only applies if we are plotting the PA as vector overlays on the image.  For the PA line plot the Q and U values and thus PA are defined by the instrument used to create data cube,  and one hopes that the Q, U directions are referenced to the sky by the processing.

**Comment by low-sky** [comment]
I agree that we're good to go with `0.5 * atan2(u, q)`. equation.

**Comment by kswang1029** [comment]
@arusstaylor @low-sky FYI about the polarization angle from CASA with immath task. 
https://casa.nrao.edu/casadocs-devel/stable/global-task-list/task_immath/about
