### ISSUE TITLE
Enhancement of spectral profile widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#475]
To make the spectral profiler widget even more useful for science productivity, the following features need to be implemented.
1) conversion of spectral axis (x), such as velocity frame, frequency, velocity, optical/radio definition, etc.(c.f. casaviewer)
2) unit conversion of intensity axis (y), such as Jy/beam <-> K, MJy/sr, Jy/arcsec^2, etc. (c.f. casaviewer)
3) custom displayed x and y range (with text input)
4) profile fitting (Gaussian, Lorentzian, Voigt etc)
5) overplotting labels of molecular transitions by querying molecular database
6) channel smoothing (hanning, boxcar, binning)
7) ability to view multiple profiles in one widget

**Comment by arusstaylor** [comment]
would add wavelength, and wavelength squared to the axis conversion options in item 1.  Useful for spectropolarimetry

**Comment by veggiesaurus** [comment]
I think we need separate issues for each of these independent feature requests once we've decided what and when to implement.

**Comment by Kechil** [comment]
This is both v1.3 and v1.4. investigate whether duplicated.

**Comment by kswang1029** [comment]
break into #643 and #644
close this one
