### ISSUE TITLE
Adding license info for U. Alberta

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#476]
![Screen Shot 2019-08-13 at 2 30 49 PM](https://user-images.githubusercontent.com/20819712/62920056-294c5f00-bdd7-11e9-8f7f-fda3d626b7a5.png)

@low-sky Shall we use "Department of Physics, University of Alberta" or simply "University of Alberta"?

**Comment by low-sky** [comment]
Please include Department of Physics.  Otherwise 👍
