### ISSUE TITLE
hanging file list if we open image file browser without closing region file browser and vice versa

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#483]
To reproduce the issue, open image file browser, then open region file browser without closing the image file browser dialog. 

Or, open region file browser, then open image file browser without closing the region file browser dialog.

**Comment by zarda** [comment]
Reopening file file browser will be an issue because the fileBrowserStore.getFileList execute after opening.

**Comment by veggiesaurus** [comment]
@kswang1029 does this need to be backported?

**Comment by kswang1029** [comment]
Yes I think we should have it in v1.2. It is quite easy to trigger the issue.
