### ISSUE TITLE
region profile update of an HDF5 cube in the Stokes widget does not have changing line opacity 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#485]
frontend master 3335f5e

When viewing region spectral profile of an HDF5 cube, the profile is updating with changing line opacity. The same feature should be applied to the Stokes widget too.

**Comment by veggiesaurus** [comment]
@panchyo0 can you have a look at how this is handled in the spectral profile widget and use that same approach for the stokes widget?
