### ISSUE TITLE
dynamically increase AST tolerance during image motion (zooming, click-drag panning)

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#487]
Currently, simply rendering the AST overlay can take almost 10 ms on its default tolerance setting (2%). While this is fine under most circumstances, when zooming in and out using devices with smooth scrolling (e.g. MacBook with touchpad), the image view is refreshed almost every 16 ms, so 10 ms becomes quite a burden. I'm wondering whether we shouldn't dynamically adjust the AST tolerance up to 2x the chosen tolerance setting during motion. This would mean that while zooming (or click-drag panning if we get round to implementing that), grid overlay lines would be less accurate, but would become more accurate when motion finishes. Doubling the tolerance threshold seems to roughly halve the overlay rendering time on my test device (MacBook 15" 2018).

**Comment by veggiesaurus** [comment]
@kswang1029 any thoughts on this?

**Comment by kswang1029** [comment]
Good idea!

**Comment by veggiesaurus** [comment]
to be implemented along with drag-to-pan support in 1.3
