### ISSUE TITLE
[server] Integrate preference & layout to DB in server version (frontend part)

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#491]
- [X] integrate layout with server DB
- [X] integrate preference with server DB
- [X] test layout/preference with server DB

**Comment by Kechil** [comment]
Is this the same is #348? If so please remove #348.

**Comment by duidae** [comment]
@Kechil  no it's a different issue, in server version we have database to save stuffs, so user preferences need to migrate to database accordingly

**Comment by veggiesaurus** [comment]
still requires a little more testing, but will re-open if the testing indicates changes are required.
