### ISSUE TITLE
Changes to widget options display

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#495]
Currently, we use a side-bar approach to widget options: commonly used widget options are displayed at the top of the widget, while more options are available by expanding the options bar by pressing the cog:
![image](https://user-images.githubusercontent.com/592504/63413275-aee49600-c3f9-11e9-9a3b-b68c3ad64352.png)
![image](https://user-images.githubusercontent.com/592504/63413185-8066bb00-c3f9-11e9-8d07-f0bc92aa0434.png)

This is feasible for widgets with a small number of options, but:
1) it only works nicely for widgets in landscape mode. In portrait mode, it looks pretty silly (see below). The Stokes widget would also look quite odd with this sidebar
2) we're getting to the stage. where some widgets need a lot more options. For example, the spectral profile widget will eventually have a suite of fitting, smoothing and catalog overlay options. 

![image](https://user-images.githubusercontent.com/592504/63413610-595cb900-c3fa-11e9-974a-818bbb6b8136.png)

Perhaps it's time that we introduce a (floating-only) "options" widget that can be opened by a settings button displayed on the widget's title? The options widget would then be sized appropriately, and contain all the settings for the widget. We then don't have to worry about screen real-estate when adding options. 

@kswang1029 @arusstaylor @low-sky any thoughts?

**Comment by arusstaylor** [comment]
I agree that a floating options widget invoked by a cog wheel in the header bar as a universal approach for widget options would be a better approach. I provides a common approach for all widgets, and frees up real estate within the widget. 

Russ

**Comment by low-sky** [comment]
I agree; a floating window makes sense. The primary thing to watch out for is whether the widget itself is visible while settings are being manipulated.  It's useful to see the effects of interactions with the preferences pane.

**Comment by veggiesaurus** [comment]
> The primary thing to watch out for is whether the widget itself is visible while settings are being manipulated. It's useful to see the effects of interactions with the preferences pane.

I think this is crucial, which is why I'd prefer for the settings to be floating, rather than docked. Floating widgets could easily be rearranged so that the config widget doesn't obscure the actual widget.

I suspect some thought may be required when determining where the config widget actually pops up initially.

**Comment by panchyo0** [comment]
@veggiesaurus since we have a floating settings panel for stokes widgets after #577. Should we start to apply this to all widgets?

**Comment by veggiesaurus** [comment]
@panchyo0 yes, that's a good idea. Lets start with the spectral profiler next

**Comment by panchyo0** [comment]
finished wth PR #592
