### ISSUE TITLE
Frontend crash when reload page

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-frontend#499]
Using Chrome on MacOS with the asiaa server for the frontend (latest dev), when I restart my local backend then reload the page to reconnect, I see the page as connected, the file browser automatically pops up, then the page goes blank.  I reload the page again, and all is well.  This error is in the dev console output:
![Screen Shot 2019-08-21 at 10 11 43 AM](https://user-images.githubusercontent.com/856604/63525224-8e304500-c4ba-11e9-8a6b-1e360cabf626.png)

**Comment by veggiesaurus** [comment]
@pford can you confirm that this is fixed in the latest `dev` and `release/1.2` commits?

**Comment by veggiesaurus** [comment]
> Intermittently still get:`react-dom.production.min.js:187 TypeError: Cannot read property 'sort' of undefined at t.render (FileListComponent.tsx:57) 

Fixing now.
