### ISSUE TITLE
Analysis widgets should default to the "active" region. 

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#512]
When a user creates a new widget, its associated region should default to the "active" region.  This means that users can easily switch from viewing the analysis results of one region to that of another by selection the other region. This has been requested since 1.0, but was blocked by the lack of partial profiles and profile cancellation.

- [ ] An item in the region dropdown needs to be added for "active" region. The active region is the selected region. If there is no selected region, spectral profiles revert to the cursor region, while stats and histogram widgets revert to the image region. 
- [ ] The requirements map checks need to be modified to correctly send requirements when a widget has an "active" region selected.
- [ ] The widget title handling needs to be updated

**Comment by kswang1029** [comment]
@zarda will you still be able to implement this in a week?

**Comment by zarda** [comment]
I think I can not make it in a week.

**Comment by TienHao** [comment]
@veggiesaurus : could stoke analysis  also be implemented this feature?:smile: it has a region dropdown too. Since the stores of spectral profile, stats, histogram and stoke analysis widgets they all extend RegionWidgetStore, I think making changes to RegionWidgetStore can reduce similar modifications in different analysis widgets.

**Comment by arusstaylor** [comment]
I think this behaviour should be common to both the profile and stokes widgets, and any other widget that acts on region data.  E.g. histograming and statistics/analysis widgets in the future.

**Comment by veggiesaurus** [comment]
> @veggiesaurus : could stoke analysis also be implemented this feature?😄 it has a region dropdown too. Since the stores of spectral profile, stats, histogram and stoke analysis widgets they all extend RegionWidgetStore, I think making changes to RegionWidgetStore can reduce similar modifications in different analysis widgets.

Yes, any widget that has a region dropdown should have the ability to select the "active" region
