### ISSUE TITLE
Extra render config options in preferences: alpha and gamma values

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#515]
Alpha and gamma values need to be added to render config options in the preferences dialog.

**Comment by duidae** [comment]
about naming of the fields,
log scaling -> alpha
power scaling -> beta
gamma scaling -> gamma

is that ok? @veggiesaurus @kswang1029

**Comment by veggiesaurus** [comment]
@duidae the `alpha` values should be the same for log and power, since they are related to the same thing. This is consistent with DS9's behaviour, and with our current use of it in the render config widget

**Comment by duidae** [comment]
kk @veggiesaurus  got it, thanks!
