### ISSUE TITLE
checking file name of a region file when exporting

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#526]
Currently the frontend checks the input file name of a region file with all other existing region files (via REGION_LIST_RESPONSE) when exporting. However, the input name may coincide with other image files or other file types. If this happens, the frontend shows successful but actually there is no region file saved. Luckily existing file is not overwritten based on my test.

If we don't want to add a field in REGION_LIST_REQUEST to include all files in the directory, we could consider to enable adding .crtf or .reg extension to lower the chance of having identical name. Not ideal though.

@veggiesaurus @pford thoughts?

**Comment by veggiesaurus** [comment]
we shouldn't associate the extension with the file type. Perhaps we should simply list all files

**Comment by kswang1029** [comment]
Yes, if the frontend is aware of all files in the backend directory, we can use the current approach to warn users.

**Comment by kswang1029** [comment]
@veggiesaurus shall we migrate this to backend?

**Comment by veggiesaurus** [comment]
Issue moved to [CARTAvis/carta-backend #344](https://github.com/CARTAvis/carta-backend/issues/344) via [**ZenHub**](https://www.zenhub.com/)
