### ISSUE TITLE
precision of cursor coordinate in z profile

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#537]
I am looking at the z profile for the GALFACTS stokes cube.  The display of the cursor value shows the frequency only with a precision of 0.01 GHz.  e.g. 1.43 GHz.  The actual step in frequency per channel is much smaller that 0.01 GHz so the cursor value remains the same even if I change the channel.  The precision of the value of the cursor position in the z profile should be set to have sufficient significant figures so that the value changes from one channel to the next.

test file: set_M17/M17_SWex.image

**Comment by veggiesaurus** [comment]
agreed. @duidae can you sort this out when you get the chance?

**Comment by duidae** [comment]
okok

**Comment by veggiesaurus** [comment]
@arusstaylor @kswang1029  what sort of precision would be appropriate? 4 decimals?

**Comment by arusstaylor** [comment]
There is probably not one solution that works for all data sets. I think this should be set dynamically to whatever the precision of the difference between two channel is.

**Comment by veggiesaurus** [comment]
> There is probably not one solution that works for all data sets. I think this should be set dynamically to whatever the precision of the difference between two channel is.

That's one possible solution, but it would mean that the precision would change depending on where the cursor is. For example, if you have two values of `1.4015` and `1.4072`, then you would need 3 decimals to tell them apart. If you have two values of `1.4072` and `1.5031`, then you'd only need 2 to tell them apart.

I'd rather we didn't assume that the delta between channels is constant, because 
(a) the WCS standard doesn't enforce this and 
(b) this might not be the case soon, for cubes with lots of NaN channels.

**Comment by arusstaylor** [comment]
hmmm.  Not sure what else makes sense. I guess you could use the total bandwidth divided by the number of channels to get the average channel difference and use that. Would be a sensible solution 99.999...% of the time.

**Comment by veggiesaurus** [comment]
> hmmm. Not sure what else makes sense. I guess you could use the total bandwidth divided by the number of channels to get the average channel difference and use that. Would be a sensible solution 99.999...% of the time.

That breaks down if we have a non-linear z-axis. Once we do conversions from one spectral quantity to another (freq <-> wavelength <-> velocity is required for 1.3 release), this becomes problematic

**Comment by arusstaylor** [comment]
Getting complicated. I guess then you would need so search for the smallest channel difference in the cube and use that to set the precision.

**Comment by arusstaylor** [comment]
Could be can expensive calculation for 32k channels. 

For the conversion from freq - velocity can you not just convert the precision using the same transformation as you use for the coversion?

**Comment by veggiesaurus** [comment]
> Could be can expensive calculation for 32k channels.

Yes, it could be. I think the best bet is to simply use the neighbouring values to calculate the required precision. Nice and simple. Although it may look a little weird if the precision changes across the image, the precision will always be _enough_ to distinguish between channels.

> For the conversion from freq - velocity can you not just convert the precision using the same transformation as you use for the quantity conversion?

For freq to velocity, yes. But that only works for linear transformations. As soon as we convert to wavelength, that no longer works.

**Comment by arusstaylor** [comment]
using the neighbouring values is a safe bet.  In most cases the precision will not change so will not be strange.  Will only change if the channel increment changes, which I guess is the right thing to do.

**Comment by veggiesaurus** [comment]
> using the neighbouring values is a safe bet. In most cases the precision will not change so will not be strange. Will only change if the channel increment changes, which I guess is the right thing to do.

@duidae please use a similar approach to how we handle precision in the spatial profiler in order to dynamically calculate what precision is needed to display the data values
