### ISSUE TITLE
cursor update for profiles stops during zoom

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#544]
When I zoom in on an image,  moving the cursor no longer updates the profiles while the image is waiting for the update from the backend for the new zoom level.  This is very annoying.

**Comment by arusstaylor** [comment]
How about using the unzoomed data still residing on the front end to create profiles while waiting for the new render of zoomed data?

**Comment by veggiesaurus** [comment]
> How about using the unzoomed data still residing on the front end to create approximate profiles while waiting for the new render of zoomed data?

That might go some way to treating the symptom you're seeing, but wouldn't fix the underlying issue (heavy network use, blocking all other received messages). There are a few issues with re-introducing approximate profiles though:

1) They are far more complex to implement with a tiling approach
2) They won't work for spatial profiles of contour images
3) They won't work when we eventually implement HEVC compression

One other option we could explore is requesting tiles more intelligently. At the moment, we request tiles as the user zooms in. This means that during a single "zoom", we might be requesting a large number of tiles that never actually get used. We could instead only request tiles once the user has stopped zooming for some interval (50 ms?). That would mean a slightly longer delay between the user stopping their zoom and the tiles appearing, but the important feature is that the relevant tiles wouldn't be at the end of a long queue of unnecessary tiles

**Comment by arusstaylor** [comment]
The more intelligent tile request sounds like a good thing to do regardless.  Would probably also speed up the responsiveness of the zoom once  it starts.

**Comment by veggiesaurus** [comment]
> The more intelligent tile request sounds like a good thing to do regardless. Would probably also speed up the responsiveness of the zoom once it starts.

Because it wouldn't request tiles until the zoom _ends, two situations will arise:
1) In situations where the network connection is very good, there will be a slightly longer delay between the user zooming and the user seeing the correct tiles
2) In situations where the network connection isn't so good, there will be much less of a delay (than the current implementation) between the user zooming and the user seeing the correct tiles, because all the intermediate layers were not requested
