### ISSUE TITLE
import craft region files does not support global parameters

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#547]
I tried importing a crtf region file with global color=white and linewidth=1 and the file failed to load.  Seem like the importer does not recognise some global parameters.

**Comment by veggiesaurus** [comment]
@arusstaylor neither DS9 nor CRTF importing currently support styling parameters. Is this a duplicate of https://github.com/CARTAvis/carta-backend/issues/340?

(I imagine adding support for these features would be for both inline and global parameters)

**Comment by arusstaylor** [comment]
Yes it looks like this is a duplicate of bs k end issue 340.
