### ISSUE TITLE
Crashed while the image be moved outside the FOV

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-frontend#553]
Reproduce:
Open one image and pan the image until it is outside the field of view.

test file: aJ.fits

**Comment by veggiesaurus** [comment]
@zarda well spotted. @duidae , I think this is due to changes in your code. Need to check if a value is defined before converting to exponential.

**Comment by kswang1029** [comment]
I couldn't reproduce the issue. Any more instructions?

**Comment by veggiesaurus** [comment]
@duidae after implementing the wrapper functions we discussed (something like below), please replace all occurrences of `toFixed` and `toExponential` with the wrapper functions, and remove the now-redundant checks.

```
// According to MDN, toFixed only works for up to 20 decimals
function toFixed(val: number, decimals: number) {
  if (isFinite(val) && isFinite(decimals) && decimals >= 0 && decimals <= 20) {
    return val.toFixed(decimals)
  }
  // leave undefined or non-finite values as is (+- INF, NaN and undefined will still appear properly)
  return val;
}

**Comment by duidae** [comment]
ok
