### ISSUE TITLE
reload button for refresh file list in file browser

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#557]
currently need to re-open the file browser to refresh file list

**Comment by veggiesaurus** [comment]
you can just click on the folder name again

![refresh_folder](https://user-images.githubusercontent.com/592504/66898172-e8e8a780-eff8-11e9-993f-0701d3a8269b.gif)

**Comment by duidae** [comment]
hmm, @veggiesaurus  how about  we add a tooltip for it? could be more intuitive

**Comment by veggiesaurus** [comment]
a refresh button could work too. I don't have a strong preference either way, but just wanted to point out that it is possible at this point without a button.

A refresh button could be useful, but would take up space, and would then mean we have less space for the title. @duidae where would you suggest the refresh button goes?

 @kswang1029? any strong opinions on this?

**Comment by kswang1029** [comment]
A refresh button would be handy. No strong opinion on where it should be located.

**Comment by duidae** [comment]
yeah I think we have 2 options, depends on which is more appropriate for users:
1. add a simple tooltip to breadcrumb for notification
2. add a refresh button in table header, but creates duplicate functions as simple click on breadcrumb

![image](https://user-images.githubusercontent.com/25971696/66906358-215ca580-f03a-11e9-9971-efca366e7fdf.png)

**Comment by veggiesaurus** [comment]
putting the refresh button in the table header looks odd, and it has nothing to do with the file name itself, so I'm not sure that's the right place for it. What about to the left of the "home" icon?

**Comment by duidae** [comment]
good idea!
