### ISSUE TITLE
Display cursor values and mean/RMS values in profilers

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#56]
Both spectral and spatial profilers shoud:
- [x] display the value of the cursor along the x axis somewhere in the widget
- [x] display the value of the graph itself at the cursor location somewhere in the widget (by looking up data efficiently
- [x] display the mean and RMS values somewhere in the widget when the "show RMS" toggle is checked

**Comment by veggiesaurus** [comment]
@arusstaylor issue based on your comment from #37

**Comment by duidae** [comment]
![1](https://user-images.githubusercontent.com/25971696/52690770-c13ccd80-2f99-11e9-88f2-28958f398a5c.png)
![2](https://user-images.githubusercontent.com/25971696/52690781-c6018180-2f99-11e9-9875-56ec67542e32.png)
![3](https://user-images.githubusercontent.com/25971696/52690787-c8fc7200-2f99-11e9-867f-c2b0301d7e58.png)

3 approaches corresponding to the requirements above

**Comment by veggiesaurus** [comment]
Graph markers already have the ability to display labels, so lets try reuse that as much as possible (see below). This might need to be extended for rectangular markers. As a starting point, you could set the label of the point region to be something like "<region name>: <value>". For cursor regions, that would look like "Cursor: 1.05e-2". 

Since we already have quite a crowded axis tick label section, due to showing WCS and image coordinates, we should probably avoid cluttering them further by showing cursor values on them. Lets start with re-using and extending the existing marker functionality, and see if that meets science team requirements. We can extend the flexibility of the marker label, changing padding, orientation and so on, to see if that works well with our RMS displays.
![image](https://user-images.githubusercontent.com/592504/52691277-60ae9000-2f9b-11e9-82b5-f54544db11b5.png)

Another possible layout suggested by the science team is shown below, with info being displayed below the graph:
![image](https://user-images.githubusercontent.com/592504/52691642-6ce71d00-2f9c-11e9-89a5-c431b6b1d70f.png)

**Comment by arusstaylor** [comment]
My preference is to have formal place holders for the values when this option is turned on, as in the bottom image.  But maybe I am old fashioned….

Russ

**Comment by duidae** [comment]
current implementation is like below

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25971696/52944085-9394c180-33a9-11e9-98a2-2294282e22a1.gif)

**Comment by arusstaylor** [comment]
This is not friendly to the users.  Having the numbers jump all over the place is terrible.  A fixed place holder below the plot would be much better. 

Russ

**Comment by duidae** [comment]
current implementation is like below: 
![all 1](https://user-images.githubusercontent.com/25971696/52944435-5846c280-33aa-11e9-97c7-cfb50941df7b.gif)

**Comment by veggiesaurus** [comment]
Yes, jumping all over the place is no good. I suggest we try to utilize the space to the left o the x axis label for mean, rms and mouse-over info. 
![image](https://user-images.githubusercontent.com/592504/52945298-14d46000-337a-11e9-9f92-3c7ece6f3232.png)

If we're pushed for space, we could use vertical labels on the cursor marker to display the the value of the graph at the region cursor, but these should not jump around with the value of the data.

**Comment by veggiesaurus** [comment]
I think displaying the mouseover cursor position in an overlay at the bottom left is more consistent with our choice to display the cursor overlay in the image viewer at a fixed position (at the top), rather than following the cursor.

**Comment by arusstaylor** [comment]
agreed.  This is the preferred option.

Russ

**Comment by duidae** [comment]
move to lower left place holder:

![div ogv](https://user-images.githubusercontent.com/25971696/53074519-f57a3600-3525-11e9-953e-3131b3f17d89.gif)

**Comment by kswang1029** [comment]
it might be better to show mean/rms values only when "Show Mean/RMS" is toggled. We could consider to just show cursor: (value_x, value_y). My two cents.

**Comment by veggiesaurus** [comment]
@kswang1029 I agree with the mean/RMS suggestion.

**Comment by duidae** [comment]
result FYI
![result](https://user-images.githubusercontent.com/25971696/53162342-c8518480-3606-11e9-9f0e-2bf22e8c06a7.gif)

**Comment by veggiesaurus** [comment]
I'm happy with this implementation. I think it's unintrusive and provides enough information without distracting the user. 

@duidae and I decided on the following behaviour (shown above):
- When the mouse cursor is not over the profile graph, the cursor value displayed is the value of the region itself (in this case the "cursor" region)
- When the mouse cursor moves over the graph, a grey line is shown, indicating the current mouse position. The cursor value displayed then switches over to the mouse position, rather than the region.
- When the mouse cursor leaves the graph, it switches back to the region value.

@arusstaylor @kswang1029 are you happy with this implementation?

**Comment by kswang1029** [comment]
Yes, sounds good to me. Nice work!

**Comment by veggiesaurus** [comment]
The nomenclature gets tricky when we're dealing with cursor regions, certainly. But I agree that we should have some way to indicate that the value is related to the the _marker_ rather than the mouse position. 

`Data` sounds like a decent alternative, although

**Comment by veggiesaurus** [comment]
fixed in #141
