### ISSUE TITLE
Contour config dialog

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#563]
Rather than relying on the chosen default values for a number of contour configuration options, an separate widget needs to be added for contour rendering. This will be quite similar to the render config widget. 
- [x] Basic widget, with "Apply" and "Clear" buttons
- [x] Number spinner to select number of contour levels (1 - 15)
- [x] Button to "Generate" contour levels based on chosen number of levels and  bounds
- [x] Parameters for generating contour levels based on a number of algorithms 
- [x] Histogram display, allowing users to manually edit min and max bounds
- [x] Allow users to manually edit contour levels by dragging on histogram display
- [x] Allow users to manually edit contour levels by editing a text box

Based on description here: https://docs.google.com/document/d/10nG54sC8XoEKhlGNnTmY6ZOHstF3zeiJi22gBjEvE_k/edit

**Comment by arusstaylor** [comment]
would this widget also allow selection of the image frame to use for the contouring?  

In the Stokes image case how would we be able to render Stokes I contours on the Stokes, Q, U or V planes (or vice versa).

**Comment by veggiesaurus** [comment]
> Where is the image frame for the contours selected? Would this widget also allow selection of the image frame to use for the contouring?
> 
> As an example, in the Stokes image case how would we be able to render Stokes I contours on the Stokes, Q, U or V planes (or vice versa).

@kswang1029 could you provide some detail on this? My understanding is that the overlaid contour cube would have its channel set based on the reference image's channel (aligned using WCS headers). 

This widget is limited to configuring how contours are generated and displayed. For a more detailed configuration of which images are loaded, which channels/Stokes are set for each image, and so on, we will need a "Layers" widget

**Comment by arusstaylor** [comment]
When you interactively drag the lowest contour level marker on the histogram the min should adjust.  Similarly when you drag the highest counter level the max should adjust.  That way the user can graphically select the range of the counters.  Then selecting generate will generate contours between those limits.

**Comment by arusstaylor** [comment]
For the data sources, one should be able to select channel and Stokes if the data sources is cube.  This would allow the user to optionally set a single channel and stokes as the source of the contours.  Useful for instance if I want to plot Stokes Q contours on Stokes I. (For polarisation cubes it would be good to be able to plot polarized intensity contours derived from the Q and U planes).    If the user wishes to overlay contours from the current (displayed) channel and stokes then they would select a "current" option, which should be the default.

**Comment by veggiesaurus** [comment]
> When you interactively drag the lowest contour level marker on the histogram the min should adjust. Similarly when you drag the highest counter level the max should adjust. That way the user can graphically select the range of the counters. Then selecting generate will generate contours between those limits.

This might work nicely if you've selected that particular generator. @kswang1029 what do you think?

**Comment by veggiesaurus** [comment]
> For the data sources, one should be able to select channel and Stokes if the data sources is cube. This would allow the user to optionally set a single channel and stokes as the source of the contours. Useful for instance if I want to plot Stokes Q contours on Stokes I. (For polarisation cubes it would be good to be able to plot polarized intensity contours derived from the Q and U planes). If the user wishes to overlay contours from the current (displayed) channel and stokes then they would select a "current" option, which should be the default.

We've specifically tried to avoid having multiple data sources for a single image, because that adds significant complexity, and has performance implications in terms of which channel is "active". To get around this, we decided to only allow the user to generate contours with the current channel and Stokes, and to allow them to easily "duplicate" an image, which can have independent channel and Stokes values (and can then be overlaid on the original image)

**Comment by kswang1029** [comment]
@veggiesaurus I think for each generator, we can have this "linked" feature between the histogram and text field. For min-max method, we need two bars. For others we need one. In any case, worth a try I think!

**Comment by arusstaylor** [comment]
Only being able to create contours for the "current" images seems very limiting to me.  Not sure what you mean by "duplicate" and image.    What is the process if I want to overlay contours from a different Stokes on the total intensity image?  Or if I want to overlay contours from a different channel?  

Perhaps something for discussion when I get back in Feb.

**Comment by arusstaylor** [comment]
It would be very good to be able to compute and overlay polarized intensity contours based on the Q, U images in a cube.  Should I enter this as a new feature request?

**Comment by veggiesaurus** [comment]
> It would be very good to be able to compute and overlay polarized intensity contours based on the Q, U images in a cube. Should I enter this as a new feature request?

Yes, please file a separate issue for this. I think we should be aiming more general than contours though. For files that have both Stokes Q and U, it would be good to be able to select polarised intensity as one of the "Stokes" values (I know that's not technically correct, but I think you understand what I mean)

**Comment by veggiesaurus** [comment]
> Only being able to create contours for the "current" images seems very limiting to me. Not sure what you mean by "duplicate" and image. What is the process if I want to overlay contours from a different Stokes on the total intensity image? Or if I want to overlay contours from a different channel?
> 
> Perhaps something for discussion when I get back in Feb.

Can you also create an issue to discuss this? It's described in some detail in the proposed image overlay feature [here](https://docs.google.com/document/d/10nG54sC8XoEKhlGNnTmY6ZOHstF3zeiJi22gBjEvE_k/edit#)
