### ISSUE TITLE
splash screen when initializing frontend

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#572]
we keep a splash screen displayed until all the basic components (AST, ZFP, etc) have been loaded by the frontend. This would prevent users from loading an image while one of the libraries is still loading

- [X] UI design
- [X] wire up check points

**Comment by duidae** [comment]
![ss](https://user-images.githubusercontent.com/25971696/70117673-fccb9400-16a0-11ea-800c-96498a4dc97c.png)

currently designed to reveal:
1. logo + app name
2. spinner
3. info from log message

mask will disappear after check points (zfp worker, ast library loaded)

@veggiesaurus @kswang1029 will that be ok?

**Comment by veggiesaurus** [comment]
@duidae that looks good. I'd replace "CARTA Viewer" with something like CARTA Viewer 1.3.0 (build date: 20191204)

some check points:
- ZFP workers (note there are multiple workers)
- AST library
- ZStd library

Note that these may occur in any order, since they're async.

**Comment by kswang1029** [comment]
1. "CARTA Viewer" ---> "CARTA\nCube Analysis and Rendering Tool for Astronomy"
2. please add version number

**Comment by veggiesaurus** [comment]
> 1. "CARTA Viewer" ---> "CARTA\nCube Analysis and Rendering Tool for Astronomy"

Something like this?

```
CARTA 1.3.0 (20191204)
Cube Analysis and Rendering Tool for Astronomy
```

We should probably make the splash screen and about screen consistent in terms of the language they use.

**Comment by kswang1029** [comment]
How about: 
<img width="774" alt="Screen Shot 2019-12-04 at 14 54 06" src="https://user-images.githubusercontent.com/20819712/70119756-f5f35000-16a5-11ea-9dcd-3a98321a2691.png">

**Comment by kswang1029** [comment]
> We should probably make the splash screen and about screen consistent in terms of the language they use.

Agree

**Comment by duidae** [comment]
> > 1. "CARTA Viewer" ---> "CARTA\nCube Analysis and Rendering Tool for Astronomy"
> 
> Something like this?
> 
> ```
> CARTA 1.3.0 (20191204)
> Cube Analysis and Rendering Tool for Astronomy
> ```
> 
> We should probably make the splash screen and about screen consistent in terms of the language they use.

yes I will modify the about tab together
