### ISSUE TITLE
incomplete contour rendering when stop animating

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#579]
frontend: 9a74dbc
backend: 9ca101c

to reproduce the issue:
1) load a large image cube in spatial domain (in my case, 2800x2800)
2) generate contours with 99.9% clip (in my case, mostly noise)
3) enable animation at 5 fps or higher
4) try to stop the animation and we "may" see contours are rendered incompletely. If not, repeat 3) and 4)

![Screen Shot 2019-10-28 at 14 59 10](https://user-images.githubusercontent.com/20819712/67658240-fc4e2800-f993-11e9-8f13-5c31ddfbe0a6.png)

**Comment by veggiesaurus** [comment]
possibly a flow control issue

**Comment by veggiesaurus** [comment]
@kswang1029 can you check if this can still be reproduced?

**Comment by kswang1029** [comment]
tried v4-stable and cannot reproduce the issue. close for now.
