### ISSUE TITLE
inconsistent labels of the coordinate system in the image viewer and in the overlay settings dialogue

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#580]
frontend: 9a74dbc
backend: 9ca101c

1) the label should be consistent. It is "AUTO" in the image viewer and "Native" in the overlay dialogue. Either term is okay I think.

2) When using the button in the image viewer to switch from AUTO to else then back to AUTO, the coordinate system in the overlay dialogue does not return to "Native".

![Screen Shot 2019-10-28 at 15 49 59](https://user-images.githubusercontent.com/20819712/67660878-c3fe1800-f99a-11e9-9da2-0e18f77fab75.png)

**Comment by veggiesaurus** [comment]
I suggest we go with "auto" everywhere.
