### ISSUE TITLE
incorrect "AUTO" coordinate system when loading image as new

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#582]
frontend: 9a74dbc

To reproduce:
1) load set_QA/M17_SWex.fits
2) switch to Galactic coordinate system
3) load set_QA/S255_IR_sci.spw25.cube.I.pbcor.fits as new (not in append mode)
4) now the coordinate system in the image viewer is AUTO but in the overlay dialogue it is "Galactic". The default coordinate system of S255_IR_sci.spw25.cube.I.pbcor.fits should be ICRS as specified in its header.

The desired behavior is to reset the coordinate system to "AUTO" rather than inheriting

**Comment by veggiesaurus** [comment]
So even if the user explicitly specifies a coordinate system, any new files should default to AUTO?

**Comment by kswang1029** [comment]
I would suggest we consider this from wcs “group” perspective. Right now load as new or load as appending is equivalent to having a new wcs group so yes we should reset the coordinate system to “auto”. However when wcs group is in place, loading new images in the same wcs group should keep the coordinate system that user has specified.

**Comment by kswang1029** [comment]
To proceed, I suggest we do the following based on the 1.4 capability:

- if the preference "WCS matching on append" is "None", when an image is loaded or appended, we should use "WCS" which is what is defined in the image header as the initial grid layout.

- if the preference "WCS matching on append" is "Spatial only" or "Spatial and spectral", when an image is loaded (no appending), we should use "WCS" which is what is defined in the image header as the initial grid layout. When an image is appended, we should use the coordinate system as defined or configured as the spatial reference image. 

@veggiesaurus would this sound sensible?
