### ISSUE TITLE
widget cannot be docked or launched by drag-to-dock

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#584]
frontend: 83072ec

widgets cannot be dragged to a desired location.

**Comment by veggiesaurus** [comment]
@kswang1029 it seems to only occur with specific types of widgets. For example, the render config widget works fine, but all the profiler widgets seem to be broken. Can you confirm this?

**Comment by kswang1029** [comment]
confirmed. 🤔

**Comment by veggiesaurus** [comment]
Going back in commits to `dev`, it seems to work in commit cbc838d.

**Comment by kswang1029** [comment]
with the mix page, it seems start from
origin/jason/json_schema 73533f3 2019-10-28 10:48:43 CST

**Comment by veggiesaurus** [comment]
I've just tried my local copy, it's not happening here. I'm pretty sure it's a toolchain issue, rather than something in our code that's changed. 

The issue pops up after the frontent console outputs the following:

```
Uncaught TypeError: Cannot read property 'config' of undefined
    at t.destroyChart (index.js:263)
```

which is part of the ChartJS library.

**Comment by veggiesaurus** [comment]
Chart.js version [2.9.0](https://github.com/chartjs/Chart.js/releases/tag/v2.9.0) and above seem to be crashing. I'll see if I can figure out the root cause and submit a PR to the repo.

For now (and for the 1.2.1 release), we should manually use 2.8.0.
