### ISSUE TITLE
misalignment in the region list widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#594]
![Screen Shot 2019-11-06 at 9 36 42 AM](https://user-images.githubusercontent.com/20819712/68260811-144f3700-0079-11ea-9043-cb2c1e90a806.png)
![Screen Shot 2019-11-06 at 9 36 32 AM](https://user-images.githubusercontent.com/20819712/68260812-144f3700-0079-11ea-84c6-3e7b3861b2dc.png)

**Comment by veggiesaurus** [comment]
@zarda can you look into this> might be best to combine the two actions into one column
