### ISSUE TITLE
double click on region lock or region to view center

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#595]
When no region is selected, double click on the region-lock button or region-to-view-center button results in a region setting dialogue saying "no region selected". It would be good to improve this for UX. It would be ideal to ignore double click for these two buttons if possible.

**Comment by veggiesaurus** [comment]
@zarda can you fix this at the same time as #594?
@kswang1029 it might be easier to just select the double-clicked region?

**Comment by kswang1029** [comment]
That would work too.
