### ISSUE TITLE
support contrast and bias 2D widget in render config

### ISSUE THREAD

**Issue by low-sky** [CARTAvis/carta-frontend#597]
[edit by KSW]
This is a feature request to support a 2D widget so that users can use it to adjust bias and contrast of the image easily. The selected scaling function with bias and contrast should be displayed on top of the histogram plot. 

The widget is something like
<img width="185" alt="Screen Shot 2021-03-30 at 11 41 19 AM" src="https://user-images.githubusercontent.com/20819712/112930449-e32f4500-914c-11eb-935e-adaf1ca09be5.png">
where by dragging the circle in the box, bias (in x direction) and contrast (in y direction) can be defined.

Mockup
![carta_renderConfig_biasContrast_mockup](https://user-images.githubusercontent.com/20819712/112931118-1c1be980-914e-11eb-97ef-7b8a7bd307c6.png)

[early messages]
Jayanne English (U. Manitoba) has requested a new transform / colour table reminiscent of the greyscale3 option in the kvis package.

[Here](https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/goixi4li7oe0fot/Greyscale3.ipynb) is an implementation of the transform function.

The color map itself is just a linear greyscale (i.e., already implemented), but this feature request would presumably create a new transform called logistic with a two parameter function.  Jayanne specifically requests a 2D adjustment tool for controlling the parameters rather that 2 sliders or 2 text entries. 

There is an extra request for a color bar, which I'll open as a separate issue.

**Comment by veggiesaurus** [comment]
@jott3077 has requested something similar in terms of a 2D control for adjusting contrast/bias. I believe the required control can be reused for "greyscale3" as well.

**Comment by veggiesaurus** [comment]
I think we can put this control next to the histogram, and simply hide this control when the widget doesn't have space for it. That would prevent it from cluttering up the interface when users don't need it

**Comment by kswang1029** [comment]
@veggiesaurus @low-sky So this issue is requesting the greyscale3 colormap, the entire render config of kvis, or just a new scaling (transfer) function that can be apply to all other colormaps?

greyscale3
![Screen Shot 2021-03-27 at 6 46 53 PM](https://user-images.githubusercontent.com/20819712/112718265-d8966500-8f2c-11eb-84fb-fbf98c2e3206.png)
kvis render config
![Screen Shot 2021-03-27 at 6 47 00 PM](https://user-images.githubusercontent.com/20819712/112718272-e0eea000-8f2c-11eb-99a1-31df1bb3deb2.png)

@low-sky the "Here" link is not accessible at the moment. could you check?

**Comment by veggiesaurus** [comment]
@kswang1029 we just need a new scaling option (probably with a more sensible name than "greyscale3") that follows the same curve as above. That looks like a sigmoid function to me, so I'm not sure what the two parameters would actually do. Perhaps they would modify the location of the "step" and the sharpness?

**Comment by kswang1029** [comment]
@low-sky @veggiesaurus Let's split the original feature request into two: this one (bias and contrast widget) and this https://github.com/CARTAvis/carta-frontend/issues/1370 (sigmoid scaling function).

**Comment by gillesferrand** [comment]
As per @low-sky request, reposting the notebook where I explored (using Matplotlib) the implementation in Karma = Grayscale3 and in DS9: 
[https://nbviewer.jupyter.org/github/gillesferrand/Matplotlib-customCmaps/blob/master/cmaps%20parametric%20sequential.ipynb](url)
