### ISSUE TITLE
Colour bar display in the raster config widget

### ISSUE THREAD

**Issue by low-sky** [CARTAvis/carta-frontend#598]
Jayanne English (U. Manitoba) has requested some display of colour bar information, i.e. a graph indicated how data values transform to screen colour.  One option would be to add this as a horizontal graph underneath the histogram in the Render configuration.  This is particularly useful for cases where the data transform has a non-linear parameter.

See also #597

**Comment by Kechil** [comment]
Useful but takes up a load of space in render config

**Comment by kswang1029** [comment]
@low-sky @veggiesaurus given that a colorbar has been added to the image viewer and the scaling function is rendered together with the histogram, do you think we still need to add a colorbar to the render config widget? The concern here is space as it is already a busy layout. 

At the moment if we apply different scales (plus different bias/contrast) the colorbar in the image viewer is updated dynamically.


https://user-images.githubusercontent.com/20819712/114487001-6a96b100-9c41-11eb-9638-d6432426f898.mp4

**Comment by low-sky** [comment]
I don't think so.  I think that people fiddling with bias / contrast are just looking at the actual image.

**Comment by kswang1029** [comment]
Ok shall we close this?
