### ISSUE TITLE
beam graphic too big

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#600]
It looks to me like the ellipse in the lower left corner meant to indicate the beam size is too big.  Perhaps the beam sizes in the header are being interpreted as minor axes instead of major axes?

**Comment by kswang1029** [comment]
Could be due to unit (rad vs degree)?

**Comment by arusstaylor** [comment]
Looks like close to a factor of 2 off, so I expect the bmaj e.g.  is being interpreted as semi-major axis when should be major axis.

**Comment by kswang1029** [comment]
I verified with the same test images in different image formats including casa, fits, miriad, and hdf5. All are correct and consistent. Could you paste the header for further diagnostics? (or the image the better)

**Comment by arusstaylor** [comment]
<img width="1851" alt="Screenshot 2019-11-07 at 17 14 00" src="https://user-images.githubusercontent.com/9055533/68401237-118c3900-0182-11ea-8fd3-d93ae9bcb22e.png">

This is a picture of a source in one of the MIGHTEE MeerKAT images.  This is an unresolved source.  The circular region shows the approximate half power width of the source.  The beam graphic at lower left is about twice as large.

**Comment by kswang1029** [comment]
And the header, please? What does it say in the file browser (file info tab and header tab)?

**Comment by arusstaylor** [comment]
File information

Name = 1525613583_sdp_l0_1284.full_pol.COSMOS.300.image.fits
Shape = [6827, 6827, 1, 4]
Number of channels = 1
Number of Stokes = 4
Coordinate type = RA---SIN, DEC--SIN
Image reference pixels = [3414, 3414] 
Image reference coordinates = [150.1192 deg, 2.2058 deg]
Image ref coords (coord type) = [10:00:28.6000, +002.12.21.0000]
Celestial frame = FK5, J2000
Spectral frame = LSRK
Pixel unit = Jy/beam
Pixel increment = -1.50", 1.50"
Restoring beam = 18.00" X 18.00", 0.0000 deg

**Comment by arusstaylor** [comment]
Header
NAXIS = 4
NAXIS1 = 6827
NAXIS2 = 6827
NAXIS3 = 1
NAXIS4 = 4
EXTEND = 
BSCALE = 1
BZERO = 0
BMAJ = 0.005
BMIN = 0.005
BPA = 0
BTYPE = Intensity
OBJECT = COSMOS
BUNIT = Jy/beam
EQUINOX = 2000
RADESYS = FK5
LONPOLE = 180
LATPOLE = 2.20583
CTYPE1 = RA---SIN
CRVAL1 = 150.119
CDELT1 = -0.000416667
CRPIX1 = 3414
CUNIT1 = deg
CTYPE2 = DEC--SIN
CRVAL2 = 2.20583
CDELT2 = 0.000416667
CRPIX2 = 3414
CUNIT2 = deg
CTYPE3 = FREQ
CRVAL3 = 1.61136e+09
CDELT3 = 2.51209e+06
CRPIX3 = 1
CUNIT3 = Hz
CTYPE4 = STOKES
CRVAL4 = 1
CDELT4 = 1
CRPIX4 = 1
CUNIT4 = 
PV2_1 = 0
PV2_2 = 0
RESTFRQ = 1.61136e+09
SPECSYS = LSRK
ALTRVAL = 0
ALTRPIX = 1
VELREF = 257
TELESCOP = MeerKAT
OBSERVER = Sharmila
DATE-OBS = 2018-05-06T13:45:29.283936
TIMESYS = UTC
OBSRA = 150.119
OBSDEC = 2.20583
OBSGEO-X = 5.10922e+06
OBSGEO-Y = 2.0068e+06
OBSGEO-Z = -3.23913e+06
INSTRUME = MeerKAT
DISTANCE = 0
USEWEIGH = 
DATE = 2019-11-06T03:03:00.104000
ORIGIN = CASA 5.5.0-149
Close

**Comment by kswang1029** [comment]
Confirmed that this issue only happens with retina display! The test I did before was using a non-retina display (2K) so I could not reproduce the issue.

**Comment by kswang1029** [comment]
@ajm-asiaa once this is fixed, we need another secret replacement of v1.2.1 packages as this is a critical bug...

**Comment by veggiesaurus** [comment]
> Confirmed that this issue only happens with retina display! The test I did before was using a non-retina display (2K) so I could not reproduce the issue.

@kswang1029 just to confirm: is it 2x too big when using a retina display, or 2x as big when _not_ using a retina display?

**Comment by kswang1029** [comment]
Yes, with a Retina display, the beam is rendered twice bigger than it should be.
