### ISSUE TITLE
support colorbar in the image viewer

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#601]
For publication purpose, a colorbar is needed along the the raster image plot to indicate intensity color mapping.

Colorbar requirements:
- [ ] vertical at the right of the image plot (default)
- [ ] horizontal at the top of the image plot
- [ ] colorbar with value ticks and label (e.g., "Intensity (Jy/beam)")
- [ ] options to show (default) or not show a colorbar

**Comment by veggiesaurus** [comment]
@lmarIT See, it's already an issue 😆 Scheduled for next release

**Comment by veggiesaurus** [comment]
@TienHao could we use a chartjs chart for the ticks and numbers? I can write a WebGL shader to dynamically display the correct colours in real time
