### ISSUE TITLE
long filenames in file browser

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-frontend#606]
We usually have pretty long filenames from the NRAO pipeline, e.g. 

VLASS1.2.ql.T14t21.J135502+143000.10.2048.v1.I.iter1.image.pbcor.tt0.rms.subim

They are difficult to read in the file browser, in particular since the prefix of many images is usually the same and only the suffixes are different. They are unfortunately truncated in the CARTA browser and to see them, the entire window plus the browser window need to be rescaled. 

An improvement would be to have a horizontal scrollbar or to make the divider between file information and fline name adjustable.

**Comment by veggiesaurus** [comment]
The functionality of the file browser is something that slipped through the cracks due to staffing issues (An overhaul was planned and assigned, but never completed). I think the best route going forward would be to replace our basic HTML table with something with a bit more functionality, such as the [BlueprintJS table](https://blueprintjs.com/docs/#table/features).

**Comment by jott3077** [comment]
Would it be easy to add a horizontal scrollbar? I am not familiar with BlueprintJS but for the moment a simple scrollbar would help until we have a more comprehensive solution.

**Comment by jott3077** [comment]
Btw, the listing of the files can take fairly long when there are many files in the directory. I assume the checks if they are known file types takes that long. So I had a few situations where it took longer to get the list of files in a directory than displaying the image itself. 

Maybe the check for known file types could be switched off.

**Comment by veggiesaurus** [comment]
> Btw, the listing of the files can take fairly long when there are many files in the directory. I assume the checks if they are known file types takes that long. So I had a few situations where it took longer to get the list of files in a directory than displaying the image itself.
> 
> Maybe the check for known file types could be switched off.

@pford is working on a backend change where we simply do a magic number check to see if the file type is fits or hdf5 (rather than determining the number of hdu entries) during file lists, this should solve this issue.

**Comment by veggiesaurus** [comment]
> Would it be easy to add a horizontal scrollbar? I am not familiar with BlueprintJS but for the moment a simple scrollbar would help until we have a more comprehensive solution.

We already use the blueprintJS library, and in fact the table package, elsewhere in the codebase, so it probably won't be too much of an issue. But yes, a scrollbar would probably be the easiest solution for this specific issue
