### ISSUE TITLE
ability to provide entire path in 'load file' widget

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-frontend#609]
in the 'file loading widget one can only browse through the file system. Frequently it is more convenient to copy and paste in the path directly, as it saves many clicks. 
Need to make sure though that this does not open a security hole.

**Comment by veggiesaurus** [comment]
This shouldn't be too difficult, considering that we have the ability to browse a specific folder by entering a `folder` parameter as a URL query. I don't think there are any security risks, as this will all be checked by the backend in any case. 

My suggestion would be to put a small "edit" icon after the folder breadcrumbs, which replaces the breadcrumbs with a text input when the user clicks it. 
![image](https://user-images.githubusercontent.com/592504/69606506-ab316280-102b-11ea-8286-064d4154efba.png)

Pressing "enter" on the input would browse to the specified folder, and pressing "escape" would reset. Both enter and escape actions would show the breadcrumbs again. Something along these lines:
![path_entry](https://user-images.githubusercontent.com/592504/69606707-33b00300-102c-11ea-89b3-15b814d179d1.gif)

My feeling is that this should be undertaken at the same time as #606

**Comment by jott3077** [comment]
That looks like a great way to do it!

**Comment by kswang1029** [comment]
Done with #2134
