### ISSUE TITLE
colour to frequency colour maps for stokes widget

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#612]
Most of the canned colour maps go from blue to red, when applied to the Stokes widget this results in the red colour on the Q,U scatter plot mapping to the high frequency end of the band.  Convention is astronomy is for redshift to correspond to longer wavelength (lower frequency) so this is counterintuitive to the user who expects red to mean longer wavelength.  Having an invert colour map option in the settings widget for the Stokes would allow the user to set an appropriate  colour mapping red to blue for increasing frequency.

**Comment by kswang1029** [comment]
Right, we better use "blue" for high frequency/low velocity and "red" for low frequency/high velocity. In fact, why don't we just provide a single colormap ("jet") and invert it when the display axis is frequency? If the display axis is velocity, we just use the normal "jet" colormap.

**Comment by arusstaylor** [comment]
I think it is nice to have a few options for colour map.  I think as you suggest it would be a good idea to choose a sensible default and invert it for frequency plots.

But also enable an invert colour map option in the widget setting.  Good to offer people to ability to depart from the defaults for strange edge cases..

**Comment by panchyo0** [comment]
is this one works? http://carta.asiaa.sinica.edu.tw/frontend/90e7156/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev
The default setting for "Invert Color Map" is true. User can change it in stokes widget settings panel.

**Comment by veggiesaurus** [comment]
> The default setting for "Invert Color Map" is true. User can change it in stokes widget settings panel.

@arusstaylor surely choosing whether to invert the color map is dependent on the image's `CDELT3` value? (and the units)

**Comment by arusstaylor** [comment]
The logic of inversion is determined by the frequency or velocity direction of the channels.  red to blue for  low frequency to high frequency,   blue to red for low velocity to high velocity.

**Comment by veggiesaurus** [comment]
@kswang1029 can we do this easily by checking `CDELT3` and the `CTYPE3`?

**Comment by kswang1029** [comment]
Yes.

If `CTYPE3` is frequency and `CDELT3` > 0 (ie frequency increasing; velocity decreasing), then it is "RED" to "BLUE". 
If `CTYPE3` is frequency and `CDELT3` < 0 (ie frequency decreasing; velocity increasing), then it is "BLUE" to "RED". 

If `CTYPE3` is velocity and `CDELT3` > 0 (ie velocity increasing; frequency decreasing), then it is "BLUE" to "RED". 
If `CTYPE3` is velocity and `CDELT3` < 0 (ie velocity decreasing; frequency increasing), then it is "RED" to "BLUE".

**Comment by veggiesaurus** [comment]
@panchyo0 see above. Should be reasonably easy to test this by accessing headers from `FrameStore`

**Comment by panchyo0** [comment]
@veggiesaurus should we still keep the user setting for "Invert Color Map"?

**Comment by veggiesaurus** [comment]
Yes, because some color maps don't go from red to blue, so the user might want to invert them.
