### ISSUE TITLE
primary colour in stokes widget should switch for dark mode

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#613]
changing to dark mode makes the primary colour traces for Stokes widget disappear.  Need to switch the default automatically to a visible colour for dark mode.

**Comment by veggiesaurus** [comment]
> changing to dark mode makes the primary colour traces for Stokes widget disappear. Need to switch the default automatically to a visible colour for dark mode.

I think this should only apply if the user has not selected a different colour in the settings widget. As soon as they select a different color, we should no longer automatically adjust the color based on light/dark theme preferences. 

@panchyo0 can you look into this? Maybe the easiest solution is to use `"default"` as the default colour setting, and then automatically determine which shade of the default color to use (based on the theme) if the widget's colour is `"default"`. 

edit: perhaps this is already done?

**Comment by veggiesaurus** [comment]
@arusstaylor which version are you testing? in the `dev` branch (as seen on carta-testing.idia.ac.za), this seems to be a non-issue:

![stokes_lines](https://user-images.githubusercontent.com/592504/69734156-32b7c800-1137-11ea-9512-b0b645b9c719.gif)

**Comment by arusstaylor** [comment]
I think the issue was that I had selected a dark colour in the light mode and when I switched to dark mode it didn't show up.  I guess this should be classed as user error?

**Comment by veggiesaurus** [comment]
> I think the issue was that I had selected a dark colour in the light mode and when I switched to dark mode it didn't show up. I guess this should be classed as user error?

I think the only way to improve that situation is to make sure the colours in the swatches in the colour picker look ok in both light and dark mode.

**Comment by panchyo0** [comment]
@veggiesaurus only colour #293742 will cause this problem in the swatches. Should we remove this one? it not really help since user can customer their own colour.

**Comment by arusstaylor** [comment]
I think this is a non issue.  We should just close this.

**Comment by veggiesaurus** [comment]
> @veggiesaurus only colour #293742 will cause this problem in the swatches. Should we remove this one? it not really help since user can customer their own colour.

I think it's fine to leave it in, since it works fine in light mode. 



> I think this is a non issue. We should just close this.

agreed.
