### ISSUE TITLE
NaN appears in numeric input

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#615]
when entering "-1" to various numeric inputs in current CARTA, NaN appears. On ubuntu platform, it can be reset by entering a normal number, however, on Mac, users could be totally stucked.

![image](https://user-images.githubusercontent.com/25971696/69707159-2d0cb300-1134-11ea-8050-099ff3e9e1a2.png)

**Comment by veggiesaurus** [comment]
I can't reproduce this bug. Which specific inputs does it occur for? And which browser?

**Comment by kswang1029** [comment]
Try typing “-“ with chrome on Mac

**Comment by veggiesaurus** [comment]
Can't you just press up or down on the number input buttons to get it working again?

**Comment by kswang1029** [comment]
That doesn’t work, either. Once it becomes NaN, the only solution is pressing the reset default button.

**Comment by veggiesaurus** [comment]
I've tried that in both Chrome and Safari. Could this be related to a specific version of blueprintJS? @kswang1029 which build, browser and input are you able to reproduce this on?

**Comment by veggiesaurus** [comment]
this is definitely related to the build version :thinking: On our CARTA servers, this doesn't show up in the latest `dev` branch, but I can see the issue on the mix 'n match page

**Comment by kswang1029** [comment]
This happens and is reported by some v1.3 beta testers. It would be good if we can find a solution for v1.3.

**Comment by veggiesaurus** [comment]
I can now reproduce this with almost every _NumericInput_ input field :disappointed: This seems to have crept into a newer version of BlueprintJS

edit: this happens with 1.2 as well, in the preferences dialog
