### ISSUE TITLE
Catalog overlay: Catalog widget

### ISSUE THREAD

**Issue by panchyo0** [CARTAvis/carta-frontend#620]
- [x] Catalog widget reads catalog file (user selected file) data and display preview data as table.

- [x] Catalog widget display user filter options. like column header, filter, overlay options, table filter in [mock-up](https://docs.google.com/document/d/1mD9cZri8S25hm6VTPehEXUXA_kDptlcr41ktbEZQv1k/edit#heading=h.ei4voydom8t8)

- [x] Catalog widget sends filter request once user click filter.

- [x] User clicks load to draw catalog data into image viewer (overlay discussion #586 )

**Comment by panchyo0** [comment]
blueprintJS table Table.columnWidths breaks column resizing after version 3.8.0 [https://github.com/palantir/blueprint/issues/3833](https://github.com/palantir/blueprint/issues/3833)

**Comment by veggiesaurus** [comment]
can we stick to version 3.8.0?

**Comment by panchyo0** [comment]
@veggiesaurus  version "3.8.0" show up an error message
<img width="2234" alt="Screen Shot 2020-01-08 at 4 33 19 PM" src="https://user-images.githubusercontent.com/22226157/72025229-acfa6280-3234-11ea-9cdf-ed6878a04b20.png">
The most stable version I found is 3.7.1, but it also having [bug](https://github.com/palantir/blueprint/issues/3779) when user pinned widget. If table overflow in one of horizontal or vertical, table will not render correctly until user scroll. Downgrading the version into 3.5.0 will not solving the problem for us.
