### ISSUE TITLE
jump to frame when clicking on spectral profiler 

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-frontend#628]
It would be a good enhancement to have an option to click somewhere in the spectral profiler and the image animator would jump to the corresponding channel map and show it in the main window.

**Comment by pford** [comment]
I thought the same thing, but it says "the **image animator** would jump to...". The animator ignores input from the spectral profiler.

**Comment by arusstaylor** [comment]
I thought this was already implemented. Just left click.
