### ISSUE TITLE
Remove FITS hdus from file list and add to file info

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#633]
create corresponding frontend issue for https://github.com/CARTAvis/carta-backend/issues/357

**Comment by duidae** [comment]
@veggiesaurus  @kswang1029  would this implementation be ok?
![blr2o-562k2](https://user-images.githubusercontent.com/25971696/101459676-83c9e100-3973-11eb-981f-95fb1a5bff7b.gif)

**Comment by kswang1029** [comment]
This looks nice! In addition to the hdu index, shall we add the name of the hdu in the dropdown menu directly? Users would easily identify which is which without trial and error by reading the info panel.

**Comment by veggiesaurus** [comment]
> @veggiesaurus @kswang1029 would this implementation be ok?
> ![blr2o-562k2](https://user-images.githubusercontent.com/25971696/101459676-83c9e100-3973-11eb-981f-95fb1a5bff7b.gif)

It seems a bit unusual to have a dropdown in the tab headers, but I think it works rather nicely. I agree with @kswang1029 that we nee the name of the HDU as well

**Comment by duidae** [comment]
@kswang1029 you mean like this, right? copied from release 1.4

![image](https://user-images.githubusercontent.com/25971696/101598244-d4ecda00-3a32-11eb-8abe-0201232c8ee4.png)

**Comment by kswang1029** [comment]
@duidae Better just like "1: image", "6: error", and "7: coverage". "HDU" and "ExtName" are redundant.

**Comment by veggiesaurus** [comment]
> @duidae Better just like "1: image", "6: error", and "7: coverage". "HDU" and "ExtName" are redundant. 

Do you think we need the "HDU List" label? Might also be redundant. Not sure how long HDU names can be, but we probably want to be as compact as possible

**Comment by kswang1029** [comment]
Maybe simply “HDU”? “list” is implicit with the dropdown menu.
