### ISSUE TITLE
[question] velocity and frequency in cursor info bar 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#634]
question to frontend developers: do we adopt "SPECSYS" (e.g., BARYCENT, LSRK, etc) in the calculations of velocity and frequency with AST for the cursor info bar? In a test case, I see identical velocity and frequency even if SPECSYS is different.

test images
casa: set_HD163296/HD163296_CO_2_1.image (LSRK)
miriad: set_HD163296/HD163296_CO_2_1.image.miriad (BARY)

(related to issue: https://github.com/CARTAvis/carta-backend/issues/377)

**Comment by veggiesaurus** [comment]
Looking at the velocity to frequency calculation, we aren't using AST, but are just using `refFreq * (1.0 - velocity / c);`

The reference frequency determined only from the `RESTFRQ` header, but this is probably not sufficient. There should be a way to easily convert the spectral values using AST though, which should take into account all the headers

**Comment by kswang1029** [comment]
I see. We better include all relevant headers.

**Comment by veggiesaurus** [comment]
@duidae can you look into this for 1.4? I thikn we can just use the spectral conversion

**Comment by duidae** [comment]
Just checked, I think I've fixed a few days ago. @kswang1029  please have a look, thanks.

![image](https://user-images.githubusercontent.com/25971696/87028228-e70ee600-c210-11ea-9729-0a94df18c4f9.png)

![image](https://user-images.githubusercontent.com/25971696/87028329-10c80d00-c211-11ea-8988-7da25cef562c.png)

**Comment by duidae** [comment]
duplicate #803

**Comment by kswang1029** [comment]
velocity and frequency are displayed correctly.
