### ISSUE TITLE
toolbar for dialogs

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#642]
we should have a separate "dialogs" toolbar at the top near the widgets. We can have buttons for preferences, file info, overlay config, contour config and so on.

**Comment by veggiesaurus** [comment]
I suggest we combine this issue with a slight refactoring of `AppStore`, moving all dialog-related actions and properties to a new `DialogStore`.

@TienHao, could you do this? It should be reasonably straightforward to implement.

**Comment by TienHao** [comment]
@veggiesaurus, sure! I can do this.
