### ISSUE TITLE
conversion of spectral axis (x), such as velocity frame, frequency, velocity, optical/radio definition, etc.(c.f. casaviewer)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#647]
sub task of epic #643 

The spectral profile widget should provide conversions in the spectral axis including
- velocity <-> frequency <-> wavelength <-> channel
- velocity frames, such as LSRK, TOPO, etc.
- velocity definition: optical or radio

The conversion should be done either with AST at frontend or with casacore/casacode at backend.

**Comment by veggiesaurus** [comment]
The conversion process has to take place each time the ticks are drawn for the graph, so I don't think its feasible to use casacore for this, it will have to be AST.

**Comment by kswang1029** [comment]
reference:
"astSpecAdd" at p.372 of AST lib manual (http://starlink.eao.hawaii.edu/starlink/AST?action=AttachFile&do=get&target=sun211.pdf

**Comment by veggiesaurus** [comment]
One of the complications here is that we currently strip the `CTYPE3`, `CDELT3`, `CRVAL3` and `CRPIX` headers from the list of headers before passing them to AST to create an `AstFrameSet` object. This is done for simplicity's sake, because otherwise AST creates a compound 2D+1 mapping, which gets complex to work with. 

Our options are to revert to this 2D+1 mapping, or create a separate 1D AST mapping for spectral transforms. I think that might be easier. If we strip out all the `CTYPE` etc headers except the third axis, and then rename those to `CTYPE1` etc, that might do it. That would keep spatial and spectral transformations nicely separate.

**Comment by duidae** [comment]
kk @veggiesaurus  thanks for the info!

**Comment by kswang1029** [comment]
@duidae @veggiesaurus I did a more systemic comparison of the spectral conversions from CASA (with casacore(?)) and CARTA (with AST). The results are in the attached pngs. The errors in BARY and TOPO conversions are larger (for frequency it is about 5 MHz and for velocity it is about 0.01 km/s). Not sure why but probably this is fine for science (I will check with the science team).

velocity is in km/s, frequency is in GHz, and wavelength is in millimeter. 
Top panel is a plot of two spectra from casa and carta, respectively.
Bottom panel is a difference between casa and carta conversion (x: channel, y: casa-carta). 
![opticalvelo_TOPO](https://user-images.githubusercontent.com/20819712/75091699-54e0ab00-55ab-11ea-9716-a69ab3828f68.png)
![opticalvelo_BARY](https://user-images.githubusercontent.com/20819712/75091701-57430500-55ab-11ea-89ef-f2b3533d3353.png)
![opticalvelo_LSRD](https://user-images.githubusercontent.com/20819712/75091702-58743200-55ab-11ea-8287-aad0e517ecbc.png)
![opticalvelo_LSRK](https://user-images.githubusercontent.com/20819712/75091703-590cc880-55ab-11ea-9e66-7b7ce6573346.png)
![radiovelo_TOPO](https://user-images.githubusercontent.com/20819712/75091704-590cc880-55ab-11ea-94b4-668a12f4afb7.png)
![radiovelo_BARY](https://user-images.githubusercontent.com/20819712/75091705-5a3df580-55ab-11ea-9e55-4ba53f51cf73.png)
![radiovelo_LSRD](https://user-images.githubusercontent.com/20819712/75091706-5ad68c00-55ab-11ea-9dac-bf3c1c50e4e6.png)
![radiovelo_LSRK](https://user-images.githubusercontent.com/20819712/75091708-5ad68c00-55ab-11ea-8c35-dd21a52392a5.png)
![freq_TOPO](https://user-images.githubusercontent.com/20819712/75091709-5b6f2280-55ab-11ea-9bc8-1e3f006addfc.png)
![freq_BARY](https://user-images.githubusercontent.com/20819712/75091710-5b6f2280-55ab-11ea-8adc-4cbfb4566ccd.png)
![freq_LSRD](https://user-images.githubusercontent.com/20819712/75091711-5c07b900-55ab-11ea-9fba-5234fa6e07ad.png)
![freq_LSRK](https://user-images.githubusercontent.com/20819712/75091713-5ca04f80-55ab-11ea-8ce0-e777c141d69a.png)
![wavelength_TOPO](https://user-images.githubusercontent.com/20819712/75091714-5d38e600-55ab-11ea-98b3-b06e51ac53ce.png)
![wavelength_BARY](https://user-images.githubusercontent.com/20819712/75091715-5d38e600-55ab-11ea-9ea2-e86001167f36.png)
![wavelength_LSRD](https://user-images.githubusercontent.com/20819712/75091716-5dd17c80-55ab-11ea-8ae6-bfc85fefd585.png)
![wavelength_LSRK](https://user-images.githubusercontent.com/20819712/75091717-5e6a1300-55ab-11ea-9d7e-f23f361b9e34.png)
![air_wavelength_TOPO](https://user-images.githubusercontent.com/20819712/75091718-5f02a980-55ab-11ea-9037-ad82ec57984d.png)
![air_wavelength_BARY](https://user-images.githubusercontent.com/20819712/75091719-5f9b4000-55ab-11ea-8484-e2d122b86982.png)
![air_wavelength_LSRD](https://user-images.githubusercontent.com/20819712/75091720-6033d680-55ab-11ea-957d-fd3bef3bff83.png)
![air_wavelength_LSRK](https://user-images.githubusercontent.com/20819712/75091721-6033d680-55ab-11ea-8fc6-8e386da15286.png)

**Comment by duidae** [comment]
thanks for the info, I think maybe we can try some experiments with casacore/AST to study the difference, and probably figure out the theory of TOPO conversion, so that we can find out what is missing in AST conversion
