### ISSUE TITLE
unit conversion of intensity axis (y) in the spectral profile widget (c.f. casaviewer)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#648]
sub task of epic #643 

The spectral profile widget should provide the ability of unit conversion in the y axis.
The most common conversion is Jy/beam <-> K.

The complexity here is some units under certain conditions cannot be converted to other units. For example, if an image with K as unit but does not have information of beam size and frequency, we cannot convert K to Jy/beam.

A full set of units and their conversions will be provided later (@kswang1029).

**Comment by veggiesaurus** [comment]
@kswang1029 it would be useful if you could look into the AST documentation to see if we can use it for these conversions as well

**Comment by kswang1029** [comment]
@veggiesaurus will do

**Comment by kswang1029** [comment]
@veggiesaurus checked the AST manual and I think there is no such conversion tools for intensity. It does have conversion tools for the spatial and spectral axes. We will need to implement the intensity conversion ourselves. Should not be too difficult. I will provide a detailed doc.

**Comment by duidae** [comment]
@kswang1029 can we have some preliminary conversion formulas for beginning? thanks.

**Comment by kswang1029** [comment]
> @kswang1029 can we have some preliminary conversion formulas for beginning? thanks.

I forgot to add the req doc. Sorry. https://docs.google.com/document/d/1dK6iaFjGYNbyHX42HR9vnxNMIiMlMG0-tGYKePwBo5A/edit Please have a look and let me know if there are unclear parts. The most common conversion pair is Jy/beam <--> Kelvin
