### ISSUE TITLE
profile fitting capability in the spectral profile widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#649]
sub task of epic #644 

The spectral profile widget should provide the capability for user to fit profiles with a given function such as Gaussian. Multiple components should be allowed. Fitting parameters should be fixable to assist convergence. 

The exact fitting can happen at frontend or backend, depending on which performance and other implementation details. If we decide to use backend, this issue should be migrated to the backend repo.

**Comment by Kechil** [comment]
Post - v1.4

**Comment by Kechil** [comment]
This is a feature that needs requirements from science team.

**Comment by kswang1029** [comment]
Requirements:

provide gaussian function as a start. Need science team input for other possible profiles (Voigt, Lorentizan, line spread functions (e.g., sinc)).
capability to set initial guess of fitting parameters
capability to fix part of fitting parameters
capability to fit multiple profiles in a single shot
export fitting results in a text file

**Comment by kswang1029** [comment]
I have created a set of test cubes with different total number of channels and with different spectral profiles at different positions. Images are available at `set_test_profile_fitting`.
