### ISSUE TITLE
overplotting labels of molecular transitions by querying molecular database or input text file

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#650]
sub task of epic #644 

The spectral profile widget should allow overplotting molecular transitions as labels. The molecular data can be from online molecular database (e.g. spatalogue) or from a text file with a certain format.

There should be a text field for users to define velocity shift or redshift so that molecular transitions are shifted accordingly.

**Comment by duidae** [comment]
duplicate #863
