### ISSUE TITLE
channel smoothing in the spectral profile widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#651]
sub task of epic #644 

The spectral profile widget should provide the following profile smoothing options:
- hanning
- boxcar
- binning

The smooth profile should be displayed together with the original profile in different colors.

**Comment by veggiesaurus** [comment]
there's a fair bit of complexity to this, because each smoothing type may have different parameters, and we will need an option to show only the smoothed profile as well.
