### ISSUE TITLE
Frontend should not display cube histogram warning if file has CUBE_HISTOGRAMS feature flag set

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#655]
The backend will not take a long time to generate cube histograms for HDF5 files. For files with the `CUBE_HISTOGRAMS` file feature flag set, the frontend should not display the cube histogram warning. The progress bar should still be displayed in off chance that the HDF5 file's metadata is incorrect.

**Comment by veggiesaurus** [comment]
@kswang1029 I think I fixed this in one of the contour branches. Can you check this?

**Comment by kswang1029** [comment]
yes, it is in the dev branch now. 👍
