### ISSUE TITLE
remove comment in SPECSYS header

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#662]
similar to #632, we need to remove comment in SPECSYS so that the cursor info bar can be displayed properly.

![Screen Shot 2020-01-03 at 2 59 16 PM](https://user-images.githubusercontent.com/20819712/71710982-c157ed00-2e39-11ea-93e3-3662b18b0527.png)

@duidae could you help?

**Comment by duidae** [comment]
kk
