### ISSUE TITLE
[question] START_ANIMATION and SET_IMAGE_VIEW 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#665]
When we start animation, there appears to be a half pixel offset in the setup of image bounds. Is that intended for some reasons?
<img width="498" alt="Screen Shot 2020-01-07 at 09 58 41" src="https://user-images.githubusercontent.com/20819712/71862437-ca480780-3134-11ea-897d-5eda004abd66.png">

**Comment by veggiesaurus** [comment]
it might have been related to a rounding issue, but I can't quite remember. I'd imagine that #625 would resolve this issue though.

**Comment by veggiesaurus** [comment]
@kswang1029 is this resolved?

**Comment by kswang1029** [comment]
there is no more SET_IMAGE_VIEW after START_ANIMATION. So I think we can close this now.
