### ISSUE TITLE
edge pixels artifacts on the right side

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#666]
could this due to #623 ?
![IRAS_17150-3224_sci spw27 cube I manual image pbcor fits-image-2020-1-8-16-53-22](https://user-images.githubusercontent.com/20819712/71964260-32cbdd00-3238-11ea-96f8-b0f24c4f46a7.png)

The requested tiles (original image is 2800 pixel x 2800 pixel) are
![Screen Shot 2020-01-08 at 16 50 38](https://user-images.githubusercontent.com/20819712/71964071-dd8fcb80-3237-11ea-8d71-a91941bc8ad1.png)

Also a question: why it requested 9 tiles (0,0) to (2,2), instead of 16 tiles from (0,0) to (3,3)?

**Comment by kswang1029** [comment]
weirdly I cannot reproduce it anymore...... Close for now and I will keep this in mind.

**Comment by kswang1029** [comment]
OK, it shows up _when_ javascript console is enabled.... even more weird....

**Comment by kswang1029** [comment]
It shows up and this time no js console is enabled!!!
 I suspect it is there for a while but with the default NaN color it is harder to see. 

Attached (generated with "export as png" button) is the case with transparent NaN.

![M83 LSB_L pbcor fits-image-2020-6-5-10-37-50](https://user-images.githubusercontent.com/20819712/83830997-0ea5f680-a719-11ea-97a3-6c641ada2611.png)

with different zoom levels, the artifacts change.
![Jun-05-2020 10-44-21](https://user-images.githubusercontent.com/20819712/83831333-c3401800-a719-11ea-8b28-3091090d2d97.gif)

**Comment by kswang1029** [comment]
More examples:

Right edge:
<img width="958" alt="Screen Shot 2020-06-18 at 10 57 52 AM" src="https://user-images.githubusercontent.com/20819712/84973031-aca2b380-b152-11ea-9918-bf1a1745e14f.png">

Top edge:
<img width="960" alt="Screen Shot 2020-06-18 at 10 57 01 AM" src="https://user-images.githubusercontent.com/20819712/84973039-b0363a80-b152-11ea-873c-04483128bce1.png">

**Comment by veggiesaurus** [comment]
@kswang1029 this was bugging me, so I tried to fix it. Can you see if `angus/666_edge_pixels` solves the problem?
