### ISSUE TITLE
Improve contour dialog generators' default paremters

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#671]
The contour dialog's generators work as expected, but some more testing needs to be done to ensure that the default parameters are sensible and useful.

**Comment by kswang1029** [comment]
I tried various kinds of images with different histogram distributions. Currently I think 
Percentages-ref.value
	reference = upper bound of 99.9% clip
	lower% = **20**
	upper% = 100
works better in general.

For the current default values of 
Min-max-scaling
	min = lower bound of 99.9% clip
	max =upper bound of 99.9% clip
	scaling = linear
works fine except histograms resembling noise. 

Start-step-multipler and Mean-sigma-list work fine in general now with their current defaults. 

I was wondering maybe we can use skewness of the histogram as a reference to set default parameters but it might be overkilled.

**Comment by kswang1029** [comment]
ps. currently the level list is empty by default. Is it possible to trigger "generate" by default, so that users just need to click "apply" to see contours?

**Comment by kswang1029** [comment]
currently, the percentages-ref.value method only allows up to 100%. We could give this more freedom to allow more than 100%. For example, with reference = 10, we can set lower = 100% and upper 500% with 5 levels to get 10, 20, 30, 40 and 50.

**Comment by veggiesaurus** [comment]
@kswang1029 do you have final settings for this?

**Comment by kswang1029** [comment]
@veggiesaurus I tried again with some images with different characteristics (most noisy, small feature, large feature, etc.) and think the current defaults are good enough in general, except the following
<img width="644" alt="Screen Shot 2020-02-25 at 12 06 26 PM" src="https://user-images.githubusercontent.com/20819712/75214489-baf64980-57c8-11ea-9952-d59d6bbbf1df.png">
We should try to have lower default as 20%. The current 60% usually creates quite some redundant contours which do not provide extra information.
