### ISSUE TITLE
Improve contour icon

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#676]
As suggested by @low-sky, we should change the contour icon to make it clearer. At the moment, it's more of a heatmap than a set of contours.

The set of existing BlueprintJS icons can be found [here](https://blueprintjs.com/docs/#icons). We should try to use one of the existing ones, as it otherwise requires some graphic design work, and needs to be made consistent with the rest of the UI. 

We could also consider creating an icon from scratch and adding that to BlueprintJS as a pull request, as the wider community using Blueprint would probably benefit from it.

**Comment by kswang1029** [comment]
I checked the existing BlueprintJS icons and think none of them is ideal representation of contours. Likely we need to make our own. What are the requirements of an icon (size, svg?..., etc.)?

**Comment by kswang1029** [comment]
would this work?
<img width="62" alt="Screen Shot 2020-01-16 at 11 10 23" src="https://user-images.githubusercontent.com/20819712/72489987-d3318b00-3850-11ea-9b5c-e76427926f73.png">

**Comment by veggiesaurus** [comment]
> would this work?
> <img alt="Screen Shot 2020-01-16 at 11 10 23" width="62" src="https://user-images.githubusercontent.com/20819712/72489987-d3318b00-3850-11ea-9b5c-e76427926f73.png">

That looks pretty good. I'm wondering if we shouldn't try to just take the SVG source for the "heatmap" icon and adjust it to something like you've just made, and then send a PR to blueprintJS

**Comment by kswang1029** [comment]
I can give a try.

**Comment by veggiesaurus** [comment]
It looks like BlueprintJS uses SVG or CSS fonts for icons, and the SVG support is deprecated. We could use a custom SVG as a stopgap, but we should eventually migrate to a custom CSS font.

Edit: Nevermind, I have that exactly the wrong way around :laughing:  SVG is the preferred method

**Comment by veggiesaurus** [comment]
@TienHao Can you work on this with @kswang1029? You can just use a custom SVG by passing it as the `icon` argument to an `Icon` element, as shown here: https://blueprintjs.com/docs/#core/components/icon

You can start this before we've finalised the icon itself, and just update the SVG. I'd suggest you make a separate class for holding all our custom SVG icons in one place.

**Comment by kswang1029** [comment]
Just as a note about some ideas for the contour icon:
<img width="61" alt="Screen Shot 2020-01-16 at 14 10 59" src="https://user-images.githubusercontent.com/20819712/72499390-a8553000-386c-11ea-8c81-0510d238d685.png">
<img width="62" alt="Screen Shot 2020-01-16 at 11 10 23" src="https://user-images.githubusercontent.com/20819712/72499391-a8edc680-386c-11ea-8f2c-f34a76929e3d.png">

**Comment by kswang1029** [comment]
@TienHao Could you try these two examples to see which one is best fit?

**Comment by veggiesaurus** [comment]
The raw font itself is black, rather than grey, so we should follow that approach, I think (and I assume the styling will be applied by CSS)

https://github.com/palantir/blueprint/blob/develop/resources/icons/16px/heatmap.svg
