### ISSUE TITLE
adding context-sensitive in-app help

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#679]
Currently the only way to access to the online user manual is via the "help" menu. For better UX, we should also provide in-app help manual with a question mark icon. For widgets, it should be in the header, next to the "cog". For dialog, it should be next to the close button (X). Once the help button is hit, we can use the blueprint "drawer" to show in-app help. For example, https://blueprintjs.com/docs/#core/components/drawer

The content for each widget and dialogue is TBD (@kswang needs to think about the maintainability of this in-app help and the online user manual).

**Comment by kswang1029** [comment]
A crazy idea: if the position of the drawer can be determined dynamically based on the location of widget/dialogue so that the drawer will not block the widget/dialogue, that would be fantastic!

**Comment by veggiesaurus** [comment]
> A crazy idea: if the position of the drawer can be determined dynamically based on the location of widget/dialogue so that the drawer will not block the widget/dialogue, that would be fantastic!

That shouldn't be _too_ hard. We can have a function that determines the best position (left, right) based on the bounding box of the widget. But the question is whether that would annoy users or not

**Comment by veggiesaurus** [comment]
Setting estimate to 3 for the actual technical work. Adjustments to the docs themselves can be tracked on the doc repo, I suppose

**Comment by kswang1029** [comment]
> That shouldn't be too hard. We can have a function that determines the best position (left, right) based on the bounding box of the widget. But the question is whether that would annoy users or not

indeed, let's not do that for now. "Right" should fit the common UX?
