### ISSUE TITLE
Feature request: zoom toggle

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-frontend#684]
It would be cool to have a toggle in the preferences for the behaviour of zoom switching between zooming in on the mouse and zooming in on the central pixel.

**Comment by veggiesaurus** [comment]
This is pretty easy to implement (~2 lines in `FrameStore` and some boilerplate code in the preference dialog). @kswang1029 any suggestions for who to assign to this?

**Comment by kswang1029** [comment]
@TienHao could you investigate this?

**Comment by TienHao** [comment]
I can take this one.

**Comment by veggiesaurus** [comment]
@TienHao just keep @duidae in the loop in terms of the preference schema changes
