### ISSUE TITLE
Scroll to right for large file names

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-frontend#685]
In the file browser, long file names are cut off, and there is no ability to scroll from left to right. It would be good if this could be implemented, since often the first part of different files are the same.

**Comment by kswang1029** [comment]
Would it be a good time to switch to blueprint table which allows column resizing and sorting?

**Comment by veggiesaurus** [comment]
> Would it be a good time to switch to blueprint table which allows column resizing and sorting?

Yes. I think we should do that at the same time as a number of improvements to the file browser. Perhaps an epic for 1.4?

**Comment by kswang1029** [comment]
sounds good 👍
