### ISSUE TITLE
Feature request: sort by date added

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-frontend#686]
In the file browser, the files are sorted alphabetically, and it becomes difficult to find files when you have several tens of them. It would be nice to be able to sort by date added (or perhaps date modified, but less ideal) so you can easily find the recent file you're looking for. It would even be nice to be able to sort by file type / extension, so CASA, FITS and HDF5 files could be separated.

**Comment by veggiesaurus** [comment]
Transferred to frontend, but may need a small ICD change and some support on the backend, so marking it as an estimate of 3.

**Comment by lh-astro** [comment]
I agree with Jordatious. Being able to sort by some sort of timestamp would be very helpful.

**Comment by Jordatious** [comment]
Is that Lennart? This out to come under #692

**Comment by veggiesaurus** [comment]
Yup, it's listed as an issue in the #692 epic.

I should point out that this needs to be implemented across the board, for images, regions and catalogs.

**Comment by veggiesaurus** [comment]
Incoming PR should sort this issue out. Displayed date is based on the file modification timestamp. If the timestamp is from _today_, the time is displayed. If older, only the date is displayed. This is similar to the default behaviour in gnome/ubuntu

![image](https://user-images.githubusercontent.com/592504/86412209-cac5f300-bcbe-11ea-8646-19c984cd9eef.png)
