### ISSUE TITLE
contours 'apply' button 

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-frontend#689]
It's not a bit confusing why some contour actions need 'apply' (like block) and others don't (like style). Maybe they should all either need to press 'apply' or not. maybe it is just a matter of getting used to it.

**Comment by veggiesaurus** [comment]
I'm not convinced that this is much of an issue. There's a clear divide between styling, which is applied instantly, with no new data or calculations required, and other contour configuration options (e.g. levels or smoothing), which require contours to be re-generated and streamed.

One option would be to move the "apply" button into each tab, but that might confuse matters as well.

**Comment by kswang1029** [comment]
will be discussed in usability review.
