### ISSUE TITLE
File browser improvements for v1.4

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#692]
Epic for tracking a variety of frontend-based file browser improvements for the CARTA 1.4 release

One of the main tasks is to migrate the file browser to [@blueprint/table](https://blueprintjs.com/docs/#table). This should probably be done first, before tackling the rest of the issues

**Comment by kswang1029** [comment]
Is it possible (in terms of time pressure) to use tooltip to show full file name for v1.3?

**Comment by veggiesaurus** [comment]
> Is it possible (in terms of time pressure) to use tooltip to show full file name for v1.3?

Yes, that would be pretty straightforward (I'd estimate it as a `1`). Will you create an issue for it?
