### ISSUE TITLE
Show correct beam for multi-beam images

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-frontend#697]
A FileInfoExtended computed entry in OpenFileAck shows the median beam for multi-beam images.

The beam table will be sent as a new field in OpenFileAck as shown in this [doc](https://docs.google.com/document/d/1nFa1OoMKz4a0i-VId6_1qXjkzxq1U7W6oPDen4JxjUk/edit), so that the correct beam can be shown for each channel and stokes.

**Comment by veggiesaurus** [comment]
@veggiesaurus and @pford to go over the ICD changes (might make more sense to use a map)
