### ISSUE TITLE
missing tool buttons in the image viewer

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#700]
Sometimes the tool buttons in the image viewer do not show up when hovering over. Only tooltip appears. We need to move the cursor to re-enter the image viewer to see the buttons.

<img width="858" alt="Screen Shot 2020-01-31 at 9 57 48 AM" src="https://user-images.githubusercontent.com/20819712/73525959-79b08b00-4410-11ea-8cc7-83c58989b504.png">

**Comment by veggiesaurus** [comment]
This has been really bugging me recently. @kswang1029 any idea when it appeared?

**Comment by kswang1029** [comment]
this is one reproducible case:
![Jan-31-2020 10-21-00](https://user-images.githubusercontent.com/20819712/73527517-7c60af80-4413-11ea-856f-b2b28cc2b1f2.gif)

It might be due to the initial position of the cursor. If we use the load button to load an image, and usually the cursor will be outside the image viewer, we are fine. However if we use double-click to load an image and the position of the cursor might be inside the image viewer, we will see the issue.
