### ISSUE TITLE
beam size of non-spatial-reference image on screen does not scale correctly with zoom level

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#710]
beam size of non-spatial-reference image on screen does not scale correctly with zoom level

reference (correct)
<img width="856" alt="Screen Shot 2020-02-05 at 09 14 28" src="https://user-images.githubusercontent.com/20819712/73823143-f7510e00-47f7-11ea-8095-2bc42128ce4e.png">

non-reference (problem)
<img width="857" alt="Screen Shot 2020-02-05 at 09 14 37" src="https://user-images.githubusercontent.com/20819712/73823161-00da7600-47f8-11ea-8739-8a7646d41505.png">

**Comment by veggiesaurus** [comment]
I should have checked this more carefully... now it updates, but doesn't take into account the resolution differences between images
