### ISSUE TITLE
support PI (polarized intensity) and PA (polarized angle) in the Stokes dropdown

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#714]
In addition to the standard Stokes parameters I, Q, U, and V, we should provide additional quantities such as PI (polarized intensity),  PA (polarized angle) and Fractional PI in the same list for better UX.

This includes:
- [ ] spectral profiles
- [ ] contours
- [ ] raster images

ref: https://github.com/CARTAvis/carta-backend/issues/433

**Comment by arusstaylor** [comment]
any chance to get this for 1.3?

**Comment by veggiesaurus** [comment]
> any chance to get this for 1.3?

The backend changes required are substantial, so this is not going to make it into 1.3.
