### ISSUE TITLE
toggle for auto-updating contour with different channels/stokes

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#716]
in the contour dialogue, there should be a toggle for auto-updating contour with different channels/stokes. With such, users will have flexibility to plot contours of a fixed channel and/or stokes on top of other contour layers and a raster image.

**Comment by veggiesaurus** [comment]
estimating as 3 for now, because the backend and ICD will have to be slightly adjusted to accommodate this change

**Comment by kswang1029** [comment]
This feature seems possible to be achieved with the spatial and spectral matching buttons in the image list. If image cubes are matched spatially, we can use the animator to control which channel for contour rendering and match the contour to other images spatially. @veggiesaurus if you also think so we may close this issue.
