### ISSUE TITLE
Feature request: Drawing axes inside the viewing window

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-frontend#722]
At the moment the axes are fixed along the boundary of the image viewing window. Depending on the dimensions of the actual image, there can be a lot of empty space. This is particularly noticeable when you export the image. I know it can be fixed by manually adjusting the size of the image viewing window before exporting the image. However, I wonder how this will work with the scripting interface where we don't have a GUI? We might need a way to choose where the axes are drawn relative to the image. Maybe drawing them from (0,0) on the image would work in most cases?

**Comment by veggiesaurus** [comment]
@ajm-asiaa to you mean like this?
![image](https://user-images.githubusercontent.com/592504/73911547-ddc4ca80-48ba-11ea-9d1d-75cad75e436f.png)

**Comment by ajm-ska** [comment]
Exactly! Thanks. I didn't realise that it is already possible!

**Comment by veggiesaurus** [comment]
You can use the "interior" setting for axes (and set axes to visible) in the overlay settings
