### ISSUE TITLE
region creating button in toolbar

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#726]
Do we want a region creating tool button in the top tool bar?  The shortcut in the popup on the image is fine,  but not intuitive.  The average user will look for a button to create a region in the upper tool bar.  Having one there is intuitive.  Not having one there is mystifying for the new user.  "How the heck do I create a region?".  

Should probably give some thought to the logic of what should be in the toolbar and what should be in the popup on the image.  One logic is to put things in the popup that change image properties in a single click on the button...  In that case the region creation tool and the coordinate change would not belong and should be moved to the top level tool bar.

Thoughts?

**Comment by veggiesaurus** [comment]
I think that's a great idea. I'd go one step further and suggest we have buttons for the individual region types in the toolbar.

This is the current interface, as it appears on a 1280x720 screen (our lowest target resolution)

![image](https://user-images.githubusercontent.com/592504/73941472-04ecbd80-48f6-11ea-9369-7edfa2339c04.png)

There's quite a bit of space left on the top. I'd suggest we create a new section to the toolbar for "actions", and place this first in the toolbar, moving the widgets and dialogs to the left.

Perhaps we could turn this issue into a more general discussion on what action buttons would be helpful in a toolbar?

**Comment by Kechil** [comment]
Usability Review issue
