### ISSUE TITLE
[imageViewer, AST] incorrect native coordinate when reopening an image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#73]
frontend version: f6daeb9, tested with MBP

to reproduce this issue:
1) open J2000_test.hdf5
2) change the coordinate system from "native" to "galactic"
3) reopen J2000_test.hdf5 (not append image)
4) now the coordinate system of the grid line is still "galactic" which may be okay (ideally maybe we should reset it to "native")
4) change the coordinate system from "galactic" to "native" (should be FK5) and we see
<img width="816" alt="screen shot 2018-10-25 at 12 51 56" src="https://user-images.githubusercontent.com/20819712/47476825-ce9c4380-d854-11e8-8788-3878bd28e530.png">
The system seems still galactic but its label format changes to FK5.

**Comment by veggiesaurus** [comment]
I think keeping it as galactic when explicitly specified is probably fine. But (5) is definitely an issue. @confluence can you look into this?

**Comment by confluence** [comment]
This is currently intentional behaviour. The native setting causes the system to be set automatically from the file. Any other setting overrides the system in the file.

**Comment by veggiesaurus** [comment]
@confluence I don't think (5) is intentional. When changing back to native, it should switch to FK5 (since that's the native system of the image). 1-4 are fine.

**Comment by confluence** [comment]
Oh, I see what you mean. I'll look into it.

**Comment by confluence** [comment]
It looks like the correct AST format string is being generated (i.e. one with `System` completely unset -- which works fine for setting and unsetting the system to native *before* the file is reopened). I suspect that this is a more subtle bug in the implementation, which somehow caches the first system to be applied when a file is opened. I will try to track this down. In the meantime, a workaround is to reopen the file again after setting the system to native.

**Comment by veggiesaurus** [comment]
@kswang1029 can you confirm this is fixed in the latest `1.1_release` build?

**Comment by kswang1029** [comment]
yes, issue gone~ 👍
