### ISSUE TITLE
QUESTION: decouple frame slider in animator and data source dropdown in contour dialogue

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#732]
With the current design of the contour dialogue, the data source dropdown is sync'd with the frame slider of animator, and vice versa. That is, if the frame slider has [a.fits, b.fits, c.fits, d.fits], the data source dropdown has the same list in the same order. If we use frame slider to switch to c.fits, the data source dropdown will point to c.fits as well and the histogram of c.fits is displayed in the contour dialogue. If we use the data source dropdown to select d.fits, we will see the raster image of d.fits in the image viewer and frame slider is updated to d.fits. 

This approach is simple but introduces some UX issues, for example, when viewing a.fits as raster and b.fits, c.fits, and d.fits as contours, if we want to just change the line width or color of the contours of d.fits, we will need to change the raster from a.fits to d.fits either via the frame slider of animator or the data source dropdown of the contour dialogue and do the configuration. This presents a problem, because we will often want to adjust the color of the contours to suit the colors of the image they are being overlaid on. With the current approach, this introduces a lot of switching back and forth between images. 

To improve this, there are a number of approaches:
1) add a "lock" or "link" toggle to the contour dialogue and enable/disable this "two-way" synchronization. When locked/linked, changing the image in the dropdown will also change the image in the animator, and vice versa. When unlocked, the two can be changed independently. 
2) move to one-way synchronization:
2.1) If we change the frame on the animator, it changes on the contour config as well. If we change the frame on the contour config, it doesn't affect the animator frame
2.2) If we change the data source in the contour config it changes the raster frame to the data source. If we then change the frame on the animator, the data source dropdown does not change.

We would like to hear your opinions on this. Could you help to give some thoughts?

**Comment by arusstaylor** [comment]
From our past conversation my vote is for 2.2.  I think this is the most intuitive approach, and provides the functionality intended by the user.  When I selected the data source I am selecting the raster that I want to use for the contours.  The contour tool should show the data for that sources and the raster image should show the data source image.  This lets me work on setting levels with the data source data in the histogram and data source image in the raster.  

When I want to view the contours ovelaid on a different raster I do this simply by changing the raster image with the animator.  The contour tool still shows the data source histogram and contour settings and the contours are overlaid on the selected raster image.  I can change the contour settings while viewing the effect overlaid on the selected raster, which is the image I want to contours overlaid on.   Basically I can selected any raster for contour overlay using the animator and adjust settings in that view.  

This is simple, intuitive and aligned with the intentions of the user.

Russ

**Comment by kswang1029** [comment]
Alternative idea:
if styling tab is activated we don’t sync, otherwise we sync. The idea is to let user see what they just need to see. For contour generation, they need to see the corresponding raster so keep it sync’d. But if just tweaking cosmetics of the existing contours, they already see the contours with a  raster that may be intended as the background so we don’t sync so users can adjust the cosmetics with the consideration of the background raster.

**Comment by arusstaylor** [comment]
I dont agree that the only issue is styling when looking at the overlaid raster.  One may want to also play with levels tot week the way the contours related to the underlying background raster.

**Comment by veggiesaurus** [comment]
I've made an initial implementation of 2.2 in branch `angus/one_way_sync_data_source_image`, which should be available for testing on mix 'n match. It's still a bit buggy, especially when removing images, but the important feature (one-way sync) works.

I find it a bit confusing to use, and it raises some important questions in the implementation:
1. What happens when you first open the contour dialog? Which image should the data source be set to?
2. What happens when you _reopen_ the contour dialog? 
3. What happens when you add a new image?
4. What happens when you close an existing image that is selected as the data source? Which image should it switch to? The first image? The active image?

**Comment by arusstaylor** [comment]
My thoughts.
1.  I dont think this matters since the drop down lets you choose, but probably the first loaded image is sensible.
2.  Does the widget know the last image selected?  If so, probably that would be good. Otherwise start from scratch with the first loaded image.
3. Just add the image to the drop down lists.
4. Probably the active image, since the first image might be the one deleted.

**Comment by veggiesaurus** [comment]
Ok, those sound like sensible choices. I'm going to take another stab at this tomorrow, and have thought of a way to easily implement approaches (1), (2.1) and (2.2) with mostly the same code. Once implemented, I'll ask for some testing feedback (and will hide a temporary setting to switch between the different approaches in the preferences menu)

**Comment by veggiesaurus** [comment]
branch `angus/one_way_sync_data_source_image` now supports all the proposed approaches. You can use the "lock" button in the contour dialog to toggle the two-way lock (option 1 as described above), or use the temporary debug menu to enable one-way sync:

`syncContourToFrame` will adjust the contour data source when the active image is changed (option 2.1)
`syncFrameToContour` will adjust the active image when the contour data source is changed (option 2.2)

Please give these different options a try.

**Comment by low-sky** [comment]
I tried these out and I think that the implemented version looks good and both options (locked and unlocked) do seem useful to include. The default should be unlocked.

**Comment by kswang1029** [comment]
@low-sky Thank you! Have you tried the two one-way lock approaches?

**Comment by low-sky** [comment]
Yes, both seem to work as intended.  Also, I'm not sure this is the place but the contour pop-up dialogue still has the old contour icon as opposed to the new one.

**Comment by kswang1029** [comment]
Well spotted! I will file an issue accordingly. 👍

**Comment by cflee25** [comment]
I also think option 2.2 is most intuitive.
