### ISSUE TITLE
Intermittent WebGL rendering bug in Firefox

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#746]
Symptoms:

For any file, the entire raster image is rendered as a single solid colour. This is just a rendering bug; the spatial profile widgets show the correct image values. The AST overlay is unaffected.

I have triggered this issue on my local Ubuntu laptop with Intel graphics, with a local frontend, and with Firefox as the browser. On the same system the exact same instance works correctly in Chromium. I have found that once the install is broken, it stays broken (although it has temporarily been fixed by various changes as described below). Installs running on remote servers work normally for me in Firefox.

@veggiesaurus has reproduced the same bug under certain circumstances, also in Firefox but very occasionally in Chrome (details TBA in a comment). 

This issue was introduced in [commit 2959d56](https://github.com/CARTAvis/carta-frontend/commit/2959d56e55d2a46d569527dce892362b502cada3). Reverting past this commit consistently resolves the issue. It seems likely that it has something to do with the modifications in `TileService.ts`.

Whenever the bug is triggered, several WebGL warnings / errors appear in the console. This is triggered in `RasterViewComponent.tsx:365`:

    bindTexture: tex: Object from different WebGL context (or older generation of this one) passed as argument.

Sometimes, but not always, these errors appear earlier in the log, triggered in `RasterViewComponent.tsx:120` and ` ContourViewComponent.tsx:54` (equivalent commands in both components):

    WebGL warning: <SetDimensions>: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.

The underlying cause appears to be related to the duplicate mounting of a component without the correct resource cleanup in between. From the console messages in both Chromium and Firefox, I can see that *before* this commit the raster view component is mounted only once (as can be seen from the message printed by the function in `TileService.ts` which creates tile textures).

*After* this commit, the raster component is mounted *twice* (by adding debugging messages I saw that the contour component was as well, which suggests that the whole image view is mounted twice). In Chromium, the raster component is unmounted in between, and various WebGL resources are cleaned up (as can also be seen from a console message). But in Firefox, the unmount function is not triggered and the resources are not released, which is possibly what eventually causes this bug.

Dead ends:

* These console warnings are unrelated and harmless: `texSubImage2D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.` and `texSubImage2D: Tex image TEXTURE_2D level 0 is incurring lazy initialization.`
* Clearing local storage has no effect.
* Restarting Firefox has no effect.
* Small edits made to `TileService.ts` appeared to fix the issue initially, even when @veggiesaurus and I later realised that they were no-ops, but after a few reloads in the browser these fixes stopped working and subsequently had no effect. They are mostly documented [in this branch](https://github.com/CARTAvis/carta-frontend/tree/angus/fix_firefox_webgl_issue).
* Running a production build with `npx serve` also appeared to fix the issue initially, but also stopped working after a few reloads.

**Comment by veggiesaurus** [comment]
happens sometimes in Chrome and Firefox on NVIDIA hardware again. I'm going to attempt to fix it by  moving the WebGL context to a canvas associated with the tile service, rather than the component
