### ISSUE TITLE
Contour rendering breaks when changing layouts

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#755]
After changing layouts, contours are no longer rendered, due to a WebGL error. A similar fix to that used for #746 is required. The contour WebGL context should be associated with a service, rather than a specific component, which can be unmounted.

**Comment by veggiesaurus** [comment]
@kswang1029 can you confirm this is fixed in `release/1.3` branch and `dev`?

**Comment by kswang1029** [comment]
with 
origin/backport_755 290ff57 2020-03-03 17:10:16 UTC
and dev, the issue is gone. 👍
