### ISSUE TITLE
Contours do not show on ipad

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#768]
When I click apply on the contour widget on my iPad the contours do not appear on the image.

**Comment by veggiesaurus** [comment]
They seem to work fine on my iPad (iPad Pro 10.5"), both when showing contours on the original image and when showing on another spatially matched image.

@kswang1029 do you see this on your iPad?

@arusstaylor what is the exact iPad model? (e.g 1st or 2nd gen iPad Pro, 12" or 11") and iOS version?

**Comment by kswang1029** [comment]
Yes, with iPad Pro 11” 3rd gen.
![AF48EA32-F22C-44A4-AAA5-2195E06249B8](https://user-images.githubusercontent.com/20819712/75104738-94f56b80-5647-11ea-8ce6-a6058ecd903f.png)

**Comment by arusstaylor** [comment]
Just tried it again. It is working now.  iPad Pro 2nd gen

**Comment by veggiesaurus** [comment]
Tried on an iPad air, also working fine. Closing this issue for now
