### ISSUE TITLE
Remember spectral system choice when switching active images

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#770]
Currently, whenever the active image is changed, the coordinate system for a spectral profile widget reverts to the system defined by the image's WCS. Even if I have explicitly selected another system. For example, if I have three images, all with `CTYPE3 = FREQ`, then there's no way to easily compare spectra as velocities, because every time I switch images, the widget defaults to frequency again. 

![spectral_coordinate](https://user-images.githubusercontent.com/592504/75120195-491be400-5692-11ea-8c72-1b1b4053ec53.gif)

I propose we add a new option to the dropdown: "WCS". When this is selected (by default), then the system is defined by the image's WCS. If I switch to an image with a different system, then the new image's WCS define the system choice. If I explicitly select another system type, then this persists even after switching images. If the new image doesn't support the given system type, it reverts back to "Channel"

@kswang1029 what do you think?

**Comment by kswang1029** [comment]
Good idea
