### ISSUE TITLE
adding the new layer widget to preset layouts

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#772]
As CARTA can do spatial and spectral matching of images, it would be good to have the layer widget enabled in all preset layouts. The other purpose of doing so is to use this layer widget to guide and train users to get used to the "match" feature in v1.3.

Default
<img width="1405" alt="default" src="https://user-images.githubusercontent.com/20819712/75153473-72964780-5746-11ea-9c7f-60fb797cfaaa.png">

Cube view
<img width="1404" alt="cube_view" src="https://user-images.githubusercontent.com/20819712/75153485-77f39200-5746-11ea-8242-f3b04aa75ee8.png">

Cube analysis
<img width="1405" alt="cube_analysis" src="https://user-images.githubusercontent.com/20819712/75153612-c9038600-5746-11ea-89b7-9839d875849d.png">

Continuum analysis
<img width="1404" alt="continuum_analysis" src="https://user-images.githubusercontent.com/20819712/75153514-88a40800-5746-11ea-9a92-b6b5b159b848.png">

@duidae Could you help quickly for v1.3?

**Comment by duidae** [comment]
ok
