### ISSUE TITLE
add a frame drop down to analytics widgets

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#778]
Currently the content in any analytics widget is sync'd with the frame slider. So users can view results from one image at a time.

To extend the flexibility to view analytics of different frames (aka different images) at a time, we need a frame dropdown in every analytics widget. This would enable more use cases, especially with WCS features in v1.3.

**Comment by arusstaylor** [comment]
I think this is a larger issue that we need to discuss in the science team.  Basically how to link profiles in liked frames, and should apply to spatial and spectral profiles,  and regions that apply to more than one frame.  There is larger user interface issue here I think.

**Comment by veggiesaurus** [comment]
For 1.3, we won't have linked regions, so for now a dropdown should suffice. But I agree, the concept of linked regions and profiles needs to be carefully thought out. It needs to be simple and easy for the most common use cases.
