### ISSUE TITLE
Contour level settings are lost when I select configuration

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#781]
In the contour widget, after I set my contour levels the way I want them I select configure to adjust smoothing. When I go back to levels my level settings are lost. The levels are back at the default settings. My setting on the levels should be preserved.

**Comment by veggiesaurus** [comment]
@arusstaylor do you mean the _levels_ or the settings for the generator? For me, the actual levels themselves are preserved, but the min/max/N settings are (annoyingly) reset to default.

**Comment by veggiesaurus** [comment]
@arusstaylor please verify that this is fixed by trying it on carta-testing

**Comment by arusstaylor** [comment]
Confirm that this is fixed on carta-testing. Thanks.
