### ISSUE TITLE
Allow users to enable/disable spatial matching on load

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#785]
Users should be able to select spatial/spectral matching via checkboxes on image load. They can still adjust these settings after loading images in the usual way

**Comment by arusstaylor** [comment]
I am not in favour of this.  I do not like cluttering up the load process with options that in general are not needed.  Loading should be a simple, clean process.  This is the beginning of a slippery slope.  This is a usability issue and should be discussed.

**Comment by veggiesaurus** [comment]
@kswang1029 shall we icebox this and wait to hear from beta testers?

I imagine casaviewer users may be confused, because they'd expect images to be matched by default. What about a setting in preferences that allows users to select whether images are matched by default?

**Comment by kswang1029** [comment]
Ok

**Comment by veggiesaurus** [comment]
@arusstaylor would that be ok with you? By default, the setting is off. If users (esp. casaviewer users) want to automatically spatially or spectrally match images, they can enable this in the preferences dialog

**Comment by arusstaylor** [comment]
Confusing casaviewer users is not necessarily a bad thing.  They have been using a poorly designed tool for years and will need to modify practices...

My suggestion would be to icebox this for now.  I think we need an overall usability review of CARTA as part of the 1.4 release goals. 

If we want to match by default as an interim, I think it should only happen for appended image and only if the appended image shares some FOV with the original load.  An initial image is loaded most likely just because I want look at that image.  If I append an image it is a more likely bet that the appended image is for the purpose of overlay.

**Comment by veggiesaurus** [comment]
yes, this would apply only during image appending.

**Comment by arusstaylor** [comment]
@veggiesaurus  I am ok to implement automated matching as a preference that is turned off by default.  What will happen if there is no FOV overlap between the images?

**Comment by veggiesaurus** [comment]
@arusstaylor if there is no FoV overlap, but the two images are adjacent, they'd still be matched. If they are on completely different hemispheres, the matching will fail, and they won't be matched. I agree that there's some confusion about appending images that don't overlap, so leaving this option off by default is probably a good bet. 

Later on, we could turn this preference from a binary one to "Always, Never, Only if FoV overlaps" for spatial matching, and "Always, Never, Only if velocity range overlaps" for spectral matching

**Comment by arusstaylor** [comment]
which means the backend will need to check for FOV and spectral overlap on appended images....
Could turn into a confusing ven logic issue with multiple appended files...  I guess if the original loaded image is the master, it is simpler.

**Comment by veggiesaurus** [comment]
> which means the backend will need to check for FOV and spectral overlap on appended images....

No, this is all done on the frontend. The AST library would be able to easily tell us this info.

>  guess if the original loaded images is the master, it is simpler.

Currently, this is the case. Although we will be able to select a new reference afterwards (hopefully in a few hours time!)

**Comment by veggiesaurus** [comment]
Closing this issue in favour of #786
