### ISSUE TITLE
Cannot show frequency axis if no conversion to velocity exists

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#793]
On `dev`, we cannot select anything other than channel:

![image](https://user-images.githubusercontent.com/592504/75415948-c915a880-5935-11ea-8a87-bb2ef8afcc8a.png)

On `master`, we can always choose to use the native WCS: 
![image](https://user-images.githubusercontent.com/592504/75415997-e5194a00-5935-11ea-8634-459dbc3715f9.png)

Example file: GALFACTS_N4_cube_Q_DQA3.3.1.fits (or any other image that doesn't have enough information for FREQ -> VRAD conversion, such as RESTFRQ)

**Comment by veggiesaurus** [comment]
@arusstaylor this is the issue we discussed yesterday. Will fix it for 1.3 final release

**Comment by kswang1029** [comment]
if I understand correctly, we just need RESTFRQ for to convert FREQ to VRAD. Missing SPECSYS should not forbid this conversion.

**Comment by arusstaylor** [comment]
If RESTFQ is specified but not SPECSYS, we should probably assume TOPOCENT for the sys.
We should be able to convert channel to frequency or wavelength without either RESTFQ or SPECSYS.    That conversion just relies on the constant speed of light....

**Comment by kswang1029** [comment]
FREQ from/to WAVE is not problem. If it is FREQ to VRAD or VRAD to FREQ, we need a RESTFRQ and this can be done without SPECSYS. It will just be the same whatever unknown SPECSYS.
