### ISSUE TITLE
a flash with missing tiles then full image restored when we press stop to stop animation

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#794]
When we stop an animation, occasionally we will see a flash with missing tiles first, then will see a full image is restored.

**Comment by kswang1029** [comment]
I suppose this has been fixed?

**Comment by veggiesaurus** [comment]
> I suppose this has been fixed?

Not fixed for 1.3, we'll have to list it as a known issue

**Comment by kswang1029** [comment]
I see. known issue added in user manual

**Comment by kswang1029** [comment]
@YuHsuan-Hwang @crocka  Guess this is fixed via #2219 too?

**Comment by YuHsuan-Hwang** [comment]
Fixed via #2219.
