### ISSUE TITLE
Different widget help display depending if CARTA is in dark mode or light mode

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-frontend#795]
I wonder if it would be possible to have a different widget help display to show up depending whether CARTA is in Light mode or Dark mode? 

I'm specifically referring to the **Image View** help as it shows some images captured in Light mode. I think it would be a neat touch if when using CARTA in Dark mode, that it could show the tool button images captured in Dark mode, plus have the first image with the Dark mode background colour and the text labels in white.

It is just a suggestion. I know it would mean extra work for @kswang1029 as he would need to create another set of images in dark mode.

**Comment by kswang1029** [comment]
Creating screenshots in dark mode is no problem at all. :)

**Comment by kswang1029** [comment]
I will need some help from @TienHao too

**Comment by kswang1029** [comment]
done with #825
