### ISSUE TITLE
Widget menu bar adjustment for Dark mode

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-frontend#796]
I noticed in Dark Mode on the widget windows (Animator, Histogram etc.), their close, pin, help, and settings options are inside a dark box. This is not apparent in Light mode, nor on the Contour Configuration for example which actually has a larger menu bar. 

I guess File info, Preference, Overlay settings, and Contour Configuration are not widgets as such so that is why they have a different sized menu bar. 

But maybe something with the close/pin/help/settings on the widget menu bars need to be adjusted slightly so that those apparent boxes do not appear in Dark mode?

![carta](https://user-images.githubusercontent.com/20802551/75422337-4a415f80-5977-11ea-9d5c-b8df1e5418e3.png)

![carta2](https://user-images.githubusercontent.com/20802551/75422704-22063080-5978-11ea-9642-adcc5cbc6324.png)

**Comment by kswang1029** [comment]
#771 ?

**Comment by ajm-ska** [comment]
Oh I'm sorry! I didn't check previous issues!
