### ISSUE TITLE
add default directory to global preferences

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#799]
It would be nice to be able to set the default directory that is open in the file load tool.  When I am consistently working on a particular project it would be good to be able to set the default to that project directory so I dont have to navigate to it every time I start up carta.

**Comment by veggiesaurus** [comment]
I think the easiest way to implement this would be to add a "star" icon next to the refresh icon, inside the browser. When the user clicks on it, the icon changes from an outline to filled, indicating that this directory is now the default directory. Clicking on it again resets the default directory. See mockup below. 

I think users are more likely to make use of this feature if it's integrated into the file browser, rather than hidden in the preferences with an additional file browser

![image](https://user-images.githubusercontent.com/592504/75522193-09e2ef80-5a12-11ea-8163-1a77a423d5ca.png)

![image](https://user-images.githubusercontent.com/592504/75522231-2aab4500-5a12-11ea-80e1-b9ff55390034.png)

**Comment by arusstaylor** [comment]
I agree this is a much better solution.  Thanks.  Is there a more appropriate icon than a star that is associated with the concept default?

**Comment by veggiesaurus** [comment]
>Is there a more appropriate icon than a star that is associated with the concept default?

Here's the icon library we use: https://blueprintjs.com/docs/#icons

The star is one of the few that has an outline and filled icon, so it was my first choice.

**Comment by arusstaylor** [comment]
Being able to indicate a selected and not selected state is important.   The little house home symbol would be more recognisable a setting the home directory.  But I guess there are no options for filled an unfilled or selected or deselected versions of that symbol?  I think then the star is probably the best option at this point.

**Comment by arusstaylor** [comment]
Could you use the home symbol and use colour to indicate selected (green) or not selected (red)?

**Comment by veggiesaurus** [comment]
We could use  the default color and another color for highlighting it, sure. But then we need another icon for the base directory.

**Comment by veggiesaurus** [comment]
I think a star is generally understood to mean "favourite". So perhaps we just change the language to "favourite", and assume the file browser starts in your favourite directory?

**Comment by confluence** [comment]
There is a bookmark icon -- that maps better conceptually to a single marked location (the star / favourite implies multiple favourites). But there's no un-filled icon. We could use grey and green (I would avoid using red to mean "off"; red usually indicates an error state), but that would break our current monochromatic colour scheme.

**Comment by confluence** [comment]
Another possibility: can we use svg or css text effects to outline a solid icon, creating our own "empty" version?

**Comment by arusstaylor** [comment]
Agree grey is better for not selected.  Didn't realise we were sticking to a monochromatic colour scheme. I appreciate that it makes the data standout against the tool.   But it seem unnecessarily limiting.   At any rate we currently use the blue and grey options to indicate on an off state of toggles. Perhaps blue and grey versions of the home symbol could be used?  Blue when you are in the home directory or when you select to set the home directory, and grey in all other cases?

**Comment by veggiesaurus** [comment]
> Another possibility: can we use svg or css text effects to outline a solid icon, creating our own "empty" version?

I think that should be fairly simple to do. If someone wants to dig into the SVG :)

**Comment by veggiesaurus** [comment]
@arusstaylor would it be sufficient to simply default to the previously opened folder across multiple CARTA sessions? That might be simpler to implement

**Comment by Jordatious** [comment]
I think that's sensible. Would that be the case when appending an image and opening a catalogue as well?

**Comment by veggiesaurus** [comment]
> @arusstaylor would it be sufficient to simply default to the previously opened folder across multiple CARTA sessions? That might be simpler to implement

@arusstaylor would this be ok?

**Comment by arusstaylor** [comment]
Hi Angus,

I think this would be sufficient, but it needs to be a global preference option to set this behaviour as default.  Otherwise default directory is the users directory.

**Comment by veggiesaurus** [comment]
Closing this in favour of https://github.com/CARTAvis/carta/issues/89, as that (along with the persistent previous directory) mostly covers the use case.
