### ISSUE TITLE
use common unit for frequency

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#803]
For frequency display, we better switch to a more common unit used by astronomers. Usually it is GHz or MHz. I suggest we implement a smarter way to automatically choose a proper unit, including
1) THz (> 1000 GHz)
2) GHz (3 GHz < freq < 1000 GHz)
3) MHz (< 3 GHz)

@arusstaylor do you have more thoughts on this?

<img width="764" alt="Screen Shot 2020-03-02 at 1 50 24 PM" src="https://user-images.githubusercontent.com/20819712/75649058-ed9eb700-5c8c-11ea-96ff-a813c9ebc473.png">

**Comment by arusstaylor** [comment]
I agree we should implement a smart choice for unit display.  In general I think carta should have build-in smarts for convenience and ease of use of the user interface.  The smart layouts is another example.   I would recommend that we place the automatic transition from MHz to GHz at 3 GHz.  I.e. if the maximum frequency in the cube is less than 3 GHz use MHz uniits. Generally people working up to a few GHz still refer to frequency in MHz.

**Comment by kswang1029** [comment]
Updated to 3 GHz🙂
