### ISSUE TITLE
not sure the removing contours after closing the contour widget window is what we want

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#810]
I am not sure that removing contours after closing a contour window is the behaviour that we want.  The contour window takes up a lot or real estate on the screen.  After I have finished setting up the contours the way I want them I would like to be able to close or minimise the widget window without removing the contours. I dont need the widget anymore.  

I am not sure what the right behaviour is.  If closing the window does not remove contours then how does one remove the contours after closing?  Does the contour window remember its last state on closing? Perhaps the best solutions is to be able to minimise widgets to get them out of the way when they are not needed but call them up when you need them again.

**Comment by veggiesaurus** [comment]
That's what the "Clear" button is for. Closing the contour widget doesn't remove contours, pressing the "Clear" button removes them. This is the same behaviour as DS9

Or do you mean removing the specific generator settings used for generating the contour levels?

**Comment by arusstaylor** [comment]
Hmm...  I am pretty sure that my contours disappeared when I closed the contour window. I'll test again.

**Comment by arusstaylor** [comment]
well.  I must have been having a brain seizure.  You can close this issue.  Apologies.

**Comment by veggiesaurus** [comment]
Closing issue. If it happens again, @arusstaylor, let me know. They're definitely not _supposed_ to disappear :)
