### ISSUE TITLE
Frontend scripting interface support

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#813]
- [x] The frontend needs to be able to receive scripting commands from the backend and send back responses when the commands complete.
- [x] The frontend needs to convert the scripting messages into execution objects, which execute a given frontend action.
- [x] Ability to save an image to base64-encoded PNGs
- [x] A few additional frontend functions, such as waiting for image data to arrive

**Comment by kswang1029** [comment]
the remaining features are addressed in #1756
