### ISSUE TITLE
breadcrumbs ... menu is greyed out

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#830]
breadcrumbs ... menu is greyed out so that users cannot jump to a certain folder easily and quickly

![Screen Shot 2020-03-19 at 11 09 39 AM](https://user-images.githubusercontent.com/20819712/77027862-492dac00-69d2-11ea-8c38-343218364e25.png)

**Comment by veggiesaurus** [comment]
this is likely a blueprintJS issue. Hopefully there is a workaround

**Comment by TienHao** [comment]
> this is likely a blueprintJS issue. Hopefully there is a workaround

Yeah, the source code of blueprintJS shows that the overflow breadcrumb will only be enabled when the item has property `href` or `onClick`. 
( see `renderOverflowBreadcrumb` in `../@blueprintjs/core/src/components/breadcrumbs/breadcrumbs.tsx` )
