### ISSUE TITLE
Render imported regions based on their color definitions if exist.

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#831]
as a request from beta test

render different imported region sets in different colors so that users can distinguish those easily.

**Comment by arusstaylor** [comment]
I think the color must as first priority obey the colour setting in the imported region file.

**Comment by veggiesaurus** [comment]
> I think the color must as first priority obey the colour setting in the imported region file.

I agree. @kswang1029 I thought that's what the user was asking for?

**Comment by kswang1029** [comment]
If color is defined we should render as it is defined. If not defined, we could consider to have a set of default colors and apply in turns for different imported sets of regions. Open to other suggestions 🙂

**Comment by veggiesaurus** [comment]
>If not defined, we could consider to have a set of default colors and apply in turns for different imported sets of regions. 

We then need a whole bunch of colours that don't clash with the colour map. If we stick to the default colour, then we can leave it up to the user. Respecting the explicitly-defined colours is a good idea though.

**Comment by kswang1029** [comment]
I was thinking three colors to take turns, judging from the probability for loading multiple region files is probably low. Loading two may be more common.

**Comment by kswang1029** [comment]
One thing we can think about is to distinguish manually created regions with imported regions by different colors.

**Comment by veggiesaurus** [comment]
this sounds like a lot of extra preferences :thinking: what about allowing users to select the default colour in a colour picker when opening the region? Not sure @arusstaylor will like that idea though

**Comment by arusstaylor** [comment]
I think this is a bit of a boon doggle.  First priority is to use the defined colour in the file.    The issue of changing colours on groups of regions after loading is something we might think about, but impinges on usability issues which we plan to put more thought into as part of 1.4.  We suggest that we pin this discussion to the usability review.

**Comment by veggiesaurus** [comment]
I think following the defined colours will already help a lot.

**Comment by arusstaylor** [comment]
agreed.  This leaves the default colour scheme for a group of regions up to the user....

**Comment by kswang1029** [comment]
I revised the issue title accordingly. The next question is to create a table mapping color label to hex code (e.g., ‘red’ : #FF0000)

**Comment by veggiesaurus** [comment]
> I revised the issue title accordingly. The next question is to create a table mapping color label to hex code (e.g., ‘red’ : #FF0000)

I think we might be able to use the built in HTML codes for that

**Comment by kswang1029** [comment]
I can investigate what color labels are supported in crtf and ds9 region format.

**Comment by veggiesaurus** [comment]
@kswang1029 is there an equivalent backend issue? the frontend issue should be pretty trivial to implement.

**Comment by kswang1029** [comment]
I cannot recall we have any in the backend repo.

**Comment by veggiesaurus** [comment]
@kswang1029 what other style properties should we include? Since this requires an ICD change, I'd prefer if we added all the required style properties at once

edit: nevermind, I found the backend issue here: https://github.com/CARTAvis/carta-backend/issues/340 and realised there's already a google doc for it :+1:
