### ISSUE TITLE
make layer list widget more obvious in the default layout 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#834]
Based on the v1.3 beta test results, there are quite some complaints on the intuitiveness of enabling WCS matching. A possible solution (as discussed with @veggiesaurus) to improve this for 1.3 is to make the layer list widget more obvious to users like the following (replacing spatial profile widgets by layer list widget and region list widget). This can save internet bandwidth too since the default cursor is not fixed so users may request lots of spatial profile update unintentionally. 

<img width="1278" alt="Screen Shot 2020-03-23 at 2 45 13 PM" src="https://user-images.githubusercontent.com/20819712/77299491-7c9c6d80-6d27-11ea-8536-81dec70320f3.png">

@arusstaylor do you have concerns on making this change in v1.3? We can review the usability afterward but for v1.3 we have to have a way to let users know how to match images.

**Comment by duidae** [comment]
@kswang1029  is this change specifically for "Default" in presets?

**Comment by kswang1029** [comment]
@veggiesaurus @arusstaylor are you okay with this proposed change specifically for v1.3?

**Comment by veggiesaurus** [comment]
I'm ok with that, because users can easily change their preferred layout or save a new preset

**Comment by arusstaylor** [comment]
Not sure about this. This default only makes sense if you append an image. So could make sense in the context of smart layouts but does not make sense as the default for a single image. 
 Think this is a deeper UI issue.

**Comment by kswang1029** [comment]
@arusstaylor @veggiesaurus thanks for the input. The idea of having this is because some beta testers cannot easily find out how to trigger WCS matching. I agree this is a deeper UI issue but as a quick and dirty improvement just for the coming v1.3 release, this approach could make the layout list widget directly visible to users so that they may trigger WCS matching easily. Surely smart layout could help.

**Comment by kswang1029** [comment]
a temporary solution has been applied in v1.3. This should be revisited in usability review. Close for now.
