### ISSUE TITLE
narrow text fields in the contour dialogue

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#836]
Based on the users feedback of v1.3 beta test, some text fields in the contour dialogue are not wide enough to display numbers properly. The example below is to load an image with values ~ 1E-10.
<img width="797" alt="Screen Shot 2020-03-24 at 10 45 42 AM" src="https://user-images.githubusercontent.com/20819712/77383322-92f50880-6dbd-11ea-9990-3915080230eb.png">

As a quick improvement for v1.3 release, some text fields belonging to different level generators are needed to be widen. To support a wide range of numbers, we display it as "%.4E". 

@veggiesaurus @arusstaylor ok to do this for v1.3?
@TienHao when permission granted, could you have a look?

**Comment by TienHao** [comment]
@kswang1029 I can have a look

**Comment by arusstaylor** [comment]
I agree to use scientific format. In general we display too many significant figures. This also makes it awkward to edit the number. Recommend three decimal places.
