### ISSUE TITLE
[question] narrower contour dialogue

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#837]
based on v1.3 beta test, users complains about the contour dialogue being too big to block widgets. As a quick solution, possibly we can make the contour dialogue narrower by changing the "Parameters" row into two rows, like the following mockup (certainly with proper alignment):
<img width="495" alt="Screen Shot 2020-03-24 at 11 39 22 AM" src="https://user-images.githubusercontent.com/20819712/77386326-8674ae00-6dc5-11ea-9cc7-6861b4a44bc2.png">

Except "mean-sigma-list" generator, all other three generators have four fields in "Parameters". So for these three generators, we use two rows to display the four fields (two in each row).

@veggiesaurus @arusstaylor ok to do this for v1.3? Later we can redesign the UI if we have better ideas on using space more efficiently.

**Comment by arusstaylor** [comment]
This is good for 1.3
