### ISSUE TITLE
incorrect number of levels is generated with the mean-sigma-list method 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#849]
To reproduce, set mean = 1, sigma = 0.1, sigma list = -1, 1, 2, 3, then generate levels. We will see 5 levels instead of 4 levels. 

<img width="592" alt="Screen Shot 2020-03-28 at 9 37 14 PM" src="https://user-images.githubusercontent.com/20819712/77824424-88c86680-713d-11ea-81e8-5bb441cdd7d4.png">

**Comment by veggiesaurus** [comment]
@kswang1029 can you reproduce this with every file? not happening for me on `dev`

**Comment by kswang1029** [comment]
seems so. Try remove all sigma list and add -1, 1, and 2, then generate levels. I see four levels being generated.

**Comment by veggiesaurus** [comment]
ohh, I think I see what's happening. You're typing `0` and its being added to the list, but not being displayed! Or is that not what's happening at all?

**Comment by kswang1029** [comment]
you are right! sigma = 0 is not displayed but is counted for level calculations

**Comment by kswang1029** [comment]
fixed via #859
