### ISSUE TITLE
Help drawer not working when using Firefox

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-frontend#854]
I have noticed that the pop out help drawer doesn't work on **Firefox** when clicking any of the question marks on the main window. It only works if you click the question mark on a widget that is already floating.

Chrome and Safari work fine.

If it is any help, I had a quick investigation using Mix 'n Match to look back to when the issue started:

It seemed to be OK at this point:
`origin/thchang/improve_help_drawer 95b0dd7 2020-03-19 03:24:27 UTC`
http://carta.asiaa.sinica.edu.tw/frontend/95b0dd7/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev

But didn't work after this:
`origin/thchang/improve_help_drawer 26ab90a 2020-03-19 08:12:53 UTC`
http://carta.asiaa.sinica.edu.tw/frontend/26ab90a/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev

**Comment by TienHao** [comment]
@ajm-asiaa  thanks for the quick investigation. I will take a look.
