### ISSUE TITLE
Spectral Line ID overlay

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#863]
- [X] 1. fetch data from splatalogue
- [X] 2. wire up UI
- [X] 3. plot spectral line on spectral widget
- [ ] 4. filtering/sorting
- [x] 5. support layout

ref:
splatalogue of NRAO:
more info about query:
https://www.cv.nrao.edu/php/splat/advanced.php 

top table: "Applications (SLAP Interface)"
https://www.cv.nrao.edu/php/splat/SLAPNotes2.html

some example scripts to make query: ftp://ftp.cv.nrao.edu/NRAO-staff/bkent/slap/

description: https://cdms.astro.uni-koeln.de/classic/predictions/description.html

design doc: https://docs.google.com/document/d/1dzhPc_XptsHFoKQ4fj7bo4TTKf5beGXfWZ0ZljYzdgM/edit

**Comment by Kechil** [comment]
From Usability Review:
Allow colorfill between the spectra and the zero level.

Is it easy to do this before code freeze @duidae?

**Comment by duidae** [comment]
@Kechil not sure what you mean, are u suggesting adding color changing function for spectral lines?

**Comment by kswang1029** [comment]
something like this
<img width="688" alt="Screen Shot 2020-07-22 at 9 48 00 PM" src="https://user-images.githubusercontent.com/20819712/88184260-0f610080-cc65-11ea-8309-139b1aaf38b0.png">
(eq. to Matplotlib's fill-between)

**Comment by veggiesaurus** [comment]
what do we define as the middle level? I'd say we leave this until 1.5, since @panchyo0 will be converting these plots from chartjs to plotly in any case
