### ISSUE TITLE
missing spatial profile while dev console is enabled

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#865]
To reproduce:
1) launch http://carta.asiaa.sinica.edu.tw/frontend/dev/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev
2) enable JavaScript console (it appears not reproducible without this step)
3) load set_M100/M100_combine_CO_cube.image.fits
4) move cursor in the image and we see
<img width="1662" alt="Screen Shot 2020-04-10 at 2 42 35 PM" src="https://user-images.githubusercontent.com/20819712/78969613-eb583400-7b39-11ea-9af8-4a9da3461d7c.png">

**Comment by veggiesaurus** [comment]
@duidae this is the bug I mentioned to you.

**Comment by kswang1029** [comment]
Aha!

**Comment by veggiesaurus** [comment]
should be fixed by #974 @kswang1029 please confirm after it has been merged
