### ISSUE TITLE
catalog overlay single source highlighting

### ISSUE THREAD

**Issue by panchyo0** [CARTAvis/carta-frontend#868]
Single source selection in catalog table view, scatter view and image view. 
- [x] User select a row in table view, it will highlight the data in table, scatter and image.
- [x] User select a point in scatter plot, it will highlight the data in table, scatter and image.
- [x] User select a point in image overlay, it will highlight the data in table, scatter and image.

**Comment by veggiesaurus** [comment]
This is partially implemented in the latest PR, but I think we still need to think about how to highlight the selected point in the image. I'd prefer to just display an additional outline around the point, rather than hiding all other points.

**Comment by panchyo0** [comment]
User can customer the shape, should we do different outline around for different shape? Should we keep the selection action consistent between scatter plots and image overlay? We can change the color of selected source to make it obvious. since user can custom the catalog color, not sure which color we should use.
