### ISSUE TITLE
Improvements to catalog file browser

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#875]
- [ ] Navigating via the file browser to the base directory and then to any sub-directory results in a `.` shown as a directory (might be backend-related, if so please create an issue for @markccchiang)
![image](https://user-images.githubusercontent.com/592504/79439848-9c951900-7fd5-11ea-8280-ced416f39eea.png)
- [x] The catalog information tab always displays `... query string .... ` instead of any meaningful information. 
- [x] Clicking on the refresh button produces an error: `Uncaught TypeError: Cannot read property 'directory' of null` and does not refresh the list.
- [x] When browsing for a second catalog to append, the header from the first selection is shown

**Comment by panchyo0** [comment]
Backend related issue https://github.com/CARTAvis/carta-backend/issues/508
 ... query string .... comes form the catalog file description. This one depends on what user put in description tag in catalog file.
