### ISSUE TITLE
Additional symbols for catalog shapes

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#876]
we probably can apply some rotations to these symbol shapes like the attached image. For closed shape, we can set it as filled or not.
<img width="889" alt="Screen Shot 2020-03-04 at 6 28 10 PM" src="https://user-images.githubusercontent.com/20819712/75870663-42396200-5e46-11ea-96bf-d2a7ccf32280.png">

_Originally posted by @kswang1029 in https://github.com/CARTAvis/carta-frontend/issues/814#issuecomment-594442762_

(In addition, the dropdown for selecting the shape should be changed to a BlueprintJS "Select", and should show the symbol shape, rather than the name)

**Comment by panchyo0** [comment]
Should we also update the catalog file dropdown and system dropdown to BlueprintJS "Select"?
UI for syetem dropdown:
<img width="1232" alt="Screen Shot 2020-04-28 at 7 49 24 PM" src="https://user-images.githubusercontent.com/22226157/80554237-ba755d00-8989-11ea-98f6-c1d7faa83e8a.png">
UI for shape dropdown:
<img width="1232" alt="Screen Shot 2020-04-28 at 7 49 01 PM" src="https://user-images.githubusercontent.com/22226157/80554263-ccef9680-8989-11ea-80dd-0ff6f462afdf.png">

We can draw all shapes in Plotly (https://plotly.com/~dmiller123/4/name-circle-name-circle-open-name-circle-dot-name-circle-open-dot-name-square-na/#plot), However Blueprint icon doesn't have all icons (like triangle and hexagon). We might need to create our own SVG icons or using a static png file.

**Comment by low-sky** [comment]
I think(5-pointed) star symbol would be good to include.  

Looking to the future, we'll also want to draw ellipses through this interface but that would be tricky.  For example, lots of astronomical source catalogs fit an ellipse to sources so the symbols should map the major, minor, and position angle from a catalog to the same properties on plotting symbol.  Like so:
<img width="566" alt="Screen Shot 2020-04-29 at 1 33 35 PM" src="https://user-images.githubusercontent.com/1139910/80638657-0b369580-8a1e-11ea-8f88-0826b9d80872.png">

**Comment by arusstaylor** [comment]
agreed.  this is very useful.  But would require is to parse properties from multiple columns of a source catalogue.

**Comment by veggiesaurus** [comment]
> Looking to the future, we'll also want to draw ellipses through this interface but that would be tricky. For example, lots of astronomical source catalogs fit an ellipse to sources so the symbols should map the major, minor, and position angle from a catalog to the same properties on plotting symbol

It's unlikely that plotly will support efficient rendering of multiple ellipses of different proportions, and the only way I can think of doing this is via some custom WebGL shaders. Could you create an issue for this, and we can continue the discussion there?
