### ISSUE TITLE
UI improvements of tables in catalog file browser and catalog widget 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#877]
- [x] disable changing vertical size of a row of the table in catalog file browser
- [x] disable changing vertical size of a row of the tables (both top one and bottom one) in catalog widget
- [x] align texts to cell center vertically in the header table of the catalog widget
- [x] switch to the default font for the header table

<img width="455" alt="Screen Shot 2020-04-17 at 1 38 15 PM" src="https://user-images.githubusercontent.com/20819712/79536240-24e8ec00-80b2-11ea-8fe8-fa0b67cd936f.png">
<img width="868" alt="Screen Shot 2020-04-17 at 1 42 02 PM" src="https://user-images.githubusercontent.com/20819712/79536245-287c7300-80b2-11ea-91e4-8d3068aa6f79.png">

**Comment by veggiesaurus** [comment]
Do you think we should use a monospaced font for the table as well? It seems a bit inconsistent to use it for the file browser header list and not the catalog widget's header list. Perhaps monospace is not needed in either?

**Comment by kswang1029** [comment]
good point. I think we need it to be consistent. As long as the font is easy to read, it is okay to use or not to use monospaced font. We also have tables in region list and layer list. So I think we need all consistent.

**Comment by veggiesaurus** [comment]
Currently we only use monospaced for the header information, with good reason (it's not in table format, so the only way the headers and values line up is with a monospaced font). I suggest we switch to the default font for the catalog header information table in the file browser, because there's no need for it.

**Comment by veggiesaurus** [comment]
I've updated the issue description to add the font change
