### ISSUE TITLE
[question] unselect a source in the catalog table?

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#879]
when we select a source in the catalog table, it is highlighted in red and the source is also highlighted in the image and the 2d scatter plot. When double click in the scatter plot, effectively it unselects the source. Is there any way to unselect the source directly in the catalog table? 
<img width="1749" alt="Screen Shot 2020-04-17 at 2 35 01 PM" src="https://user-images.githubusercontent.com/20819712/79539469-f7537100-80b8-11ea-9877-8d11b0173e23.png">

**Comment by panchyo0** [comment]
How about a button in bottom "unselect" to unselect all highlights? Should we also add a way to unselected source in image view?

**Comment by kswang1029** [comment]
Is it possible to use click? If a selected row is clicked, it becomes un-selected. 

When multiple rows are selected and users click on one of the selected row, it will effectively un-select all other selected rows and only the clicked one remains selected.

**Comment by panchyo0** [comment]
closed with PR 922
