### ISSUE TITLE
Reset 2D scatter plot if a catalog file is closed

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#881]
Currently if we close a catalog file via the close button in the catalog widget, the 2D scatter plot still shows what it shows and we can still change the plot by selecting different columns of the closed catalog. 

When a catalog is closed (the catalog overlay in the image is gone), we see 
<img width="1750" alt="Screen Shot 2020-04-17 at 2 58 09 PM" src="https://user-images.githubusercontent.com/20819712/79541329-36cf8c80-80bc-11ea-811a-c7531b8355e6.png">

and we can still change the columns used to generate the 2d scatter plot.
<img width="1751" alt="Screen Shot 2020-04-17 at 2 58 54 PM" src="https://user-images.githubusercontent.com/20819712/79541399-54045b00-80bc-11ea-9380-a0c251e2b9da.png">

**Comment by panchyo0** [comment]
should we close all associated scatter plots, if catalog file closed?

**Comment by kswang1029** [comment]
I suggest we clear the scatter plot and show either an empty plot with the two dropdown greyed out or show the message just like the catalog widget.
