### ISSUE TITLE
update the file dropdown in the catalog widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#882]
Two scenarios,
1) if users load two catalogs one by one, when the second catalog is loaded, the dropdown should point to "2" and update the content in the catalog widget to show catalog 2.
2) when there are multiple scatter plots for different catalog files and the catalog widget is showing catalog 1, if users click one source in the scatter plot corresponding to catalog file 2, the file dropdown in the catalog widget should update to catalog 2 accordingly and show the highlighted selected source. Currently we see table 1 and table 1 updates. Not sure what it does.

<img width="1749" alt="Screen Shot 2020-04-17 at 3 14 24 PM" src="https://user-images.githubusercontent.com/20819712/79542981-3be20b00-80bf-11ea-8ec9-ea8a9c1c42ff.png">

**Comment by veggiesaurus** [comment]
@kswang1029 please confirm this is fixed after merging in #931

**Comment by kswang1029** [comment]
Confirm fixed.
