### ISSUE TITLE
incorrect formatting on rms in  spatial profile windows

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#883]
The formatting of the rms in the mean/rms display in profile windows is incorrect. 

I have set display mean and rms option in the y profile window in this screen capture.  The values are reported as -1.30e-03/0.01.  

The rms values should also be reported in 'e' format in the same way as the mean and the data value.  As currently displayed the number is not precise enough to be useful. This seems to be an issue only with the spatial profiles.  The z-profile has it right.

<img width="1684" alt="rmsvalue" src="https://user-images.githubusercontent.com/9055533/79603928-11ce2000-80a2-11ea-8c4f-ced1377583e5.png">

**Comment by arusstaylor** [comment]
Also the green rectangular display of the mean and dotted line for the rms and the display of values are not retained when the image is exported.

**Comment by Kechil** [comment]
better to use scientific notation to 3 sig figs
