### ISSUE TITLE
include catalog overlay when export as png

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#888]
Catalog overlay should also be included when exporting as png

**Comment by veggiesaurus** [comment]
@panchyo0 can you implement this by taking the same approach used for contour and raster images?

**Comment by kswang1029** [comment]
looks like the Retina display issue also applies to the exported png. The catalog layer looks blurry. 
![paws-pdbi+30m-12co10-6as-mom0 fits-image-2020-7-21-14-55-27](https://user-images.githubusercontent.com/20819712/88022713-5ca87980-cb62-11ea-891a-e44c3b1ab6b7.png)
