### ISSUE TITLE
support catalog overlay on spatially matched images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#890]
As an example, the "ring" should sit at the center of the image view when switching to other spatially matched image. 
![Apr-20-2020 14-16-51](https://user-images.githubusercontent.com/20819712/79719666-a1c5d100-8311-11ea-9fbf-af76e6d8c05a.gif)

**Comment by Kechil** [comment]
Something needs to be done for v1.4 but this could be an interim measure and done properly for v1.5.

**Comment by veggiesaurus** [comment]
> Something needs to be done for v1.4 but this could be an interim measure and done properly for v1.5.

@Kechil did you mean to close this? We definitely need to do _something_ for 1.4 .

**Comment by Kechil** [comment]
Release note needed. Plot to be removed

**Comment by panchyo0** [comment]
closed with PR #1430, optimization at #1432
