### ISSUE TITLE
load button needs to be disabled while catalog is loading

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#898]
At the moment, you can press the `Load Catalog` button as many times as you want, and each time submits another `OPEN_CATALOG_FILE` request. The button should be disabled while loading the catalog, similarly to how the `Load` button is disabled between `OPEN_FILE` and `OPEN_FILE_ACK` messages.

**Comment by panchyo0** [comment]
closed with PR 907
