### ISSUE TITLE
support pixel coordinate catalogs

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#899]
Some  source-finding software (e.g. SoFiA) outputs source catalogs in pixel coordinates, rather than WCS. We should be able to select "Pixel" as a coordinate type, which would then allow us to select "X" and "Y" in the "Represent As" 

One issue is that there's ambiguity as to whether the coordinates are zero-based (FITS) or one-based. Should we instead allow two coordinate types? "Pixel (0-based)" and "Pixel (1-based)"?

**Comment by kswang1029** [comment]
Good point and good idea to have pixel-0 and pixel-1 as options

**Comment by low-sky** [comment]
My thoughts here are that pixel coordinates only make sense in the context of the image for which the catalog is produced.  Thus, if it has 0-based coordinates, the catalog is 0-based and 1-based coordinates images would be 1-based catalogs.  I contend that only one Pixel coordinates is needed for most cases.

HOWEVER, I can assume that there are cases where people generate a catalog in 0-based pixels in something like python and then try to put it on a FITS image.  I can see it being a potentially useful edge case.

**Comment by veggiesaurus** [comment]
> My thoughts here are that pixel coordinates only make sense in the context of the image for which the catalog is produced. Thus, if it has 0-based coordinates, the catalog is 0-based and 1-based coordinates images would be 1-based catalogs. I contend that only one Pixel coordinates is needed for most cases.

CARTA uses 0-based pixel coordinates for all file types, rather than adjusting based on the file type. I know of at least one popular use case that will require 0-based and 1-based adjustments: the source finding software package Sofia produces VOTable output in pixel coordinates only, and we will need to explicitly specify the offset correctly to avoid confusion in comparison with other image viewers

**Comment by veggiesaurus** [comment]
@panchyo0 this seems to be working nicely in your latest PR (merged in). I wonder, do we need tooltips in the select menu to explain what `PIX0` and `PIX1` are?

**Comment by panchyo0** [comment]
@veggiesaurus or explain `PIX0` and `PIX1` in the help section? not sure which one is better.

**Comment by veggiesaurus** [comment]
> @veggiesaurus or explain `PIX0` and `PIX1` in the help section? not sure which one is better.

Good point. @kswang1029 which would you prefer?

**Comment by kswang1029** [comment]
I prefer we have both, tooltip and in-app help. The tooltip would allow users know the meanings with less click and less scan though help context.

**Comment by veggiesaurus** [comment]
@panchyo0 can you implement the tooltip? @kswang1029 will send you the text to use, and will update the help

**Comment by kswang1029** [comment]
suggested tooltip:

PIX0: 0-based image coordinates
PIX1: 1-based image coordinates
