### ISSUE TITLE
Improve catalog filtering GUI

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#908]
It is currently not immediately clear to users that columns can be filtered on. I suggest we change the column headers to something like this: 

![image](https://user-images.githubusercontent.com/592504/80951880-00527b00-8df9-11ea-9081-2dd1eeceb9b3.png)

where the placeholder text is shown whenever a user doesn't have a specified filter. We also need to find a way to indicate that the filters have changed, but new results still need to be calculated, otherwise users may expect that the results are immediately available when editing filters.

**Comment by veggiesaurus** [comment]
@kswang1029 has suggested that we make the "Double-click to filter" placeholder slightly more subtle, possibly by adjusting the colour.

**Comment by kswang1029** [comment]
Maybe when filter conditions are changed, we make the text color in the table “grey”?

**Comment by veggiesaurus** [comment]
> Maybe when filter conditions are changed, we make the text color in the table “grey”?

we also need to indicate to the user that they need to perform some action. Perhaps by changing the "Filter" button's name to "Update" and changing the colour?

**Comment by kswang1029** [comment]
On a related feature, maybe we should use tooltip to show example filter syntax when hovering over the filter fields. The content of tooltip should dynamically adjusted based on the types of columns (number, string, etc)

Update: on a second thought, why don’t we just use those placeholder texts for filter syntax examples?
