### ISSUE TITLE
catalog filtering: use tooltip to show example filter syntax

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#909]
On a related feature, maybe we should use tooltip to show example filter syntax when hovering over the filter fields. The content of tooltip should dynamically adjusted based on the types of columns (number, string, etc)

Update: on a second thought, why don’t we just use those placeholder texts for filter syntax examples?

_Originally posted by @kswang1029 in https://github.com/CARTAvis/carta-frontend/issues/908#issuecomment-623373275_

**Comment by veggiesaurus** [comment]
> Update: on a second thought, why don’t we just use those placeholder texts for filter syntax examples?

Using a tooltip would allow for a very clear explanation with examples of the different filter types

**Comment by veggiesaurus** [comment]
@kswang1029 I think we could still have clearer explanations and examples in the tooltips, what do you think?

**Comment by kswang1029** [comment]
@veggiesaurus @panchyo0 How about:
for floats:

> Operators: >, >=, <, <=, ==, !=, .., ...
e.g. < 10 (everything less then 10)
e.g. == 1.23 (entries equal to 1.23)
e.g. 10..50 (everything between 10 and 50, exclusive)
e.g. 10...50 (everything between 10 and 50, inclusive)

ps: although we support ... as range filter too, maybe we can hide it as .. servers the same function and it is slightly more concise. 
question: or does ... mean between or equal to? e.g, 10...50 means everything greater than or equal to 10 and less than or equal to 50?

> Filter by substring
e.g. gal (no quotation, entries contain the "gal" string)
e.g. "gal" (with quotation, entries exactly match the "gal" string)

**Comment by veggiesaurus** [comment]
> > Filter by substring
> > e.g. gal (no quotation, entries contain the "gal" string)
> > e.g. "gal" (with quotation, entries exactly match the "gal" string)

I wasn't aware that we had to support exact matches :thinking: 

> question: or does ... mean between or equal to? e.g, 10...50 means everything greater than or equal to 10 and less than or equal to 50?

Isn't the one open and the other closed range?

**Comment by panchyo0** [comment]
`e.g, 10...50 means everything greater than or equal to 10 and less than or equal to 50?`
Yes, `...` means closed range

**Comment by kswang1029** [comment]
@panchyo0 to confirm:
10..50 is 10 < x < 50
10...50 is 10 <= x <= 50
Is the above correct?

**Comment by panchyo0** [comment]
yes

**Comment by panchyo0** [comment]
`e.g. "gal" (with quotation, entries exactly match the "gal" string)`
also I think we are not support exact matches for substring currently
.

**Comment by kswang1029** [comment]
@low-sky do you think we should support exact match of strings with quotations? e.g. "Star" will search for entries exactly as **_Star_**. Entries such as **_StarFormation_** will not be selected.

**Comment by low-sky** [comment]
Both exact and partial matching are useful as long as it's clear what's meant.  Using double " to indicate an exact match and without quotes being a partial match makes sense.
