### ISSUE TITLE
make source selected in catalog table all visible in the image view when catalog overlay is enabled

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#916]
Currently when catalog overlay is enabled in the image viewer, selecting a source in the image view will highlight the source in the catalog table and the highlighted source is visible in the table view. Similar behavior should be applied in the opposite way:

1. when catalog overlay is not enabled, selecting a source or multiple sources in the catalog table  results in nothing changed in the image view
2. when catalog overlay is enabled, selecting a single source in the catalog table results in changing the image view so that the selected source is centered in the image view without changing zoom level (effective only pan action is applied).
3. when catalog overlay is enabled, selecting multiple sources in the catalog table results in zooming and panning the image so that all selected sources fit in the image view. This can be achieved by deriving a bound box of all selected sources and translate it to have proper pan and zoom factor.

item "3." has a potential issue that the the spatial coverage of a catalog might be larger than the spatial coverage of an image.

@low-sky @Jordatious @veggiesaurus @arusstaylor @panchyo0 suggestions are welcome

**Comment by veggiesaurus** [comment]
I think (3) would be frustrating to the user, because it would adjust the zoom for the image, rather than the selected sources, which may be clustered in one part of the image, or may extend past the image. I don't think there are likely to be issues with performance if we simply calculate the XY bounds (using existing performance-optimised functions), and use those bounds to determine the appropriate center and zoom.

**Comment by kswang1029** [comment]
Using bound is ideal if performance is not an issue with millions of sources.

**Comment by veggiesaurus** [comment]
> Using bound is ideal if performance is not an issue

Based on my previous [jsperf](https://jsperf.com/minmaxarraytesting/), calculating min/max for a 1e6 point array (both X and Y) should take about 27 ms. If we need faster performance, we can also use WebAssembly

**Comment by kswang1029** [comment]
> I think (3) would be frustrating to the user, because it would adjust the zoom for the image, rather than the selected sources, which may be clustered in one part of the image, or may extend past the image. I don't think there are likely to be issues with performance if we simply calculate the XY bounds (using existing performance-optimised functions), and use those bounds to determine the appropriate center and zoom.

have modified the issue accordingly.

**Comment by veggiesaurus** [comment]
@kswang1029 please confirm this is fixed after merging in #931

**Comment by kswang1029** [comment]
confirm fixed after merging in #931
