### ISSUE TITLE
stubborn tooltip of the catalog selection button 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#920]
It appears that once the tooltip is enabled, it is hard (but not impossible) to make it disabled. 

<img width="744" alt="Screen Shot 2020-05-12 at 3 11 48 PM" src="https://user-images.githubusercontent.com/20819712/81649559-14365680-9463-11ea-92af-8a681263d9e8.png">

**Comment by veggiesaurus** [comment]
Does this _only_ happen with the catalog selection tooltip, or other tooltips in the toolbar?

**Comment by kswang1029** [comment]
Just the catalog selection tooltip I think. Not sure if this is because the button is disabled?

**Comment by veggiesaurus** [comment]
> Just the catalog selection tooltip I think. Not sure if this is because the button is disabled?

That must be it. @panchyo0 you should use an `AnchorButton` instead of a button if you need tooltips to work while disabled (see [here](https://blueprintjs.com/docs/#core/components/tooltip.props))

**Comment by panchyo0** [comment]
closed with PR 922
