### ISSUE TITLE
Invisible labels of exported images during dark mode

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-frontend#923]
When exporting images (including plots) during dark mode, the labels in the output figure are invisible, or otherwise difficult to see, since they're white, over a gray background, which seems to be semi-transparent. Using black would be much more useful, as when exporting images during light mode. I can't find a preference to configure the label colours, but perhaps there is, in which case the default should be updated.

**Comment by kswang1029** [comment]
> shall we add a setting in preferences for exporting with opaque or transparent backgrounds? For embedding images in presentations, a transparent background is better, but for simply saving images, an opaque background is preferred, as @Jordatious mentioned.

yes good idea. I think we need to provide three options: 
1) transparent
2) white opaque background
3) black opaque background

**Comment by Jordatious** [comment]
This seems to be resolved for exporting images from the viewer, but not for exporting images of figures from the widgets (e.g. attached).
![image](https://user-images.githubusercontent.com/10542136/88167461-2a0d8800-cc19-11ea-8ebf-f549fb245244.png)
![image](https://user-images.githubusercontent.com/10542136/88167516-3e518500-cc19-11ea-9caa-e107d8a1b9aa.png)
