### ISSUE TITLE
cannot close debug execution dialog

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#924]
can close the dialog via the close button but not the "x"

<img width="496" alt="Screen Shot 2020-05-21 at 11 18 25 AM" src="https://user-images.githubusercontent.com/20819712/82519726-eaf98280-9b54-11ea-8fc8-a310bc9b6ae2.png">

**Comment by veggiesaurus** [comment]
@confluence looks like you weren't the only person to spot this :laughing:
