### ISSUE TITLE
display warning/error toast longer in time

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#925]
As an example, when exporting regions to a file, we use toast to display the state of request and error messages if failed. It would be good to have different display time for different states. If it is success (green toast), the display period can be as it is now. For orange and red toast, we need longer display time so that users can have sufficient time to read (or copy-paste) error messages. It would be good to have a "dismiss" button in red toast so that users can read the error messages with no pressure.

**Comment by veggiesaurus** [comment]
it might also be useful to add a "copy to clipboard" icon button to all warning and error messages

**Comment by veggiesaurus** [comment]
increasing estimate to 2 due to copy to clipboard functionality

**Comment by kswang1029** [comment]
@TienHao could you take care of this issue for v1.4?
