### ISSUE TITLE
File browser opens behind contour widget

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-frontend#932]
When using the contour configuration widget, and the file browser is opened (e.g. to append an image), the contour widget stays in front of it. It should open on top of all the widgets. It would actually be preferable to be able to pin the contour widget like the others. I don't see why it's different.

This should come under Epic #692

**Comment by veggiesaurus** [comment]
@kswang1029 pinning the contour config widget would require quite a few changes. It would be much easier to just re-arrange the dialog layers. Our current ordering is (back to front):

```
<SplashScreenComponent/>
<RootMenuComponent/>
<FileBrowserDialogComponent/>
<AboutDialogComponent/>
<RegionDialogComponent/>
<PreferenceDialogComponent/>
<SaveLayoutDialogComponent/>
<ContourDialogComponent/>
<FileInfoDialogComponent/>
<DebugExecutionDialogComponent/>
<ExternalPageDialogComponent/>
<HelpDrawerComponent/>
```

I propose we change this to 
```
<SplashScreenComponent/>
<RootMenuComponent/>
<AboutDialogComponent/>
<RegionDialogComponent/>
<SaveLayoutDialogComponent/>
<ContourDialogComponent/>
<FileInfoDialogComponent/>
<PreferenceDialogComponent/>
<FileBrowserDialogComponent/>
<DebugExecutionDialogComponent/>
<ExternalPageDialogComponent/>
<HelpDrawerComponent/>
```

**Comment by kswang1029** [comment]
Do these dialog components not support click-to-front, just like floating widgets?

**Comment by veggiesaurus** [comment]
> Do these dialog components not support click-to-front, just like floating widgets?

Not the way they're currently configured :thinking:

**Comment by kswang1029** [comment]
How about the following? I move "about", "save layout", and "preferences" toward front as usually they are used less frequently but once they are used they should be at front. Splash screen is used when initializing and when the connection is broken. When the later happens, it should be at the very front.
```
<RootMenuComponent/>
<RegionDialogComponent/>
<ContourDialogComponent/>
<FileInfoDialogComponent/>
<FileBrowserDialogComponent/>
<PreferenceDialogComponent/>
<SaveLayoutDialogComponent/>
<DebugExecutionDialogComponent/>
<AboutDialogComponent/> 
<ExternalPageDialogComponent/>
<HelpDrawerComponent/>
<SplashScreenComponent/>
```
