### ISSUE TITLE
Animator frames sorted alphabetically, not numerically

### ISSUE THREAD

**Issue by marcinglowacki** [CARTAvis/carta-frontend#934]
The Play or Next/Previous buttons will go by frames sorted alphabetically rather than numerically.

Example:
Open image, append 20 other images, for a total of 21 frames.
Hitting Play from Frame 0, rather than going 0, 1, 2, 3, ..., 20, 21, 0, 1,... will instead do jump between the frames like so:

0, 1, 10, 11, 12, 13...18, 19, 2, 20, 21, 3, 4, 5....9, 0, 1, 10 (etc.)

**Comment by kswang1029** [comment]
oh dear JS....

**Comment by kswang1029** [comment]
Fixed via #939
