### ISSUE TITLE
icon and text inconsistency

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#935]
There are few icon inconsistencies (including text descriptions) in GUI:

<img width="685" alt="Screen Shot 2020-06-03 at 11 03 03 AM" src="https://user-images.githubusercontent.com/20819712/83591661-0750e280-a58b-11ea-9904-87dea534af62.png">
<img width="707" alt="Screen Shot 2020-06-03 at 11 03 31 AM" src="https://user-images.githubusercontent.com/20819712/83591664-0b7d0000-a58b-11ea-8b8a-2123fe6b3dd4.png">
<img width="712" alt="Screen Shot 2020-06-03 at 11 04 09 AM" src="https://user-images.githubusercontent.com/20819712/83591666-0cae2d00-a58b-11ea-9b66-afe723123c38.png">
<img width="667" alt="Screen Shot 2020-06-03 at 11 04 26 AM" src="https://user-images.githubusercontent.com/20819712/83591667-0d46c380-a58b-11ea-94c9-512b9576c240.png">

**Comment by kswang1029** [comment]
I propose to have the following changes of icons. Not sure if all make sense and are sufficiently intuitive... @veggiesaurus @Kechil 

<img width="863" alt="Screen Shot 2020-06-29 at 12 30 35 PM" src="https://user-images.githubusercontent.com/20819712/85973209-a3440180-ba04-11ea-82d7-ddf1903376b4.png">
<img width="1014" alt="Screen Shot 2020-06-29 at 12 30 57 PM" src="https://user-images.githubusercontent.com/20819712/85973216-a808b580-ba04-11ea-8210-794d43790f9e.png">
 

There were some discussions before to have different regions as individual icons on the top (so it becomes "widget icons" -> "dialogue icons" -> "region icons", or "region icons" -> "widget icons" -> "dialogue icons"). If that happens, we probably can place the region list icon together with those region icons and use the icon as it is now. Currently the icons for the region list widget and log widget are quite similar, especially they are placed side by side. 


We don't have any icons for the "file" menu at the moment. Do we need icons too?

**Comment by veggiesaurus** [comment]
These look sensible, I think. Although I'd like to reserve the "dashboard" icon for the server dashboard. Perhaps we don't need icons for the rest of the help menu? the information icon is pretty standard for "About"

**Comment by Kechil** [comment]
Not sure about the Media icon which indicates luminosity. I associate Media with what media the object will be saved on. I think my problem is with the word 'Media' and not the symbol, which is used with certain common tools to indicate colour themes.

Control looks too much like Page Layout. I prefer the Dashboard but I take Angus's point about this. 

I prefer the 'i' Icon for About as this is the international symbol for information, used in airports, shopping centres etc.

There are two rotation icons I know of. One is the almost complete circle with an arrow on one end of the line, the other is as with the Apple Photo Edit tool which shows a tipped square with two arrows on the corners.

**Comment by kswang1029** [comment]
@veggiesaurus @Kechil Thanks for the feedback. I made some changes and please have a look again.
1) revised file info icon (as "Application header"
2) add one new option (as "Film") for the "Frames" icon
3) revised "Controls and Shortcuts" icon to "Key: control"
4) keep "About" icon as "i" (the one we adopt now)
5) revised the "region list" icon with a new idea

<img width="851" alt="Screen Shot 2020-06-30 at 2 18 12 PM" src="https://user-images.githubusercontent.com/20819712/86090763-49633a80-badd-11ea-9952-08e9d0f15961.png">
<img width="956" alt="Screen Shot 2020-06-30 at 2 18 24 PM" src="https://user-images.githubusercontent.com/20819712/86090779-4ec08500-badd-11ea-8917-378297c2985d.png">

**Comment by Kechil** [comment]
Great. Not sure I understand point 2: add one new option (as "Film") for the "Frames" icon

**Comment by kswang1029** [comment]
> Great. Not sure I understand point 2: add one new option (as "Film") for the "Frames" icon
 @Kechil this
<img width="325" alt="Screen Shot 2020-07-01 at 5 43 22 PM" src="https://user-images.githubusercontent.com/20819712/86229536-70476c80-bbc2-11ea-9868-30b64544f52b.png">

**Comment by kswang1029** [comment]
@duidae @TienHao Can anyone of you handle this for v1.4?
