### ISSUE TITLE
Scripting support: changing contour colour directly does not cause image to re-render

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#943]
When the contour colour is changed via the colour picker in the UI, the contour image is immediately re-rendered with the new colour, as expected.

When the `setColor` action in the contour config store is called directly via the scripting interface or the debug execution console, the stored colour changes (if you have the contour style panel open, you can see the selected colour change in the panel) but the image is not re-rendered.

**Comment by veggiesaurus** [comment]
@confluence `setColor` takes an RGBA object: 

```
export interface RGBA {
    r: number;
    g: number;
    b: number;
    a?: number;
}
```

If you pass it a string, then the color picker will handle it appropriately, but the rest of the frontend will get very confused. What argument were you passing to `setColor`?

**Comment by veggiesaurus** [comment]
We could reasonably easily adapt `color` to represent either a `string` _or_ an `RGBA` object. Perhaps that's the best course of action?

**Comment by confluence** [comment]
Ah, I was wondering about that! I was passing strings, and because the colour picker was working, I was expecting everything else to work too.

Yes, my preference would be to be able to handle string colours -- that's what can be used to set the background of the exported images, and it would be frustrating for this not to work the same way.

**Comment by veggiesaurus** [comment]
@confluence try branch `angus/fix_943` and see if it works ok. By string colours, do you mean hex strings, or would you need to support standard web colours (e.g. `"red"`, `"LemonChiffon"` etc) as well?

**Comment by confluence** [comment]
Ideally web colours as well -- they work on the picker and the image background. I will check the branch.

**Comment by veggiesaurus** [comment]
> Ideally web colours as well -- they work on the picker and the image background. I will check the branch.

Ok, I think we need something like that anyway for the DS9 region colour support anyway, so I'll find a utility library to handle it.
