### ISSUE TITLE
initial connection to the backend failed in the electron app

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#945]
Over the past weeks (probably starting from v1.3) I noticed that _sometimes_ the backend is not launched successfully when we launch the electron app. It is hard to find a robust way to reproduce this but it seems to only happen when the computer is just waken up. 

<img width="1392" alt="Screen Shot 2020-06-02 at 10 09 06 AM" src="https://user-images.githubusercontent.com/20819712/83472319-8bd33080-a4b9-11ea-908d-30d6c253d907.png">

log:
/Applications/CARTA.app/Contents/Resources/app/carta-backend/bin/carta_backend: Version 1.3
Listening on port 55131 with root folder /, base folder /Users/kswang, 4 threads in worker thread pool and 16 OMP threads
Session 1 (Tue Jun  2 10:08:01 2020): Client 1 [::1] Connected. Num sessions: 1
Session 1 (Tue Jun  2 10:15:42 2020): Client 1 [::1] Disconnected. Remaining sessions: 1
No remaining sessions.

"10:08:01" is when I launched the electron app and I saw the above screenshot. 
"10:15:42" is when I closed the electron app.

(may consider to mark this issue as a critical bug)

**Comment by ajm-ska** [comment]
Would it help debug what is going on by having the DevTools console accessible? 
I know it is not so practical to open it. You need to manually comment in line 502 (`mainWindow.webContents.openDevTools()`) of 
`/Applications/CARTA.app/Contents/Resources/app/main.js` beforehand.
So maybe you could keep it commented in so that you would be able to check when the problem occurs again.

**Comment by kswang1029** [comment]
@ajm-asiaa ok I enabled the dev console. Will report back when I encounter the issue again.

**Comment by veggiesaurus** [comment]
@ajm-asiaa on that note, can we add that as an application flag? it would be useful for debugging in general, without manually editing the app code

**Comment by ajm-ska** [comment]
Hey that's a great idea! I should have thought of that before. 
We can simply do it like this: 
```
if (items.debug === true) {
  mainWindow.webContents.openDevTools()
}
```
Then if we are using an alias, we can activate the DevTools as follows: `carta --debug`.

I'll list it in the help menu and add it into the upcoming v1.4-alpha0 version.

**Comment by kswang1029** [comment]
gotcha 
<img width="976" alt="Screen Shot 2020-06-12 at 6 34 51 PM" src="https://user-images.githubusercontent.com/20819712/84494102-7ccf5800-acdb-11ea-84e8-9dfdc31168eb.png">

**Comment by Kechil** [comment]
Assigned to @duidae for now but could be re-assigned.

**Comment by duidae** [comment]
@Kechil shouldnt this be assigned to veggiesaurus? It's mentioned in the discussions.

**Comment by veggiesaurus** [comment]
> @Kechil shouldnt this be assigned to veggiesaurus? It's mentioned in the discussions.

Sure, I'll handle it. I can reproduce the issue easily in a dev build by simply starting the frontend and waiting ~5 seconds before starting the backend process. The first connection to the backend then fails, and when it attempts a connection again, it thinks it has already dropped a connection for a session in progress.

**Comment by kswang1029** [comment]
Finally I caught the event that v1.3.1 failed to load but v1.4a1 loaded successfully. Now I think we can confidently claim the fix should work properly.
