### ISSUE TITLE
raster image rendering precision at high(er) zoom level

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#949]
In the example below, initially we have a 3x3 px square region covering a 3x3 px area. When zooming in at the bottom-left corner, at some point we start to see visible offset between the raster image and the region. 

![Jun-18-2020 11-06-29](https://user-images.githubusercontent.com/20819712/84973631-1ff8f500-b154-11ea-8e84-22ad8225d1da.gif)

top-right corner
<img width="963" alt="Screen Shot 2020-06-18 at 11 10 59 AM" src="https://user-images.githubusercontent.com/20819712/84973756-7108e900-b154-11ea-9009-a96ac5b39c2a.png">

**Comment by veggiesaurus** [comment]
@kswang1029 can you see if this still occurs in `dev`? I thought it might have been fixed by the changes I made (zero- versus one- indexing)

**Comment by kswang1029** [comment]
still there.

**Comment by kswang1029** [comment]
assignee @veggiesaurus or @YuHsuan-Hwang TBD.
lower priority for v3-final release

**Comment by YuHsuan-Hwang** [comment]
I'm not sure if this reproduces the problem, but it seems that the raster image has the precision problem:
1. open a image with size of even pixels and create a region with a corner placed at the center
<img width="534" alt="image" src="https://user-images.githubusercontent.com/43841102/175194021-d604a58f-38a2-4115-92fa-b28ff5283083.png">

2. click Zoom to fit in the image view toolbar

4. keep clicking Zoom in ...
<img width="532" alt="image" src="https://user-images.githubusercontent.com/43841102/175194421-d1261ea0-212a-49be-ace4-fa1f392e707c.png">
<img width="530" alt="image" src="https://user-images.githubusercontent.com/43841102/175194606-6b6ef176-7fa5-4ae4-b50c-df49e3aa6235.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/43841102/175194651-826c5066-4b58-4f92-8f47-5c53316d3450.png">
<img width="530" alt="image" src="https://user-images.githubusercontent.com/43841102/175194693-2dfc2629-ba1b-4afb-a173-08db43ab8818.png">
<img width="533" alt="image" src="https://user-images.githubusercontent.com/43841102/175194739-978a78d2-e082-406f-b0e6-a957dd5c97b4.png">

**Comment by kswang1029** [comment]
@YuHsuan-Hwang yes I confirm these steps can reproduce the "issue" which is actually a raster image rendering precision problem instead of a region rendering precision problem. Feel free to update the issue title.
