### ISSUE TITLE
missing tiles when animation stops

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#954]
This issue is not very easy to be reproduced. With MBP16 and an image cube of 2k x 2k x 2k, at "30" fps, we might have chance to see missing tiles when animation stops. 

<img width="1277" alt="Screen Shot 2020-06-23 at 6 25 30 PM" src="https://user-images.githubusercontent.com/20819712/85393278-4fa66380-b57f-11ea-879f-4680b6c44996.png">

**Comment by kswang1029** [comment]
@veggiesaurus While testing the new "step" function of the animator, I see the missing tile issue. When missing tiles are present, the tile streaming indicator persists when the animation has stopped. The console shows "Missing compression map for key=5_0_63".  See below the screenshot:
![Screen Shot 2020-11-03 at 1 51 57 PM](https://user-images.githubusercontent.com/20819712/97953671-2a9ee880-1ddc-11eb-925e-a7dd92f66ffa.png)

**Comment by veggiesaurus** [comment]
@kswang1029 still only when stopping?

**Comment by kswang1029** [comment]
Apparently yes. Not every time and this could happen even with 1 fps.

**Comment by kswang1029** [comment]
This is a demo on how to reproduce the issue and it also results disordered tile positioning afterward. The test environment is the backend is running on a ubuntu desktop and I run the frontend from a laptop. Both are connected via a wifi. The issue is easy to reproduce.

https://drive.google.com/file/d/1iwFYCEJ39vudCEn7ydyVsXxRhNA0k4Sb/view?usp=share_link

**Comment by kswang1029** [comment]
@YuHsuan-Hwang @crocka #2219 should have addressed this issue, right? Can we close this one?

**Comment by YuHsuan-Hwang** [comment]
Fixed via #2219.
