### ISSUE TITLE
Add mip and range to spectral and spatial profile requests (frontend)

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#955]
As discussed in [this backend issue](https://github.com/CARTAvis/carta-backend/issues/491), we need a way to avoid requesting slow full-resolution profiles (in this case spatial) when they are not needed before merging [HDF5 tile cache and mipmap support](https://github.com/CARTAvis/carta-backend/pull/430) into the backend.

I think that what we agreed on is that requests for profiles should include a mip and a start/end range. This will allow the backend to speed up responses considerably by sending partial and/or approximate profiles which might be fetched from only a subset of tiles or from a downsampled dataset.

This is straightforward to implement in the backend, but will probably require more thought in the frontend (which would be responsible for deciding what segment of a profile is needed and at what resolution).

**Comment by confluence** [comment]
I have closed the duplicate issue and reassigned this.

**Comment by confluence** [comment]
I have created [a PR for the protobuf portion of this](https://github.com/CARTAvis/carta-protobuf/pull/40), and reactivated [the original backend PR](https://github.com/CARTAvis/carta-backend/pull/430) (they should only be merged when this is implemented, as they introduce a breaking change to the interface).

Please note that the mip is interpreted as the *maximum permitted* mip, and the returned values may be a higher resolution than requested, up to the full resolution. This is because it only really makes sense for the backend to honour the mip for files with mipmap datasets -- otherwise the full resolution data has to be downsampled, which means more computation for no real advantage (the purpose of this change is to reduce the need for full resolution tile reads, not the size of the transmitted 1D data).

So FITS files and other files which continue to use the full channel cache will continue to return full resolution profiles; only HDF5 files which use a full resolution tile cache and have mipmap datasets will return downsampled profiles.

The actual returned resolution can be determined from the mip field in the returned data, which may be different to the requested mip.

**Comment by confluence** [comment]
Small update: contrary to my earlier plans, non-HDF5 files now return decimated profiles. The metadata values from the returned objects should still be used, since the requested values may be defaults (e.g. a requested end value which is unset or explicitly set to zero defaults to the height or width; the returned end value reflects the actual end).

**Comment by kswang1029** [comment]
When exporting the profile as a text file, are we able to get a full resolution one?

**Comment by confluence** [comment]
That depends entirely on what the frontend requests. The backend just returns what is requested. The intention is for lower-res profiles matching the raster mip to be loaded by default during navigation, and for full profiles to be requested if data is exported (and perhaps preloaded when the cursor has been idle for some length of time).

**Comment by kswang1029** [comment]
Ok so we need a frontend issue to address this if there hasn’t been one filed.

**Comment by confluence** [comment]
I thought that we would address it in _this_ issue -- the bare minimum required for compatibility with the ICD change is to change the profile format, but actually requesting the different mips is needed to make the mipmap feature usable.

**Comment by veggiesaurus** [comment]
> When exporting the profile as a text file, are we able to get a full resolution one?

If the cursor is frozen or remains stationary for some time, we will request the full-resolution profiles. So when exporting, they should be full-res

**Comment by veggiesaurus** [comment]
> the bare minimum required for compatibility with the ICD change is to change the profile format

@confluence I will create a branch _today_ that just send through full-res profile requests in the format required. Then we can tentatively get your branch merged into dev and this will become a frontend problem (and can also be tested carefully with ICD tests)

**Comment by veggiesaurus** [comment]
I've changed this to a 3, because I think we'll just implement the full-res profiles when the cursor is frozen (and not do stationary checks).

**Comment by veggiesaurus** [comment]
reduced story points to 2 because of separating out issue #1546
