### ISSUE TITLE
catalog: region creation mode is not activated immediately by click when catalog selection mode is enabled

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#961]
When the catalog selection mode is enabled, we need TWO clicks to enable region creation mode instead of the expected one click.

![Jun-29-2020 10-07-38](https://user-images.githubusercontent.com/20819712/85965832-97e6db00-b9f0-11ea-96da-880ba6a43055.gif)

**Comment by panchyo0** [comment]
the first tooltip shows `Double-click to select region type`. I think that's why we need TWO clicks to enable region mode. @veggiesaurus Can we combine `RegionMode.CREATING` and `RegionMode.MOVING` into one button, rather than checking `regionSet.mode` to choose which one to display?

**Comment by veggiesaurus** [comment]
@kswang1029 do we need to backport?

**Comment by kswang1029** [comment]
> @kswang1029 do we need to backport?

Yes please.
