### ISSUE TITLE
performance degradation when editing file name for region export

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#967]
This happens when there are lots of (image) files in the folder where a region file is going to be created. In the region file browser, when editing the file name for region export, typing is laggy.

**Comment by veggiesaurus** [comment]
I think this has the same root cause as #968

**Comment by veggiesaurus** [comment]
@kswang1029 is this fixed now?

**Comment by kswang1029** [comment]
yes! just checked.
