### ISSUE TITLE
empty spatial profile widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#969]
to reproduce:
1) load an image with NaN pixels as border (e.g. set_M17/M17_SWex.fits).
2) freeze cursor at the position which produces all NaN in x spatial profiler.
3) drag-to-dock a new spatial profiler

example:
![Jun-30-2020 10-52-31](https://user-images.githubusercontent.com/20819712/86078310-69383580-bac0-11ea-8392-6a5adc677bee.gif)

**Comment by kswang1029** [comment]
Error message

![Screen Shot 2020-06-30 at 4 34 01 PM](https://user-images.githubusercontent.com/20819712/86103640-9819d000-baef-11ea-8c27-fcb260d35d81.png)

**Comment by veggiesaurus** [comment]
> Error message
> 
> ![Screen Shot 2020-06-30 at 4 34 01 PM](https://user-images.githubusercontent.com/20819712/86103640-9819d000-baef-11ea-8c27-fcb260d35d81.png)
> 

Excellent, this is just what I needed to fix the issue
