### ISSUE TITLE
[imageviewer] export image as png

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#97]
frontend version: c626cb2

the saved png image is not consistent what we see on screen. 
On screen:
<img width="857" alt="screen shot 2018-12-07 at 10 57 36" src="https://user-images.githubusercontent.com/20819712/49625096-1941db80-fa0f-11e8-8b55-4f4c5dcd1d78.png">

Saved:
![carta-exported-image-2018-12-7-10-57-26](https://user-images.githubusercontent.com/20819712/49625108-23fc7080-fa0f-11e8-8acb-2f7dbd9f4fd4.png)

**Comment by veggiesaurus** [comment]
@confluence related to the canvas size of the raster view. You may need to just scale up the raster image and it's padding by devicepixelratio

**Comment by confluence** [comment]
Fixed this in 38e7e21.
