### ISSUE TITLE
Error reporting and suggested course of action when WebGL fails to initialise

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#971]
Currently, if WebGL fails to initialise, the frontend does not display any error notifications. Since it is a critical failure (we can't display images correctly at all), it would make sense to display a detailed error message and some suggested course of action. 

If running CARTA in a browser, the best thing to do is to check WebGLReport with the same browser in order to check if it is a CARTA-specific issue or a browser-wide issue. If running the application, we should mention issues with X11 forwarding and VNC.

@kswang1029 what do you think? See https://github.com/CARTAvis/carta-backend/issues/549 for the sort of issue that could be more easily cleared up by this addition

**Comment by kswang1029** [comment]
Good/necessary to show error message + troubleshooting guide as a popup once the frontend detects there is no WebGL support.

**Comment by veggiesaurus** [comment]
@kswang1029 can you suggest some text for the error message (both in browser and desktop version?)
