### ISSUE TITLE
regression: broken dynamic precision of world coordinate tick label in the image viewer

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#972]
v1.3.1 works fine.

dev:
There are two 21 and two 22 in RA.
![Screen Shot 2020-06-30 at 5 11 58 PM](https://user-images.githubusercontent.com/20819712/86107826-f301f600-baf4-11ea-93fb-660a74f7a843.png)

**Comment by veggiesaurus** [comment]
@duidae this must be related to our changes to AST, or to the AST upgrade itself :thinking: Could you investigate?

**Comment by duidae** [comment]
ok
