### ISSUE TITLE
frontend crashes or behaves abnormally if closing an image while animation playback is on

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#977]
to reproduce
1) load set_M17/M17_SWex.fits
2) set fps to 15
3) enable animation playback
4) after few seconds close the image
5) launch the file browser
6.1) the frontend might crash (entire GUI gone with an empty page)
6.2) if the frontend survived, the entire UI behaves abnormally when a new image is loaded (no histogram, spatial profile, etc)
6.3) potentially the backend might crash 

Possibly we need to send a STOP_ANIMATION message before CLOSE_IMAGE if animation playback is on?

**Comment by veggiesaurus** [comment]
> Possibly we need to send a STOP_ANIMATION message before CLOSE_IMAGE if animation playback is on?

We should already be doing that. I'm not sure why it ends up in such a weird state... It seems like it's waiting for something but I'm not sure what exactly it's waiting for. I might try stop the animation and then delay by 10 ms or so, in case there's a weird race condition occuring.

**Comment by veggiesaurus** [comment]
@kswang1029 please test with branch `angus/fix_977`

**Comment by kswang1029** [comment]
@veggiesaurus yes it seems to work.
