### ISSUE TITLE
rounding histogram widget axis value floating points

### ISSUE THREAD

**Issue by al-jshen** [CARTAvis/carta-frontend#985]
![2020-07-07 11-15-42](https://user-images.githubusercontent.com/22137276/86803516-0efd1e80-c044-11ea-927f-79910b7d777b.png)

Current number of decimal places makes some of the labels unreadable or difficult to read (see the x-axis). Shows up inconsistently but frequently. Would be nice to round off the .0000000001 etc.

**Comment by veggiesaurus** [comment]
possibly resolved by plotly migration
