### ISSUE TITLE
allowing a custom range for rendering the scatter plot in the Stokes widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#990]
Currently, the range for rendering the scatter plot in the Stokes widget based on a colormap is determined by the full spectral range of the cube. This is nice when there is only one feature in the spectral coverage since the full colormap is mapped to mostly full feature in the spectral coverage. However, possibly there are multiple features in one cube. Then only a subset of the colormap is used to render a feature, potentially resulting in a scatter plot with much less contrast, such as the following example.
Full range:
<img width="981" alt="Screen Shot 2020-07-09 at 11 49 15 AM" src="https://user-images.githubusercontent.com/20819712/86995446-a21c8c80-c1db-11ea-9f7d-28b2e2e03db1.png">
Zoom to the strongest line:
<img width="981" alt="Screen Shot 2020-07-09 at 11 50 45 AM" src="https://user-images.githubusercontent.com/20819712/86995454-a648aa00-c1db-11ea-9dbb-b4b15234d3b4.png">

To improve this, shall we allow users to customize the spectral range for color mapping? That is, in the above example, we can use the full colormap to render the line feature only. Or, the spectral range of color mapping is automatically determined by the zoomed range of the QU/PI/PA plots?

@arusstaylor @veggiesaurus @panchyo0 thoughts?

**Comment by veggiesaurus** [comment]
What about auto adjusting the range based on the zoom of the other plots? So as you zoom in on a feature, the colormap stretches around it.


Edit: I see that's exactly what you suggested 😄
