### ISSUE TITLE
shortcut for profile smoothing and moment generator

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#991]
Currently if we want to apply smoothing to a profile, we need to visit the setting dialogue then click the smoothing tab. The same procedure is needed for making moment images. 

How about we add new buttons close to the "export as text" and "export as png" as shortcut? That is, once clicked, the setting dialogue will launch with the smoothing/moments tab enabled. 

<img width="731" alt="Screen Shot 2020-07-09 at 2 54 16 PM" src="https://user-images.githubusercontent.com/20819712/87007508-faac5380-c1f4-11ea-9a9d-5de799a725c7.png">

@arusstaylor @jott3077 @Jordatious @veggiesaurus @low-sky thoughts?

**Comment by jott3077** [comment]
Hi Kuo-Song, 
that could work. The tricky bit could come when there are multiple spectra overlaid in that plot. Then there should be a way to smooth each spectrum separately and possibly an options to smooth all. Same for moments. WIll the buttons launch new widgets with the details of the individual processes?
Juergen

**Comment by low-sky** [comment]
I think the logical place for the smoothing and moments would be at the top with the other profile-control UI elements, but the general principle is good.

**Comment by kswang1029** [comment]
@low-sky such as the following with those persist buttons? That's good too.
<img width="1330" alt="Screen Shot 2020-07-10 at 10 05 33 AM" src="https://user-images.githubusercontent.com/20819712/87108580-3860b900-c295-11ea-8c8a-58f3d1af469c.png">

@jott3077 Yes, once the shortcut button is clicked, we will see a "dialogue" popping up with the "smoothing" tab enabled like the above screenshot. When later on we have support of profiles from different image cubes, there will be a "data source" dropdown allowing us to select which profile we want to apply smoothing. Same logic for moments.

**Comment by kswang1029** [comment]
This is needed for v1.4. @TienHao could you help on this?

**Comment by TienHao** [comment]
Yes, I can help on this.

**Comment by kswang1029** [comment]
I will try to get two icons for you. Before that, please use the blueprint icons as placeholders.
